### ISSUE TITLE
Possibility to have numeric keypad for unlock

### ISSUE THREAD

**Issue by andreapx** [beemdevelopment/Aegis#1001]
I use a pin to unlock Aegis since having the phone unlocked with fingerprint seems enough to me.
It would be nice to have the possibility to select to view a keypad instead of the full keyboard.

**Comment by DeaneOC** [comment]
Settings > Security > Use Pin Keyboard on lockscreen

Is that what you are looking for? @andreapx

**Comment by andreapx** [comment]
Dammit...yes! Thanks @DeaneOC !!!
