### ISSUE TITLE
Add an option to disable the entry thumbnail icons

### ISSUE THREAD

**Issue by 07416** [beemdevelopment/Aegis#1003]
All HOTP/TOTP entries get their own thumbnail (which by default is assigned to the first letter of the issuer — the behavior appears to match the AOSP 'contacts' app).

I don't plan to use favicons and feel that the list would be more readable without the images.

[screenshot in this comment](https://github.com/beemdevelopment/Aegis/issues/971#issuecomment-1241061089) (the round icons on the left)

**Comment by alexbakker** [comment]
Duplicate of #662.
