### ISSUE TITLE
Export a vault to windows

### ISSUE THREAD

**Issue by Answersahead** [beemdevelopment/Aegis#1004]
Hi. Is it possible to export a Aegis Vault to windows? If yes, which windows authenticators accept the vault?

**Comment by alexbakker** [comment]
This will take some Googling, I'm not aware of any authenticator apps for Windows that support importing from Aegis, but there might be one out there.

**Comment by krisu5** [comment]
Only one currently that works "out of the box": https://github.com/pwltr/tauthy (non-encrypted only)
