### ISSUE TITLE
Let us import TOTPs using secret instead of QR

### ISSUE THREAD

**Issue by KitCat36** [beemdevelopment/Aegis#1007]
I have my TOTP secrets, but I can't import them to Aegis because it only wants to scan QR.
I tried using it on Windows 11 WSA and my PC doesn't have camera so it's useless for me. importing TOTPs using their secrets should be added to Aegis, it exists for many other authentication apps.

**Comment by emmaexe** [comment]
Doesn't this already exist? Instead of pressing the "Scan QR code" after you press on the big (+) button just click on "Enter manually"?

**Comment by alexbakker** [comment]
Indeed, this is already possible.

**Comment by alexbakker** [comment]
Ah! I guess you're one of the first ones to try running Aegis on Windows 11. There are actually supposed to be more buttons in that menu. Here's what it's actually supposed to look like:

<img width="200" src="https://user-images.githubusercontent.com/2387841/197798371-55a14b1e-5658-48bf-b959-a535e7b75f64.png"/>

Is it possible to pull up that menu to show the full list of buttons? Or does that not work?

**Comment by alexbakker** [comment]
Right, but I meant: Press and hold on "Scan QR code" and try to pull to menu up by dragging your cursor up.
