### ISSUE TITLE
Please add support for "Entrust Identity"

### ISSUE THREAD

**Issue by daveloyall** [beemdevelopment/Aegis#1010]
Hi.  There is an app out there called Entrust Identity.  Here is their [support page](https://www.entrust.com/resources/identity-and-access-management/support/entrust-identity-app).

Some work (I think all the work that is necessary, and more!) has already been done to parse their QR codes.  See the [entrust-identityguard-tools repo](https://github.com/ss23/entrust-identityguard-tools).

Please add support for this app to Aegis.

**Comment by colans** [comment]
It works really well, but I wasn't given a QR code.  It was given the following:
* Serial #
* Activation code

I had to generate the Registration Code from their app on set-up with the two items above, but I could use the above 2 things along with the Registration Code to generate OTPs on the CLI using the GitHub project.

**Comment by alexbakker** [comment]
We don't have plans to add support for "Entrust Identity".

**Comment by colans** [comment]
@alexbakker Rather than closing it, would you be open to tagging it with "Accepting PRs" or similar?  It would be fantastic if you'd be open to contributions from the community.  Closing tickets like this implies that you're not.
