### ISSUE TITLE
Please add support for OTP Auth

### ISSUE THREAD

**Issue by franz82** [beemdevelopment/Aegis#1011]
Hi all,
it would be nice to add support for [OTP Auth](https://cooperrs.de/otpauth.html) backup file to Aegis.
Thanks,
-f

**Comment by alexbakker** [comment]
Thanks for the suggestion. I took a quick look, but it looks like we'd need to add two new dependencies just to add support for this. One for an implementation of RNCryptor and one for Apple's property list format. I'm not sure it'd be worth it.

**Comment by alexbakker** [comment]
Closing for now, introducing 2 extra dependencies just for this seems like a bit much.
