### ISSUE TITLE
Ugly placeholders when codes set to be hidden

### ISSUE THREAD

**Issue by nvllz** [beemdevelopment/Aegis#1012]
###### Info

-  __Version__: 2.0.3

###### Steps to reproduce

Set _'tap to reveal'_ in app settings. Managed to get it look like that on Samsung with default system font.

###### What do you expect to happen?

The feature was made to look like this: https://github.com/beemdevelopment/Aegis/pull/486. Unfortunately it turns out this solution isn't flexible enough to always display the bullet points like shown in the mentioned PR. For me it looks really bad and I expect Aegis to either have a custom font for codes and placeholders, or change the way placeholders are displayed when turned _'tap to reveal'_ on. I suggest to make them consistent and make both the displayed code and hidden asterisks' font look similar and suit the overall app design.

###### What happens instead?

Bullet placeholders shown below are way too big and totally unproportional compared to the code size on some devices.

![image](https://user-images.githubusercontent.com/110673332/199312663-31562df4-f99f-4bc3-8c8f-e5c9ef383ed1.png)

**Comment by elliotwutingfeng** [comment]
Would reverting to ASCII asterisks and using a monospace font for the one-time-password work?
