### ISSUE TITLE
Language setting still does not work

### ISSUE THREAD

**Issue by WaleedMortaja** [beemdevelopment/Aegis#1015]
###### Info

* __Version__:  2.0.3
* __Source__: I do not remember
* __Vault encrypted__: Yes
* __Device__: SM-J500H
* __Android version and ROM__: 6.0.1

###### Steps to reproduce

Go to `Settings` --> `Appearance` --> `Language`, Most of the languages do not work, they do not translate the app.
The only thing that was translated is the `cancel` button in dialogues!
 
The languages that actually work:
- English
- Chinese (Simplified Han, China)
- Chinese (Traditional Han, Taiwan)
- Porugese (Brazillian)

RTL languages, but no translations:
- Arabic
- Persian

###### What do you expect to happen?

Changing the language in the settings would translate most of the sentences.

###### What happens instead?

Sentences are in English for most of the languages.

###### others
- I noticed that all the working languages, except English, has parentheses in their names :man_shrugging: 
- A maybe related issue: #287

**Comment by alexbakker** [comment]
Please fill out the full bug report template. In particular: Which device do you have?

**Comment by WaleedMortaja** [comment]
@alexbakker I thought it would not be relevant to localization issue. The full template is filled now.

**Comment by WaleedMortaja** [comment]
Aegis Version: 2.1. The problem still exists.
