### ISSUE TITLE
Add support for codes from YubiKey

### ISSUE THREAD

**Issue by kamack38** [beemdevelopment/Aegis#1021]
Hi, I'd really like for Aegis to have support for reading 2FA codes from YubiKey, as the [yubico app](https://github.com/Yubico/yubioath-android) does.

**Comment by kamack38** [comment]
I mean, it would be a great feature to have as I prefer Aegis to theirs app, but I totally understand if You have much more important features to implement.

**Comment by pauleonix** [comment]
> If you're already using a YubiKey for your TOTP needs, why not use the Yubico Authenticator app?

The Yubico Authenticator only works with the more expensive Yubikeys, not with the cheaper "Yubico Security Keys" as far as I understand. So I think being able to use any (pair of) FIDO Security Key(s) instead of or in addition to a password for decrypting the Vault and/or Backups would be cool features.

**Comment by castaway** [comment]
The yubico authenticator app doesn't work on Chromebook yet (grrrr) so if Aegis does/could, that's a reason. (tho i assume there's some usb access related reason that it doesn't)

**Comment by ManuAgora** [comment]
+1 on loving if we could support FIDO security keys. My office requires 2FA to log in to their systems. Option 1 is DUO authenticator which has no setup, automatically goes to Duo (i prefer Aegis Open Source), option 2 is with FIDO security keys. If Aegis supported that protocol, it would be awesome!

**Comment by alexbakker** [comment]
After letting this sit for a while our conclusion is still the same: We consider this out of scope for Aegis.
