### ISSUE TITLE
UX: Prompt for biometric login on login-app, when biometry is activated

### ISSUE THREAD

**Issue by ssssamstrup** [beemdevelopment/Aegis#1025]
Info: Aegis 2.0.3 (latest on F-droid) on Android 10 on Xperia XZ2 Compact.

Note: If this issue has been solved in an update that's not available on Android 10, please just close this issue.

Hi

I've set up biometry in the app, but every time I open it, it prompts me to log in with kode/keyboard, and I have to close keyboard and press biometry.

It would be great if it directly prompted to login with biometry as the first option, when biometry is set up. It's just so much easier.

(In my situation it further doesn't help that I use a password-manager, which also pops up and makes it difficult to press the "use biometry" link every time 😆.)

![Screenshot_20221111-150502](https://user-images.githubusercontent.com/4302516/201357734-2d47cc5f-f430-4cb7-a920-65b057a41860.png)

Hope you'll consider. Thank you for your continued work on this app!

**Comment by ssssamstrup** [comment]
Oh, maybe this was just because it wanted to check I still knew the code?

**Comment by alexbakker** [comment]
> Oh, maybe this was just because it wanted to check I still knew the code?

Correct! The popup should explain this. Is the translation bad, or did you just not notice the popup? (Not trying to blame you, just genuinely curious, as we're trying to improve the popup. See: #989)

**Comment by ssssamstrup** [comment]
Yeah I overlooked it (probably because of both the keyboard and password manager also taking focus. :)
