### ISSUE TITLE
com.beemdevelopment.aegis.importers.DatabaseImporterException: Unsupported schema version: 3

### ISSUE THREAD

**Issue by AzagraMac** [beemdevelopment/Aegis#1026]
### Version

2.0.3

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Google Pixel 6 Pro

### Android version

Android 13

### ROM

Stock rom

### Steps to reproduce

Import file from 2FAS Auth v4.0.0

### What do you expect to happen?

That you import it correctly

### What happens instead?

Error when importing the 2FAS Auth App file version 4.0.0

It happens whether the file is encrypted with password or not. 
<img width="200" src="https://user-images.githubusercontent.com/571796/202003671-faf8dfb3-24d7-42e3-91be-935f9ca43384.png"/>

**Comment by alexbakker** [comment]
Thanks for the report. Looks like they've changed their format in order to support HOTP.

**Comment by AzagraMac** [comment]
Thanks to you, for this great App, it seems that yes, I have a copy of an older version, and although it can import some tokens, most of them give errors.
