### ISSUE TITLE
Can't import from google auth app

### ISSUE THREAD

**Issue by TalOrenshtein** [beemdevelopment/Aegis#1028]
### Version

V2.0.3

### Source

F-Droid

### Vault encryption

Yes

### Device

Mi 9t

### Android version

10

### ROM

LineageOS

### Steps to reproduce

Try to import from google auth app

### What do you expect to happen?

Import successfully

### What happens instead?

Error:
com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 81

**Comment by alexbakker** [comment]
Importing directly from the Google Authenticator app internal storage is no longer possible. See: #918.

**Comment by TalOrenshtein** [comment]
Ty
