### ISSUE TITLE
Add auto backup

### ISSUE THREAD

**Issue by nekromantik** [beemdevelopment/Aegis#103]
Hi
Is it possible to add scheduled backup option?

**Comment by alexbakker** [comment]
Would #18 suffice or do you have a specific use case for scheduled backups in mind?

**Comment by nekromantik** [comment]
hi
I am thinking about a scheduled export option so you dont have to remember to backup.
Or even a integration with something like tasker to automate it. 18 needs to be done for this to work as we need way to export it.

**Comment by alexbakker** [comment]
Right, but what's the use case for the schedule specifically? Is storing the vault external storage as planned in #18 good enough?

**Comment by nekromantik** [comment]
yes external storage is fine. 
just need way to automate it either from schedule or api for tasker to use

**Comment by SecT0uch** [comment]
Same here, I would love to be able to automate it and choose a custom location. (For NextCloud to sync it).

**Comment by MRVMV** [comment]
I think you should add an option for automatic backup after adding a new token to be specific and not scheduled by days

The use case is to keep a secure/plain backup for me if the app/device crashed and it will be surely better if it can be in cloud service like Google drive, OneDrive and Dropbox 
Or just keep it for users (I will surely use tasker to automate it)

Another thing can be added (in the same context) is allowing tasker to send intent/ or like a plugin to Aegis to make a backup

**Comment by Wilker-a** [comment]
i think it would also help to just have a "share" button to make it easier to transfer to places like MEGA

**Comment by bmurphy1976** [comment]
Share button would be a nice option until some more robust sync/backup mechanisms are in place.  Instead of backing up to my Android device (which is more of hassle then helpful), sharing the encrypted database to my email would be great.

**Comment by rnc** [comment]
Not just external storage but also to e.g. Dropbox would be very useful I think.

**Comment by drkui** [comment]
Personally I'd like to see WebDAV support, which would allow me to backup directly to Nextcloud.

**Comment by chiraag-nataraj** [comment]
Maybe a plugin architecture with only the "export to local storage" 'plugin' built-in? Additionally, to prevent bad actors, maybe only allow plaintext backups to local storage?

This would be a _lot_ more work, but would also ensure that:

1. All relevant use-cases can be met (if the plugin doesn't already exist, someone can create it and share it!)
2. The core program doesn't become bloated (people only install the plugins they want)

Additionally, there is already precedent for this (see e.g. Ghost Commander).

What do people think?

**Comment by PopeRigby** [comment]
I think it would be a good idea to have synchronization between your backup target and Aegis. Then you could have a synchronized 2FA app on all your devices.

**Comment by moritzm** [comment]
I always like to have a scheduled or event based backup.
Example for event based backup:

1. new 2FA was added or
2. existing 2FA was being changed
3. do not want to "remember" for manually backing up my stuff

Why i want this? 
Easy. I had some 2FA in Google Auth App. I guess they removed it from my device because of altest security issue. Now all my 2FA saved their are gone and i have somehow to manage my access to those logins again.

**Comment by Wilker-a** [comment]
going off-topic a bit: @moritzm Google should not at all have that kind of power over your own device. even if the app was in fact unsafe, disabling would be the most acceptable (with your consent, and allowing you to re-enable it at your own discretion). and Google knows the implication of such act, so i say that this was a malicious action.

btw, the backdoor comes from Google Play Services, their ToS explains that.

------

now back to the topic, event-based should be good. and for some fail-safes, journals and multiple copies of a file (as chosen by the user) should be good enough to make it safer, instead of overwriting the old backup files.

**Comment by key-equivalent** [comment]
New/Updated MFA code events seems to cover my use cases.  Time isn't a factor afaik

**Comment by dkrm0** [comment]
Same request as everyone, automated backup when adding/updating an entry would be appreciated.

Thank you for your work :)

**Comment by alexbakker** [comment]
Configuring backups is now possible in the latest release (v1.2)! A backup can be made whenever important changes (like adding/editing an entry) happen to the vault. It's not scheduled, as initially requested, but we feel this will suffice for the majority of users. Let us know what you think!

**Comment by dkrm0** [comment]
I think that an automated backup when adding/updating an entry is better. It prevents the loss of credentials.

**Comment by bettyvschmartz** [comment]
This is moving in the right direction but I agree, automated backups to the backup location would be much better. Users will forget to backup regularly otherwise. 

-- BVS

**Comment by alexbakker** [comment]
@bettyvschmartz That's exactly what the backup feature added in v1.2 does.

**Comment by bettyvschmartz** [comment]
@alexbakker OK great but where do I find the schedule? How often does this happen? I can only see an option to trigger a manual backup but nothing about automation or scheduling. 

-- BVS

**Comment by alexbakker** [comment]
@bettyvschmartz As said, a backup is made whenever important changes (like adding/editing an entry) happen to the vault. Scheduled backups are not supported.

**Comment by bettyvschmartz** [comment]
@alexbakker thanks for clarifying. I read it differently. Personally this is much better IMO. Pointless to trigger backups with no changes. 

Having something in the settings like '_backups are automatically triggered when you make changes to your vault. Would you like to run a manual backup now?_', or similar would help i think. 

-- BVS
