### ISSUE TITLE
Export to Clipboard

### ISSUE THREAD

**Issue by xmha97** [beemdevelopment/Aegis#1034]
Please add feature below:
- Export to Clipboard
```
otpauth://totp/Bugzilla%3Axxxxxx%40gmail.com?secret=GFSDIT3COFMWEY3MNBDHQQRWMI&issuer=Bugzilla
```
(Like "Authenticator Pro" app)
https://github.com/jamie-mh/AuthenticatorPro

**Comment by alexbakker** [comment]
Thanks for the suggestion. Adding a "Copy URI" button to the TransferEntriesActivity can't hurt. I think this only makes sense for regular URI's though, not Google Authenticator export URI's.

**Comment by jidanni** [comment]
All I know is to export an individual item, all there is is "copy QR code". So the roster should be away to do it with strings.
