### ISSUE TITLE
Add support Import from Authenticator Pro

### ISSUE THREAD

**Issue by xmha97** [beemdevelopment/Aegis#1035]
Hi, I really like Aegis
Pleaae add support Import from "Authenticator Pro" feature.
https://github.com/jamie-mh/AuthenticatorPro

**Comment by alexbakker** [comment]
Sounds good to me, feel free to submit a PR!

**Comment by ipkpjersi** [comment]
I've dropped a 75 USD bounty on this if anyone ever wants to add this functionality: https://app.bountysource.com/issues/115277810-add-support-import-from-authenticator-pro

**Comment by alexis-opolka** [comment]
Hi, would it be ok if I try to work on adding support for Authenticator Pro?

**Comment by alexis-opolka** [comment]
> I've dropped a 100 USD bounty on this if anyone ever wants to add this functionality: https://app.bountysource.com/issues/115277810-add-support-import-from-authenticator-pro
> 
> It might be worth adding the 100 USD bounty to the title of this issue to generate some interest.
> 
> edit: It's worth pointing out that Authenticator Pro technically supports exporting to an encrypted file (with categories and icons), an HTML file (with QR codes that need individually scanning), and to a plain-text file. Aegis can already import the plain-text file from an Authenticator Pro export, and Authenticator Pro can import the plain-text file from an Aegis export. The plain-text file preserves order even when importing to Aegis but obviously a plain-text file is not safe for long-term storage, so it'd be nice to see the ability to import the encrypted Authenticator Pro backup file directly into Aegis, this is what my bounty is for.

It would indeed be better for long-term storage to not use encrypted files, I'll look into it. 😄

**Comment by ipkpjersi** [comment]
I forgot to link the issue but someone already opened a PR for this.

**Comment by alexis-opolka** [comment]
Ok, nice then. ^^
