### ISSUE TITLE
Notification remains after the app is killed by Android

### ISSUE THREAD

**Issue by alexbakker** [beemdevelopment/Aegis#1037]
A user reported that sometimes, the "Aegis is unlocked" notifcation remains after the app has been killed by Android. To reproduce: Unlock the vault and terminate the app using ``adb shell am kill com.beemdevelopment.aegis.debug``.

**Comment by minhdient49** [comment]
minhdient49@gmail.com 
Truongminhdien833@gmail.com > A user reported that sometimes, the "Aegis is unlocked" notifcation remains after the app has been killed by Android. To reproduce: Unlock the vault and terminate the app using ``adb shell am kill com.beemdevelopment.aegis.debug``.
