### ISSUE TITLE
Launcher QR code quick action icon

### ISSUE THREAD

**Issue by mdmk** [beemdevelopment/Aegis#104]
The icon for QR code scanner quick action on launcher is not material design.
If you could pick one with a more minimalist style and no color or only one color + black/white that would feel more polished.

![](https://i.imgur.com/Ik9iNlF.jpg)

**Comment by mdmk** [comment]
There seems to be no official Google icon neither for QR code nor for barcode scanner.
I suggest something like this : https://materialdesignicons.com/icon/qrcode-scan

**Comment by michaelschattgen** [comment]
![image](https://user-images.githubusercontent.com/7524012/58593260-b2d5a180-826a-11e9-87a1-8fee4b44d9dc.png)

Thanks again for the suggestions mdmk! I've used your icon, removed the outlines to make it a bit more cleaner, added a material grey circle behind it and made the icon itself our secondary color.
