### ISSUE TITLE
Implement support or import for Norton/Symantec/Verisign VIP Access

### ISSUE THREAD

**Issue by gemorgan** [beemdevelopment/Aegis#1040]
This one's not just an importer request. In fact I don't care if there's an importer at all. I have one app left to get rid of and there's a few big corp type sites that are using Symantec's VIP access app. 

Looks like it's a layer on top of standard TOTP (https://locima.com/2019/06/01/replacing-symantec-vip-with-a-generic-totp-app/). 

Looks doable at first glance...

**Comment by alexbakker** [comment]
I'm afraid we won't be able to implement support for this. Looking at that blog post, it appears that Aegis would need to reach out to the internet for activation of some sort. Aegis does not request the internet permission, and we don't have plans to change that.

**Comment by MyAnoneNeko** [comment]
For anyone find this, as a workaround, you can use [python-vipaccess](https://pypi.org/project/python-vipaccess/) module to provision a new token, output a uri, and then convert an otpauth:// URI to a QR code to add it into Aegis.
