### ISSUE TITLE
Manually decrypt the JSON backup

### ISSUE THREAD

**Issue by RemyMachado** [beemdevelopment/Aegis#1044]
_First, thanks for this great tool, it's a relieve. I'm coming from the terrible Google Auth app._

### I'm concerned about the Aegis Application being the single entry point of my JSON backups.  

Currently, I don't know if there's a way to decrypt my backup by hand with my passphrase. I guess it's possible to retro-engineer this repository code to use the same decryption function, but it seems unrealistic.

Let's say for any reason, the Aegis App can't be used anymore and I only have a JSON backup, how can I be sure to decrypt it and use it on another provider? This makes me want to do a `.txt` backup file every now and then, encrypted by my own standards.

**Comment by alexbakker** [comment]
There's no need to reverse engineer anything, as the vault file format is documented [here](https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md). There are no official implementations other than the Aegis Android app, but there are several third party tools that can read Aegis vault files, like: OTPClient and GNOME Authenticator.

**Comment by krisu5** [comment]
Also see [`decrypt.py`](https://github.com/beemdevelopment/Aegis/blob/master/docs/decrypt.py) and [aegis-tools](https://github.com/alexbakker/aegis-tools) (`decrypt.py` works for me, but aegis-tools doesn't).
