### ISSUE TITLE
Long press should also deselect

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#1048]
Long pressing on an icon selects that entry.

A second long press should then deselect it too.

Yes you might say all they have to do is hit the back button. But that's unsymmetrical.

You might also say, "Well you can select only one item anyway." But maybe in the future that might not be the case. So there's no harm in fixing it early.

**Comment by alexbakker** [comment]
I think users will typically expect long pressing of an entry to allow them to drag it around to a different spot in the list. That's also the current behavior (if you're using "Custom" sorting, that is).

There are already multiple natural ways to deselect entries: tapping on them, pressing the back button, or tapping on the back button at the top left.
