### ISSUE TITLE
Warning block and timeline bar same color

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#1049]
It is very bad that  the timeline bar at the bottom is the exact same color as the warning block above it!
![Screenshot_20221203-165309.jpg](https://user-images.githubusercontent.com/1230959/205465529-685acc64-bd56-41cc-9958-a5889b9cc773.jpg)
There at least should be a separator bar.
(Yes, if one just stares at it one realizes that part of it is moving and part of it is not, and there is a little notch etc. etc.)

**Comment by alexbakker** [comment]
Agreed. We should do something about this.
