### ISSUE TITLE
Use openPgP for encryption

### ISSUE THREAD

**Issue by eloyesp** [beemdevelopment/Aegis#105]
May be it adds some work now, but it might simplify the code (as encryption is delegated) and it would make users need to remember just one password. (and only for decryption as encryption does not need a password).

**Comment by alexbakker** [comment]
>it might simplify the code (as encryption is delegated)

This would have to be a separate option in addition to the ones we already have as I don't expect every user to understand how to use PGP.

**Comment by chiraag-nataraj** [comment]
It would also be nice to have one key secured with the existing mechanism and one key with openPGP. The reason I say that is that I currently have a sweet setup with a GPG key on a Yubikey which I use for decrypting stuff on my phone. Part of that setup involves using Pass to store my passwords, so I need my Yubikey to unlock stuff on my phone anyway.

**However**, I'd like to not be locked out should I lose my Yubikey. Thus, my passwords are encrypted to multiple GPG keys - one which is on my Yubikey and another one which never leaves my laptop. This means I never lose access to my passwords and *also* don't have to store a private key on my phone.

In the case of Aegis, that redundancy plan would take the form of having an additional backup passphrase in addition to using my Yubikey-based GPG key as a primary unlock mechanism.

From what I understand, the vault already supports multiple keys, so this should be easy, but just wanted to put that out there in case there were thoughts of fully replacing the existing mechanism with GPG.

**Comment by MuntashirAkon** [comment]
Additionally, there's an option in andOTP to backup data encrypted with PGP (via OpenKeychain). Currently, there's no way to import such backup in Aegis.

**Comment by michaelschattgen** [comment]
Closing this issue as we don't have plans to implement this. If someone wants to take responsibility of implementing this, feel free to restart this discussion.
