### ISSUE TITLE
Recent changes not backed up warning

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#1050]
When we see this warning,
![Screenshot_20221203-165309.jpg](https://user-images.githubusercontent.com/1230959/205465652-9ccd3062-5a8f-4345-b9cb-84e1fd490f85.jpg)
We think it also means that earlier changes **are** backed up.
And then it should also have a "courtesy button" to help us catch up with our backups.
But when we push the "i" with a circle button, we realize that we might not have set up backups ever in the first place.

So the message should be different in that case.

**Comment by alexbakker** [comment]
Setting up automatic backups is not the only way to make this banner go away. Creating a manual export is also an option. So changing the message to something like "Automatic backups are not set up" doesn't really work. What I'll do to make this a little clearer though, is add some info about when the last successful backup/export was.

**Comment by alexbakker** [comment]
8cf48a94aaf1794123c5bbe960ebd7751ada542b
