### ISSUE TITLE
[bug] APP crashes when editing group

### ISSUE THREAD

**Issue by Tinsus** [beemdevelopment/Aegis#1056]
When opening the APP (v.2.1.1), selecting an Entry by long Holding it, clicking in the pen icon, changing the group and saving it the APP crashes. After reopening I noticed it changes the group AS expected, BUT crashes every time I do so. Pixel 6, Android 13.

**Comment by alexbakker** [comment]
Can you try updating to the latest version (2.1.2) and see if you can still reproduce the issue?

**Comment by Tinsus** [comment]
Update done, unproduceable. Thanks for that.
