### ISSUE TITLE
Password re-prompt error.

### ISSUE THREAD

**Issue by MuhayminShakur** [beemdevelopment/Aegis#1062]
Currently on a pixel 7, upon startup I was asked to re-enter my password. I entered it through auto-fill with Bitwarden so I know it wasn't incorrect. Tried manually typing it and same issue. Uninstalled since I have 3 backups through nextcloud. Upon reinstalling and using the backup I get prompted with this message
 "com.beemdevelopment.aegis.importers.DatabaseImporterException: Password incorrect "

If there is anything that can help please let me know.

**Comment by MuhayminShakur** [comment]
Hello thanks for getting back to me. Yes I am sure that the password is correct, I entered it about 2 days ago. I have tried all 3 backups. 
So I opened up my backup file and in the slot section there are two types : type : 1 and type : 2 < this type comes first then 1.
There is a is_backup field and it's value is false.
Other than that in the repaired value is set to true. 
Let me know what else I can do.

**Comment by MuhayminShakur** [comment]
Hi so I tried another password , I wasn't aware that the backup is different than the account password. Thank you for your help. Much appreciated. Case solved.

**Comment by alexbakker** [comment]
Glad to hear it!

> I wasn't aware that the backup is different than the account password.

Could you clarify? Which "account password" did you think you had to enter?

**Comment by MuhayminShakur** [comment]
Yeah so I had a password stored in bitwarden once. But installed grapheneos yesterday and changed it without realizing. For some reason i thought i was entering a pin instead of a password. Completely my fault. I changed it back to the secure password. Thanks again!
