### ISSUE TITLE
Paper wallet crypto is trapped.

### ISSUE THREAD

**Issue by Kadence007** [beemdevelopment/Aegis#1065]
I have a paper wallet with cryptocurrency that was placed their several years ago. How do I remove it from the paper and get it onto an exchange??

**Comment by alexbakker** [comment]
This is not the right place to ask questions unrelated to Aegis Authenticator.

**Comment by Kadence007** [comment]
Thanks for the feedback please point or Direct me as where i can pose
the question.
    Regards Steve Homeniuk
