### ISSUE TITLE
Some efficiency improvement suggestions for migrating to Aegis

### ISSUE THREAD

**Issue by GottemHams** [beemdevelopment/Aegis#1066]
I just switched from Google Authenticator since they started encrypting the database, so I can't reliably (and automatically) back up just my secrets anymore. I do try to keep a copy of the original QR code and/or plaintext secret whenever I add a new one, but certain circumstances could lead to forgetting that. Anyways, I imported all keys into Aegis and wanted to set icons and groups for all of them. I actually have a whole load of keys and I missed some bulk/mass actions for this.

1. Setting icons: perhaps it could work by selecting multiple entries and allowing to set icons consecutively. It could flip through multiple screens, one for each entry and for speed it could proceed to the next one when you set an image. No tapping on a `Save` button needed.
    - Alternatively: a `set default icon` thingy. For example: I have an entry for AWS, then Aegis (using the `aegis-icons` pack) will automatically suggest a couple of Amazon-related icons when I go to change it. The default icon can then simply be the first match, or none if there are no suggestions (or any icon packs even).
        - Sidenote about a potential bug: I noticed when setting the icon for issuer `Dropbox` the one for `Box` actually appeared first. I think that might be because `Dropbox` contains all letters of `Box`, so it's a "100%" match and due to being shorter it comes first? It would actually need to be a 50% match though.

2. For adding entries to groups in bulk I actually found some pending issues ([1](https://github.com/beemdevelopment/Aegis/issues/597), [2](https://github.com/beemdevelopment/Aegis/issues/27)), but it's been about a year since the last response on these, so I figured I'd bring em up again. :>

**Comment by alexbakker** [comment]
1. We're probably going to do something similar to what's suggested in: #773.
2. There are already open issues for this, like you said.

**Comment by GottemHams** [comment]
Cool. =] I did try to search for already existing issues for the first point too, but I used the terms `bulk` and `mass`. ;_;
