### ISSUE TITLE
Cannot import Battle.Net manually

### ISSUE THREAD

**Issue by neheb** [beemdevelopment/Aegis#1068]
The Authenticator+ instructions give a URI of the form:

```
otpauth://totp/X%40Y.com?secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&issuer=Battle.net
```

as far as I can tell, the secret is in hexadecimal.

Any way to import?

ping @JordanPlayz158 @alexbakker 

edit: also note the length is 38. code says 40. Not sure of the significance.

**Comment by alexbakker** [comment]
> The Authenticator+ instructions

Could you share a link to those instructions?

> as far as I can tell, the secret is in hexadecimal.

This would make the URI invalid. Try re-encoding the secret as base32 and see if that helps. Also, Battle.Net uses 8 digits if recall correctly, so the ``digits=8`` parameter is missing from the URI as well.

**Comment by neheb** [comment]
https://blog.nigelsim.org/2021-01-15-extracting-authenticator-plus/

I'll try those suggestions.

**Comment by alexbakker** [comment]
Glad you figured it out
