### ISSUE TITLE
Red banner at top of App warning about Backup

### ISSUE THREAD

**Issue by giwrgosmant** [beemdevelopment/Aegis#1072]
### Version

2.1.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

POCO F1

### Android version

Android 13

### ROM

crDroid

### Steps to reproduce

- Open the Vault
- Add a new entry or edit an already exist entry

### What do you expect to happen?

Actually I didn't expected something to happen just the changes apply successfully as usual.

### What happens instead?

There is a red banner in top of Aegis app warning me that the latest backup is outdated. However I don't use and I don't want to use backup, I do my backups manually. It's very annoying. This is also happening on my brothers phones.
If I go to the backup settings and turn on/off the android backup the banner disappears but why this happening?
This is started to happen after a recent update and I don't remember exactly when, but it wasn't like that before.
Excuse me if there is already an open issue about that or discussed before, you can link my issue there.

**Comment by giwrgosmant** [comment]
> This was introduced to remind users of the fact that they need to make backups. It'll disappear if you set up automatic backups, or if you create manual exports.
> 
> > I do my backups manually
> 
> How do you do backups?

Yeap, it will disappear as I also mentioned if I do that, but I don't want to set up automatic backups and that's annoying. I do the backups manually, I export the vault and I transfer/save the file somewhere else locally in hard driver/usb.

**Comment by alexbakker** [comment]
It's meant to be annoying though. The banner should also disappear after you do a manual export, not just when enabling automatic backups.

Anyways, perhaps we can show a dialog when you tap that banner that tells you why it's being shown and why backups are important, with a checkbox that you can tap to not show the banner again.

**Comment by giwrgosmant** [comment]
> It's meant to be annoying though. The banner should also disappear after you do a manual export, not just when enabling automatic backups.

Yes but I may don't want to export the vault exactly at the time I add something, since I may be busy or something and I will do it when I will get some time which it can takes some days.
> Anyways, perhaps we can show a dialog when you tap that banner that tells you why it's being shown and why backups are important, with a checkbox that you can tap to not show the banner again.

That would be awesome.
I understand the important of the backups and it's good you inform the users about it, but a persist banner it's annoying for anyone, actually any persist banner would be annoying. The user who read this I think it's in a position which can understand about backups and he should have the option to dismiss it if he wants and not be forced to do backups if he doesn't want. (or at least at the current time)

Thanks for your work 😊

**Comment by ztNFny** [comment]
+1 for an option to disable it.

I'm rooted and the DB is backed up automatically, no need to back it up manually, so no need for the in-app reminder.

**Comment by FWDekker** [comment]
I also agree with the option to disable it, though, as you suggested, definitely somewhere in the settings with a checkbox indicating the user understands the consequences.

I do not have backup set up because that'd require a password, but I don't want a password because I think my phone's lock password is sufficient.

**Comment by Tom-Fawcett** [comment]
I intentionally don't back up the app and instead back up elsewhere (e.g secondary secure devices). So being able to dismiss the banner would be great.

**Comment by CaviaPorcellus** [comment]
I made a manual export and the banner disappeared. But then it just reappeared a few days later, so even as-is it's not working as intended (at least as I understand it). I haven't added anything since the last export, so there's no reason to pester me to make a new backup.

**Comment by ner00** [comment]
> I made a manual export and the banner disappeared. But then it just reappeared a few days later, so even as-is it's not working as intended (at least as I understand it). I haven't added anything since the last export, so there's no reason to pester me to make a new backup.

Depends, if you use HOTP entries, generating the next code will change the vault, that's the only thing I can thing of, besides the obvious of adding/removing entries or changing any app setting.
