### ISSUE TITLE
AndOTP import fails reproducibly

### ISSUE THREAD

**Issue by gschintgen** [beemdevelopment/Aegis#1073]
### Version

2.1.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Samsung Galaxy s10e

### Android version

Android 12

### Steps to reproduce

1. Open Aegis
2. choose import from AndOTP
3. select an AndOTP export

### What do you expect to happen?

I'd expect the import to work fine.

### What happens instead?

It throws an error, both for encrypted backups (no asking for password, maybe unsupported but no indication of such a limitation in the UI) and for plaintext backups. For obvious security reasons I'll only post a redacted version:
```com.beemdevelopment.aegis.importers.DatabaseImporterException: com.beemdevelopment.aegis.vault.VaultFileException: org.json.JSONException: Value [{"secret":"...........," ..................., used_frequency":0,"period":30,"tags":[]}] of type org.json.JSONArray cannot be converted to JSONObject```
I looked at the JSON in my editor and formatted it for readability. It's an array of objects. Is that unexpected? I can see no obvious issues with the json (and neither can the syntax highlighter ;-)).

AndOTP is version 0.9.0.1 (latest available on F-Droid)

**Comment by alexbakker** [comment]
It sounds like you're trying to import an andOTP file from the intro. The intro only supports importing Aegis vault files. Try going through the setup process, and then importing the andOTP file through "Settings -> Import & Export -> Import from file". Make sure to select "andOTP" in the dialog that pops up.

**Comment by gschintgen** [comment]
> It sounds like you're trying to import an andOTP file from the intro. The intro only supports importing Aegis vault files. Try going through the setup process, and then importing the andOTP file through "Settings -> Import & Export -> Import from file". Make sure to select "andOTP" in the dialog that pops up.

Oops, you're right. I must have been so fixated on importing my AndOTP backup on first use that I couldn't conceive that "Import Vault" is not able to actually import a vault exported from another app. I even thought it said I could import from andOTP when the actual button label was simply "Import Vault". Sorry for the misleading phrasing in my original post and thanks for your help!

Anyway, I humbly suggest to change the rather generic wording on the first intro screen to "Restore Aegis Vault" or "Import Aegis Vault".

Using the proper import facilities in the settings, the import worked fine.

**Comment by holocronweaver** [comment]
@alexbakker +1 to renaming the 'import vault' segment to something more specific like @gschintgen suggested. I was also tripped up by the ambiguous naming.
