### ISSUE TITLE
Biometrics grayed out on Galaxy S10e if only face recognition is set up

### ISSUE THREAD

**Issue by gschintgen** [beemdevelopment/Aegis#1075]
### Version

2.1.2

### Source

Google Play

### Vault encryption

Yes

### Device

Samsung Galaxy S10e

### Android version

Android 12

### ROM

stock

### Steps to reproduce

Open Settings / Security in Aegis.

### What do you expect to happen?

Biometric unlock via face recognition should be available, as it is for other apps.

### What happens instead?

"Biometric unlock" is grayed out even though I can use the OS's face recognition perfectly fine for unlocking the phone itself and also for biometric access control in at least two other apps (notably Bitwarden).

Further info: I did not enroll my fingerprints as the reader is so unreliable that it's too frustrating to use. If I add a fingerprint for testing purposes it does work fine (but I know that it's too finicky to keep activated), but I'm never prompted for face recognition unlock. If I then remove the fingerprint Aegis will tell me "no fingerprint enrolled". But it's never referencing face recognition as biometrics option even though it's properly set up.

Also: after removing of my enrolled fingertip the "Biometric unlock" is grayed out again but still activated! If I open the app it complains about a missing fingerprint (as expected) but in order to disable "Biometric unlock" I first have to re-enroll a finger, just to have the possibility to disable biometrics in the settings...

Unrelated: Happy new year! And thanks for Aegis.

**Comment by alexbakker** [comment]
This is unlikely to be an issue in Aegis, because we don't have any device-specific code for biometrics, and face unlock is known to work with the Pixel 4. It's possible that the face unlock sensor on the Samsung S10e is not considered [Class 3](https://source.android.com/docs/security/features/biometric/measure), making it unsuitable for Android Keystore authentication as used in Aegis.

**Comment by gschintgen** [comment]
Ah, okay, that explains it! Thanks.

For reference if anyone else ends up here:
https://source.android.com/docs/security/features/biometric
