### ISSUE TITLE
A way to decode the database from my computer

### ISSUE THREAD

**Issue by bbureau** [beemdevelopment/Aegis#1083]
I would like to use my aegis database on my computer with `pass-otp`, but I don't want to risk the backup being transferred through an insecure channel.

Would it be possible to add to the documentation the way to decipher the encrypted database from a computer? (with the password, of course)

**Comment by krisu5** [comment]
https://github.com/beemdevelopment/Aegis/issues/1044#issuecomment-1335359351

**Comment by alexbakker** [comment]
You can read all about it here: https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md.
