### ISSUE TITLE
Error when re-importing database

### ISSUE THREAD

**Issue by ed5494** [beemdevelopment/Aegis#1086]
### Version

2.1.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 5

### Android version

Android 13

### Steps to reproduce

Struggling to consistently reproduce however summary is that my 2FA backup from Aegis will not restore on my Pixel 5 but had no problems on an old Samsung S5 I had lying around.

Backup date was recent (you can see in the filename captured within the error).

### What do you expect to happen?

Successful restore

### What happens instead?

 Get the following error

ImportFileTask(uri="content://pl.solidexplorer2.files/-548115613/storage/emulated/0/Download/aegis-backup-20221225-224902.json"): java.io.FileNotFoundException: No content provider: content://pl.solidexplorer2.files/-548115613/storage/emulated/0/Download/aegis-backup-20221225-224902.json

**Comment by alexbakker** [comment]
This is probably a bug in Solid Explorer. Try using Android's built-in file selection instead.
