### ISSUE TITLE
FYI - Aegis mentioned in new paper "Security and Privacy Failures in Popular 2FA Apps"

### ISSUE THREAD

**Issue by joshtrichards** [beemdevelopment/Aegis#1088]
Ran across this today and thought you might be interested in reading it since Aegis was one of the apps evaluated in it:

https://github.com/blues-lab/totp-app-analysis-public

Apologies in advance if you've already seen it.

**Comment by alexbakker** [comment]
We've seen it! Thanks for sharing though.
