### ISSUE TITLE
Sort by last used

### ISSUE THREAD

**Issue by BartG95** [beemdevelopment/Aegis#1089]
As a follow up to https://github.com/beemdevelopment/Aegis/issues/122, in particular https://github.com/beemdevelopment/Aegis/issues/122#issuecomment-1268815257 and https://github.com/beemdevelopment/Aegis/issues/122#issuecomment-1272524227.

When sorting by usage count, if usage shifts over time, but some entry was used a lot in the past, it will stay at the top for quite a while. Sorting by last used solves this quite fast.

I also think that sorting by last used is more intuitive.
Maybe because other applications (not just other otp apps), seem to have the same behaviour.

Is there any use case where sorting by usage count is better? I've read the comments there, but I don't see how it ended up as 'usage count is better'. On the contrary, to me.

**Comment by alexbakker** [comment]
> When sorting by usage count, if usage shifts over time, but some entry was used a lot in the past, it will stay at the top for quite a while

There's a button in the menu of the entry editing screen that allows you to reset the usage count of an entry.

> Is there any use case where sorting by usage count is better?

Yes. Sorting by usage count allows you to develop a kind of muscle memory for tapping the couple of entries at the top, because they'll usually stay in the same spot for a while. Sorting by last used means that the order will change as soon as you tap one of the entries.

**Comment by BartG95** [comment]
> > When sorting by usage count, if usage shifts over time, but some entry was used a lot in the past, it will stay at the top for quite a while
> 
> There's a button in the menu of the entry editing screen that allows you to reset the usage count of an entry.

That is only a full reset, which will make the item go to the bottom. It doesn't account for *less* usage (as opposed to no usage). Of course, if the entry is used after that, it will slowly climb again, but if the app has been in use for a long time, that will take a while. And it still requires manual intervention. The fun thing with last used is that it is fully automatic, and accurate.

> > Is there any use case where sorting by usage count is better?
> 
> Yes. Sorting by usage count allows you to develop a kind of muscle memory for tapping the couple of entries at the top, because they'll usually stay in the same spot for a while. Sorting by last used means that the order will change as soon as you tap one of the entries.

Hmm, I can understand how people prefer that. Probably I am too much used to apps that do last used. Talking about muscle memory, I sort of expect entries to change places after using them. If I use an entry that was way down the list, and I want to use that entry again an hour later, I don't expect to have to scroll or search again. Instead, I expect it at or near the top. I know that it sound weird to have muscle memory for things that change, but somehow my mind is programmed to remember the fact that I used that entry recently.

I do this with pretty much anything. Previously with andOTP (well, that is obviously by now ;) ), but also with the KISS launcher app, with the launcher on my desktop, with my files, etc. I want my computer to organize this for me, instead of doing it myself. And last used (or frecency, a combo of last used and usage count), worked pretty well so far.

btw, it might always be helpful to have a last used timestamp for administratively purposes and debugging.

So I suggest a two-step process: first adding last used timestamps, and secondly an extra sorting option. I think the first is not objectionable anyway, and the second will be just an extra sorting option; there are already six, making a seventh at the end is probably not in the way of those who don't want it.

**Comment by dd23** [comment]
I also think re-ordering the list by putting the most recently used one to the top would be a nice feature to have. I miss this since I switched from andOTP.
