### ISSUE TITLE
[Feature Request] Allow hiding 'Changes are not backed up' banner

### ISSUE THREAD

**Issue by OdinVex** [beemdevelopment/Aegis#1090]
I'd prefer to be able to hide the 'Changes are not backed up' banner. A simple checkbox in 'Behavior' to acknowledge and disregard would be nice.

**Comment by ndulisdul** [comment]
What's the reason why it appears? How can the underlying problem be resolved?

**Comment by alexbakker** [comment]
See: https://github.com/beemdevelopment/Aegis/issues/1072#issuecomment-1366541892.
