### ISSUE TITLE
Implement UI Changes

### ISSUE THREAD

**Issue by fu8765** [beemdevelopment/Aegis#1092]
1) Authenticator pro (https://github.com/jamie-mh/AuthenticatorPro) has a very useful tiled view for those of us who want to make the most out of our screen space

2) Implement group tabs
Similar some android launchers where you can slide left and right to go from tab to tab or group to group, the main tab when the app opens, needs to be able to be defined.
Example. you open the app, and you have a screen called "Personal" with all your personal tokens, then you slide left, and get a new screen called "Work"

3) Zoom token when tap to reveal used as an option

thank you

**Comment by jenom** [comment]
I just wanted to suggest a two column mode ;). Instead, I'll put my quick mock up here though I really like the tiles from Authenticator Pro as they have better visual seperation.

![two_columns](https://user-images.githubusercontent.com/1188467/217094570-8a177900-528f-407f-8ff0-4ff7e370e134.png)

**Comment by fu8765** [comment]
> I just wanted to suggest a two column mode ;). Instead, I'll put my quick mock up here though I really like the tiles from Authenticator Pro as they have better visual separation.

That is exactly what I had in mind, but that is only the first suggestion..
the 2nd is the ability to swipe to reveal a different group, that can also viewed in tioles or whatever format is chosen.

the zoom is pretty much self explanatory.

**Comment by pedromsmendes** [comment]
Group tabs would certainly be helpful, and for the exact same reason. Personal and Work groups.

**Comment by cryptikon** [comment]
I would also appreciate it if the group name(s) which are currently assigned to the entries could be displayed next to each entry. For example next to the entry name or somewhere within the row or tile.

**Comment by gaborbit** [comment]
1. Group names should be displayed only and we could collapse-expand those by clicking on the group name
2. Showing groups on separate tabs is another good idea, swiping left and right to change tabs would be great

**Comment by michaelschattgen** [comment]
Thank you for your report. In the meantime we already implemented a tile view mode. We're not fond of the idea of adding a group tabs feature to our entries list but we agree that we should work on our groups feature. The chips will stay but we're planning on making improvements of the overall usage of the sorting/groups. Also group names as headers is something we're considering.

In the future we'd appreciate if you stick to 1 issue per feature request so it makes things a bit more clear.

**Comment by gaborbit** [comment]
Tiles looks great, I have switched to this view immediately. Unfortunately if you have more than 14 tiles it will cause scrolling and searching again. Switching between groups should be easier. 
1. Instead of current horizontal scrolling I would prefer vertical paging (like some launcher app drawer) 
2. and groups could be also organized into pages
3. or at least the first few group names could appear in the top bar to the left of the current group button for quick switching
