### ISSUE TITLE
Adding second entry of Anydesk does not show the icon

### ISSUE THREAD

**Issue by angelosne** [beemdevelopment/Aegis#1094]
### Version

2.1.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Xiaomi redmi note 9 pro

### Android version

12

### ROM

MIUI 13.0.5

### Steps to reproduce

Add an entry of Anydesk (I don't know if it works with other apps but I already have 2 google and amazon entries without problem) and it should have the right icon.
Add a second entry of Anydesk and it should not take the icon

### What do you expect to happen?

The second entry of Anydesk should had the right icon

### What happens instead?

The icon is just the letter A

**Comment by alexbakker** [comment]
Aegis does not automatically assign icons to entries yet.

**Comment by angelosne** [comment]
> Aegis does not automatically assign icons to entries yet.

I am sorry I totally forgot that is a manual procedure and I missed the top three dots on the op right!
