### ISSUE TITLE
Give option to make fingerprint default when opening app

### ISSUE THREAD

**Issue by makedir** [beemdevelopment/Aegis#1095]
It is super annoying, that the app doesnt ask for fingerprint automatically when opening it, and you have to click a super tiny text link with your finger, which is really badly positioned a few pixel above the keyboard and hard to hit with fingers for "biometric data".

**Comment by michaelschattgen** [comment]
We have implemented password reminders to try to get users to type in their passwords every now and then so they won't lose access to their vault. There should be a prompt on your unlock screen telling you to type in your password.

You can either type in your password once (recommended), or disable the password reminder in the settings.

**Comment by Uhter** [comment]
@michaelschattgen 
I didn't understand how it works either. Thanks for the explanation :)
