### ISSUE TITLE
Can't save to phone if documentui was removed

### ISSUE THREAD

**Issue by meaz** [beemdevelopment/Aegis#1098]
Hi,

I can't save to the phone coz it complains that I don't have documentUI app, which I have removed and replaces with another app from fdroid. Would be nice to have a way to have this working with any document app.

**Comment by alexbakker** [comment]
The prompt also tells you that DocumentsUI "is an important system component necessary for the selection and creation of documents" and that you "will have to reinstall it".

Removing [DocumentsUI](https://source.android.com/docs/core/ota/modular-system/documentsui) essentially breaks access to SAF for all apps on your device. A third-party app from F-Droid that happens to be able to browse documents is not a replacement for a system component.
