### ISSUE TITLE
List of entries does not refresh after removing search query after deleting all results

### ISSUE THREAD

**Issue by FWDekker** [beemdevelopment/Aegis#1099]
### Version

v2.1.2

### Source

F-Droid

### Vault encryption

No

### Device

Pixel 6

### Android version

Android 13

### ROM

GrapheneOS

### Steps to reproduce

1. Add at least two 2FA entries to the app. Let's name them "Foo" and "Bar".
2. Use the search function to search for "Foo".
3. Press-and-hold the entry for "Foo". Use the kebab menu (three vertical dots) to delete the entry. Confirm the deletion.
4. Remove the search filter for "Foo" by pressing the "x" next to the search filter.

### What do you expect to happen?

After step 3, I expected to see the message "Showing 0 entries"; as if I had only added "Bar" in step 1, and then searched for "Foo".

After step 4, I expected to see the "Bar" entry that was added in step 1.

### What happens instead?

After step 3, the list of entries contains only the placeholder "No entries found", with an explanation of how I can add an entry. This is distinct from the "Showing 0 entries" message; the "No entries found" placeholder and explanation are normally only shown when the user has never added an entry or has deleted all entries.

After step 4, the same "No entries found" placeholder is shown, even though there is no search filter, and "Bar" is still in there.

**Attempted mitigations:**
* Pressing the phone's back button to close the search filter input does not resolve the issue.
* Fully closing and re-opening the app resolves the issue.
* Adding _three_ entries, "Foo A", "Foo B", and "Bar", then searching for "Foo", then deleting "Foo A", then removing the filter _does not_ trigger the bug.
* Adding _three_ entries, "Foo A", "Foo B", and "Bar", then searching for "Foo", then deleting both "Foo A" and "Foo B", then removing the filter _does_ trigger the bug.

**Comment by michaelschattgen** [comment]
Thank you for the detailed report, I was able to reproduce this issue. We will have to fix this.
