### ISSUE TITLE
Countdown bar is invisible

### ISSUE THREAD

**Issue by PopeRigby** [beemdevelopment/Aegis#110]
The red countdown bar that usually sits under the 'Aegis' heading, is gone. It happened after I added a Nextcloud TOTP secret. I force closed Aegis and then tried again to see if the bar was back. No secrets showed up and Aegis crashed a few seconds later.

**Comment by alexbakker** [comment]
Thanks for the report. Can you capture a log with ADB and share if with us?

**Comment by alexbakker** [comment]
Which version of Aegis are you using? Also, this is probably not an issue with Nextcloud. I just tested it with a demo instance and it works fine.

**Comment by PopeRigby** [comment]
0.4

**Comment by PopeRigby** [comment]
> Thanks for the report. Can you capture a log with ADB and share it with us?

How do I capture a log, @alexbakker?

**Comment by gkeegan** [comment]
You could download the app matlog and use that most likely. @poperigby

**Comment by PopeRigby** [comment]
matlog? Sorry. I'm not too familiar with Android debugging

**Comment by gkeegan** [comment]
https://play.google.com/store/apps/details?id=com.pluscubed.matlog

You could download this.

**Comment by PopeRigby** [comment]
The bar is back now for some reason. Bizarre.

**Comment by alexbakker** [comment]
Did you update Aegis by any chance?

**Comment by PopeRigby** [comment]
No. It says it updated 3 days ago. I opened this issue 4 days ago, so it might have been fixed and I didn't check. I guess I'll close this. I'll re-open it if I have the same issue.
