### ISSUE TITLE
Add backup to cloud to StorJ

### ISSUE THREAD

**Issue by pataquets** [beemdevelopment/Aegis#1103]
[StorJ](https://storj.io), has great privacy features, since it's a zero-trust cloud storage protocol.

**Comment by alexbakker** [comment]
Thanks for the suggestion, but we don't have plans to add support for specific cloud providers. If Storj has an Android app that fully participates in Android's Storage Access Framework, Aegis will be able to back up to it.

**Comment by pataquets** [comment]
Fair enough. Thanks for the prompt reply and for considering, @alexbakker.
