### ISSUE TITLE
Archive option

### ISSUE THREAD

**Issue by salad612** [beemdevelopment/Aegis#1108]
Instead of deleting, also allow archiving entries so that they are hidden from the regular view but can be recovered later

**Comment by fiorins** [comment]
Yeah, it would be very very useful with an archive icon next to the search one.

**Comment by alexbakker** [comment]
We'll implement this as part of #624.

**Comment by fiorins** [comment]
> We'll implement this as part of #624.

news ?

**Comment by michaelschattgen** [comment]
No news, a PR to implement this has been opened but we just didn't find the time to review it yet.
