### ISSUE TITLE
Add support for Proton Drive

### ISSUE THREAD

**Issue by d4f5409d** [beemdevelopment/Aegis#1109]
Please add support for having a backup via Proton Drive. Thank you.

**Comment by alexbakker** [comment]
Thanks for the suggestion, but we don't have plans to add support for specific cloud providers. If Proton Drive has an Android app that fully participates in Android's Storage Access Framework, Aegis will be able to back up to it.

**Comment by skariko** [comment]
> Thanks for the suggestion, but we don't have plans to add support for specific cloud providers. If Proton Drive has an Android app that fully participates in Android's Storage Access Framework, Aegis will be able to back up to it.

Hello,
I noticed that Proton Drive is built into Android and can be seen while browsing files whereas with Aegis it does not appear.

Is there any particular reason for this? I attach the screenshots: the first is file manager and the second is Aegis.

![Screenshot_20231006-221302](https://github.com/beemdevelopment/Aegis/assets/25532821/d283b70c-fea0-4f02-aac3-f2670ab67f08)
![Screenshot_20231006-221317](https://github.com/beemdevelopment/Aegis/assets/25532821/34630117-28f4-4cab-9402-e6e0654df70f)

**Comment by alexbakker** [comment]
The problem is that Proton Drive does not appear to support selection of a folder: [ACTION_OPEN_DOCUMENT_TREE](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE). Creating a single export on your Proton Drive should work, but using it for automatic backups will not.
