### ISSUE TITLE
andOTP import does not work

### ISSUE THREAD

**Issue by williamdes** [beemdevelopment/Aegis#1110]
### Version

2.1.3

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Redmi Note 10 Pro

### Android version

12

### Steps to reproduce

- Have andOTP 0.9.1-play
- Export as plain text
- Import in Aegis (first time open of Aegis)
- Weird JSON import error, import failed
- Go back to andOTP
- Export as encrypted
- Import in Aegis (first time open of Aegis)
- Fails horribly, does not understand it's an andOTP encrypted backup.

Maybe add a safety for this last one, because it displays the first chars of the file. Maybe it could be a security issue.

### What do you expect to happen?

plain text and encrypted backups to import

### What happens instead?

See "Steps to reproduce"

**Comment by alexbakker** [comment]
In the initial setup screen, you can only import Aegis vault exports/backups. If you want to import from a different app, go through the setup process first and then go to Settings -> Import & Export.

**Comment by williamdes** [comment]
> In the initial setup screen, you can only import Aegis vault exports/backups. If you want to import from a different app, go through the setup process first and then go to Settings -> Import & Export.

Okay, maybe add a bit of safety there?
