### ISSUE TITLE
Aegis crashed on launching. 

### ISSUE THREAD

**Issue by sangampanda** [beemdevelopment/Aegis#1115]
### Version

2.1.3

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Realme X2

### Android version

Android 11

### ROM

Default (RealmeUI 2.0)

### Steps to reproduce

Randomly started crashing immediately on launch, no new accounts added, previous used it to login 2 days before the bug occurred.

### What do you expect to happen?

It shouldn't crash, nor it should clear the data just after a crash. 

### What happens instead?

It crashes. 
<img src="https://user-images.githubusercontent.com/46146023/227718007-4f73bdee-c19e-42f9-899f-9eed4e42c923.jpg" width="200"/>

Also, after restarting the device, aegis data got cleared!

**Comment by alexbakker** [comment]
Can you still reproduce this? If so, please [collect a log of the crash](https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb) and share it here.

Did you have "Android cloud backups" enabled in Aegis?

> nor it should clear the data just after a crash

Aegis does not clear its internal storage on its own. Did you press the "Clear immediately" button displayed in the screenshot? It's not entirely clear to me, but it sounds like that may do it.

**Comment by sangampanda** [comment]
> Can you still reproduce this? If so, please [collect a log of the crash](https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb) and share it here.
> 
> Did you have "Android cloud backups" enabled in Aegis?
> 
> > nor it should clear the data just after a crash
> 
> Aegis does not clear its internal storage on its own. Did you press the "Clear immediately" button displayed in the screenshot? It's not entirely clear to me, but it sounds like that may do it.

Can't reproduce, unfortunately lost all logs as well.
I did press the clear immediately button as I thought it's for clearing app from ram. That kinda explains how I lost my data. But even after that clear I wasn't able to open the app. It wasn't until a reboot I was.able to open it.
