### ISSUE TITLE
biometric authentication as first method

### ISSUE THREAD

**Issue by DunkelBlauer** [beemdevelopment/Aegis#1116]
Every time I start the app I am asked for the password to unlock it. 
Would it be possible to set biometric authentication as the default method?

_OT: Thanks for this great app, just wonderful!_

**Comment by alexbakker** [comment]
https://github.com/beemdevelopment/Aegis/blob/master/FAQ.md#why-does-aegis-keep-prompting-me-for-my-password-even-though-i-have-enabled-biometric-authentication
