### ISSUE TITLE
Add an option to show uncropped icons

### ISSUE THREAD

**Issue by sabi0** [beemdevelopment/Aegis#1118]
Not every icon / logo looks nice cropped to a circle.
Take for instance Microsoft logo:
![image](https://user-images.githubusercontent.com/11509875/229502858-5d9a569b-1c6e-46db-ba0b-053764cf7cba.png)

The icon looks nicer in the (legacy) FreeOTP:
![image](https://user-images.githubusercontent.com/11509875/229502939-16e221cf-7f10-43e7-abb2-0178df08a75a.png)

I would love to have full control over how the entries' icons are displayed.

**Comment by alexbakker** [comment]
Duplicate of #216.
