### ISSUE TITLE
cant import backup .json file

### ISSUE THREAD

**Issue by stakoholic** [beemdevelopment/Aegis#1119]
### Version

2.1.3

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Mi11 lite 5G

### Android version

android 12

### ROM

lineage os 19

### Steps to reproduce

Hello, i switched from lineage 18 to 19 and so i made a backup in aegis and export the  .json file, now i want import it and it comes directly an error?? on my pc i can decrypt the file successfull with the provided python script 

### What do you expect to happen?

importing my keys

### What happens instead?

com.beemdevelopment.aegis.importers.DatabaseImporterException: com.beemdevelopment.aegis.vault.VaultFileException: org.json.JSONException: Value of type java.lang.String cannot be converted to JSONObject

**Comment by Buraus** [comment]
same

**Comment by alexbakker** [comment]
@stakoholic, @Buraus Can you open that JSON file in a text editor and take a look at the structure (don't share it here)? Is it similar to https://github.com/beemdevelopment/Aegis/blob/efd8e2d9ff25f59e3d4bcaab664641b0e45761e4/app/src/test/resources/com/beemdevelopment/aegis/importers/aegis_encrypted.json? If not, what's different? 

> on my pc i can decrypt the file successfull with the provided python script

Are you 100% sure it's the same file? Similar question: What does the resulting structure look like? Does it look similar to the object under "db" in https://github.com/beemdevelopment/Aegis/blob/efd8e2d9ff25f59e3d4bcaab664641b0e45761e4/app/src/test/resources/com/beemdevelopment/aegis/importers/aegis_plain.json? If not, what's different? 

@albotroz That's unrelated. Aegis does not support FreeOTP's new format yet. See: #1084.

**Comment by stakoholic** [comment]
@alexbakker 
when i open the json file, the difference i see is, i have in the slots, a  "type": 2, and after the "repaired": true there "is_backup": false . and yes i can decrypt the same json and there is no "db" this the header
{
    "version": 2,
    "entries": [

**Comment by alexbakker** [comment]
@stakoholic Are you trying to import the file that resulted from that ``decrypt.py`` script into Aegis? That's not going to work. As you noticed, that script just decrypts what's under "db" and is not actually a valid Aegis vault file.

**Comment by stakoholic** [comment]
@alexbakker no there is only one exported encrypted aegis_export...json, and when i try to import this .json i get that error. this exactly same encrypted vault, i can decrypt in the shell and i get only the output in the shell, the decrypt.py script dont create a new file from this .json , i would need to make this manually, what I have not done, because i know i need the encrypted .json for the import

**Comment by stakoholic** [comment]
@alexbakker is there are difference between export the database via import/export menu and trigger manually backup??
because i exported the database and get the error when try to import it again, but when i trigger manually a backup, importing this file is successfully working, so for what purpose is the export database function ??

**Comment by alexbakker** [comment]
There is no format difference between backups and exports. I really don't understand what's going on here.

Can you create a screen recording of you reproducing the issue? (Temporarily disable "Screen security" in Aegis' settings first). Start by triggering a manual backup and import that file to prove that this works. Then create an export and try to import that file to prove that that fails.

While you're doing this, have an ADB log capture running in the background.

Share the screen recording and the log capture with us.

**Comment by michaelschattgen** [comment]
Any news on this? Unfortunately there's nothing we can do here without more information. I'm closing this issue for now but we will re-open this in case we receive similar reports.
