### ISSUE TITLE
Double tap to copy option

### ISSUE THREAD

**Issue by JD21P** [beemdevelopment/Aegis#1120]
Hi, I like using the tap to highlight & tap to copy behaviours, however could a double tap to copy option be added also? Thanks :-)

**Comment by alexbakker** [comment]
Double tap is also the current behavior for the combination of tap to reveal and tap to copy. It may make sense to do the same here, though not everybody was happy when we made that change previously: https://github.com/beemdevelopment/Aegis/issues/1064.
