### ISSUE TITLE
Delete a entry by searching can cause vaults list empty

### ISSUE THREAD

**Issue by gracie95** [beemdevelopment/Aegis#1123]
### Version

v2.1.3

### Source

F-Droid

### Vault encryption

Yes

### Device

Galaxy A52

### Android version

Android 13

### Steps to reproduce

https://user-images.githubusercontent.com/107738923/234354720-03df54ef-eec3-474e-b208-42d312c54630.mp4

1. Go and search a entry (with single result)
2. Delete the entry
3. Remove the text you type.
4. Entries become empty

### What do you expect to happen?

It should show all entries.

### What happens instead?

Entries are empty.

**Comment by alexbakker** [comment]
Duplicate of #1099.
