### ISSUE TITLE
Biometric unlock enabled but doesn't work after import through setup

### ISSUE THREAD

**Issue by DomHeadroom** [beemdevelopment/Aegis#1126]
### Version

2.1.3

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Poco X3 NFC

### Android version

Android 13

### ROM

LineageOS 20

### Steps to reproduce

Make a backup of a vault with a biometric unlock set, delete the app data, then import the backup done before. 

### What do you expect to happen?

Aegis to unlock with biometric data (or atleast uncheck the biometric unlock setting)

### What happens instead?

The unlock with biometric data is checked, but Aegis always ask for the password and never for the biometric unlock.

**Comment by Suncatcher** [comment]
Yes, very look like I experienced the same. I imported the vault from another phone and biometric unlock disappeared from UI

**Comment by alexbakker** [comment]
Thanks for the report. I suspect you guys imported the vault through the setup screen, not through the "Import & Export" menu. The difference between those two screens is that the former copies the entire vault file (including the biometric key slot that is no longer valid), while the latter only reads entries from the file and imports those into the existing vault file.  

We should strip that biometric key slot, but I'm not sure yet where we should do that. Either during export/backup or during import.

The same issue exists in the BackupAgent, by the way.

@Domefemia As a workaround for now, disabling and re-enabling biometrics in Aegis' settings should fix this issue.

**Comment by Domefemia** [comment]
Yes I confirm this happened to me by importing the backup from the prompt in the setup screen.

**Comment by ALISHERkhan11100** [comment]
> ### Version
> 2.1.3
> 
> ### Source
> F-Droid
> 
> ### Vault encryption
> Yes (with biometric unlock)
> 
> ### Device
> Poco X3 NFC
> 
> ### Android version
> Android 13
> 
> ### ROM
> LineageOS 20
> 
> ### Steps to reproduce
> Make a backup of a vault with a biometric unlock set, delete the app data, then import the backup done before.
> 
> ### What do you expect to happen?
> Aegis to unlock with biometric data (or atleast uncheck the biometric unlock setting)
> 
> ### What happens instead?
> The unlock with biometric data is checked, but Aegis always ask for the password and never for the biometric unlock.
> 
> ### Log
> _No response_

#Google.pixel.luncher

**Comment by ALISHERkhan11100** [comment]
<details><summary>Details</summary>
<p>

Google  pixel Home 

</p>
</details>
