### ISSUE TITLE
Lost password

### ISSUE THREAD

**Issue by siriusstar2007** [beemdevelopment/Aegis#1128]
Hello,

I lost the password to my Aegis safe. To have access to my safe, I was using only the biometrics so little by little I forgot the written password!
The problem is that I just changed the fingerprint I use to unlock my smartphone and when I go back to the Aegis application, I am asked to unlock my safe only with the password.
How do I get my password back please?

Thank you very much!

**Comment by oviliz** [comment]
When setting the password up that's the first thing we are warned. Without the password there is no way back.

**Comment by alexbakker** [comment]
I'm sorry to hear you're in this situation, but I'm afraid there's nothing we can do to help. There's no way to recover the password or reset it. Aegis should have periodically asked you to enter your password, so that you don't forget it. Did you have the password reminder disabled?
