### ISSUE TITLE
Automatically sort tokens by usage frequency

### ISSUE THREAD

**Issue by keystrike** [beemdevelopment/Aegis#1129]
## Feature description
*Summary*: Implement a sorting option to automatically sort tokens by usage frequency.

*Background*: Many users have 50 or more tokens saved in the app, making it time-consuming to scroll through them or search by text.

*Details*: Add an option to sort tokens based on how frequently they are used. The app should remember the number of times each token is used and automatically sort them accordingly. The existing "sort by usage count" option is unclear, so there should be a system for letting the app know which code was used.

*Alternative approach*: Tokens could be grouped into three categories: frequently used, occasionally used, and rarely used. This would require tracking the time each token is used so that statistics can be applied to sort them into the appropriate category. This categorization could make it even easier for users to find and access their most commonly used tokens.

*Benefits*: This feature will help users navigate through their tokens more quickly and efficiently, improving the overall user experience.

*Possible implementation*: A counter could be added to each token, which would increment every time a token is used. The sorting algorithm would then sort the tokens based on this counter's value.

**Comment by RDKRACZ** [comment]
I don't get it. What is missing in this option?

![Screenshot_20230520-141038.jpg](https://github.com/beemdevelopment/Aegis/assets/43277609/e83d030c-67e5-4d40-98a3-b3278fc721f0)

**Comment by keystrike** [comment]
After resetting the usage count numbers and adjusting the tokens to copy, highlight, and freeze upon tapping, the system is working perfectly. Previously, tapping on tokens was not a step I would typically take, as the necessity of doing so wasn't quite apparent, especially given that I hadn't been utilizing the usage count sorting feature. However, with these adjustments the tokens are now sorting themselves which makes it easier to find what I need.

I believe there could still be improvements made in terms of usability. Specifically, I'd propose that the usage count for each token be displayed directly on the main screen, potentially in the bottom right corner of each token. This would offer a more immediate, at-a-glance understanding of each token's usage, thereby enhancing navigation and decision-making for users managing a large collection of tokens.

**Comment by eliotb** [comment]
Coming from andOTP,  I was using the option "Last used" for sorting.   I.e. the ones I used most recently come to the top.   this accommodates changing usage pattern over time.

**Comment by michaelschattgen** [comment]
Thanks for your report, as you noticed we already have this feature and it's currently working as intended. We don't think we like showing the usage count on each token individually but we're open to other ideas on how to make this feature more clear.
