### ISSUE TITLE
Cannot import vault

### ISSUE THREAD

**Issue by Anja-dhnd** [beemdevelopment/Aegis#1130]
### Version

v2.1.3

### Source

F-Droid

### Vault encryption

Yes

### Device

Pixel 4 XL

### Android version

Android 13

### ROM

GrapheneOS

### Steps to reproduce

1. Open the app
2. Tap import vault
3. Choose aegis backup file exported in .json

### What do you expect to happen?

My vault to be imported, or at least to be prompted to enter the password of the vault

### What happens instead?

An error appears with the following message:

com.beemdevelopment.aegis.importers.DatabaseImporterException: com.beemdevelopment.aegis.vault.VaultFileException: org.json.JSONException: Value HBEGIN of type java.lang.String cannot be converted to JSONObject

And I am blocked because all my accounts rely on this vault...

**Comment by michaelschattgen** [comment]
Thank you for your report and we're sorry to hear that you're having issues. It looks like you're trying to import an encrypted file (not encrypted by Aegis) which our app isn't able to read. Are you importing the json file from a service like Nextcloud or ownCloud? We found the following documentation regarding encryption used on those platforms which led us to this conclusion:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_details.html#id1

How exactly are you importing the file? Through the androids default file picker or through a file provider?

**Comment by alexbakker** [comment]
No response. I think it's fair to assume that @michaelschattgen's assessment was accurate.
