### ISSUE TITLE
support SeedVault backups

### ISSUE THREAD

**Issue by uniqx** [beemdevelopment/Aegis#1131]
I deem [SeedVault](https://github.com/seedvault-app/seedvault#seedvault) safe enough for my OTP backups. However Aegis seems to have disabled support for Android/SeedVault Backups.

**Comment by uniqx** [comment]
Under "Settings" > "Backups" I can see 3 options:

* Automatically backup the vault - greyed out (i.e. doesn't let me tap to activate it) and disabled
* Backup reminder - enabled
* Android Cloud backups - greyed out (i.e. doesn't let me tap to activate it) and disabled

I'm using the latest Aegis from f-droid.org (2.1.3) on the latest CalyxOS (4.9.0, Android 13, SeedVault built in as default backup solution)

**Comment by alexbakker** [comment]
That setting is only available if you have enabled encryption for your Aegis vault.

**Comment by uniqx** [comment]
Thanks that helped! Got my backups setup now. :)
