### ISSUE TITLE
Make please AEGIS on Linux!

### ISSUE THREAD

**Issue by VXEAD** [beemdevelopment/Aegis#1136]
Hi, i like your app so match. But i use very bad OTPC/2FA client
Make AEGIS cross-platform and make flatpak!

**Comment by Max1385** [comment]
Hey, do you know if the aegis backup can also be used with OneDrive? Nothing shows up on my Samsung phone.

**Comment by Max1385** [comment]
Hey, do you know if the aegis backup can also be used with OneDrive? Nothing shows up on my Samsung phone.

**Comment by VXEAD** [comment]
> Hey, do you know if the aegis backup can also be used with OneDrive? Nothing shows up on my Samsung phone.

Idk i make encrypted json file and upload to my clowd!

**Comment by Max1385** [comment]
Oh well, okay. :D

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alexbakker** [comment]
Duplicate of #165.

**Comment by VXEAD** [comment]
> Duplicate of #165.

ok, whats good alternative to Aegis on Limux? 
Spoiler: nothing

**Comment by VXEAD** [comment]
> 

Yeap, but i need some TOTP/2FA like Aegis on my Linux, i have trouble with [GNOME auth](https://github.com/beemdevelopment/Aegis/issues/1136#issuecomment-1580146849) , im installed OTPC Client, but he look like shit. Btw, -_- install Yubikey, but i dont have Yubikey = im dumb, so i cant use Yubikey, cause i need login.

**Comment by egooner** [comment]
I have created a client that uses the Aegis backup (copied over using Sync thing) I can put that up on GITHub if it might help people ... It's not pretty but it's functional

**Comment by Granddave** [comment]
Here's a CLI utility I've written that uses the backup file just like @egooner mentioned.
See if that is something that would work for you as well @Devious3901. 

https://github.com/Granddave/aegis-rs
