### ISSUE TITLE
Being able to login with fingerprint after having added additional fingerprint to android system

### ISSUE THREAD

**Issue by enterausernameenter** [beemdevelopment/Aegis#1138]
Hey,

as the title says, after having added another fingerprint I can only unlock the vault with the password and not with the fingerprint.

(as you might have rightfully assumed, I have forgotten my password and have been opening the vault by fingerprint only for some time now. I added another fingerprint and now when opening the app I get this notification:

_A change in your device's security settings has been detected. Please go to "Aegis -> Settings -> Security -> Biometric unlock" to disable and re-enable biometric unlock._

Unfortunately I can't.

Does someone have any suggestions?

**Comment by alexbakker** [comment]
The only option in this situation is to use the password to decrypt the vault. If you don't remember your password, I'm afraid there's no way to recover the contents of your Aegis vault.
