### ISSUE TITLE
Use the android storage access framework for cloud-backup and exports

### ISSUE THREAD

**Issue by R1123345** [beemdevelopment/Aegis#1139]
Aegis currently does not use saf (storage acces framework)/document picker to select a folder for import/export/backups. 
That means that apps used for cloud storage (google drive/dropbox/icloud/protondrive/tresorit etc.) Cannot be selected, regardless of the storage permission given to aegis.

Is it possible to use document picker for this?

**Comment by alexbakker** [comment]
Aegis does use SAF to select the folder for backups. Some cloud providers don't implement ``ACTION_OPEN_DOCUMENT_TREE`` though and thus don't support selecting a folder.
