### ISSUE TITLE
Searching for Proton shows multiple entries not named Proton

### ISSUE THREAD

**Issue by ZippierOstrich1** [beemdevelopment/Aegis#1141]
### Version

v2.1.3

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Fairphone 3

### Android version

Android 13

### ROM

LineageOS with microG

### Steps to reproduce

- open Aegis
- search for Proton

### What do you expect to happen?

shown only one entry named Proton

### What happens instead?

gets shown multiple entries (16 in total), although not named Proton
![Screenshot_20230611-124135_Aegis](https://github.com/beemdevelopment/Aegis/assets/29605737/bbe774e5-d6bc-4d71-9db0-2f83ca26b1b7)

**Comment by michaelschattgen** [comment]
Thanks for your report. It's hard for us to determine what causes this issue this way, but could you perhaps have 16 accounts signed up with a protonmail email address which are saved under the name field of an entry? The search feature also looks at the names of the accounts.

**Comment by michaelschattgen** [comment]
No worries, glad we found the problem! 

No it's not possible to change the search function and I don't think we will implement this as I doubt many users are running into this. Obviously we can rethink this as we're getting more reports similar to yours. I suggest changing your Proton entry to something like Proton Email (or anything else you'd prefer over 'email') so you can just seach for "email" and Proton pops up. Not the nicest workaround but it works!
