### ISSUE TITLE
[Feature Request] Option for Custom time/timezone and generating codes based on in-app time

### ISSUE THREAD

**Issue by chromer030** [beemdevelopment/Aegis#1145]
Use case is for users changing timezone frequently (on trip) or users using spoof timezone extensions for more privacy and security.

Thanks.

**Comment by alexbakker** [comment]
I don't really understand your request. Traveling to different timezones has no effect on Aegis as long as the time set on your device is correct for the timezone you're in.

**Comment by chromer030** [comment]
It's OK when the generated code will be used on same phone , but i mean when it's on a desktop browser with spoofed timezone / different location / different time etc

**Comment by alexbakker** [comment]
It's not the browser that looks at the time, but the server of the service you're trying to log into.
