### ISSUE TITLE
Default app for otpauth: protocol

### ISSUE THREAD

**Issue by burtek** [beemdevelopment/Aegis#1147]
I know Aegis supports otpauth: protocol, but when I click such link in web browser, MS Authenticator opens rather than Aegis and I can't find an option to make Aegis a default one for such links. Lemmy instances of 0.18.0 use such links as example. It would be great if Aegis had an option that would set it as default within Android to open such links

**Comment by michaelschattgen** [comment]
Thank you for your feature request. After doing some research on this I think unfortunately there's nothing we can do here. Default apps for opening links like otpauth:// are done entirely by Android itself; we don't have control over your default apps and we can't programmatically set Aegis as the default. I **think** the only way to solve this is to go to the settings of MS Authenticator in your Android settings and press "Clear default preferences" as shown in the screenshot below. After this Android will ask you what app you want to use to handle your otpauth:// links again.

[<img width=350 alt="Screenshot"
src="https://github.com/beemdevelopment/Aegis/assets/7524012/58d8b2c4-d0a1-43b0-8516-6dca8bb143e8">](https://github.com/beemdevelopment/Aegis/assets/7524012/58d8b2c4-d0a1-43b0-8516-6dca8bb143e8)

Closing this as this is not something we can solve for you, but feel free to continue the conversation going.
