### ISSUE TITLE
Update to Material Design 3 

### ISSUE THREAD

**Issue by Wojtaz0w** [beemdevelopment/Aegis#1149]
Hi. I updated Aegis to MD3 and it looks really good to me. This is my first commit to any Android app ever so please expect some beginner issues🙂I would also be very grateful if you would accept this - I spent a lot of time writing this. Here's the repo: https://github.com/Wojtaz0w/Aegis-MD3 and here are some screenshots.
![obraz](https://github.com/beemdevelopment/Aegis/assets/104674625/3083ca0a-aa78-426e-b284-aed811a0599a)
![obraz](https://github.com/beemdevelopment/Aegis/assets/104674625/8c8675d3-4b4f-4772-88e6-c4a59a2ac7de)
![obraz](https://github.com/beemdevelopment/Aegis/assets/104674625/8358e3bd-ac04-4e66-9951-43ab60c55de9)
![obraz](https://github.com/beemdevelopment/Aegis/assets/104674625/dc4100bb-eb81-46b6-90ee-538cfa35f08c)

**Comment by Wojtaz0w** [comment]
> duplicate of #842

 but i actually started working on it

**Comment by ubionexd** [comment]
You should create a pull request.

**Comment by Wojtaz0w** [comment]
> You should create a pull request.

Soon™

**Comment by Wojtaz0w** [comment]
I'm back!!!
Now Dialogs are rounded!!!
![obraz](https://github.com/beemdevelopment/Aegis/assets/104674625/cf0d451d-983e-452a-9d00-b0d403bb04da)

**Comment by Wojtaz0w** [comment]
PR will be ready today!!

**Comment by TeaOwO** [comment]
> PR will be ready today!!

Any more proggress on the PR

**Comment by Wojtaz0w** [comment]
I'm currently working on fixing bottom sheet corners. also i have school, so I think PR will be ready tomorrow or on Saturday.

**Comment by Wojtaz0w** [comment]
https://github.com/beemdevelopment/Aegis/pull/1208

**Comment by Wojtaz0w** [comment]
FYI for everyone who's been interested:
My PR has been rejected. Not gonna lie, that really hurt me. Authors said they will "soon" begin integrating MD3 by themselves. I am considering creating and maintaining a fork which will be basically upstream Aegis with my patches. If that's desired by anyone please let me know.

**Comment by michaelschattgen** [comment]
@Wojtaz0w We have been working on it. Here's the draft PR for Material 3: #1149.

**Comment by Wojtaz0w** [comment]
Oh. I didn't notice. Closing this issue then
