### ISSUE TITLE
Add ability to automatically adapt to Android Q's dark mode / battery saver

### ISSUE THREAD

**Issue by michaelschattgen** [beemdevelopment/Aegis#115]
Android Q comes with a built-in dark mode. This version of Android allows developers to automatically change the UI of their app when Androids dark mode or battery saver is enabled.

It would be nice if Aegis changes the theme to Dark or OLED mode (user preference?) when I have dark mode enabled.

**Comment by rodrigoswz** [comment]
Any progress on this feature request? I really would like that, only the Aegis, Bitwarden and Telegram X on my device don't follow Android 10 dark mode yet

**Comment by alexbakker** [comment]
I don't think anyone's currently working on this. Would you like to give it a shot?
