### ISSUE TITLE
Automatically start biometric unlock

### ISSUE THREAD

**Issue by jokakilla** [beemdevelopment/Aegis#1151]
Hi all,
first: Thanks for your  effort in developing the app. It's already awesome!
But there is one thing bugging me. I'm using biometric unlock (fingerprint). Everytime I want to use the app I first need to press the small "button_biometrics" textView to start unlocking with fingerprint.

I'd like to add a preference (by default off) to automatically start unlocking with biometrics but first wanted to hear your opinion about that before starting with an implementation.

I guess it shouldn't be much effort.
- New SwitchPreference in SecurityPreferenceFragment depending on the Biometrics Preference.
- Let AuthActivity.onCreate check preference and preconditions and call showBiometricPrompt.

**Comment by michaelschattgen** [comment]
Hey! Thanks for considering contributing to Aegis.

But are you sure you're not running into our password reminder? We implemented a password reminder to decrease the chances of people forgetting their passwords. If someone forgets their password, they may lose access to their vault. You can either type in your password once (recommended), or disable the password reminder in the settings.

https://github.com/beemdevelopment/Aegis/blob/master/FAQ.md#why-does-aegis-keep-prompting-me-for-my-password-even-though-i-have-enabled-biometric-authentication

**Comment by jokakilla** [comment]
Hey, I just had a look at the AuthActivity. It seems like in the onResume there is a check for remindPassword. I guess this would avoid automatically bio prompt when the password reminder is active.

I guess the easiest thing would be calling startAuthActivity from MainActivity with parameter true when the preference is true. AuthActivity would respect the reminder nevertheless.

May I prepare a change and you can check it?

**Comment by michaelschattgen** [comment]
I'm not quite sure if I follow you here. It's our intended behaviour to not show the biometrics dialog if the app thinks it's time for the password reminder. We want to make sure our users are aware that their vault is protected by a password and that forgetting that password could potentially mean losing their vault.

You can already make the biometrics default again if you either enter your password once (so the reminder goes away) or by disabling the reminder.

Could you please elaborate on what you want to achieve?

**Comment by jokakilla** [comment]
I've forked the repo and made a change on my fork: https://github.com/jokakilla/Aegis/commit/f7d5f3fb02f52b7292ae354fbb4f3521e772fe53

When the app is started an the preference "pref_auto_biometrics" is true AND the remindPassword flag isn't set the AuthActivity will show the biometrics prompt. This way I don't have to press "button_biometrics" on each app start.

Because the condition still checks remindPassword I guess it shouldn't break the password reminder functionality.
```
        if (_bioKey != null && _bioPrompt == null && _prefs.isAutoBiometrics() && !_inhibitBioPrompt && !remindPassword) {
```

**Comment by michaelschattgen** [comment]
I appreciate the effort you put into this but I feel like you've disregarded my previous explanations, There is no need for this change if the user either enters their password **once** or they disable the password reminder all together. Having this "auto biometrics" toggle completely defeats the purpose of why we implemented this reminder. We **want** to force the user to enter their password instead of using biometrics because losing your password puts you at risk of losing access to your tokens.

Disable the password reminder and you'll see that biometrics automatically pop up upon opening the app.

While I agree that the connection between the password reminder and the biometrics popup may be somewhat unclear, this behavior is intentional.

**Comment by jokakilla** [comment]
Oh man. Finally got it. Sorry was too stupid to get it and too lazy to type the password once.

Maybe it could make sense to add a hint to the view that biometric dialog isn't shown automatically because of the reminder funtionality?

**Comment by michaelschattgen** [comment]
All good! My apologies if I wasn't being clear enough and we appreciate your effort.

We've had multiple reports similar to yours and we agree we have to make this more clear (see #989). We assume the password reminder tooltip doesn't work on every device or people are just too quick dismissing it.
