### ISSUE TITLE
Support plus sign in email addresses

### ISSUE THREAD

**Issue by myksmith** [beemdevelopment/Aegis#1153]
### Version

2.1.3

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 6 Pro

### Android version

Android 13

### ROM

no; standard ROM

### Steps to reproduce

Attempted to import account with a plus sign (+) in the email address via both:
- qr code image import from Google Authenticator
- direct QR code scan from web site
Both caused the import to error.

When I removed that account from the export list from Google Authenticator it worked fine.

Use case: I have a paypal account for the USA with my primary address and for the UK using a plus sign. Using a plus sign in a gmail account is a fairly standard "hack".

### What do you expect to happen?

I expected the import or account addition to work 

### What happens instead?

Error message on import

**Comment by alexbakker** [comment]
What does the error message say?

**Comment by myksmith** [comment]
Closing. I attempted to duplicate and it worked in BOTH cases. I have no idea what didn't work the first time.

**Comment by myksmith** [comment]
Could not dupe
