### ISSUE TITLE
scanning works unreliably on Oneplus 8T 

### ISSUE THREAD

**Issue by 07416** [beemdevelopment/Aegis#1154]
### Version

2.1.3

### Source

F-Droid

### Vault encryption

Yes

### Device

Oneplus 8T

### Android version

13

### ROM

LineageOS 20

### Steps to reproduce

attempt to scan an image:

![github](https://github.com/beemdevelopment/Aegis/assets/14923168/1aa569fc-fd47-49e9-a673-484ca3e3f383)

```
image.svg:
com.beemdevelopment.aegis.helpers.QrCodeHelper$DecodeError: Unable to decode stream to bitmap
```

![image](https://github.com/beemdevelopment/Aegis/assets/14923168/693e9569-a9ee-4f32-ae2b-0f84df3a58d5)

```
image.png:
com.beemdevelopment.aegis.helpers.QrCodeHelper$DecodeError: com.google.zxing.NotFoundException
```

### What do you expect to happen?

The QR code is read near-immediately.

### What happens instead?

The QR code isn't practically detected. 

Scanning via camera has worked very reliably in the past — I've used past versions of Aegis on at least Oneplus 5T, 3T and the original Oneplus One. Now I was only able to get the PNG image detected once after minutes (the issuer didn't accept the code, may have been read incorrectly).

**Comment by alexbakker** [comment]
Both of these QR code images are invalid because they lack white padding around them (i.e. the quiet zone). Also, Aegis does not support scanning QR codes from SVG files.

**Comment by 07416** [comment]
The issue was caused by [the Dark Reader addon](https://github.com/darkreader/darkreader/).
