### ISSUE TITLE
Donations to Aegis : Create new donation channels

### ISSUE THREAD

**Issue by TeddyTeddy** [beemdevelopment/Aegis#1156]
Hi!

Gr8 work! Want to donate money, but current methods forcing to disclose credit card number.
Can you create new payment channels enabling EUR and $ payments? At least via Paypal? And others?
Also consider creating wallets attached to all main blockchains. At least, PulseChain has much lower tx fees.

Thanks!

**Comment by michaelschattgen** [comment]
Hi, thank you for considering donating, highly appreciated! As far as I know BuyMeACoffee uses Stripe payments and thus supports PayPal. We also have a btc address if you want to support us that way. 

https://www.blockchain.com/explorer/addresses/btc/bc1q26kyxqjkc6tu477pzy0whagwhs4ypv93qls22n

**Comment by TeddyTeddy** [comment]
Nope. Stripe is asking for credit card number. Don't have BTC to send either.

**Comment by Maroko** [comment]
Could you add support for https://liberapay.com/ where Paypal Donations are possible?
