### ISSUE TITLE
Add option to default to biometrics

### ISSUE THREAD

**Issue by eater** [beemdevelopment/Aegis#1159]
Whenever I open the Android app, it opens the keyboard for me to type in a password. In order for me to use biometric authentication, which I prefer, I have to take two extra steps: first, dismiss the automatic keyboard popup, which is in the way; second, tap the "Biometrics" link.

It would be a much smoother user experience if I didn't have to go through those steps each time I open the app, a dozen times a day or more.

**Comment by michaelschattgen** [comment]
You're probably running into our password reminder! We implemented a password reminder to decrease the chances of people forgetting their passwords. If someone forgets their password, they may lose access to their vault. You can either type in your password once (recommended), or disable the password reminder in the settings.

https://github.com/beemdevelopment/Aegis/blob/master/FAQ.md#why-does-aegis-keep-prompting-me-for-my-password-even-though-i-have-enabled-biometric-authentication

Closing this now but feel free to continue the conversation

**Comment by eater** [comment]
Ahh, you are right. It wasn't clear to me that it was a reminder prompt, rather than a necessary login prompt. Maybe that could be made clearer in the interface somehow. And I looked through the settings and I saw "Password Reminder" but I didn't guess that that was the setting I needed to change.

**Comment by michaelschattgen** [comment]
You're completely right and it's still something we have to make more clear as it would definitely improve the user experience. Glad it solved the issue for you though!

**Comment by fyksen** [comment]
> You're probably running into our password reminder! We implemented a password reminder to decrease the chances of people forgetting their passwords. If someone forgets their password, they may lose access to their vault. You can either type in your password once (recommended), or disable the password reminder in the settings.
> 
> https://github.com/beemdevelopment/Aegis/blob/master/FAQ.md#why-does-aegis-keep-prompting-me-for-my-password-even-though-i-have-enabled-biometric-authentication
> 
> Closing this now but feel free to continue the conversation

Thanks for this. I had the same issue. Is it possible to make it clearer for the user that this is a password reminder, so they don't just ignore it, and use the biometrics?

**Comment by michaelschattgen** [comment]
Absolutely, we already released a beta version which contains #1163. It shows a dialog when the password reminder is active and the user still manually clicks on "biometrics" explaining why the biometrics unlock wasn't showing. We're planning on releasing this update to production today.
