### ISSUE TITLE
Proposal: Aegis Sync (Cloud/Desktop autofill)

### ISSUE THREAD

**Issue by 1fexd** [beemdevelopment/Aegis#1164]
Hello,

first of all, thanks great app, I have been using it for years and it is always a pleasure, but I lately, I have noticed some "problems" / things I'd like to see implemented/**implement myself**. I therefore propose the following:

# Aegis Sync: A backup and desktop autofill service

### Backup service

**Why:** Currently, I am using [DAVx⁵](https://f-droid.org/en/packages/at.bitfire.davdroid/) to mount a remote WebDAV share into my file system, then select this directory in Aegis for backups. This works fine at first, but after a while, the share disconnects, meaning it has to be remounted, then re-selected in Aegis. A purpose-built sync service would allow seamless synchronisation/backups.

**Specification:**
   * Sync service user credentials should be seperate from app credentials
   * Server does not need to know anything about the contents of the backup, it should just accept the encrypted JSON backup file (user storage could be limited to 500 MB or something like that)
   * Server should, of course, be open source and easily self hostable. Maybe someone could even host an official instance with a few MB free storage for everyone, but personally, I intend to host this myself. 

**Advantages:**
* Backup is backed into the app and works seamlessly
* Tokens are not (directly) accessible from outside Aegis, so it can still be considered an actual second factor

### Desktop code sharing / autofill

**Why:** While unlocking the vault with biometrics is reasonably fast, having to search for the correct code and type it into a desktop web-browser is tedious. I therefore propose building a browser extension, which connects to the sync service mentioned above. Once both the extension and Aegis are connected to the same account, the browser's context menu should be extended by the browser extension to include an option called something along the lines of "Fill two factor code". If this context menu button is clicked within a textfield, the app should receive a popup where the user just has to allow filling in the code - everything else works automatically: No code searching, no typing.

**Specification:**
   * App needs to connect via something like a Websocket to the Sync server if an account is connected and this feature is enabled.
   * Code entries need to be extended to allow hosts/domains to be added for automatic matching (alternatively, the app could prompt the user to select the correct code)
   * Communication should be encrypted with a key derived from the user's sync password
   * The "flow" of filling in a code should look like this:
       * User clicks "Fill two factor code"
       * Extension opens a websocket to the sync server, then sends a mesasge with the (encrypted) hostname
       * Server sends a message to all connected open Aegis vaults with the hostname
       * Aegis attempts to find an entry with the hostname
          * If there are multiple, or if none could be found, the user is prompted to choose one
      * The current two factor code is encrypted, and sent back to the server, which forwards it back to the extension
      * Extension fills in the code

**Advantages:**
* Makes two factor authentication way more convienient while retaining security/privacy

## Drawbacks  / Things to take into consideration

* A sync service requires server hosting - someone has to pay for that if there should be a public instance, as most users probably don't have the capabilities to self host their own server (this should be fairly cheap, as backups probably don't require a lot of storage, and if they do, they user could be asked to pay for more storage)
* Metadata is leaked: The server knows the client's IP address, backup file sizes, backup times and when two factor codes are filled in.
* Backups are hard: The server operator must assure the backups are redundantly backed up to guarantee the user backup saftey (of course, the service can be provided on a best effort basis, but there should still be redundancy)
* While a strong key can be derived from the user's sync password, there should probably be another layer of server side storage encryption (to also keep backups saved to third party services like storage buckets safe).
* There probably also should be a small web-frontend served by the sync server where users can create an account, and download backup JSON files.
* Password resets can not be offered, as the password is always needed to derive the encryption key. We therefore probably also don't need to ask the user for an email - a username shoud suffice.

As already mentioned, I would like to go ahead and implement these features, as I would really like to use them myself. For the stack, I would like to use:

* Sync server
    * Kotlin
    * Javalin (Webserver)
    * Exposed (ORM)
    * SQLite or Postgres (Database, Postgres probably not needed as SQLite scales very well)
    
* Web frontend
    * Typescript
    * SolidJS (or React, but I am a big Solid fan, so I'd prefer that - we also don't need a whole lot of functionality, so it should be fine)

* Browser extension
   * Typescript
   * Not sure, probably also Solid? I don't have a lot of experience with browser extension user interfaces

Of course, I am going to use proven cryptography. [Bitwarden's encryption](https://bitwarden.com/help/bitwarden-security-white-paper/) is quite good, so I would like to replicate it:

* Clientside:
    * Master key `MK` is derived via PBKDF2 or Argon2 from master password `MP` salted with username (265 bit)
    * Stretched master key `SMK` is `MK` stretched to 512 bit using HKDF
    * A 512 bit symetric key `SK` and Initialization Vector `IV` are generated
    * Protected symetric key `PSK` is the `SK` is encrypted with AES-256 and `SMK` as key and initialization vector `IV`
    * Master password hash `MPH` is derived via PBKDF2 with `MK` payload  and the `MP` as salt

* Serverside
   * `MPH` is sent to server and hashed again with a random salt and PBKDF2
   * `PSK` is is sent to server where it is stored in the database, so the client can retrieve it later, then decrypt to get back the `SK` which is used to encrypt backups, hostnames and two factor codes.

What do you think? Is this something we could integrate into the official app and use the Aegis "brand" for? What do you think about the stack (I am going to write specification document so there can also be other implementations)? Is this something you would like collaborate on?

**Comment by 1fexd** [comment]
I am building the backend over at [Aegis-Sync](https://github.com/1fexd/Aegis-Sync). It is currently in MVP state. App development takes place in [Aegis](https://github.com/1fexd/Aegis) (branch `feature/sync`)

**Comment by michaelschattgen** [comment]
Hey! Thank you for the very detailed proposal and the effort you took into putting this together. We haven't had time to properly discuss this internally but before you continue working on this I want to inform you that we're not planning on introducing functionality that requires a connection to the internet. This has been our policy since the beginning and it's one of the major reasons why so many people trust us. Aegis is designed to be a simple offline 2FA app and we intend to keep it that way. While breaking our users trust is our main concern here, we would also like to limit the potential attack vectors and we want to give our users full control over their vault.

We totally recognize the convenciences your proposal offers but unfortunately the points I stated are keeping us from implementing it into Aegis. I wish I had a better answer for you but hopefully you understand our stance on this.

I'm closing the issue but feel free to keep conversation going.

**Comment by 1fexd** [comment]
Could there not be two versions, one fully offline and one with online integrations?
