### ISSUE TITLE
[question] an alternative/support for android 4.1.2

### ISSUE THREAD

**Issue by FurhadTheNerd** [beemdevelopment/Aegis#1166]
i know this is such an ancient version of android, but its my old and trustful phone which nobody except me cares about that i keep hidden between my clothes, i would like to get agies or anything smilier to it working there as a physical backup

**Comment by michaelschattgen** [comment]
I'm sorry to hear that. Currently we support Android 5 (which is released in 2014) and up and we're not planning on including lower versions than that.
