### ISSUE TITLE
Fingerprint unlock not working 

### ISSUE THREAD

**Issue by burnoutprojects** [beemdevelopment/Aegis#1169]
### Version

v2.1.3

### Source

Google Play

### Vault encryption

Yes

### Device

Xiaomi Redmi Note 8 (ginkgo)

### Android version

Android 13

### ROM

Arrowos

### Steps to reproduce

* Open Aegis app
* Go to settings > security
* Press biometric unlock
* Throw error and biometric unlock remains disable.

### What do you expect to happen?

Go through same steps to enable the biometric unlock.

### What happens instead?

Throw error (see log)

### Log

com.beemdevelopment.aegis.crypto.KeyStoreHandleException: android.security.KeyStoreException: User authentication required (internal Keystore code: 2 message: In generate_key.

Caused by:
    0: In store_new_key.
    1: In store_new_key. Failed to handle super encryption.
    2: In handle_super_encryption_on_key_init. Failed to super encrypt with LskfBound key.
    3: In super_encrypt. Device is locked.
    4: Error::Rc(ResponseCode(2))) (public error code: 2 internal Keystore code: 2)

**Comment by alexbakker** [comment]
Thanks for the report, but this is a bug outside of Aegis' control. Sometimes users have had success working around this "User authentication required" issue by re-configuring their Android lockscreen/biometrics. Also, in case you have any odd Xposed modules enabled like https://github.com/beemdevelopment/Aegis/issues/299#issuecomment-600636705, try disabling them.

If that doesn't help, you could consider reporting this upstream (either to the makers your ROM or the manufacturer of your device).
