### ISSUE TITLE
Support "Duo-Protected" accounts

### ISSUE THREAD

**Issue by chiraag-nataraj** [beemdevelopment/Aegis#117]
I don't know if this is feasible, but I've slowly been migrating all my accounts over to Aegis from Duo (my previous authenticator), and the only accounts I'm not able to migrate are the so-called "Duo-Protected" ones. The QR codes are most likely non-standard, which is why the regular method fails.

**Comment by chiraag-nataraj** [comment]
Here's an implementation involving Linux and PAM (should _hopefully_ give you an idea of how to approach this): https://github.com/duosecurity/duo_unix

**Comment by alexbakker** [comment]
We can take a quick look, but I wouldn't hold my breath. This seems to integrate tightly with Duo's proprietary 2FA service.

**Comment by chiraag-nataraj** [comment]
Shouldn't we be able to generate the [HOTP tokens](https://duo.com/product/trusted-users/two-factor-authentication/authentication-methods/totp) that Duo uses as the alternative to Duo Push? I think it's just a matter of figuring out what's provided in the QR code. I'll do some more digging.

**Comment by chiraag-nataraj** [comment]
Hmm, so looking at the QR code, it seems like there are 20 alphanumeric characters, a -, and then an unchanging part of 38 alphanumeric characters. I suspect the second half is some unique ID, while the first part is based on time or request number or something. I have access to test QR code parsing and stuff, but I'm not _entirely_ sure what I should be looking for.

**Comment by michaelschattgen** [comment]
Closing this issue as we don't have plans to implement this. If someone wants to take responsibility of implementing this, feel free to restart this discussion.
