### ISSUE TITLE
Error when trying to import Authenticator Pro encrypted backup.

### ISSUE THREAD

**Issue by rafaelazvdo** [beemdevelopment/Aegis#1176]
When trying to restore an encrypted backup from Authenticator Pro, Aegis Authenticator displays an error message as shown in the screenshot below.

Android Version: 13

Aegis Version: 2.2.1

<img width="200" src="https://github.com/beemdevelopment/Aegis/assets/122113441/88ef1088-a0f5-4529-83d4-99ac8651f3ad"/>

**Comment by alexbakker** [comment]
I'll take a look at this later today. We took so long to release this feature that their format has already changed again.

**Comment by rafaelazvdo** [comment]
That's exactly it, the change occurred from version 1.19.0, backups made in versions 1.18.0 and older, can be restored in Aegis.

**Comment by rafaelazvdo** [comment]
> I'll take a look at this later today. We took so long to release this feature that their format has already changed again.

That's exactly it, the change occurred from version 1.19.0, backups made in versions 1.18.0 and older, can be restored in Aegis.

**Comment by rafaelazvdo** [comment]
> I'll take a look at this later today. We took so long to release this feature that their format has already changed again.

That's exactly it, the change occurred from version 1.19.0 of Authenticator Pro, backups made in versions 1.18.0 and older, can be restored in Aegis.

**Comment by alexbakker** [comment]
The fix for this is included in [v2.2.2](https://github.com/beemdevelopment/Aegis/releases/tag/v2.2.2)

**Comment by rafaelazvdo** [comment]
> The fix for this is included in [v2.2.2](https://github.com/beemdevelopment/Aegis/releases/tag/v2.2.2)

Very nice, it's working perfectly now.
