### ISSUE TITLE
Show biometric unlock on opening app (if enabled) 

### ISSUE THREAD

**Issue by cosmicvibes** [beemdevelopment/Aegis#1177]
Currently when opening the app the first thing I have to do is tap "or tap here to use biometrics".

I would expect really that if biometrics is enabled, it would just pop up immediately and ask for my thumbprint. This is how the Bitwarden app and a few other banking apps I use handle it.

It's a minor annoyance I know, but one that bugs me nonetheless! Would be a nice little layer of polish to add if it's easy to do.

Many thanks.

**Comment by michaelschattgen** [comment]
Hi, thanks for your report. You're running into our password reminder. We implemented a password reminder to decrease the chances of people forgetting their passwords. If someone forgets their password, they may lose access to their vault. You can either type in your password once (recommended), or disable the password reminder in the settings. After that; biometrics become default again.

What version of Aegis are you running? We rolled out an update yesterday which explains this situation as soon as you tap 'biometrics' and the password reminder is active.

Closing this now but feel free to continue the conversation
