### ISSUE TITLE
Back button doesn't work on password prompt screen

### ISSUE THREAD

**Issue by chiraag-nataraj** [beemdevelopment/Aegis#118]
If I have unlocked the vault and hit the back button, it exits the app (and locks the vault) as expected.

However, if I am at the password prompt and hit the back button, it doesn't do anything. I can only exit by hitting the home button.

**Comment by alexbakker** [comment]
This is a known bug we haven't gotten to yet. Thanks for creating an issue for it.

**Comment by chiraag-nataraj** [comment]
To add to my original report (which may help with debugging):

I've noticed that if I press back before entering the password, the app immediately exits after I unlock the vault.

**Comment by troyengel** [comment]
Pixel 2, Android 9 (stock) -- along with the above from a user-experience perspective, when I'm in the OTP token main screen and press Back (arrow), it returns to the Password prompt screen where back button doesn't work as reported. This feels weird.

In my opinion, the expected action from the main screen -> Back button is to lock to lock the database silently/invisibly and exit, not take me to the Password screen. That should only come up when I open the app, not trying to quit it -- this opinion is based on how other apps like it (same conceptual category) work, such as say Bitwarden password manager. Thx!

**Comment by michaelschattgen** [comment]
Thanks for your suggestion! This is a bug we need to fix but I like your idea about closing silently.

**Comment by alexbakker** [comment]
This was fixed a while ago, but we forgot that this was still open. See: #192.
