### ISSUE TITLE
Biometrics greyed out in app setup

### ISSUE THREAD

**Issue by ancoron** [beemdevelopment/Aegis#1181]
### Version

v2.1.3

### Source

Google Play

### Vault encryption

No

### Device

Fairphone 3+

### Android version

Android 13

### Steps to reproduce

1. Install Aegis
2. Open Aegis
3. In the setup screens, Biometric option is greyed out → continue with password
4. After finishing setup, go to Settings → Security
5. Option "Biometric unlock" is greyed and cannot be enabled/disabled

### What do you expect to happen?

Biometric option is available as it is for other apps on the same device.

### What happens instead?

No Biometric option to speed up access to tokens

**Comment by alexbakker** [comment]
It looks like the Fairphone 3+ does not have a [Class 3](https://source.android.com/docs/security/features/biometric/measure) biometric sensor: https://forum.fairphone.com/t/fairphone-3-and-3-a13-fingerprint-sensor-update/97654. This means that you won't be able to use biometric unlock in Aegis.

**Comment by ancoron** [comment]
Thx @alexbakker and sorry that I didn't do my research before.

For the record, they actually maintain a list of apps to be affected by this issue with Android 13:
* https://forum.fairphone.com/t/list-of-apps-and-their-status-of-fingerprint-support-on-fp3-with-android-13/97658
