### ISSUE TITLE
Biometric unlock without clicking it every time

### ISSUE THREAD

**Issue by msdosfx** [beemdevelopment/Aegis#1186]
If Biometric unlock is enabled, it would be preferable if I didn't have to click " or tap here to use biometrics " every time I want to unlock my vault. Bitwarden on Android for example brings up the biometric unlock automatically when opening the app, if you have it enabled. It is just a tiny extra step to click the button first in Aegis, but when you use your TOTP constantly, as I do, the convenience of the Bitwarden biometric unlock compared to the Aegis 2 steps is very noticeable.

**Comment by michaelschattgen** [comment]
Thanks for your report. What version of Aegis are you using? You're running into our password reminder. We implemented a password reminder to decrease the chances of people forgetting their passwords. If someone forgets their password, they may lose access to their vault. You can either type in your password once (recommended), or disable the password reminder in the settings. After that; biometrics become default again.

We rolled out an update a few days which explains this situation as soon as you tap 'biometrics' and the password reminder is active.
