### ISSUE TITLE
F-Droid still supported?

### ISSUE THREAD

**Issue by guidot** [beemdevelopment/Aegis#1187]
### Version

2.1.3

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Realme XT

### Android version

12

### Steps to reproduce

I know that F-Droid builds are behind about a week or so and I know you don't control the update process on F-Droid. But since the last update is six months old now I'm curious:
- Do you still support F-Droid builds?
- Has there been some change that is interrupting the update process that the F-Droid guys need to know about? 

### What do you expect to happen?

See F-Droid builds about a week or so after an update has been released.

### What happens instead?

No updates for 6 months.

**Comment by alexbakker** [comment]
> Do you still support F-Droid builds?

Yes.

> Has there been some change that is interrupting the update process that the F-Droid guys need to know about?

Looks like they're working on fixing the build on their end: https://gitlab.com/fdroid/fdroiddata/-/commit/fbf266ebf8d7343757b31ccffba821bbffa6d402

**Comment by guidot** [comment]
Thanks a lot, Alex!
