### ISSUE TITLE
F-Droid Version Dated

### ISSUE THREAD

**Issue by SunDevil311** [beemdevelopment/Aegis#1189]
I'm not sure how the process works, but in case you're not aware, the latest F-Droid version available is 2.1.3--significantly dated.

I suppose I'll just install directly via APK for now. The Google Play version, which I'd prefer not to use, appears to be correct.

Would be nice if this could be fixed! Thanks much.!

[Screenshot_20230916_170014_Droid-ify.png](https://github.com/beemdevelopment/Aegis/assets/10506001/3d9879f6-dd6a-47c9-81e7-44decafc6c95)

**Comment by krisu5** [comment]
Duplicate: #1187

**Comment by alexbakker** [comment]
https://github.com/beemdevelopment/Aegis/blob/master/FAQ.md#why-is-the-latest-version-not-on-f-droid-yet

The build succeeded a couple of days ago: https://monitor.f-droid.org/builds/log/com.beemdevelopment.aegis/62#site-footer. Looks like it has not been published yet though.

**Comment by SunDevil311** [comment]
@alexbakker Thank you for the information, my apologies for the duplicate issue.

I'll keep an eye on F-Droid for now. Thanks again!
