### ISSUE TITLE
Export data to another phone via direct connection

### ISSUE THREAD

**Issue by fiorins** [beemdevelopment/Aegis#1197]
Can you implement a way to transfer the Aegis data on the Aegis app of another phone with a direct connection between the two phones or via a QR code ?

**Comment by michaelschattgen** [comment]
We actually already support that, select (tap and hold) all the tokens you want to share and tap on the QR code icon in the menu at the top.

**Comment by alexbakker** [comment]
Also:

> with a direct connection between the two phones

Aegis' vault is included in D2D transfers.

**Comment by fiorins** [comment]
> We actually already support that, select (tap and hold) all the tokens you want to share and tap on the QR code icon in the menu at the top. 

Thanks, but there is no "select all" button. Hope will be implemented.

**Comment by fiorins** [comment]
> Also:
> 
> 
> 
> > with a direct connection between the two phones
> 
> 
> 
> Aegis' vault is included in D2D transfers.

You mean exporting the vault in aegis format ?

**Comment by michaelschattgen** [comment]
>Thanks, but there is no "select all" button. Hope will be implemented.

I agree we could use a select all button. I will make an issue.

>You mean exporting the vault in aegis format ? Cause I can't see the linked android account to my app

Aegis supports Device-to-device backups, meaning Android will automatically include Aegis and all its content (vault, settings etc) in your phones backup. Whenever you restore this backup (ie. setting up a new phone or after a factory reset) the vault and all the settings will be restored. Make sure this is enabled in the Aegis settings if you'd like to make use of this. I'm not sure if this fits your use case here but we just wanted to point out that we have such a feature.

**Comment by michaelschattgen** [comment]
What exactly is the use case here? How often do you use this? Is our backup/export feature not enough in this case? You could easily share that backup file with your other phone through Nearby Share.

Aegis will never support anything that would require a direct connection so until we find out what the best fit would be in this case I don't see us reopening this issue. Would it be better if you had the ability to have multiple tokens combined into 1 QR code just like Google Authenticator?

**Comment by fiorins** [comment]
![Screenshot_20230928-161721](https://github.com/beemdevelopment/Aegis/assets/32281481/09a8e6b1-3109-4e62-938c-7846d78e0e68)

Ok, in the end I did with nearby share, but if I can make a note, I think the interface should be improved because when I got to this screen I didn't understand what the password to use was and I understood it only after some time that it was the one used for the app, so I would put a sign warning about this, like a text "Encrypt the vault. (with Aegis' set password)".
