### ISSUE TITLE
Simple Windows/MacOS/Linux (flatpak) version

### ISSUE THREAD

**Issue by NSurtsev** [beemdevelopment/Aegis#1201]
I would like to see cross-platform version, like Authy.
What if smth happens to my smartphone? I do not have any other Android device.
Not even talking how comfortable it would be to work, having your Aegis next to KeepassXC.

P.S. I know, you answered in your F.A.Q., but still, it was written long ago. There are no issues about this as I have looked through.

**Comment by alexbakker** [comment]
Duplicate of #165.
