### ISSUE TITLE
 Issue in Build Process: "Process 'command 'git'' finished with non-zero exit value 128" 

### ISSUE THREAD

**Issue by Jaymin-Bhadani** [beemdevelopment/Aegis#1202]
### Version

2.2.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

s20

### Android version

13

### ROM

13

### Steps to reproduce

I encountered an issue while building my project on GitHub, and I need assistance in resolving it. The error message I'm receiving is:

Process 'command 'git'' finished with non-zero exit value 128

This error occurs during the build process, specifically when executing Git-related commands.

### What do you expect to happen?

The error message indicates that a Git command executed during the build process returned a non-zero exit value, which typically suggests that there was an issue with the Git operation. This error can prevent the successful completion of the build process.

### What happens instead?

To resolve this issue, I have already taken the following steps:

Checked Git Configuration: Ensured that Git is properly configured with the correct settings and credentials.

Repository Authentication: Verified that the repository I'm trying to access during the build process is accessible and that I have the necessary permissions.

Repository URL: Confirmed that the repository URL is correctly specified in the project's configuration.

Repository Status: Checked the status of the repository for any uncommitted changes or conflicts that might be causing the issue.

### Log

A problem occurred evaluating project ':app'.
> Process 'command 'git'' finished with non-zero exit value 128

**Comment by alexbakker** [comment]
You'd have to take a look at what the error message from Git actually says. That 128 exit code could mean a number of different things. For example, this exit code is also used when a Git command is executed outside of the context of a Git repository.
