### ISSUE TITLE
About icons

### ISSUE THREAD

**Issue by BabyOilJohnson** [beemdevelopment/Aegis#1205]
Change "search" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Asearch%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "sort" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Asort%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "more" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Amore_vert%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "+" in add button to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aadd%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 

In add button;
Change QR-code to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aqr_code_scanner%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change image scan to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aadd_photo_alternate%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "enter" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aedit%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 

Entry selected;
Change "back" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aarrow_back%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change star to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Astar%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) and selected star to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Astar_half%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change copy to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Acontent_copy%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "edit" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aedit%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change QR-code to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aqr_code_2%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change drag handle to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adrag_handle%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 

In setting page;
Change appearance icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Abrush%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change behavior to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Atouch_app%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change pack icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Apackage_2%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change security to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Asecurity%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change backups to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Abackup%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "import/export" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aconstruction%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 

In icon pack, change detele icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adelete%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
In backups, change  "automatic" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Abackup%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change tick to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adone%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
Change android logo to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aandroid%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 

Edit:
In edit entry page;
Change name icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aperson%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
Change notes to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Anotes%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
Change security to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Asecurity%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
Change info to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Ainfo%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
Change usage icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Apin%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
Change drop-down arrow to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aarrow_drop_down%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)

**Comment by deepanshubarve** [comment]
Can you please assign me

**Comment by alexbakker** [comment]
Thanks for the suggestion. When we update Aegis to Material 3, we'll also take a look at all of the icons and make sure all of them are up-to-date. I don't think it makes sense to update the icons before then, though.

**Comment by BabyOilJohnson** [comment]
Hi @alexbakker 
Thanks for updating the icons to the latest standard. Could you make them a bit more rounded, like I suggested above? It'll make them more appealing. Thanks!
