### ISSUE TITLE
Can't enroll to SafeNet Trusted Access

### ISSUE THREAD

**Issue by walla5e** [beemdevelopment/Aegis#1206]
### Version

2.2.2

### Source

GitHub

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 7

### Android version

Android 13

### ROM

GrapheneOS

### Steps to reproduce

Trying to enroll my device with MobilePASS token I got from my company by scanning QR code in Aegis.

### What do you expect to happen?

add OTP

### What happens instead?

I got error:
"An error occurred while trying to read the QR code

com.beemdevelopment.aegis.otp.Google
AuthInfoException: Unsupported protocol: null"

**Comment by alexbakker** [comment]
Aegis does not support SafeNet Trusted Access. See #250.
