### ISSUE TITLE
Build UI using Jetpack Compose

### ISSUE THREAD

**Issue by Divyank7436** [beemdevelopment/Aegis#1207]
I thing for more Attractive UI UX, we should use Jetpack compose, So I would like to suggest that instead of Creating XML file, lets work on Jetpack compose

**Comment by Wojtaz0w** [comment]
That would require a COMPLETE re-write of the app, despite it currently working great... if it isn't broken, don't fix it. if you want to make Aegis in Compose maybe create a fork or something... or just live with Aegis using androidx, etc.

**Comment by alexbakker** [comment]
We don't have plans to rewrite Aegis to use Jetpack Compose.
