### ISSUE TITLE
Add an option to use another password for encrypted backups

### ISSUE THREAD

**Issue by rustforfuture** [beemdevelopment/Aegis#121]
Hello

Thank you for this great app.
Please add option to select another password other than app password for encrypted backups.

What i mean is exactly like andOTP encrypted backup feature.

the use case here is for example i use a simple password for app itself but i want to set a long and complex password for backups that i want to store them in cloud or ...

Thanks

**Comment by alexbakker** [comment]
I'm glad you like it!

I can see how having a separate password for backups could be useful. However, I'm really not a fan of the use case you're describing. It's just as important to encrypt the vault with a strong password on your phone as it is anywhere else. If we decide to implement this, we should take care not to expose this feature in a way that encourages users to set a weak password.

That being said, I think this would be relatively easy to implement, as the vault format already supports having multiple password slots. We could simply add a slot for the backup password and exclude the other one when creating a backup.

**Comment by julian-fairfax** [comment]
I would also appreciate this feature being added. I have a strong passphrase on my phone and would like to have access to Aegis without having to enter a passphrase. I do understand however, that encrypting your backup is important, so if I could just set a passphrase for the backup, but not the app itself, that'd be perfect for me. Thanks for your work on this wonderful app!

**Comment by naacbin** [comment]
+1, I wait this feature to move from andOTP to Aegis !

**Comment by alexbakker** [comment]
Implemented in #926.

**Comment by ka223** [comment]
Only password and biometric are offered under "Security" - "Encryption" in version 2.1.3 ?

**Comment by alexbakker** [comment]
@ka223 There should ba a "Separate password for backup & export" option.
