### ISSUE TITLE
Enhance Password Validation to Utilize Feedback from zxcvbn4j

### ISSUE THREAD

**Issue by 1162706031** [beemdevelopment/Aegis#1210]
**Issue Overview**
While the application currently checks for password equality and non-null values, it doesn't effectively leverage the feedback and suggestions provided by zxcvbn4j. As a result, the powerful feedback and warnings from the library, which are designed to guide users to set stronger passwords, become less meaningful.

**Expected Behavior**
When a user sets or updates their password:

The application should display dynamic feedback and warnings as the user types.
Password strength should be evaluated in real-time, with relevant suggestions and warnings shown immediately.
The final validation should consider the score from zxcvbn4j and potentially set a minimum threshold score for password strength.
Current Behavior
The application only checks if the password and confirmation password fields are equal and not null, missing out on the opportunity to guide users to create a more secure password.

**Steps to Reproduce**
Navigate to the password set/update screen.
Enter a password and observe the lack of dynamic feedback or suggestions based on password strength.
**Proposed Solution**
Integrate real-time feedback from zxcvbn4j on the password input field.
Display warnings or suggestions provided by the library dynamically.
Before saving the password, ensure that it meets a certain strength score as per zxcvbn4j's evaluation.

**Comment by Junan-YU** [comment]
Hi, I would like to try to reach out this issue if it's possible : )

**Comment by alexbakker** [comment]
I don't think we should enforce a minimum password quality score. zxcvbn has some pretty good feedback for the most common bad patterns passwords, but there are quite a few cases where the actual quality estimation is bad.

> Navigate to the password set/update screen.
> Enter a password and observe the lack of dynamic feedback or suggestions based on password strength.

I'm not sure what you mean here. The password strength and quality feedback already changes as the user enters their password.
