### ISSUE TITLE
Unsupported Protocol tiqrauth

### ISSUE THREAD

**Issue by alfureu** [beemdevelopment/Aegis#1211]
### Version

2.2.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 7

### Android version

Android 13

### ROM

GrapheneOS

### Steps to reproduce

My employer requires me to use an authenticator app tiqr. Based on their [website](https://tiqr.org/technical/) it seems like another open source authenticator app, however, they apparently use their own protocol. 

Would it be please possible to introduce its support?

### What do you expect to happen?

scanning Tiqr QR codes

### What happens instead?

Error message `com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: tiqrauth`

### Log

see above the error

**Comment by michaelschattgen** [comment]
Thanks for creating this issue. From quickly scanning the website you linked it looks like this protocol requires an active internet connection and that's not something we're planning on adding in Aegis. This unfortunately means I don't see Aegis ever supporting this protocol.
