### ISSUE TITLE
Open specific app on copy

### ISSUE THREAD

**Issue by KaKi87** [beemdevelopment/Aegis#1212]
Hello,

Instead of only minimizing the Aegis after copying a code, it would be nice to automatically open a specific app.

Thanks

**Comment by alexbakker** [comment]
Could you explain how you imagine the flow here, step by step?

**Comment by KaKi87** [comment]
1. I open Aegis ;
2. I click a code ;
3. The related app is opened ;
4. I paste the code.

Currently I'm just opening the related app manually.

**Comment by michaelschattgen** [comment]
We're not planning on adding this; we think it's not worth the effort and suggest just using the Androids multitask feature to quickly switch back to the app you're trying to log into.

**Comment by KaKi87** [comment]
That means opening the related app *before* opening Aegis, and *then* switching back to it, which takes even more steps.

This feature is all about removing and automating steps.

**Comment by davchana** [comment]
many of my codes are used on websites.  maybe the app can simply switch to last opened app? i.e. mimic the multitask, click the last app?

**Comment by KaKi87** [comment]
That would be interesting as well but still require more clicks than my proposal, plus, going back to the last app is as simple as a swipe gesture.

There's also a *Mimimize on copy* feature that exists but that one doesn't go back to the previous app.
