### ISSUE TITLE
Add a in-built keyboard whenever you type in your password

### ISSUE THREAD

**Issue by BIRBURE** [beemdevelopment/Aegis#1213]
So whenever you have to type in your password, whether for logging in or in the settings menu for changing the password, you type it into something like this (Screenshot from Green Wallet)
![Screenshot_20231014_003629_Green](https://github.com/beemdevelopment/Aegis/assets/147885525/0cf6f0d8-a622-4fde-8fc9-26387cd06b24)

**Comment by michaelschattgen** [comment]
Could you elaborate on this? I fail to see the purpose of this "keyboard". Am I missing something here?

**Comment by BIRBURE** [comment]
This would enhance the security 
On my phone, my keyboard is connected with the internet because my clipboard is synced between my computer and my phone
So potentially someone could read my input on the keyboard.
tbh I don't know how likely something like that could happen, however crypto wallets like green wallet and electrum have those in built keyboards

**Comment by michaelschattgen** [comment]
The fact that your keyboard is connected to the internet is probably a worse security breach than Aegis not having a built-in keyboard. Having a built-in keyboard means that we have to completely write a custom keyboard supporting different languages and screen sizes.
