### ISSUE TITLE
[Feature request/Bug] Biometric unlock by default on startup

### ISSUE THREAD

**Issue by Bokoblin** [beemdevelopment/Aegis#1214]
Hi,

I find the current UX on app opening a bit cumbersome on small devices like my Pixel 3, especially when using the app almost every day:
1. Open app
2. The keyboard auto opens to type a password 
    * This hides the line which proposes to use biometric
4. Scroll to show the biometric link again
5. Tap biometric link
6. Dismiss a modal "biometric unlock by default" (is this a bug then that I always get password first?)
7. Use your biometric (fingerprint in my case)

I would propose to directly use biometric instead when it is enabled.
Only if biometric is dismissed, we show the keyboard to type the password.

This would enable a seamless workflow, especially for users having face unlock with nothing to do

If the proposal is acceptable, I would like to try to do it myself and propose a Pull Request.
I already worked with Android before during my studies, it does not seem too difficult to me.

Note: As a slightly less interesting alternative, we could also improve the layout not to lose space with a giant icon and a two-line title.
I can't share screenshot as the app prevents it.

-----------

App version: 2.2.2
Device: Google Pixel 3 (blueline)
OS: Pixel Experience Plus 13

**Comment by michaelschattgen** [comment]
Thanks for your report. The scenario you're describing is working as intended. The modal you're dismissing explains that you're running into our password reminder; either type in your password once or disable the password reminders to get rid of it. 

We *want* you to type in your password every now and then to avoid losing access to your vault. After entering your password once you'll notice the biometrics unlock will become default again.

**Comment by Bokoblin** [comment]
Alright I see, seems working then, thanks.
I would have thought that never entering the password would forbid to use biometrics in this case.
What's the reminder used for if it can be bypassed?

**Comment by Bokoblin** [comment]
> We're continuously improving this password reminder feature so feel free to leave your thoughts on how we can make this more clear without compromising the UX even more.

I guess for me it was just the way the prompt was written, it made me just skip it, thinking it's a bug. But that's subjective.
I would have put a more direct wording with a second button to go back to password typing:

```
**We\'re encouraging you to retype your password now! to default back !**

We will then default back to biometric unlock by default until it\'s time for another password reminder.
We occasionally prompt you to enter your password to ensure you haven\'t forgotten it.
We will never lock you out of the application if you continue to use biometric without confirming your password.
However you will need the password on a new device or when reinstalling the application.
```

And also replaced text input placeholder "Password" by "Confirm password for biometrics unlock".
But the current UI is fine as long as most understand.
