### ISSUE TITLE
Can not login to aegis after reinstall it

### ISSUE THREAD

**Issue by Vungcocanh** [beemdevelopment/Aegis#1215]
I don't remember my aegis password so i uninstall  and reinstall aegis to setup a new password. But the app asks me to log in whenever I reinstall it. How can i bypass this.

**Comment by ragnarbull** [comment]
> I don't remember my aegis password so i uninstall  and reinstall aegis to setup a new password. But the app asks me to log in whenever I reinstall it. How can i bypass this.

So the key should be deleted from the Keystore (expected Android behavior on uninstall but the developers might persist it as otherwise you could be locked out of your 2FA apps). 

Maybe you need to clear your cache (Settings > Apps > Aegis> Storage & Cache (clear both)

**Comment by alexbakker** [comment]
Did you have Android backups enabled in Aegis, by any chance? If so, your vault will be restored every time you reinstall the app. You should be able to reset by clearing Aegis' storage.
