### ISSUE TITLE
Double-tap to copy a certain code.

### ISSUE THREAD

**Issue by mc4n** [beemdevelopment/Aegis#1218]
I would be much more practical if we were able to copy a code by just double tapping on the list item. Otherwise it is kinda more time consuming to select and copy considering there is a count-down for all codes.

Or maybe just add a copy button for each entry but that would also change the look and takes more consideration.

**Comment by Tipoff4317** [comment]
??? Currently, in the Token list page, I tab on an item, and there is a pop-up at the bottom that says "copied", and the code is in the clipboard.

**Comment by mc4n** [comment]
I don't have it bro. you must be a chosen one.

**Comment by mc4n** [comment]
ohh sory we can actually achieve this functionality in the settings. how can I close this issue.

**Comment by davchana** [comment]
i am glad it is not default.  my default wish is single tap. i am happy we get to choose.
