### ISSUE TITLE
Nintendo Account 2FA code issue

### ISSUE THREAD

**Issue by Gamerhenky** [beemdevelopment/Aegis#1221]
### Version

v2.2.2

### Source

Google Play

### Vault encryption

Yes

### Device

realme narzo 50i Prime

### Android version

Android 11

### ROM

Realme UI R

### Steps to reproduce

When setting up new 2FA can be found on Nintendo Support here: https://en-americas-support.nintendo.com/app/answers/detail/a_id/27496/~/how-to-set-up-2-step-verification-for-a-nintendo-account

When logging in:
1. Login Nintendo Account as per usual.
5. Enter 2FA code from Aegis (or any other Authenticator).

### What do you expect to happen?

Successfully set-up 2FA or signed in.

### What happens instead?

Every generated codes from Aegis didn't work but works on Google Authenticator with Sync Now. Also, the code doesn't match on each other.
![Screenshot_20231101-171240](https://github.com/beemdevelopment/Aegis/assets/37840226/7d49bfa5-3e9e-44ef-8361-c654e9dabc50)

**Comment by alexbakker** [comment]
The time on your device is probably out of sync. Google Authenticator will sync the clock for itself, but Aegis doesn't.

You can use https://time.is on that device to check how far the clock has drifted.
