### ISSUE TITLE
Single Tap to Copy+Tap to Reveal no longer works correctly

### ISSUE THREAD

**Issue by Bazoogle** [beemdevelopment/Aegis#1223]
### Version

v2.2.2

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Moto Edge 2021

### Android version

Android 13

### ROM

LineageOS 20

### Steps to reproduce

Settings -> Behavior -> Copy tokens to clipboard: Single tap
Settings -> Security -> Tap to reveal: enabled

Restart app, then when tap a token.

### What do you expect to happen?

Previously, when you tapped the hidden token, it would reveal it. If you tapped it a second time, it would copy and minimize the app.

### What happens instead?

When you tap it the first time, it immediately copies the value and minimizes. In order to view the token to enter on another device, I have to view my clipboard.

**Comment by michaelschattgen** [comment]
I'm afraid I don't quite understand what the bug is you're describing. 

>When you tap it the first time, it immediately copies the value and minimizes. In order to view the token to enter on another device, I have to view my clipboard.

This is the intended behavior when you set "Copy to clipboard" to single tap and enable "Tap to reveal". What exactly do you want to happen?

**Comment by Bazoogle** [comment]
> After rereading your report it seems like you want to avoid minimizing the app? That's another setting in the "Behavior" section of Aegis. You can either disable "Minimize on copy" or set "Copy to clipboard" to never or double tap. Hope this helps.

I don't want to avoid minimizing the app, rather I'd like it to copy and minimize on tap only if the token is revealed (like it originally did). This means if the token is hidden, the tap would not copy the token and minimize, but simply reveal the token. If I am copying it I am going to a different app on my phone, so the app will need to be minimized anytime I copy it, whether manually or automatically. The original functionality is what I want. The tap to copy (and consequently minimize) should only apply once the token is revealed. I suppose technically this is no longer "single tap" given you have to tap it once to reveal it, and then a second time to do the actual copying. Though it is still only one tap after you can see the token.

I'm not sure if the change was intentional or accidental. I assumed accidental, which is why I marked it as a bug report.

**Comment by ibrahimjelliti** [comment]
are there any updates on this bug, copy to clipboard doesn't work
