### ISSUE TITLE
 Will there be a PC app ?

### ISSUE THREAD

**Issue by MaximusPanin** [beemdevelopment/Aegis#1224]
I would like a PC app in the future.

**Comment by EhrenmannXD** [comment]
Check [the FAQ](https://github.com/beemdevelopment/Aegis/blob/master/FAQ.md) 

> Can you port Aegis to iOS/Windows/MacOS/Browser Extension?
> We don't have plans to port Aegis to other platforms.

**Comment by alexbakker** [comment]
Duplicate of #165.
