### ISSUE TITLE
sorting by issuer should sort by account second

### ISSUE THREAD

**Issue by mbunkus** [beemdevelopment/Aegis#1229]
### Version

2.2.2

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

OnePlus Nord

### Android version

12

### Steps to reproduce

I have three entries all with the same issuer called "Hetzner". The three have different accounts: "LINET m.bunkus", "LINET support" & "private". The first two are members of a group called "work", the third one belongs to the group "private".

When sorting by "Issuer (A-Z)" the entries appear in the following order:

1. Hetzner (LINET m.bunkus)
2. Hetzner (private)
3. Hetzner (LINET support)

Note that sorting the overall sorting by issuer works (meaning that all entries with issuers starting with A–G sort before "Hetzner", those with I–Z sort after "Hetzner"); it's not about sorting solely by issuer — it's about the order of entries that share the same issuer.

My current workaround is not to use the "account" field at all & to put all the information into the "issuer" field, e.g. "Hetzner LINET m.bunkus", "Hetzner LINET support", "Hetzner private". That way sorting by issuer works as I'd expect it to work.

By the same argument sorting by account should also sort by issuer second.

### What do you expect to happen?

I would expect the entries to be ordered alphabetically by issuer first & by account second so that there's a coherent order. The expected order is:

1. Hetzner (LINET m.bunkus)
2. Hetzner (LINET support)
3. Hetzner (private)

meaning the accounts should be sorted alphabetically A-Z, too, with case-insensitive collation.

### What happens instead?

The entries are only sorted by issuer. When multiple entries have the same issuer, the order seems to be random. I suspect the actual order has something to do with the order they're retrieved from storage/the database.

**Comment by michaelschattgen** [comment]
Makes sense to me, will be implemented.

**Comment by mbunkus** [comment]
Thank you very much!
