### ISSUE TITLE
Vault backup failed recently: VaultRepositoryException: No persisted URI permissions

### ISSUE THREAD

**Issue by devxzero** [beemdevelopment/Aegis#1230]
### Version

2.2.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 8

### Android version

14

### Steps to reproduce

1. Open the Aegis app on my phone.
2. Unlock the vault using biometrics. Then a red top row is shown with the text "Vault backup failed recently".
3. Click on the red top row. Then the following text will be shown:

> An error occurred
> A recent vault backup attempt using Aegis' built-in automatic backups failed because an error occurred. The backup was attempted 7 minutes ago. Please check your backup settings to make sure backups can complete successfully.

4. Click "details". Then the following text is added to the already shown error: 

> com.beemdevelopment.aegis.vault.VaultRepositoryException: No persisted URI permissions`.

### What do you expect to happen?

Backup to function normally without errors.

### What happens instead?

The previously mentioned error.

**Comment by alexbakker** [comment]
This permission issue can happen for one of two reasons:
- A change was made to the backup destination (renamed, moved, deleted, etc)
- Aegis was restored from an Android backup

You should be able to fix the issue by reconfiguring the backup destination in Aegis' settings.

I've submitted a patch to make this more clear in the dialog: #1233.

**Comment by devxzero** [comment]
> You should be able to fix the issue by reconfiguring the backup destination in Aegis' settings.

With the backup problem still in place, it says for `Directory for backup files`: 

> Backups will be stored at: content://com.android.externalstorage.documents/tree/primary:Aegis

I'm not an Android developer, so I don't really know what the best/safest location would be for backups. When I click on `Directory for backup files` button, it will show the public directories on my phone that other apps can also access. That is the only location available. That doesn't sound like a safe place to store it, even if there is a password enabled on it. Shouldn't it be stored in a location that only Aegis has access to?

**Comment by alexbakker** [comment]
If you want only Aegis to be able to see the vault file, you should not enable automatic backups.

On modern versions of Android, apps either need the storage management permission, or explicit permission from you, in order to be able to access the directory you configured for Aegis automatic backups.
