### ISSUE TITLE
Feature request: allow remote storage for automatic backup (google drive, owncloud/nextcloud...)

### ISSUE THREAD

**Issue by mcarbonne** [beemdevelopment/Aegis#1237]
Currently, when I try to activate automatic backup, Android's directory selector only allows "local" folders.

But, in other applications, the same directory chooser also allow to pick a location from another application (google drive, synology drive, owncloud, nextcloud...). Most likely, there is an option in the API to (dis)allow external applications in the folder picker. I'm not familiar at all with android app development, so I don't know the implications of such a change.

I think this would be a great feature for the following reasons:
- backing-up locally is not secure (lost/broken phone...)
- using android-cloud isn't an option for most users who want to get rid of Google services

EDIT: I quickly dug into the code responsible for this:
```c++
    private void selectBackupsLocation() {
        Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);
        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION
                | Intent.FLAG_GRANT_WRITE_URI_PERMISSION
                | Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION
                | Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);

        _vaultManager.startActivityForResult(this, intent, CODE_BACKUPS);
    }
```
It seems that `Intent.ACTION_OPEN_DOCUMENT_TREE` might not be implemented by most (if not all) cloud storage applications. So folder selection may not be possible this way :confused:

**Comment by alexbakker** [comment]
Looks like you already found the reason why this doesn't work with most cloud providers: Most don't implement ``ACTION_OPEN_DOCUMENT_TREE``. Nextcloud does though, and Aegis' automatic backups are known to work with it.

Once #745 is implemented, automatic backups should work for more cloud providers. With the downside being that you won't get backup versioning.

**Comment by mcarbonne** [comment]
Thanks for your feedback! Regarding versioning, I'm not worried as most cloud providers already provide automatic history for files.
