### ISSUE TITLE
QR Code Scan on Dark Background Fails

### ISSUE THREAD

**Issue by bigboipete** [beemdevelopment/Aegis#1241]
### Version

v2.2.2

### Source

F-Droid

### Vault encryption

Yes

### Device

Shift5me  (https://shiftphones.com)

### Android version

AOSP 8.1

### ROM

ShiftOS 2.0 L (officially supported by Shift, but not strictly stock)

### Steps to reproduce

1. Scan QR code on a dark theme (QR Code on dark background) for new entry in Aegis

### What do you expect to happen?

QR code is scanned and a new entry for OTP is added to Aegis.

### What happens instead?

QR code and some thin shaking/flickering turquoise and yellow lines are visible on the device's screen. Same QR code is easily scanned on white background.

**Comment by alexbakker** [comment]
Do you have an example of a QR code that Aegis fails to scan (make sure it's not a 2FA QR code for your actual account)? Is there a quiet zone (i.e. white border) around the QR code? If not, it's an invalid QR code.

**Comment by bigboipete** [comment]
No, unfortunately I can't provide one. But it's not invalid, because it always works scanning the same with white backround.
