### ISSUE TITLE
2FAS import schema version 4

### ISSUE THREAD

**Issue by 777moneymaker** [beemdevelopment/Aegis#1243]
### Version

2.2.2

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 8 Pro

### Android version

Android 14

### Steps to reproduce

Open 2FAS auth
Go to 2FAS backup export the file
open Aegis
go to setting and import & Export
Import from file
select 2FAS Authenticator
select the .2fas file

### What do you expect to happen?

Import ends with success 

### What happens instead?

Aegis fails to import

### Log

Unsupported schema version: 4

**Comment by TonyHoyle** [comment]
Still getting this error 'Unsupported schema version'.  Alas it's meant I can't try aegis.

**Comment by alexandre-eliot** [comment]
@Multowz @TonyHoyle 
For anyone looking for a workaround.
Whilst the version 4 import is not officially supported by Aegis, it does work anyway.
All you need to do is change the version number in your `.fas` file (which is basically a JSON file) from 4 to 3 or lower, the import will work successfully
