### ISSUE TITLE
Scan QR Code not working

### ISSUE THREAD

**Issue by ktlknss** [beemdevelopment/Aegis#1247]
### Version

v2.2.2

### Source

F-Droid

### Vault encryption

Yes

### Device

Samsung Galaxy A20E

### Android version

Android 11

### Steps to reproduce

Click the `(+)` button on the homescreen, click "`Scan QR code`", aim at 2FA QR code

### What do you expect to happen?

The QR code is scanned

### What happens instead?

Nothing happens

### Log

N/A

**Comment by alexbakker** [comment]
Duplicate of #802. We'd appreciate your help this issue though: https://github.com/beemdevelopment/Aegis/issues/802#issuecomment-1859288329
