### ISSUE TITLE
Crash when zooming image out and saving

### ISSUE THREAD

**Issue by tygoee** [beemdevelopment/Aegis#1253]
### Version

v2.2.2

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Samsung S9

### Android version

Android 10

### Steps to reproduce

- Make a new entry (manually)
- After filling in the details, click on the image to select an image
- Select a custom image from your device
- When selected, you can zoom in/out with 2 fingers. Zoom out and keep it zoomed out
- While keeping it zoomed out, click save

### What do you expect to happen?

Saving the new entry

### What happens instead?

A crash

**Comment by alexbakker** [comment]
Thanks for the report. I'm unable to reproduce this. Could you [capture a log using ADB](https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb) of you reproducing the crash and share it here?

**Comment by alexbakker** [comment]
No response, closing for now.
