### ISSUE TITLE
Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [beemdevelopment/Aegis#1254]
It would be nice if the project's code were moved to GitLab or Codeberg. GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Comment by alexbakker** [comment]
We're happy with GitHub.

Also, please don't:

![image](https://github.com/beemdevelopment/Aegis/assets/2387841/6f01e235-7744-4809-be42-594600c67f20)
