### ISSUE TITLE
Biometrics unlock can not be turned on any more

### ISSUE THREAD

**Issue by iamgitcat** [beemdevelopment/Aegis#1256]
### Version

2.2.2

### Source

F-Droid

### Vault encryption

No

### Device

Tecno Pova 3

### Android version

Android 12

### Steps to reproduce

It just happened, no more biometric unlock and when I try to enable it, it gives me error: `com.beemdevelopment.aegis.crypto.KeyStoreHandleException: android.security.KeyStoreException: Keystore not initialized`

### What do you expect to happen?

Well, it always worked for years. I tried rebooting, uninstalling, starting new db, disbling and enabling in Android itself, nothing helps.

### What happens instead?

Biometrics unlock still work with BitWarden, Brave, Firefox, Standard Notes, ente Auth, phone unlock. But it do not works with Aegis and Autentificator Pro no more.

**Comment by alexbakker** [comment]
This is very likely to be a bug in the implementation of the Android Keystore on your device. The fact that the issue does not resolve itself after a reinstall of Aegis means that there isn't really anything we can do from our end. If you haven't done so yet, I'd suggest factory resetting your device to see if that helps. Either way, I'd suggest reporting this to the manufacturer of your device.
