### ISSUE TITLE
Import of Aegis exported file fails with "Password incorrect"

### ISSUE THREAD

**Issue by philipp-reinhardt** [beemdevelopment/Aegis#1261]
### Version

v2.2.2

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

One Plus 5t

### Android version

Android 13

### ROM

Lineageos 20

### Steps to reproduce

I'm not sure about reproducibility. What I did:
- Update Lineageos (v20 -> v20, minor update)
- Export Aegis database (json, encrypted), store offline (linux)
- factory reset phone
- reinstall aegis
- try to import backup file by using Aegis password (safed in vault)
   - "import file"
   - "Aegis"
   
 I tried to reproduce by exporting and importing on my current android version, which works quite well. But I don't think I'll be able to easily reproduce with upgrading from / to any other android version.

### What do you expect to happen?

- Import works out of the box

### What happens instead?

Error message after entering password:
" An error occurred while trying to unlock the vault

com.beemdevelopment.aegis.importers.DatabaseImporterException: Password incorrect"

The password for aegis has been stored in a vault, so I think it's pretty unlikely that the password is wrong. Although I used it with biometrics for most of the time and I can't remember when I used the PW the last time.

**Comment by alexbakker** [comment]
We're not aware of any bugs that could cause Aegis to fail to decrypt your Aegis vault with a correct password. We've spent a bunch of time investigating similar reports in the past, but it in almost all cases the reporter admits that they were entering the wrong password or they stop responding after some time.

If you discover that this is an actual reproducible issue, we will look into this of course.

> The password for aegis has been stored in a vault, so I think it's pretty unlikely that the password is wrong. Although I used it with biometrics for most of the time and I can't remember when I used the PW the last time.

You wouldn't be the first. Especially since you always used biometrics to unlock Aegis, it's easy to forget how you set up the app. This is why Aegis periodically reminds you to enter your password. Did you disable the password reminder?

**Comment by philipp-reinhardt** [comment]
Thanks for coming back to this.

Regarding your question: I don't remember if I disabled it, but I don't think so. I can just say, that Aegis feels different now, after having a fresh install. I'm pretty sure it's because of different configuration, but maybe you can spot something:

Old install:
- opening app, I needed to click "tap here to use biometrics"
- after clicking, some kind of warning dialog appeared about potential password entering (I didn't enter the password for ages)
- biometric login popped up

Current install:
- biometrics pops up on its own


In the settings I can see, that a "biweekly reminder" can be activated, but for me it was every single time (without the need of actually entering the password). I didn't wait for two weeks to see how it would behave now.

I don't think that this relates, but maybe it rings a bell for someone.

Thanks for checking :+1:

**Comment by alexbakker** [comment]
Right. So on your old install, you passed the "two weeks without entering your password" mark at some point. Aegis stopped prompting you for biometrics by default and started asking for your password instead. In this mode, Aegis shows a small popup asking you to enter your password. If you ignore that popup and tap "use biometrics", the dialog you mentioned is shown with the following message:

> We occasionally prompt you to enter your password instead to ensure you haven't forgotten it and won't get locked out of your vault. After entering your password once, Aegis will default back to biometric unlock until it's time for another password reminder.

Your new install is probably too recent so the password reminder hasn't been triggered yet.

**Comment by philipp-reinhardt** [comment]
Makes totally sense. Thanks again :)
