### ISSUE TITLE
Changes not detected for backup?

### ISSUE THREAD

**Issue by some-guy-23** [beemdevelopment/Aegis#1264]
### Version

v2.2.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 6 Pro

### Android version

Android 14

### Steps to reproduce

Have Android Backups Enabled
Have backup changes reminder Enabled
Add a new key to the App

### What do you expect to happen?

Android backs up the new key during nightly backup

App shows reminder to back up new changes

### What happens instead?

Even though key was added 2 days ago, still shows last Android backup as 9 days ago. Confirmed the Android backup was run last 2 nights.

Never received any reminder to backup new changes as well.

**Comment by alexbakker** [comment]
How did you confirm that Android backup was run during the last 2 nights? Do those backups contain your Aegis vault with the new entry you mentioned?

> Never received any reminder to backup new changes as well.

We don't show that reminder after we've asked Android to schedule a backup. Otherwise, because Android backups don't happen immediately, you'd see that reminder until Android has decided it's time for a backup.

**Comment by some-guy-23** [comment]
For confirming Android backup ran, I checked the Google One app each morning, and it showed the backup time. Not sure if the Aegis vault backup contains the new key or not, is there a way to check without a re-install or the app? I assumed new key wasn't backed up, since the app still says 9 days ago was last Android backup.

**Comment by alexbakker** [comment]
I'm not sure if Google One offers a way to look at the backup contents.

It may be helpful to take a look at the logs using ADB once you see that a backup occurred recently in Google One. Once you've obtained the logs using ``adb logcat``, check if ``AegisBackupAgent`` occurs and if so share the relevant logs here. You may have to increase the log buffer size in Developer options in order to retain enough information overnight.

**Comment by some-guy-23** [comment]
Think I may have found what the issue is, looking at the implementation of BackupAgent here -

https://github.com/beemdevelopment/Aegis/blob/566bcac3e08869b83348c5ee032870f9ff73614d/app/src/main/java/com/beemdevelopment/aegis/AegisBackupAgent.java#L67

I may be misunderstanding, but it looks like when it attempts to make a backup for Android Cloud, it will first try to write it to the local backup storage directory that is selected in the "Automatic backups" section of settings? I never enabled this, because I assumed I just had to turn on "Android cloud backups".

Which, now that I think back, the only existing Android Cloud backup may be when I manually kicked off the backup process through the Google One app itself. I wonder if that doesn't use the app's implementation of BackupAgent (and that's why it worked)?

I may be going down totally wrong path here, but just wanted to throw this out there.

**Comment by alexbakker** [comment]
> it looks like when it attempts to make a backup for Android Cloud, it will first try to write it to the local backup storage directory that is selected in the "Automatic backups" section of settings

No, the Android backup option works entirely independently from Aegis' built-in automatic backups. The reason we have our own implementation of BackupAgent, is that Aegis needs to do some special handling before it can hand off the vault file to be backed up. It needs to ensure the file is not corrupt (AtomicFile) and it needs to strip a password slot if the user has configured a separate password for backups.

After that's done and the resulting temporary file is copied to the files/backup directory, control is handed back to the built-in implementation of BackupAgent, which will read [backup_rules.xml](https://github.com/beemdevelopment/Aegis/blob/master/app/src/main/res/xml/backup_rules.xml) and back up the files listed there.

**Comment by some-guy-23** [comment]
Ah, thanks for the explanation, that all makes sense now! Also, I will try to check those logs and get them posted tomorrow.

**Comment by some-guy-23** [comment]
@alexbakker I checked this morning and there were no log entries for `AegisBackupAgent`. Google One says there was a backup last made 1 hour ago though. For a test, I manually kicked off a backup manually (via Google One app), and then Aegis is backed up, and I see that in the log file as well -

```
2694 22743 1 AegisBackupAgent: onFullBackup() called: flags-I, quota-26214400
2694 22743 1 AegisBackupAgent: onFullBackup() finished
2694 22743 1 AegisBackupAgent: onFullBackup() called: flags-I, quota-26214400
2694 22743 1 AegisBackupAgent: onFullBackup() finished
```

Not sure if it is expected to see the log entry twice, one right after the other (same second in timestamps). So, seems like for whatever reason, Aegis is included when I manually trigger a backup, but not during automatic nightly backups?

**Comment by alexbakker** [comment]
Actually that makes sense. When you make a change in Aegis, we signal to Android that the app's data has changed and that a backup should be made. The Google One backup transport probably only includes apps in automatic backups that have sent that signal. When you do a manual backup, it includes all apps. To confirm, you could make a random change to one of the entries in your Aegis vault (change the issuer for example), then wait for the nightly backup and check whether Aegis now reports a more recent Android backup date.

**Comment by some-guy-23** [comment]
So, this is very odd, but 3 nights ago I flipped the Aegis "Android Cloud" backup setting off, then on. Ever since then, each morning Aegis has said that it was backed up (even without any changes being made).

So... I guess it is working fine now...? Not really sure what happened before, could have been a fluke with my phone / backups in general. Sorry for the wild goose chase, might be a case of "did you try turning it off then on again". 😂

**Comment by alexbakker** [comment]
Yeah, it does sound like a fluke. Either way, we've established that when Android does perform a backup, Aegis's backup agent works properly, so we'll close this.
