### ISSUE TITLE
Vault export notifications

### ISSUE THREAD

**Issue by minus21grams** [beemdevelopment/Aegis#1265]
[Neither a bug nor a feature request, just a mere question to put my mind to ease]

Earlier today I was greeted with a "The vault was recently exported to unencrypted text" (or similar) message.
It wouldn’t caught my attention normally, I did export the vault in plain text and then compressed it adding a password.
**But that happened 2 weeks ago** (still have the zip archive, timestamps and all) - not that recent, don’t you think? And I’ve run the app several times since then.
Is this to be expected? Has it occurred to you?
Should I be worried?

**Comment by alexbakker** [comment]
That banner appears as soon as you start Aegis again after a plain text export. Aegis can't check for you whether you cleaned things up properly, so tapping the banner and dismissing the dialog is a manual action you have to do every time you do a plain text export.
