### ISSUE TITLE
Blank view when the keyboard is open

### ISSUE THREAD

**Issue by Paragoumba** [beemdevelopment/Aegis#1267]
### Version

2.2.2

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Nothing Phone (2)

### Android version

Android 14

### Steps to reproduce

- Start the app
- Click on the password field

### What do you expect to happen?

To see the keyboard and the password field

### What happens instead?

The view becomes blank when the keyboard appears

**Comment by alexbakker** [comment]
Could you share a screenrecordig taken while you reproduce the issue? (Temporarily disable "Screen security" in Aegis' settings first)

**Comment by Paragoumba** [comment]
I have tried to record the issue but could not reproduce even with a fresh Android 14 VM in Android Studio.
