### ISSUE TITLE
Steam?

### ISSUE THREAD

**Issue by pedrom34** [beemdevelopment/Aegis#127]
Hello,

I read that Aegis supports steam 2FA. But I cannot figure out how to add it? What am I supposed to enter in the differents fields in the app?

I'm sorry, this is not really an issue, but I cannot find documentation.

**Comment by michaelschattgen** [comment]
Hi Pedrom, no need to say sorry. The add/edit activity can be a bit overwhelming. I'm pretty sure that the only way to obtain your Steam secret is to root your device and search for the Steam-app data files.

Is your device rooted?

**Comment by michaelschattgen** [comment]
Hi Pierre, no need to be sorry. The add/edit activity can be a bit overwhelming. 

I'm pretty sure that the only way to obtain your Steam secret is to root your device and search for the Steam-app data files.

Is your device rooted?

**Comment by pedrom34** [comment]
Nope. I'll stay with the steam app then :smile:
Thanks, you can close the issue!

**Comment by BearBuster** [comment]
I think docs are realy necessar.
I have my phone rooted, extract shared secret, and added to Aegis, but it generates different key, not same as Steam app. And I can't authenticate with it.
