### ISSUE TITLE
Backup icons 

### ISSUE THREAD

**Issue by hotice52** [beemdevelopment/Aegis#1272]
Possibility to include the backup of the icons with that of the keys

**Comment by alexbakker** [comment]
Thanks for the suggestion, but I don't think we should include full icon packs in the Aegis backup file. It would inflate the size quite a bit. Icons you assigned to entries are included in the backup. If you switch to a new device and want to assign an icon to a new entry, you'll have to do a one-time re-import of the icon pack.
