### ISSUE TITLE
Incompatable Colour scheme

### ISSUE THREAD

**Issue by SwiftScriptr** [beemdevelopment/Aegis#1273]
### Version

V2.2.2

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

VDF 200

### Android version

5.1

### Steps to reproduce

Hello,

As it stands, the android app is not fully compatible with the lowest android version it is currently said to support (on F-droid) and this is what I hope to be a simple solution preventing the new threshold to be marshmellow and onward leaving behind 5.1.

The following issues I find with the build 2.2.2 are as follows:

The mainscreen dropdown menu is completely "cloaked" once any non white theme is chosen preventing any text on the settings dropdown list (after pressing the three dotted colon) at the top right to be shown.

I have tested this out after seeing if ram had anything to do with it and it has improved, uninstalled a few apps and that prevented the entire settings to be completely 'cloaked' too (which was more troublesome), however I am unable to change from light mode.

To be clear the colour scheme inverts to white in 'dark mode' for the blank dropdown, and dark grey in default light mode whilst being visible.

An issue of callibration is what I gather from this and I hope to be informed of any new developments to combat this hopefully not a single user issue.

Kind regards, 

### What do you expect to happen?

I hope to be directed or informed of a stable version of the app. Or for the investigation to generate a hotfix.

### What happens instead?

The color inversion prevents any visible setting to be seen, after enabling more ram, there was still a color inversion issue with the dropdown list menu itself. 
Thefore space and memory isn't an issue on my side.

### Log

N/a

**Comment by SwiftScriptr** [comment]
Hello, I am a patient person.
As you can tell, i like that f-droid opensource app repos are the last of the 5.1 android stores left for the most part.

I do hope this app doesn't just jump to 6.0+ as having 'older' discontinued Google OS tech has it's benefits when using those for seperate offline tasks that your app is apart of, making things more secure IMO if direct usage online is restricted.

**Comment by alexbakker** [comment]
Does https://github.com/beemdevelopment/Aegis/issues/754#issuecomment-852263884 look similar to what you're seeing?

> I do hope this app doesn't just jump to 6.0+

I wouldn't count on Aegis supporting old Android versions forever. We're currently working on Material 3 support. If it turns out to be too much of a pain to make it work well on old Android versions, we'll bump ``minSdkVersion``.

**Comment by alexbakker** [comment]
No response, so assuming this is indeed a duplicate of #754.
