### ISSUE TITLE
Safe to close Authy account after importing all accounts from Authy into Aegis? 

### ISSUE THREAD

**Issue by dimyself** [beemdevelopment/Aegis#1275]
Hi there! I followed a guide and successfully exported all my Authy accounts / codes into Aegis and another desktop app. 

Is it safe to now close my Authy account and uninstall it? 

I have read some people say that after transferring accounts into Aegis if you close your Authy account, the accounts will no longer work? 

I don't have twitch btw, as I read that one had more issues

I would think they should still work because they're in another app now?

Thank you!

**Comment by steveclarke** [comment]
> Hi there! I followed a guide and successfully exported all my Authy accounts / codes into Aegis and another desktop app.
> 
> Is it safe to now close my Authy account and uninstall it?
> 
> I have read some people say that after transferring accounts into Aegis if you close your Authy account, the accounts will no longer work?
> 
> I don't have twitch btw, as I read that one had more issues
> 
> I would think they should still work because they're in another app now?
> 
> Thank you!

Would you mind sharing a link to the guide you followed? I'd like to do the same.

**Comment by JerboaGobi** [comment]
To the best of my knowledge if you are exporting and importing the OTP from Authy to Aegis via the desktop debug method then you **cannot** delete your Authy account. Authy does a bit of abstraction to where the codes you're exporting/importing aren't actually the codes which will function directly your apps. The most proper migration path is to go to each application remove and re-add OTP scanning a new QR code. It's painful yes but if you want to delete your Authy account it is the way forward. 

https://gist.github.com/keeganwitt/4609a39b30c9de68d476c400f2ed12ac

> Important: You can NOT delete your Authy account, even after migrating your TOTP tokens to another software! If you do, you could be locking yourself out of all the accounts that require Authy!

**Comment by alexbakker** [comment]
Any pure TOTP/HOTP entries can be safely imported into Aegis and deleted from Authy. If you have any entries that are backed by Authy's proprietary 2FA offering, I would be a bit more careful. I'd suggest deactivating 2FA for those first and then setting up 2FA with Aegis (if possible).

**Comment by dimyself** [comment]
> To the best of my knowledge if you are exporting and importing the OTP from Authy to Aegis via the desktop debug method then you **cannot** delete your Authy account. Authy does a bit of abstraction to where the codes you're exporting/importing aren't actually the codes which will function directly against your apps. The most proper migration path is to go to each application remove and re-add OTP scanning a new QR code. It's painful yes but if you want to delete your Authy account it is the way forward.
> 
> https://gist.github.com/keeganwitt/4609a39b30c9de68d476c400f2ed12ac
> 
> > Important: You can NOT delete your Authy account, even after migrating your TOTP tokens to another software! If you do, you could be locking yourself out of all the accounts that require Authy!

Here is the GO app I used to export. I see people saying its ok to delete and you say its not. 

If I'm reading this correctly, it looks like I can delete authy, and that only a few apps won't export out correctly???

App used to export from Authy to Aegis: https://github.com/alexzorin/authy

From a portion of their README:

`This program will enrol itself as an additional device on your Authy account and export all of your TOTP tokens in Key URI Format.`

`It is also able to save the TOTP database in a JSON file encrypted with your Authy backup password, which can be used for backup purposes, and to read it back in order to decrypt it.`

^ That sounds to me like its getting the actual TOTP keys , so its safe to delete???

Here's a different portion of the README that says you can't delete Authy. BUT, it reads like its only for certain apps (like Twitch (which I dont have))??

`Twitch (and a handful of other sites) are the latter: Authy Apps.`

`Now, authy-export registers itself as a device on your Authy account. Per the explanation above, that means it is assigned a unique TOTP secret for sites like Twitch, which means it will generate different 7-digit codes to your primary Authy device. These codes will work as long as you don't deregister the authy-export device from your Authy account.`

`This is unfortunate, but the fact is: you cannot fully delete your Authy account if you want to keep using TOTP-based authentication with Twitch. If you do, all of the TOTP secrets will be revoked, and you will locked out of Twitch. It happened to me, and Twitch support chose to not help me out ^_^.`

Thank you I appreciate it!!
