### ISSUE TITLE
Authy is pulling Desktop App, so here is an opportunity for keyboard workflow!

### ISSUE THREAD

**Issue by noxidsoft** [beemdevelopment/Aegis#1276]
Hi,

I have been a long time user of Authy on mobile and desktop. I have today recieved the following email and I'm on the search for an alternative and came across Aegis as that possible alt. If you folks can port your App to Windows 10/11 desktop, you will be helping people keep a choice and defy the political agenda to move us to full ID checks for device usage "show me your papers", that's the reality.

Any way, I am going to try an attempt at porting myself when I get time around my full-time workload, it will be a nice side project.

The email...
![image](https://github.com/beemdevelopment/Aegis/assets/729135/fdc7a67b-d1ee-494b-8d6b-fbf06816abf4)

**Comment by polyzen** [comment]
Duplicate of #165

**Comment by noxidsoft** [comment]
Thanks for the heads up @polyzen and thank you for the awesome work you folks are doing here, I'll definately make use of the software anyways. I'll follow @war59312 workaround, it looks viable for my needs for now (:

**Comment by AtomicRobotMan0101** [comment]
> .... I'll follow @war59312 workaround...

https://github.com/beemdevelopment/Aegis/issues/165#issuecomment-1937186325

I'll be doing this for my Linux Mint desktops 🐱😸😺
