### ISSUE TITLE
Backup bug

### ISSUE THREAD

**Issue by fiorins** [beemdevelopment/Aegis#1284]
### Version

v.2.2.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Galaxy S22

### Android version

Android 13

### Steps to reproduce

I change my smartphone with my new galaxy s22 and used Samsung smart switch to get aegis in my galaxy s22 phone from my old one and get this error
![Screenshot_20240226_181357](https://github.com/beemdevelopment/Aegis/assets/32281481/cf6eb105-3eb4-43ae-be23-f3f633114215)

I solved it by creating a new folder on the smartphone for the backup but the error message doest help and it would be better to change the text to help other users who might encounter it.

### What do you expect to happen?

Not get this screen

### What happens instead?

Get this screen each time I retried to backup my vault

**Comment by alexbakker** [comment]
The next version of Aegis will have a better message for this error: #1233.
