### ISSUE TITLE
Biometric unlock stopped working after updating LineageOS

### ISSUE THREAD

**Issue by rozbrajaczpoziomow** [beemdevelopment/Aegis#1287]
### Version

v2.1.3

### Source

F-Droid

### Vault encryption

Yes

### Device

Xperia 10

### Android version

Android 14

### ROM

LineageOS 21.0

### Steps to reproduce

I'm unsure and unable to test if this happens only after upgrading from LineageOS 19.1 (Android 12 iirc) to 21.0 (Android 14).
I don't really have reproduction steps, but assuming the above is false:
1. Install LineageOS 21.0 on an Xperia 10 / kirin device
2. Install Aegis, enable encryption and try to enable biometric unlock

### What do you expect to happen?

For Aegis to allow me to turn on Biometric unlock.

### What happens instead?

An "An error occured" popup is shown and a more detailed stacktrace is printed into the debug.log

### Log

[debug.log](https://github.com/beemdevelopment/Aegis/files/14438426/debug.log)
(I did only logcat before I clicked `Biometric unlock` and stopped after dismissing the popup)

**Comment by rozbrajaczpoziomow** [comment]
After updating to the newest version on F-Droid (thus the newest on GitHub as well) v2.2.2, this bug still occurs. Here's a new debug.log because line numbers changed significantly making it very hard to track this bug down (mainly for my own curiosity, but also for anyone else looking into this).
[debug.log](https://github.com/beemdevelopment/Aegis/files/14438519/debug.log)

**Comment by alexbakker** [comment]
This is a bug in the Keystore implemenation on your device. See the [previously opened issues for "Key user not authenticated"](https://github.com/beemdevelopment/Aegis/issues?q=is%3Aissue+Key+user+not+authenticated+is%3Aclosed)

I would suggest reporting this issue to LineageOS.

**Comment by rozbrajaczpoziomow** [comment]
After you said that and looking at the other issues you linked, it does seem like a bug in LineageOS as none* of the other non-system apps I have work with biometric authentication anymore.
* - Firefox still works somehow.
Thank you for your time.
