### ISSUE TITLE
No entries (without restart) after successfully importing andOTP backup

### ISSUE THREAD

**Issue by iGadget** [beemdevelopment/Aegis#1299]
### Version

2.2.2

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Fairphone 4

### Android version

Android 13

### Steps to reproduce

1. Have existing andOTP backup
2. Install Aegis
3. Open app and finish the first-run wizard
4. Import andOTP backup via Settings (importing from first-run wizard does not work)
5. Notice andOTP entries have been imported
6. Fiddle around on the other settings to customize the app
7. Return to main screen

### What do you expect to happen?

Imported entries should show up without needing to restart the app.

### What happens instead?

Nothing shows up.

However, after killing the app and restarting it, all entries are shown (albeit without icons).

**Comment by alexbakker** [comment]
Thanks for the report! I'm able to reproduce this. I'm a little surprised that nobody (including us) has noticed this before.

To be clear: No data is lost. It's just that the refresh mechanism is not triggered when you return to the main view.
