### ISSUE TITLE
Material 3 inconsistencies

### ISSUE THREAD

**Issue by GiorgioMendieta** [beemdevelopment/Aegis#1300]
### Version

v3.0-beta1

### Source

GitHub

### Vault encryption

Yes (with biometric unlock)

### Device

Galaxy Note S20 U

### Android version

Android 13

### Steps to reproduce

Activate the Dynamic colors option under Appearance > App.

Then access Three dot menu > About

It applies to the following dialogs :
- Changelog
- License

It does not affect Third-party licenses dialog, it seems it's using a different (older?) version of the modal window.

### What do you expect to happen?

A dialog opens with the correct background color.

### What happens instead?

The dialog has a bright blue background instead, not following the Material Design theme. 

If I turn off the Dynamic Colors option, the changelog's background will be the correct color.

**Comment by michaelschattgen** [comment]
Thank you for creating the issue. You're right that this modal is a bit outdated, but since dynamic colors are personalised could you please attach a screenshot of the bright blue background you are talking about?

**Comment by GiorgioMendieta** [comment]
Here are some photos attached, I couldn't take screenshots due to the security policy preventing me from doing so. 

Hopefully this will be of help, thanks for your hard work updating the app!

With Dynamic colors option turned off: 
![20240313_185815](https://github.com/beemdevelopment/Aegis/assets/31053658/5704aecb-cb98-4f28-9f01-d5db7871baa1)
![20240313_185825](https://github.com/beemdevelopment/Aegis/assets/31053658/d3d28e95-164f-4f28-98b8-9fac81c1c2eb)

With Dynamic colors option turned on: 
![20240313_185837](https://github.com/beemdevelopment/Aegis/assets/31053658/0ebeb178-27fd-4fea-be2e-7ffc488610bc)
![20240313_185840](https://github.com/beemdevelopment/Aegis/assets/31053658/cd8dc481-80bc-4d6b-9f3a-90e206305569)
