### ISSUE TITLE
v3.0 Beta 1 - Visual bugs

### ISSUE THREAD

**Issue by cyb3rko** [beemdevelopment/Aegis#1306]
### Version

v3.0-beta1

### Source

GitHub

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 7 Pro

### Android version

Android 14

### Steps to reproduce

Should be obvious, see the screenshots below

### What do you expect to happen?

- Show only one time bar
- Show whole input views

### What happens instead?

If only one item is shown in the list, there are suddenly two time bars:  
<img src="https://github.com/beemdevelopment/Aegis/assets/46033730/58141211-4fb9-41c2-a489-91774bd2984c" height="600"/><img src="https://github.com/beemdevelopment/Aegis/assets/46033730/1b1f3004-fab5-472a-bf6b-2c79b3fd233c" height="600"/>

---

One of the input views is cut off in the dialog for new entries:  
<img src="https://github.com/beemdevelopment/Aegis/assets/46033730/788dcc9e-7e66-48c4-a576-e23658ef5508" height="600"/>

**Comment by michaelschattgen** [comment]
Thank you for reporting this issue. We will fix these.
