### ISSUE TITLE
Import from app error with authy

### ISSUE THREAD

**Issue by rajarshikhatua100** [beemdevelopment/Aegis#1309]
### Version

v2.2.2

### Source

GitHub

### Vault encryption

No

### Device

Samsung m31

### Android version

Android 14

### ROM

TukiOS

### Steps to reproduce

Import from app with root > select Authy 
I am using the letest beta version of authy which is 24.14.5

### What do you expect to happen?

import tokens

### What happens instead?

error occurring 
![Screenshot_20240316_025840](https://github.com/beemdevelopment/Aegis/assets/77912617/4f946d71-ead5-4783-9506-f9f0ceed6960)

### Log

com.beemdevelopment.aegis.importers.DatabaseImporterException: java.io.FileNotFoundException: No such file or directory: /data/user/0/com.authy.authy/shared_prefs/com.authy.storage.tokens.authenticator.xml

**Comment by michaelschattgen** [comment]
There's a big chance we've already fixed this (issue: #1077 and pr: #1278). Could you please try our latest APK to see if that fixes it for you?

**Comment by rajarshikhatua100** [comment]
sorry, mistake on my part, ignored the letest release, working fine

**Comment by michaelschattgen** [comment]
All good, it's a beta release and it has only been out for 2 days. Glad it works for you!
