### ISSUE TITLE
JCenter removal and dependency replacement

### ISSUE THREAD

**Issue by cyb3rko** [beemdevelopment/Aegis#1313]
Hey guys,  
I would like to work on updating the build structure (moving to best-practice build.gradle structure).

One part of that is the removal of the JCenter repository as it was deprecated in 2021.

https://github.com/beemdevelopment/Aegis/blob/9737c85f8659ec797af2524a6495d8837c36dd1d/build.gradle#L18-L25

---

But there are two dependencies that still use that repository, just because they have not been updated in a decade:
- https://github.com/amulyakhare/TextDrawable (10 years)
- https://github.com/guardianproject/TrustedIntents (9 years)

I therefore recommend moving these two implementations to the Aegis source code, that would help us get rid of their old gradle dependencies as a side effect.  
They both only consist of 2-3 classes each, I've cut down the TextDrawable logic to one class and the TrustedIntents to 3 classes and only a few methods (all other logic is not used in Aegis' case).

Do you agree that this step is meaningful? PR can be opened soon

PS: We have to keep licensing in mind, as the licenses dialog will then no longer give attribute to those libraries by itself.

**Comment by alexbakker** [comment]
3a66851df5536c16274d5c5ecd316f937dd65360
