### ISSUE TITLE
AMOLED background color not applying when Dynamic colors are selected

### ISSUE THREAD

**Issue by naiyerasif** [beemdevelopment/Aegis#1316]
### Version

3.0-beta1

### Source

GitHub

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 8 Pro

### Android version

Android 14

### Steps to reproduce

1. Select "System default (AMOLED)" under **Appearance** > **Theme**
2. Switch **Dynamic colors** on under **Appearance**

### What do you expect to happen?

The background color of the app should switch to AMOLED dark.

### What happens instead?

The background color remains the same for all theme options: **AMOLED theme**, **System default** (when dark mode is turned on) and **System default (AMOLED)**.

**Comment by michaelschattgen** [comment]
Thank you for your report, this was already fixed in #1303 and will be released soon
