### ISSUE TITLE
Optional warning banner on main activity when user has exported a plaintext backup

### ISSUE THREAD

**Issue by chiraag-nataraj** [beemdevelopment/Aegis#132]
I was thinking it might be useful to optionally alert the user when they have exported an unencrypted backup of the database. In my case, I do that so I can transfer it (over Signal, of course) to my laptop so I can have a plaintext backup, but a little persistent banner at the top would remind me to then go back and delete the backup file after having transfered it.

I think it goes without saying that there should be a toggle for this in the settings and it should be off by default, but it's something I know *I* personally would turn on.

**Comment by michaelschattgen** [comment]
Thanks for your suggestion. I really like this idea since we focus a lot on security. With this minor feature we can push our users in the right direction to make sure they don't leave their unencrypted databases on their phones.

**Comment by alexbakker** [comment]
I like it. I actually wouldn't mind enabling this by default.

**Comment by alexbakker** [comment]
Implemented by #957.
