### ISSUE TITLE
Notification if database is unlocked

### ISSUE THREAD

**Issue by chiraag-nataraj** [beemdevelopment/Aegis#133]
When a PIN is set for Signal and I have unlocked it, there's a persistent notification at the top which lets me know that Signal is unlocked and gives me the option to lock it or enter the app (that notification goes away if I lock it). It would be nice for Aegis to also have this.

**Comment by michaelschattgen** [comment]
Just letting you know that we've implemented this and that it's available in Google Play as an open beta. If you would like to test this version please visit our [Google Play Store beta page](https://play.google.com/apps/testing/com.beemdevelopment.aegis) and enroll as beta tester.

Please let us know if you have any questions regarding this new beta.
