### ISSUE TITLE
Flashing screen

### ISSUE THREAD

**Issue by BabyOilJohnson** [beemdevelopment/Aegis#1330]
### Version

V3.0

### Source

GitHub

### Vault encryption

Yes (with biometric unlock)

### Device

Samsung A30

### Android version

Android 11

### Steps to reproduce

Open the app.

### What do you expect to happen?

Show the lock screen.

### What happens instead?

Happens a weird screen, the instantly show the lock screen.

<details><summary>Record</summary>
<p>

https://github.com/beemdevelopment/Aegis/assets/101601874/949698e3-1d03-4f79-a8d5-78581ee9b03c

</p>
</details>

**Comment by michaelschattgen** [comment]
Thank you for the report and for the screen recording. I have a feeling this is related to #1325 (which already has been fixed, but not released). Is the app usable for you? Could you try changing your theme to light mode and see if that fixes it for you?

**Comment by BabyOilJohnson** [comment]
> Is the app usable for you?

Yes

> Could you try changing your theme to light mode and see if that fixes it for you?


No, it didn't.
