### ISSUE TITLE
License Section in About Page broken

### ISSUE THREAD

**Issue by elliotwutingfeng** [beemdevelopment/Aegis#1333]
### Version

3.0.1

### Source

Google Play

### Vault encryption

Yes

### Device

Pixel 7a

### Android version

Android 14

### Steps to reproduce

Go to About, then License.

### What do you expect to happen?

See the GPLv3 license text.

### What happens instead?

I see "../../../../LICENSE"

**Comment by alexbakker** [comment]
Thanks for the report. That's unfortunate... This happened because 3.0.1 was built on Windows with Git without symlink support.

**Comment by elliotwutingfeng** [comment]
Would running readAssetAsString on the symlink contents work?

**Comment by alexbakker** [comment]
No, this was just a configuration issue on the machine the APK was built on.

**Comment by alexbakker** [comment]
Fixed in [v3.1-beta1](https://github.com/beemdevelopment/Aegis/releases/tag/v3.1-beta1)
