### ISSUE TITLE
Can't export vault to Google Drive

### ISSUE THREAD

**Issue by jcglza** [beemdevelopment/Aegis#1334]
### Version

3.0.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Galaxy S7

### Android version

8

### Steps to reproduce

Export vault as encrypted JSON to Google Drive

### What do you expect to happen?

The file uploads to my Drive and stays there.

### What happens instead?

The file uploads to my Drive and then instantly gets PERMANENTLY deleted.
![firefox_2024-03-26_11-47-13](https://github.com/beemdevelopment/Aegis/assets/42979427/b58a7899-c958-405c-8eb0-fbac60098668)

**Comment by alexbakker** [comment]
Please capture a log using ADB while the issue occurs and share it here. Guide: https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb

**Comment by alexbakker** [comment]
No response, so I'm going to close this for now, as this is very unlikely to be a bug in Aegis.

**Comment by sequtan** [comment]
I have a similar problem on the Samsung Galaxy S25 (Oneui 7). I choose JSON exports, then share and indicate the Google Drive application. After that, AEGIS writes that everything has successfully unloaded, but in fact there is a notification from the Google Drive application, that the file is loading and there is an endless waiting process. At the same time, on the Google Drive itself, the file appears for a short time and immediately disappears.

**Comment by jcglza** [comment]
@sequtan Yes correct. I never shared my log because I don't care enough to actually do it but I always knew this issue was real. But I have no idea if Aegis can even fix it, maybe? It clearly has something to do with what Google thinks the file is or contains, so it just auto-deletes it.

I have tried to upload the file from my desktop and the same happens, so it has nothing to do with your phone, the issue is the file.
