### ISSUE TITLE
When can I get v3.0 on fdroid ?

### ISSUE THREAD

**Issue by dev-leom** [beemdevelopment/Aegis#1335]
I can't update aegis to v3.0. Google play store tells me there is a new update but I'm not able to install it.

**Comment by alexbakker** [comment]
Did you install Aegis from F-Droid? If so, you can't update it through the Google Play Store. You'll have to wait for F-Droid to release the v3.0.1. 

If you installed Aegis through the Google Play Store, but can't update the app, please report the issue to Google.

**Comment by dev-leom** [comment]
Yes I have installed aegis with fdroid. The latest version available on f droid is 2.2.2. I think I will uninstall aegis and install it with the Google play store.
