### ISSUE TITLE
Aegis for Fossil Smartwatches

### ISSUE THREAD

**Issue by Bout2GitIt** [beemdevelopment/Aegis#1343]
I **love** Aegis way more than I love my phone. In fact, I wish I could use Aegis on my smartwatch and just leave the phone at home.

Maybe I can! My watch is a Fossil HR Collider, and developers can write their own apps using the [Fossil HR SDK](https://github.com/dakhnod/Fossil-HR-SDK). If someone created an Aegis app for Fossil, I could load it onto my watch and then always carry my 2-factor codes with me, even when I leave my phone at home. (I'd still need 2 factor to login to services on my laptop.)

**Comment by alexbakker** [comment]
I'll grant you that this is different compared the usual "please port Aegis to X" requests, but the same answer still applies: We don't have plans to port Aegis to other platforms.
