### ISSUE TITLE
Attempting to run project as is in Android Studio

### ISSUE THREAD

**Issue by dsputnikk** [beemdevelopment/Aegis#1344]
### Version

Latest

### Source

GitHub

### Vault encryption

Yes

### Device

VS Android Emulator

### Android version

Marshmallow API Level 23

### Steps to reproduce

1. git clone repo
2. open in android studio
3. start Visual Studio Emulator for Android / Marshmallow XXHDPI API Level 23 till successful boot.
4. Ensure anroid studio sees Android
5. Run app
6. AegisDev appears as an app, "click on it"

### What do you expect to happen?

The app to start

### What happens instead?

All I see in logcat is:

```
2024-04-04 18:29:22.446  9634-9634  AppCompatDelegate       com.beemdevelopment.aegis.debug      D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
---------------------------- PROCESS ENDED (9634) for package com.beemdevelopment.aegis.debug ----------------------------
---------------------------- PROCESS STARTED (9804) for package com.beemdevelopment.aegis.debug ----------------------------
2024-04-04 18:29:28.066  9804-9804  AppCompatDelegate       com.beemdevelopment.aegis.debug      D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
---------------------------- PROCESS ENDED (9804) for package com.beemdevelopment.aegis.debug ----------------------------
```

App doesn't appear to launch on phone

**Comment by alexbakker** [comment]
I suggest you try Google's Android Emulator. Neither of us use Visual Studio Android Emulator, so I'm afraid you'll have to do most of the heavy lifting to figure out what's going on here.

> All I see in logcat is

There's probably more. Perhaps there's a package name filter enabled? I'd be happy to take a quick look at the full log.

**Comment by dsputnikk** [comment]
> I suggest you try Google's Android Emulator. Neither of us use Visual Studio Android Emulator, so I'm afraid you'll have to do most of the heavy lifting to figure out what's going on here.
> 
> > All I see in logcat is
> 
> There's probably more. Perhaps there's a package name filter enabled? I'd be happy to take a quick look at the full log.

I switched from a VM machine to a physical machine and the android studio emulator. Fine now. Thanks.

My only current problem is the inability to toggle the Biometrics vault encryption. Its greyed out and I'm unable to toggle on.
