### ISSUE TITLE
Multi Device Syncing 

### ISSUE THREAD

**Issue by asmsayeem** [beemdevelopment/Aegis#1348]
Is it possible to add multi device syncing on local network or p2p network in future?  
I know it is a wonderful project and also open source but if it is possible somehow to implement such a feature like multi device syncing eliminating the cloud storage it will be a master piece.

This feature can be done by implementing a unique nameing system for a unique user then under the unique name there can be multiple devices like Android or iphone or even browser extension

**Comment by InfiniteCoder06** [comment]
Duplicate of #866

**Comment by alexbakker** [comment]
Syncing between devices is unlikely to ever be implemented, but Aegis does support automatic backups: https://github.com/beemdevelopment/Aegis/blob/master/FAQ.md#how-can-i-back-up-my-aegis-vault-to-the-cloud-automatically
