### ISSUE TITLE
Progress bar hard to see if combined with dark mode and dynamic colors

### ISSUE THREAD

**Issue by tedd-wq** [beemdevelopment/Aegis#1350]
### Version

3.0.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Xperia 1 IV

### Android version

14

### Steps to reproduce

Use dark mode or AMOLED mode

### What do you expect to happen?

The progress bar to remain visible

### What happens instead?

Progress bar remains black, so is barely visible in dark mode and completely invisible in AMOLED dark mode.

**Comment by alexbakker** [comment]
Could you share a screenshot of what this looks like for you? Temporarily disable "Screen security" in Aegis' security settings first.

**Comment by tedd-wq** [comment]
![Screenshot_20240415-061740~2](https://github.com/beemdevelopment/Aegis/assets/49110506/071a5976-941b-4ec5-955c-422071659af0)
![Screenshot_20240415-061713~2](https://github.com/beemdevelopment/Aegis/assets/49110506/5090cd74-d06f-4b10-a1d0-512c2e210a2a)
![Screenshot_20240415-061713](https://github.com/beemdevelopment/Aegis/assets/49110506/4d8fe3d8-6e06-4e83-91f2-50d118c3847b)

**Comment by tedd-wq** [comment]
![Screenshot_20240415-061740~2](https://github.com/beemdevelopment/Aegis/assets/49110506/0d6945ed-e801-4098-a20f-05b7cfb4feba)
![Screenshot_20240415-061713~2](https://github.com/beemdevelopment/Aegis/assets/49110506/3e462d97-e220-4064-b682-e71f73ed7ca4)
![Screenshot_20240415-061643~2](https://github.com/beemdevelopment/Aegis/assets/49110506/9e909728-7644-4e04-8c65-2241e28c3b4f)

**Comment by elliotwutingfeng** [comment]
I am able to reproduce this by setting my Android system color to black&white, and turning on dynamic colors and dark mode in Aegis.

Phone is Google Pixel 7a, Android 14, Aegis 3.0.1
