### ISSUE TITLE
adding more security, usb token access

### ISSUE THREAD

**Issue by f1-outsourcing** [beemdevelopment/Aegis#1355]
I am a little worried about that if your phone is unlocked or remotely hacked your stuff can be easily accessed. What about having an encryption key stored on a external usb pen drive and only with this usb pen drive inserted, the encryption key is available to unencrypt aegis files and access is possible.

**Comment by f1-outsourcing** [comment]
I don't think other apps have this option. I think it is quite nice! ;)

**Comment by alexbakker** [comment]
Thanks for the suggestion, but I don't agree this adds any meaningful security. This is essentially equivalent to a very strong passphrase. You can actually already achieve something like this if you really wanted to, by configuring a Yubikey as an HID keyboard and having it output a strong password to unlock Aegis.

I also think we would be able to count the number of people who would use this feature on one hand.
