### ISSUE TITLE
Firefox 2FA added to the app, code invalid on the account

### ISSUE THREAD

**Issue by luisimasd** [beemdevelopment/Aegis#1358]
### Version

3.0.1 and 3.0.0

### Source

F-Droid

### Vault encryption

No

### Device

smasung s23

### Android version

android 13

### ROM

Stock

### Steps to reproduce

Create a firefox account
enable 2fa
on the phone, scan the code displayed on the computer by firefox.com
code is correctly scanned, and 2FA toke is correctly imported into Aegis (it looks like)
enter the code generated by aegis into the firefox account in the computer to finally enable 2FA on the firefox account
ERROR: firefox account refuses the 2fa token as it is declared incorrect.

notes: phone and computer are with the correct time

### What do you expect to happen?

the token generated by aegis should be valid on the firefox.com account

### What happens instead?

the 2fa  code is declared invalid on the firefox account.

**Comment by michaelschattgen** [comment]
Do you have any other 2FA codes in Aegis? Are these working?

We've yet to hear about codes not working where the issue wasn't an unsynchronized clock. Please make sure your phones time is in sync, which you can verify by going to [this website](https://time.is/) on your phone.

**Comment by luisimasd** [comment]
Nah, my bad, the computer was ahead on time. Now it is totally ok
