### ISSUE TITLE
Unable to enable biometric unlock

### ISSUE THREAD

**Issue by Avrution** [beemdevelopment/Aegis#1359]
### Version

3.0.1

### Source

Google Play

### Vault encryption

Yes

### Device

Oneplus 7T

### Android version

14

### ROM

Crdroid

### Steps to reproduce

Login to app - try to enable biometric unlock

### What do you expect to happen?

Enable the option

### What happens instead?

An error occurred

### Log

com.beemdevelopment.aegis.crypto.KeyStoreHandleException: android.security.KeyStoreException: User authentication required (internal Keystore code: 2 message: system/security/keystore2/src/[security_level.rs:626](http://security_level.rs:626/)

Caused by:
    0: system/security/keystore2/src/[security_level.rs:199](http://security_level.rs:199/)
    1: system/security/keystore2/src/[security_level.rs:176](http://security_level.rs:176/): Failed to handle super encryption.
    2: system/security/keystore2/src/[super_key.rs:678](http://super_key.rs:678/): Device is locked.
    3: Error::Rc(r#LOCKED)) (public error code: 2 internal Keystore code: 2)

**Comment by michaelschattgen** [comment]
Thanks for the report but unfortunately this is outside of our control. You can try reconfiguring your biometrics in the Android settings but in most cases it's an Xposed module like https://github.com/beemdevelopment/Aegis/issues/299#issuecomment-600636705 that's causing this issue, try disabling those and try again.

Otherwise you would have to contact the manufacturers of your ROM.

**Comment by Avrution** [comment]
Quick update, after many hours of testing I figured out how to fix this, in case anyone else ends up with this issue.

Delete these files and reboot the phone and setup the pin/code/prints again and Aegis will work

data/system/locksettings.db
data/system/users/0/settings_fingerprint.xml
data/misc/keystore/persistent.sqlite

Not sure why Aegis works differently than the other 10+ apps that use biometrics, but I love Aegis and didn't want to switch.

**Comment by michaelschattgen** [comment]
Thanks for reporting back! Your comment is definitely going to be useful for people running into the same issue. Glad you got it sorted out.
