### ISSUE TITLE
All Icon packs are not working simultaneously

### ISSUE THREAD

**Issue by SujitPalRICO** [beemdevelopment/Aegis#1368]
### Version

3.0.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Redmi 3S Prime

### Android version

Android 6.0.1 Marshmallow

### ROM

MIUI Global 10.2 [Stable 10.2.2.0 (MALMIXM)]

### Steps to reproduce

1. Install more than two icon packs e.g. aegis-icons, aegis-simple-icons and delta-aegis-icons.
2. Tap and hold a token
3. Tap 'Assign icons' in the top right menu
4. Try to change the icon of the token
5. Tap the three dots in the top right corner

### What do you expect to happen?

I should be able to access all the installed icon packs e.g. aegis-icons, aegis-simple-icons and delta-aegis-icons.

### What happens instead?

I am able to access only one icon pack "aegis-simple-icons". Other two installed icon packs are not showing. 
I have attached screenshots for better understanding of the problem. Please see them.

![1](https://github.com/beemdevelopment/Aegis/assets/168930789/9b5fe8b6-2999-4bcd-80af-7ebf2ce40a52)
![2](https://github.com/beemdevelopment/Aegis/assets/168930789/4c8f55cd-ca65-4e3f-a7ce-2a0204907c3b)
![3](https://github.com/beemdevelopment/Aegis/assets/168930789/81e4f64c-a827-41b4-9b04-8d1ff842c7be)

**Comment by michaelschattgen** [comment]
Thanks for your report. This only seems to happen if you try to assign an icon through the 'Assign icons' menu. As a workaround for now you can go to the edit screen of a token and tap the avatar at the top. You'll be presented with the same 'Pick an icon' menu, but this one does show all the installed icon packs.

**Comment by SujitPalRICO** [comment]
> Thanks for your report. This only seems to happen if you try to assign an icon through the 'Assign icons' menu. As a workaround for now you can go to the edit screen of a token and tap the avatar at the top. You'll be presented with the same 'Pick an icon' menu, but this one does show all the installed icon packs.

Thank you so much.
