### ISSUE TITLE
Dropbox 2fa QR code is not getting recognized by Aegis Authenticator

### ISSUE THREAD

**Issue by SujitPalRICO** [beemdevelopment/Aegis#1369]
### Version

3.0.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Redmi 3S Prime

### Android version

Android 6.0.1 Marshmallow

### ROM

MIUI Global 10.2 [Stable 10.2.2.0 (MALMIXM)]

### Steps to reproduce

1) Try to enable 2 factor authentication in Dropbox.
2) They give you a QR code to scan by authenticator apps
3) Try to scan with Aegis Authenticator app

### What do you expect to happen?

Aegis Authenticator app should be able to scan the QR code and entry the secret code automatically.

### What happens instead?

Nothing happens when I try to scan the QR code. Aegis Authenticator app is not recognizing the QR code at all.

**Comment by michaelschattgen** [comment]
I can't seem to reproduce this issue. Are other services/websites working for you? Are you sure you're not running any browser extensions that change the colors of the page (dark mode browser extensions for example).

**Comment by SujitPalRICO** [comment]
> I can't seem to reproduce this issue. Are other services/websites working for you? Are you sure you're not running any browser extensions that change the colors of the page (dark mode browser extensions for example).

1) QR codes of other websites are getting recognized without a problem. I have already set up 39 tokens using QR codes from those respective websites and Aegis authenticator is working amazingly.
2) I am not running any browser extensions that change the colors of the page (dark mode browser extensions for example).

I did not do any tweak in my Google Chrome browser. The browser is in it's default state. My laptop (Windows 11), however, is in **dark mode**. Could it be the reason of the issue? I have manually entered the secret code from the Dropbox website and the tokens are working fine. I have tried with two different Dropbox accounts and the Aegis authenticator recognizes none of those QR codes. But when those secret codes are entered manually they are working fine.

**Comment by SujitPalRICO** [comment]
Hello! It is a problem of DARK MODE of Windows 11 which also forces Google Chrome browser to dark mode by default. After setting Windows 11 to LIGHT MODE those Dropbox QR codes are getting recognized by the Aegis authenticator app. Everything is working absolutely fine.
Thank you so much.

**Comment by michaelschattgen** [comment]
Ahh that makes sense. Thanks for reporting back, glad it's working now! I will close this issue then.
