### ISSUE TITLE
Not able to change password

### ISSUE THREAD

**Issue by ISO8807** [beemdevelopment/Aegis#1372]
### Version

3.0.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Motorola G6

### Android version

9

### Steps to reproduce

Initially set up with password and biometric (fingerprint) security. Try to change password with Settings/Security/Change Password.

The following may just be due to lack of documentation (or my understanding) rather than a bug

### What do you expect to happen?

Should be able to enter new password and tap OK.

### What happens instead?

OK button remains grayed out no matter what password I enter.

Actually it's not clear if I have to enter the old password first before entering the new one (though I tried that). Perhaps having a biometric lock as well as a password prevents a new password being used? Or perhaps a password cannot be changed once a vault is encrypted.

**Comment by ISO8807** [comment]
Exactly right. My phone shows only one password field in a popup (without scrollbars). But if I drag up then there is a second password field and I'm able to change the password 😊 Thanks.

**Comment by michaelschattgen** [comment]
Good to hear, glad it resolved your issue!
