### ISSUE TITLE
Manually triggering a backup results in 5 new backup files, instead of 1

### ISSUE THREAD

**Issue by alpenblauwtje** [beemdevelopment/Aegis#1374]
### Version

3.0.1

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

A52s

### Android version

14

### Steps to reproduce

I uninstalled Aegis from Google Play and installed from F-Droid (this specific scenario has likely nothing to do with the bug).
I open the most recent backup file in my backup location and enter the password. In _Settings > Backup_ I select _Automatically backup the ..._ Next I select _Trigger backup_. A backup is made. However not 1, but 5 new files are in my backup location, which means all my old (default 5) backups have been overwritten. They all have a timestamp within minutes where my backups had all a timestamp of 1 month ago (before reinstall).

I tried to reproduce this scenario. Now "only" two new backups are made. 

### What do you expect to happen?

Only 1 new backup file, and my older backup files are preserved (at this time).

### What happens instead?

See steps to reproduce.

**Comment by alexbakker** [comment]
When you initially set up automatic backups, Aegis automatically schedules an initial backup for you. If you then also tap "Trigger backup", you'll have a total of two backups. So no irregularities there.

Regarding the 5 new files you noticed, I don't see a reason why just setting up automatic backups would trigger the creation of 5 backups. It's more likely that you made a couple of small changes, each triggering a separate backup.

**Comment by alexbakker** [comment]
If you have a precise list of steps that reproduces the issue, we're happy to take another look.
