### ISSUE TITLE
show previous and upcoming TOTP codes

### ISSUE THREAD

**Issue by Abdull** [beemdevelopment/Aegis#1376]
quite open it is that one opens an entry only a few seconds before the next TOTP is to appear.
Depending on the task at head, keeping six digits in my head can be challenging, requiring to go back and forth for collecting and typing in all TOTP digits, especially for a task on the same smartphone that Aegis is running on. By then, the TOTP may have already rolled over, requiring to start over.

To my experience, TOTP-enabled services often have a grace period after a TOTP has become stale during which that TOTP is still accepted.

Therefore, it would be useful if Aegis also shows the previous and the next upcoming TOTP code.

**Comment by alexbakker** [comment]
It sounds like the "Freeze tokens when tapped" option under behavior settings would help you out here.
