### ISSUE TITLE
Migrate to Authy or something else? 

### ISSUE THREAD

**Issue by DannyBeanz** [beemdevelopment/Aegis#1384]
I fully appreciate there are no plans for an ios app and this is not a request for one, so close / delete this if you feel it's inappropriate.

My employer is **forcing** me to adopt an iPhone SE, but I have all my MFA accounts configured with Aegis.

Have any other users migrated to another MFA app (eg Authy or Google) from Aegis? If yes, how?

Many thanks
D

**Comment by Berlingwo** [comment]
I would recommend against using Authy as it uses SMS for account access. There is a dedicated option to export to Google Authenticator in the Aegis app.

**Comment by DannyBeanz** [comment]
Excellent, thank you for your response!
