### ISSUE TITLE
Microsoft Authenticator app import to Aegis not working on rooted phone

### ISSUE THREAD

**Issue by eviscerat** [beemdevelopment/Aegis#1386]
### Version

v3.0.1

### Source

F-Droid

### Vault encryption

Yes

### Device

Xiaomi Redmi Note 9 Pro

### Android version

Android 13

### ROM

Lineage OS

### Steps to reproduce

- Have some tokens in Microsoft Authenticator App (com.azure.authenticator)
- Go to Aegis app -> Settings -> Import&Export -> Import from app 
- Select Microsoft Authenticator
- Allow root access if prompted
- Import entries pagw will show with no entries to import

### What do you expect to happen?

- The tokens in microsoft authenticator app should show as entries available for import

### What happens instead?

- nothings shows up

### Log

* Aegis HAS root access
![Screenshot_20240522-131212_Setting](https://github.com/beemdevelopment/Aegis/assets/17407021/9b935b11-4f3b-4e71-94c4-6097a716d5ee)

**Comment by alexbakker** [comment]
Which type of tokens do you have in Microsoft Authenticator that you'd like to import into Aegis? Are they regular TOTP/HOTP or are they Microsoft-proprietary ones?

**Comment by eviscerat** [comment]
> Which type of tokens do you have in Microsoft Authenticator that you'd like to import into Aegis? Are they regular TOTP/HOTP or are they Microsoft-proprietary ones?

Closing this issue since the tokens that were unavailable for import were Microsoft proprietary ones. 

Cheers
