### ISSUE TITLE
Request for adding remote backup facility

### ISSUE THREAD

**Issue by sarowarhosen03** [beemdevelopment/Aegis#1388]
I am using aegis it's very good application alternative of Google. But it's storing back up into local device which is a very dangerous if any phone lost or device damage happened it will be very dangerous so I hope it is will add a functionality to remote backup self hosted server, next cloud ,Google drive, drop box  can be a good option

**Comment by alexbakker** [comment]
https://github.com/beemdevelopment/Aegis/blob/master/FAQ.md#how-can-i-back-up-my-aegis-vault-to-the-cloud-automatically
