### ISSUE TITLE
Keyboard Obscures Tokens

### ISSUE THREAD

**Issue by NathanHawke** [beemdevelopment/Aegis#1392]
### Version

v3.0.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Samsung S24 Ultra

### Android version

Android 14`

### Steps to reproduce

1.) Have enough search result entries to fill your device's screen (For me that's at least 8 entries issued by "Test" with "View mode" set to "Small").
2.) Click search and type in "Test" (or whatever string returns too many results to display at once on your device).
3.) Try to scroll down and see all of the matching results.

### What do you expect to happen?

I expect to be able to scroll down to the bottom of the results list without needing to close the keyboard first.

### What happens instead?

The bottom of the search results are obscured by the on screen keyboard forcing you to close the keyboard if you want to see everything.

**Comment by michaelschattgen** [comment]
Thanks for your report. I agree that this isn't ideal, but I don't think we should have the list appear on top of the keyboard in order for our users to see all results. In my opinion hiding the keyboard on scroll (thus confirming the search term) is a better experience overall and is more consistent with how other apps on Android handle this behavior.
