### ISSUE TITLE
[Feature Request] Require new password to be entered when updating password

### ISSUE THREAD

**Issue by v4u6h4n** [beemdevelopment/Aegis#1395]
Hey everyone :-)

I would like for an additional check to be implemented during the password update process, specifically after the user has entered the new password into the two dialogue boxes, that a final dialogue require the user to enter the new password for the changes to be finalised. I know this adds a level of redundancy that is not typical for password updates, but it was just a bit nerve racking updating it today, and seems to me like a reasonable candidate for an atypical level of verification. That said I understand if devs think its overkill ;-)

**Comment by alexbakker** [comment]
I'm not sure I see the value in an additional password check. If you want to double check, just lock the app after changing the password and try to unlock it again using the new password. If you discover you mistyped your password, restore from a backup.
