### ISSUE TITLE
New install unable to restore from Google Backup

### ISSUE THREAD

**Issue by sirgooey** [beemdevelopment/Aegis#1397]
### Version

v3.0.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

S24 Ultra

### Android version

Android 14 OneUI 6.1

### ROM

Samsung

### Steps to reproduce

I run Aegis on my S24 Ultra. It's configured with a password and biometrics.
I have this issue both with the standard encrypted backup, and a different backup password.
I have "Android cloud backups" enabled, and it shows a recent backup was completed.
Drive seems to confirm (~16KB used by Aegis in the Google Cloud Backups).
When installing Aegis on another phone (have tried two different phones, including when I set up my S24 Ultra), using the same Google account, I do not get an option to restore from the Google cloud backup - only to create a new vault, or import from file etc.
No change even if I force a Google Cloud device backup (Aegis updates as well to show the most recent backup was done).
I know I could create a separate on-device file backup and upload that to Google Drive, but that defeats the point of simplicity.
Is this a bug? Is it supposed to work cross-device using the same Google account?
Thank you!

### What do you expect to happen?

When installing Aegis on a new phone running under the same Google account, I would expect Aegis to find the Google Cloud device backup and prompt me for a password to restore it.

### What happens instead?

Nothing, Aegis only gives me the standard options to create a new vault or import from file etc.

**Comment by alexbakker** [comment]
A couple of questions:
- Did you set up the other device from a factory state, log into your Google account and opt into restoring from backup?
- When did you enable "Android cloud backups" in Aegis? Before, or after you set up the other device?

> I do not get an option to restore from the Google cloud backup

You won't see a prompt for this in Aegis. Android will automatically restore your Aegis vault in case you install it on a new device and opted to restore from backup.

**Comment by aL1aL7** [comment]
Same issue here.
Have activated google backup at Aegis app on my Pixel 6 Pro.
Now the Pixel 6 is broken and I installed Aegis app on my old Pixel 2 (logged in at google) , but there  is no option or question at app setup to restore from cloud backup

**Comment by alexbakker** [comment]
@aL1aL7 Did you set up that old Pixel 2 from scratch?

**Comment by aL1aL7** [comment]
I didn't set up from scratch.
Nevertheless, I got my new phone set up from scratch and the Aegis restore worked
