### ISSUE TITLE
Import from KeePassXC?

### ISSUE THREAD

**Issue by pglpm** [beemdevelopment/Aegis#1400]
This connect to issue #549 : I use KeePassXC on my Linux desktop, and I'd like to import its tokens to Aegis on my phone. I tried by exporting from KeePassXC to a text file (csv, xml, html), but Aegis doesn't seem to recognize or accept the file during import. For the moment then I'll use some other app on my phone instead of Aegis.

Any other possible solutions?

**Comment by alexbakker** [comment]
As you discovered, Aegis does not support importing from KeePass database files. The only option I'm aware of is to do it manually.
