### ISSUE TITLE
Import from Ente Auth

### ISSUE THREAD

**Issue by aryanrajseo** [beemdevelopment/Aegis#1405]
Add support to import 2FA from Ente Auth file https://github.com/ente-io/ente. https://play.google.com/store/apps/details?id=io.ente.auth&hl=en_IN

Thank you

**Comment by alexbakker** [comment]
Sounds good to me. Feel free to submit a PR!

**Comment by aryanrajseo** [comment]
My apologies, i don't have the skillset required for this.

Thanks.

**Comment by valentinb102** [comment]
You can import an unencrypted ente export using the Import from file -> Plain text option.

**Comment by valentinb102** [comment]
Ente Auth uses the XChaCha20-Poly1305 algorithm which is not currently supported in bouncycastle https://github.com/bcgit/bc-java/pull/957

**Comment by sigmundxia** [comment]
Sounds like a great idea:) I've submitted a PR which I hope will fix this issue.

**Comment by alexbakker** [comment]
Implemented by ##1470.
