### ISSUE TITLE
[Feature Request] Option to personalize the display of groups

### ISSUE THREAD

**Issue by PurpleMartian** [beemdevelopment/Aegis#1406]
Grouping is a feature missing in the big tech authenticator (Microsoft Authenticator and Google Authenticator for example).
I really enjoy the feature in Aegis but would love the possibility to display the groups differently.

Example 1:
Collapsible vertically aligned tabs. Tap on it to hide or display its content.

Example 2:
Groups displayed on the side of the screen to select from.

Example 3: 
Similar to browser tabs, displaying the groups in a sidescrolling tab bar on top.

**Comment by jmoses** [comment]
I also would like to be able to view my groups in the main view.  Even just the ability to "show groups" and order them manually (while still sorting within the group by one of the sort methods) would be great.
