### ISSUE TITLE
Custom vault file location

### ISSUE THREAD

**Issue by JohnnyBrav0Sr** [beemdevelopment/Aegis#1409]
Hi

First and foremost I would like to express my appreciation for making and maintaining a great app! However, I would like to make the following feature request:

During the setup of the Aegis app, I would like to pick any folder to store the encrypted Aegis vault file, so that I can pick a folder that automatically synchronizes with a cloud storage (using a cloud syncing app like MetaCtrl). That way, I wouldn't have to bother with exporting / importing backups, because on any device or user profile, the Aegis vault would always be up to date automatically!

I use this setup for my Keepass vault file, and it works like a charm! Keepass DOES allow picking a custom vault file location during setup. I would really like to use the same method for my Aegis vault, if only Aegis would allow me to select a custom location for the Aegis vault file during setup. (For security purposes, I would not use the same cloud storage used for my Keepass vault, even though both files are encrypted).

I would very much appreciate if you would consider this feature request. Thank you.

(With Keepass I mean KeepassXC for Windows and Keepass2Android for Android).

P.s. I noticed a similar feature request in [this thread](https://github.com/beemdevelopment/Aegis/issues/1404). I think my request could provide an easy and practical solution to that request as well.

**Comment by alexbakker** [comment]
I understand the use case, but SAF is just not reliable enough to trust it with writing and updating an important file like your Aegis vault file. There are zero guarantees about the behavior for opening and writing a file through SAF (especially with third-party document providers).

(#1404 is asking for something different and is not related)

**Comment by JohnnyBrav0Sr** [comment]
@alexbakker Does this imply that keepass isn't as safe as I thought? Or does keepass not use SAF encryption?

**Comment by JohnnyBrav0Sr** [comment]
Sorry, I didn't mean to close the issue yet; just pressed the wrong button.

**Comment by alexbakker** [comment]
@JohnnyBrav0Sr It's more about reliability. Corrupting files if the app crashes in the middle of a write, for example. SAF doesn't have anything to do with encryption.
