### ISSUE TITLE
Update the token when it is about to expire

### ISSUE THREAD

**Issue by andreabat1991** [beemdevelopment/Aegis#1410]
A button near the token to refresh it when is near to expire.

**Comment by iminto** [comment]
No, it's not necessary.

In fact, OTP allows you to use expired token, as long as the expiration time is not too long（usually 120 seconds,it 's enough）. Because the time difference between "you see" and "wait for you to finish" was considered in the design.

Therefore, any refresh buttons and worries are redundant

**Comment by alexbakker** [comment]
Could you elaborate a bit more about why you need this feature? There's an option under "Behavior" to "Freeze tokens when tapped". Would that work for you? If not, why not?

**Comment by andreabat1991** [comment]
I have a token that expires every 15 minutes. I need a function that give me the opportunity of generate a new token 5 minutes before that the token expire.
This because i need to give the token to the user but the user can insert the token only after a few minutes later. In some situations can happen that i give to the user a token that is near to expire and when the user had the opportunity to insert the token it is expired. For this reason i need to regenerate the token a few minutes before the expiration.

**Comment by elliotwutingfeng** [comment]
Would the ability to display the next TOTP concurrently with the current TOTP be useful? Something like ente auth.

![auth-home-screen.jpg](https://github.com/user-attachments/assets/1f51a572-98bf-418b-a394-a09f0880e362)

**Comment by fuzzzerd** [comment]
@elliotwutingfeng I would find that a very useful feature, even for my personal short lived codes. There are plenty of times that I open the app and the current code is in the bottom 30% of lifetime and I know I wont be able to get over to the other app and punch it in quick enough, so I wait for the next one.

**Comment by elliotwutingfeng** [comment]
I read the comment by @andreabat1991 again. Couldn't you give the user the password only at the moment it is updated (0 minute mark) so the user would have 15 minutes to use it? I am assuming the TOTP server is unusually strict with no grace period.

**Comment by marbv1** [comment]
> Would the ability to display the next TOTP concurrently with the current TOTP be useful? Something like ente auth.
> 
> ![auth-home-screen.jpg](https://private-user-images.githubusercontent.com/30223404/359270633-1f51a572-98bf-418b-a394-a09f0880e362.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDg0MzMsIm5iZiI6MTcyNDI0ODEzMywicGF0aCI6Ii8zMDIyMzQwNC8zNTkyNzA2MzMtMWY1MWE1NzItOThiZi00MThiLWEzOTQtYTA5ZjA4ODBlMzYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEzNDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZjZiZWQzMWVjYWM3ZWFmZTkzMGZmNThjOTc2MzhkZDUzM2EyMDU1YTZiYmY4MzI2ZTBiYzk2YTU0ODRiMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p6WnHLiRNC6E9JMaS2jUkIwNR8TQ4rWMunqG5mGCis4)

That would be very useful!
I actually tried switching to Ente Auth just for this feature, but I still prefer the Aegis interface...

**Comment by michaelschattgen** [comment]
Merging this issue with the one we already had #923 since it has quite some overlap. Feel free to continue the discussion over there.
