### ISSUE TITLE
any way to reset my password without the old one?

### ISSUE THREAD

**Issue by BatDevil** [beemdevelopment/Aegis#1411]
I know i know, forgetting my password is an amateur mistake especially knowing the risks coming with it but is there any alternative?

**Comment by michaelschattgen** [comment]
Unfortunately if you lost your password and you can't get into your vault with biometrics there is nothing you can do. You'd have to contact the services you had 2FA with to reset your two factor authentication.

**Comment by BatDevil** [comment]
i can still access it through biometrics, I'm just quite stressed about the password.

sorry for the other issue i got confused because it looked like it disappeared when the sorting was on open

**Comment by michaelschattgen** [comment]
Copied from the other issue:
>I can access Aegis Authenticator through biometrics, the problem is I'm highly concerned about the issue of losing my password, is it a big deal if i can still access it?

Yes. Yes it is a big deal and you should make sure you never lose the password to your vault. A change in your devices biometrics settings (in Android settings) invalidates all fingerprints and requires you to unlock the vault with your password.

My advice would be to safely store your password somewhere and if you forgot it, unlock the vault with biometrics and immediately change your password.

**Comment by BatDevil** [comment]
how can i change my password if the old one is required for it to be reset?

**Comment by michaelschattgen** [comment]
Your old password is only required if you made changes to your biometric settings in Android. 

If you're still able to unlock the vault with biometrics then you're lucky and you can just change the password.

**Comment by BatDevil** [comment]
sorry I'm dumb i thought the old password was required, really shouldn't have selpt late. thanks pal, your help is genuinely much appreciated.

**Comment by michaelschattgen** [comment]
No problem! Whenever your vault is unlocked you can just change the password without the need of the old one.

Good luck!

**Comment by BatDevil** [comment]
may god reward you for your service to all humankind and no this is not a sarcastic statement.
