### ISSUE TITLE
App crashes after unlocking vault (and after importing encrypted vault)

### ISSUE THREAD

**Issue by J0hn-Lawrence** [beemdevelopment/Aegis#1416]
### Version

3.1

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 6

### Android version

Android 14

### ROM

GrapheneOS

### Steps to reproduce

1. open app
2. unlock vault (either by password or biometrics, does not matter)
3. app shows black screen and crashes after a few seconds

### What do you expect to happen?

Vault unlocks and allows me to use the app normally, i.e. show 2FA codes from my vault.

Note: I installed aegis in my Android work profile and imported one of my encrypted backups (meaning the app had no cache), I was able to import the vault, but when I hit the button to complete the setup, the app showed a black screen and crashed after a few seconds.

### What happens instead?

app crashes
Note: This behavior was first observed after upgrading to V 3.1.

**Comment by michaelschattgen** [comment]
Thanks for your report. Your issue is probably either related to [this issue](https://github.com/beemdevelopment/Aegis/issues/1298#issuecomment-1994359143) where your vaults size is big or it's related to the Pixel June update #1342.

**Comment by J0hn-Lawrence** [comment]
Thanks for linking these issues! I read that some people had success with rebooting their device. I tried it and it worked!! I am unsure on how to handle this issue now, I suppose we should close it, as this issue is already beeing tracked in #1342 ?

**Comment by michaelschattgen** [comment]
I'm glad the reboot worked in your case! I already closed your issue as I was pretty confident it was similar to the ones reported, but feel free to continue the discussion!

What version of Android 14 are you running exactly? I have a feeling the latest Pixel July update (which came out a few days ago) magically fixes this bug but I'm still looking into it.

**Comment by J0hn-Lawrence** [comment]
I am running Graphene OS, Android 14, build number 2024070201 with July 5, 2024 Android security update. I am not able to find something like a commit or version hash in the settings page unfortunately.

**Comment by michaelschattgen** [comment]
Ahh right, I wasn't aware of this issue happening on more ROMs other than AOSP (Pixel)... We still have too little information about this bug, all I know that this was introduced with the June Pixel update. Hopefully we'll have more information to share about this soon.

P.S.: Thank you so much for the donation!
