### ISSUE TITLE
Advanced from entry Edit disappears.  No Advanced items visible.

### ISSUE THREAD

**Issue by andbenn** [beemdevelopment/Aegis#1417]
### Version

3.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 6a

### Android version

14 (AP@A.240605.024)

### Steps to reproduce

Put any entry into Edit mode
Tap Advanced
// expect to see advanced fields
// get: Advanced disappears

### What do you expect to happen?

I expect to see the advanced items for the current entry

### What happens instead?

They aren't visible.
I have found that a small downward swipe on certain areas of the lower screen cause it to paint and show the fields.

**Comment by alexbakker** [comment]
Confirmed, thanks. This regression was probably caused by: 2b2c4fc0ce94ba94a0f4543b3841e2ca5ba85bed.

**Comment by andbenn** [comment]
Wow, super thanks for the fix. Got it on my phone couple hours back.
