### ISSUE TITLE
Make third party license info more accsesible

### ISSUE THREAD

**Issue by blap-o** [beemdevelopment/Aegis#1419]
I wanted to review Aegis's Third Party licenses, but the list is quite extensive, and I can only access it through the app.

Would it be possible to add this information to GitHub?

If not, is there any other way to review this information outside the app?

**Comment by alexbakker** [comment]
It's also available in JSON format: https://github.com/beemdevelopment/Aegis/blob/1201b505f7735e10abc7e3767fed0d1d298545b4/app/src/main/res/raw/aboutlibraries.json.
