### ISSUE TITLE
[Feature] Use Google Play Open Beta program

### ISSUE THREAD

**Issue by troyengel** [beemdevelopment/Aegis#142]
Alex commented in #125 he's built a debug APK to assist in solving that issue. It would be nice if we could source these test builds through the Google Play beta program as a distribution method: https://support.google.com/googleplay/android-developer/answer/3131213?hl=en

This would enable (a) devs to publish to the wider audience in one control panel, and (b) enable users to obtain test builds using the standard Play experience. Thanks for considering the idea. :)

**Comment by chiraag-nataraj** [comment]
As someone who is actively trying to reduce my exposure to Google, it would be sad if this were the only way to obtain the beta APKs.

**Comment by gkeegan** [comment]
I'm sure it wouldn't be the only method to get them. @chiraag-nataraj

**Comment by alexbakker** [comment]
We've discussed doing beta releases before and I think @michaelschattgen and I agreed that it would be a good idea to have a small group of users test new features and bug fixes that way. We usually only provide debug APKs for like issues like #95 and #114, where pushing potential fixes directly to beta users would just be too risky, so you'll probably still see those pop up every now and then.

Also, @gkeegan is right. Google Play will never be the only source for builds of our app. Beta releases would be tagged in Git and have an APK attached to them on GitHub, just like we do for stable releases now. I'm not sure how to handle F-Droid though. Do they also have a separate channel for beta releases? If not, we should not forget to update the tag filter to exclude beta releases there.

**Comment by troyengel** [comment]
This might be for a new issue, but sort of combined here since I was just looking for it testing that debug build- we need an in-app About line item in the Settings which lists the version / build number as part of this solution for testers.

**Comment by alexbakker** [comment]
@troyengel Indeed. It's on the list: #137.

**Comment by alexbakker** [comment]
We have started using the Google Play Open Beta program by releasing v1.0-beta1! This is a big release, so we would appreciate some extra testing by the community before we release it to production channel. You can opt into the beta here: https://play.google.com/apps/testing/com.beemdevelopment.aegis.

Unfortunately, F-Droid users will not receive alpha/beta releases. See [this pull request](https://gitlab.com/fdroid/fdroiddata/merge_requests/5371/diffs) for the rationale of this decision. The beta release will be made available on GitHub once that pull request has been merged.

If the Open Beta program turns out to yield valuable feedback, we may start publishing beta releases before every major release in the future.

**Comment by Wilker-a** [comment]
regarding F-Droid, maybe looking at info about unstable builds can help?

that is how get KeePassDX beta updates
![a cropped screenshot of the F-Droid settings. In particular, highlighting two settings, them being Expert Mode and Unstable Updates. Both are enabled.](https://user-images.githubusercontent.com/10854855/64078401-7d4cb400-ccb0-11e9-8846-007076b49bf1.png)

**Comment by alexbakker** [comment]
@Wilker-a Thanks for the tip.

So, apparently there _is_ a way to separate unstable app versions from stable ones on F-Droid, but it's kind of hacky. We would have to manually set the [``CurrentVersion``](https://f-droid.org/en/docs/Build_Metadata_Reference/#CurrentVersion) field in the metadata file to the current stable version every time we publish an update. Currently, that field is updated automatically every time we push a new non-beta version tag to GitHub. I really don't want to lose that automation, as getting pull requests merged into ``fdroiddata`` tends to take a while. 

If someone knows of a good way to handle unstable versions for F-Droid, we're all ears, but I think we'll stick with the current setup for now.
