### ISSUE TITLE
To use Pin, need all Number Password?

### ISSUE THREAD

**Issue by DarkAoRaidenX** [beemdevelopment/Aegis#1421]
Yo, I tried finding an email to ask this question but couldn't. 

I am wondering why is it that to use a PIN to open the app I need a password with only numbers?

**Comment by michaelschattgen** [comment]
The PIN keyboard feature doesn't work as an additional code/password to your vault, it **is** your password. So you're unable to have the PIN keyboard if your password doesn't only contain numbers.

This feature just simply replaces the normal qwerty keyboard to a pin keyboard for easier input, but the password itself remains the same.
