### ISSUE TITLE
Authy import not working

### ISSUE THREAD

**Issue by phixion** [beemdevelopment/Aegis#1422]
### Version

3.1

### Source

Google Play

### Vault encryption

No

### Device

Pixel 3a

### Android version

Android 14

### ROM

LineageOS

### Steps to reproduce

Neither file import or app import do work. I get a prompt to enter the encryption password. but it alwas fails

### What do you expect to happen?

have all my otps imported

### What happens instead?

nochting is imported

**Comment by alexbakker** [comment]
Take us through the actions you took in the app step by step. What does "it fails" mean? Do you see an error dialog? What does it say?

**Comment by tomrex4** [comment]
Hi, I was having the same issue. Phone is rooted with Magisk.

- Click on import from Authy 
- Root access granted 
- Prompt: Please enter a password. (Authy tokens encrypted)
- I tried opening Authy, it doesn't prompt me for a password, I also turned off the PIN and tried again. 
- When I pasted the master password in Aegis, I got an error (BAD_DECRYPT). 


What worked for me, is to turn off the backup in Authy, then turn it on again. It prompted me for my master password, and once it was validated, Aegis was able to find the tokens. 

Hope this helps! @phixion
