### ISSUE TITLE
Error: scanning QR code 

### ISSUE THREAD

**Issue by ARN1333** [beemdevelopment/Aegis#1427]
### Version

3.1

### Source

F-Droid

### Vault encryption

No

### Device

Pixel 7a

### Android version

Android 14

### ROM

LineageOS

### Steps to reproduce

Scan QR code

### What do you expect to happen?

Get the QR code scanned

### What happens instead?

Error message: com.beem development.aegis.otp. Google AutinfoException:unsupported protocol

### Log

com.beem development.aegis.otp. Google AutinfoException:unsupported protocol

**Comment by michaelschattgen** [comment]
What online service are you trying to scan the QR for? You're either presented a non standard OTP qr code **or** you're trying to scan a QR code which contains a download link to a 2FA app (Yahoo is known for doing this).

**Comment by alexbakker** [comment]
No response, so closing this for now. Given the "unsupported protocol" error I think it's safe to assume they tried to scan to wrong QR code.
