### ISSUE TITLE
Aegis gets stuck on the same screen when unlocking

### ISSUE THREAD

**Issue by rexon113** [beemdevelopment/Aegis#1428]
### Version

v3.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Google Pixel 7

### Android version

Android 14

### Steps to reproduce

1. Open Aegis
2. a. If enabled, wait for biometric fingerprint promp and press the valid finger on the screen
2. b. Otherwise enter valid password

### What do you expect to happen?

The next screen should appear, that is the screen with all tokens should appear

### What happens instead?

Nothing happens. The only thing that happens is that the "Unlock" button gets grayed out. After a few seconds the screen gets black. It doesn't matter whether biometric unlock is used, or password. 

The next screen only appears when I temporarily switch to another app, and then back to Aegis

### Log

[logbiometricunlock.txt](https://github.com/user-attachments/files/16240284/logbiometricunlock.txt)
[logspasswordunlock.txt](https://github.com/user-attachments/files/16240285/logspasswordunlock.txt)

I tried resetting appdata and reimporting the vault. No effect

**Comment by michaelschattgen** [comment]
Thanks for your report. This is already a known bug and unfortunately a bug in Android.

You can join and follow the discussion here: #1342
