### ISSUE TITLE
Shizuku

### ISSUE THREAD

**Issue by kittenvr** [beemdevelopment/Aegis#1440]
When importing from an ap (requires root access) make it so it asks [shizuku](https://github.com/RikkaApps/Shizuku-API) access

**Comment by alexbakker** [comment]
I'm not sure what the benefit of implementing support for Shizuku would be, as accessing internal storage of other apps would still require root access. What am I missing here?

**Comment by alexbakker** [comment]
No response, closing for now.

**Comment by kittenvr** [comment]
I just thought there would be a way to access it with shizuku
