### ISSUE TITLE
Microsoft Authenticator import file not found 

### ISSUE THREAD

**Issue by AA1999** [beemdevelopment/Aegis#1441]
Hi, I'm trying to import my 2FA tokens from Microsoft authenticator using files. However, even with a Root Explorer like Mixplorer I cannot find the given path in /data/data as it only contains the Mixplorer data.
Is there another way to import or do I need to have it rooted?

**Comment by alexbakker** [comment]
You need root access in order to be able to read from the internal storage of Microsoft Authenticator.
