### ISSUE TITLE
AEGIS doesn’t export non-encrypted JSON!? Does 2FAS phone home?

### ISSUE THREAD

**Issue by Wynstan** [beemdevelopment/Aegis#1443]
My Android phone and its battery are nearing their EOL. So, I want to install an authenticator on my iPad for fallback. I decided on 2FAS for the iPad since Aegis for iOS doesn’t exist.

But Aegis doesn’t export its vault in a non-encrypted JSON which 2FAS could import. Am I right?
I have Aegis 3.1.1 on my phone.

Until I get a way to export Aegis’ vault in a non-encrypted form, I plan to do the following to add all my accounts, one by one, into 2FAS on the iPad:
In Aegis, for each account, display its QR code (What a fantastic feature!).
Scan the QR code using 2FAS on the iPad.

On this occasion, please let me vent about 2FAS.
I’m betting that users in this Github will have honest responses, if any.

I’ve been testing Aegis and 2FAS side-by-side on my phone during the last 2 days.

Why is 2FAS’ app size 60MB, compared to Aegis’ 20MB?  2FAS has fewer features than Aegis. 
2FAS is the second biggest user of battery after “Screen”.  Aegis isn’t even on the list.
2FAS’s maximum memory usage was 98MB, compared to Aegis’ 65MB. 
2FAS has used, in 2 days, 0.95MB of data and 0.02MB of Wi-Fi, while Aegis used 0MB.

Why did 2FAS use data and Wi-Fi? What is it doing? I never turned on its “Google Drive Sync” feature. (I usually have Wi-Fi turned off except when necessary.)

**Comment by michaelschattgen** [comment]
We do support non encrypted exports in Aegis. Go to settings -> import & export -> export. You'll be presented with a modal where you can choose to export the vault without encryption.

**Comment by Wynstan** [comment]
Its good to hear that Aegis supports non encrypted exports.
Then, what's wrong with my darn phone?  (LG-M151, Android 6.0.1)
When I de-select "Encrypt the vault", "OK" becomes unclickable.

In the same vein, "OK" is unclickable when I select Export format ".TXT" or ".HTML".
Thanks

![Capture+_2024-08-02-02-15-59 copy](https://github.com/user-attachments/assets/f586a0d8-0713-46e3-a960-69f125e88370)

**Comment by michaelschattgen** [comment]
I understand that is unclear, but due to your screen size the rest of the form gets hidden behind the modal. Scroll the contents of the modal and tap "I understand the risk".

**Comment by Wynstan** [comment]
I think the word "modal" means the pop-up window titled "Export the vault"?
If yes, nothing moves when I move my finger around inside the modal.
Thanks
