### ISSUE TITLE
Request for Aegis Development for Windows/Linux

### ISSUE THREAD

**Issue by enesehs** [beemdevelopment/Aegis#1452]
I believe that by developing Aegis Auth for Windows and Linux, you will continue to uphold your commitment to providing secure and efficient solutions to a wider audience. Your attention to this request would be greatly appreciated, and I am confident that it will contribute positively to your brand’s reputation and user base.

Thank you for considering this request. I look forward to your positive response.

**Comment by alexbakker** [comment]
Duplicate of #165.
