### ISSUE TITLE
Consider a 2nd Master Password

### ISSUE THREAD

**Issue by davidovic999** [beemdevelopment/Aegis#1456]
Please consider adding a 2nd password that is a Master Password for encryption, backup and the vault.

Because we can't set a hard-to-remember password to access the application.

That's why I suggest keeping this 1st password for access to the application as a kind of PIN.

And ask for a 2nd Master password, which we'll safeguard ourselves, and which will be used to encrypt/decrypt the vault.

I don't know if this proposal is going in the right direction.

Thanks for this great App,

**Comment by davidovic999** [comment]
I've just found out that it is possible to set a PIN in the settings.
The only condition is that the password must be made up of numbers.
And that's not good!

Why this restriction on the password?

**Comment by elliotwutingfeng** [comment]
Under the Security section, what is your setting for "Use PIN keyboard on lockscreen"?

**Comment by davidovic999** [comment]
I've enabled “Use PIN keybord on lockscreen” in Security.
But as you can see in the comment about this feature in the app, it says: “ ... This only works for numeric passwords”.
It means that the master password must only be numeric in order to use the PIN!
This restriction on password format is unwise.

**Comment by elliotwutingfeng** [comment]
> This only works for numeric passwords

No. You should turn **off** the "Use PIN keyboard on lockscreen" if you want to use non-numeric passwords.

The "Use PIN keyboard on lockscreen" setting is for switching to a numeric-keypad-only input, which is only allowed if your password is numeric.

**Comment by alexbakker** [comment]
The "Separate password for backup & export" is the option you're looking for.

**Comment by davidovic999** [comment]
What I want to achieve is to compose a master password with “uppercase letters, lowercase letters, digits, special characters” that is reserved for the vault's encryption. I'm going to save this password.

And I want to use an easy-to-remember PIN to open the application when it asks me to “Unlock the vault”.

Because, of course, nobody will be able to remember a complicated password every time they want to open the application.

**Comment by alexbakker** [comment]
That's exactly what you're able to accomplish with the option I mentioned.

**Comment by davidovic999** [comment]
Okay, I'll enter a master password in “Separate password for backups & export” and enter a pin in “password”.

**Comment by davidovic999** [comment]
Thanks alexbakker,
