### ISSUE TITLE
Allow sync over multiple devices

### ISSUE THREAD

**Issue by Jn115759** [beemdevelopment/Aegis#1463]
It would be beneficial if an option is provided to allow syncing over multiple devices. E. G by allowing to store the encrypted database on a cloud drive and automatically read this database when the app is used on an installed device

**Comment by alexbakker** [comment]
Aegis supports automatically backing up to cloud providers if they fully participate in Android's Storage Access Framework (SAF), but there are no plans to implement a synchronization mechanism.
