### ISSUE TITLE
Description Text should also be searched

### ISSUE THREAD

**Issue by SVNKoch** [beemdevelopment/Aegis#1469]
You can specify a description field for each 2FA entry. This description should also be searched by the search feature please :)

**Comment by michaelschattgen** [comment]
Thanks for your feature request! This already has been requested in #1314 and we've already made a pull request for this in #1468. This is going to be available in our next release.

**Comment by SVNKoch** [comment]
whops, didnt find that issue as i was searching for description rather than notes, my bad.
Thanks for the change! ❤️
