### ISSUE TITLE
Long press for reorder not working on favorite entries 

### ISSUE THREAD

**Issue by elliotwellick** [beemdevelopment/Aegis#1471]
### Version

3.1.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 4

### Android version

Android 14

### ROM

Stock Android 

### Steps to reproduce

Long press an favorite item. Once it selects, long press again.

### What do you expect to happen?

It allows me to drag the item up or down to reorder in favourite entries/accounts 

### What happens instead?

It doesn't reorder. It just scrolls up and down.

**Comment by michaelschattgen** [comment]
What are you exactly trying to do here? It is intended that favorites cannot be dragged around, that's what favorites are for. They will always stay at the top.
