### ISSUE TITLE
I made screenshot graphics for this app, let me know how to make it better.

### ISSUE THREAD

**Issue by jugaaadd** [beemdevelopment/Aegis#1473]
These are the screenshots 
![aegisfeaturelist2](https://github.com/user-attachments/assets/380ac608-36b2-4053-91a9-034209262926)
![aegisfeaturelist3](https://github.com/user-attachments/assets/b30e353a-585c-42aa-b0b9-e546e41043e2)
![aegisfeaturelist4](https://github.com/user-attachments/assets/5fdd62f6-1f9d-45a6-9e2c-11764f0b396a)
![aegisfeaturelist5](https://github.com/user-attachments/assets/fcc821a3-b2fe-4dec-a4af-0720adc380c5)
![aegisfeaturelist6](https://github.com/user-attachments/assets/7accb326-0deb-4c49-ba7a-e2bc66671a45)
![aegisfeaturelist7](https://github.com/user-attachments/assets/fbf9b8c3-cf18-4b7d-8648-916868927115)
![aegisfeaturelist8](https://github.com/user-attachments/assets/e6fcf8ba-0d18-4037-9720-a05df5e6355e)
![aegisfeaturelist1](https://github.com/user-attachments/assets/9a943f4a-07c2-4107-990e-f346851432d6)

**Comment by michaelschattgen** [comment]
Thanks but I think the featured graphics we currently have work just fine. Also this contains screenshots from Aegis from over half a year ago, the app has had a major UI overhaul (Material 3). Do you have any suggestions on how to improve ours?

**Comment by krisu5** [comment]
And font you're using isn't Roboto, that could confuse users.
