### ISSUE TITLE
Password reminder happens too often

### ISSUE THREAD

**Issue by Hawk777** [beemdevelopment/Aegis#1474]
### Version

3.1.1

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Motorola 5G One Ace

### Android version

11

### Steps to reproduce

1. Set up both password and biometric authentication.
2. Set the password reminder to quarterly.
3. Use Aegis on a daily basis, always unlocking biometrically.

### What do you expect to happen?

Every three months, biometric unlock should not be offered immediately; instead, the login screen should ask for a password (though allow me to choose biometric unlock if I insist).

### What happens instead?

The login screen asks for a password rather than biometrics every few days.

**Comment by alexbakker** [comment]
Do you actually unlock Aegis with the password when prompted to do so? That's the only way to dismiss the password reminder.

**Comment by Hawk777** [comment]
I think I did sometimes, but I can’t remember for sure. I’ll use a password next time it asks for one, and record the date when it does so and when it next asks.

**Comment by alexbakker** [comment]
Thanks, I'll close this for now. If you discover that this actually doesn't work as expected, just drop a comment and we'll reopen this.
