### ISSUE TITLE
Start with fresh install

### ISSUE THREAD

**Issue by 1Eyed** [beemdevelopment/Aegis#1476]
Hey!

Do to my own stupidity, i've forgotten my password.
Luckily i was able to access the app with my fingerprint and backup all the entries.
What i wish to do now is start from scratch and import my backup (reinstall app). But when i want to do this, it asks me for my vault password.
Anyway i can delete the old vault?
Or is they any way to start from scratch so i can import my backup?

I was hoping to have some kind of option to start from scratch, "new user" or "new vault".

Let me know if you require any further information from me.

**Comment by michaelschattgen** [comment]
Glad to hear you're still able to access your vault. You could just backup your vault, go into your device settings and wipe app storage for Aegis. But since you're able to unlock your vault you could also just re-enable Encryption in the settings and you can set up a new password.

**Comment by 1Eyed** [comment]
> Glad to hear you're still able to access your vault. You could just backup your vault, go into your device settings and wipe app storage for Aegis. But since you're able to unlock your vault you could also just re-enable Encryption in the settings and you can set up a new password.

Thank you for the help, that worked like a charm.  🍻
Once i deleted the App data, i  just imported my backup and now i have everything back.
