### ISSUE TITLE
Question - Time delay for decrypting back up

### ISSUE THREAD

**Issue by anglefu** [beemdevelopment/Aegis#1484]
Long time user. Love your app and the ability to export encrypted backups. 

Was reading up on how long it takes to bruteforce a password recently. I saw that keepass has feature that sets the number of iterations to increase the computational effort of a guessing attack. https://keepass.info/help/base/security.html#secdictprotect

Does Aegis offer a similar thing? I think this is something that is stored on the encrypted file, and used for decrypting. Not sure how keepass implements it either. 

Context is I want to put my keepass db and encrypted 2FA aegis backup somewhere less secured(basically public) to make the these files more available.

Thank you!

**Comment by anglefu** [comment]
I read more about it. 

Basically KeePass: master pass key is first hashed, then key K is transformed using key derivation function(KDF) with a random salt to a better key that is actually used to encrypt user data. KDF has some tunable parameters + a salt that slows down the brute force creation of better keys. 

The time delay used is to adjust these tunable parameters so the user can use more secured, higher compute effort KDF while not degrading their user experience of unlocking their encrypted database at the same time. These parameters are stored in plain text in their files. So application can read them and use those parameters for the KDF to generate better key(from master passkey) to decrypt database. 

I am guessing Aegis doesn't have something like this.

**Comment by alexbakker** [comment]
Aegis has a default set of parameters that it uses for scrypt, but they are not hardcoded. So in theory, you could develop a small piece of software to customize the parameters for your Aegis vault file.

I don't think we will ever support that level of customization in the app though. It leads to all kinds of challenges on mobile devices (And even without customization: #114). You could also run into issues when trying to decrypt an Aegis vault on an older device that doesn't have as much RAM as the newer device you set up Aegis on, for example. In addition, even the more technical users usually don't understand what KDF parameters do. I think it's better to have a sane default, and encourage strong passwords instead.
