### ISSUE TITLE
Importing accounts from Google Authenticator 6

### ISSUE THREAD

**Issue by nigelp** [beemdevelopment/Aegis#1488]
Does the roadmap include the ability to import accounts from Google Authenticator 6 (and beyond?). I'm trying to migrate from Google to open source and it's going to be a pain to transfer accounts manually to Aegis.

**Comment by nigelp** [comment]
Thanks for the quick response. I haven't tried it, because when I went to the Import & Export function in Aegis, and selected Import from File - Google Authenticator, it says "only database files from Google Authenticator v5.10 and prior are supported". Hence my question?

**Comment by michaelschattgen** [comment]
I understand the confusion. This message has been added introduced in #922 since Google Authenticator started encrypting their entries in v5.2 which makes it impossible for us to read the contents.

So yeah the only option now to import Google Authenticator tokens is to use the 'Transfer' method I explained above, which works just as well! Closing this issue but feel free to continue the conversation.

**Comment by michaelschattgen** [comment]
No need to be sorry! It seems like you're trying to import the screenshot through the "Import file" wizard. This doesn't work. Press the big '+' sign on the main screen of Aegis to select to scan an image.

**Comment by nigelp** [comment]
I'm starting to feel really stupid now. When I try to scan the image I get an error message again. 

Screenshot_20240916_132223_Authenticator.jpg:
com.beemdevelopment.aegis.helpers.QrCodeHelper$DecodeError: com.google.zxing.NotFoundException

**Comment by nigelp** [comment]
Done! Seems like I had to scan the two QR codes directly from another screen (my PC) instead of via a file. Once I did the two, it worked perfectly. Thanks very much for your patience! :)

**Comment by michaelschattgen** [comment]
Ahh yeah there's some inconsistencies with the QR code scanner we use as discussed in #802, I was hoping you would not run into this issue. Glad you were able to transfer over your accounts though!
