### ISSUE TITLE
Consider Reverse Engineering / Supporting Microsoft Proprietary 2FA

### ISSUE THREAD

**Issue by Giwayume** [beemdevelopment/Aegis#1493]
I am aware of #559 #588, as mentioned in those issues, Microsoft no longer has an "application without notifications" button and is forcing their proprietary app.

![362771373-c2c69059-9ad9-43c0-a32c-fdd48d3c0014](https://github.com/user-attachments/assets/688ca167-3b21-4347-a9db-e01b0a8e38e7)

Please consider adding support for their proprietary 2FA, once it is reverse engineered from their Android app the effort will not need to be repeated, because in order for them to update their algorithm they would need to force all of their app users to both update their app and re-authenticate.

**Comment by alexbakker** [comment]
Duplicate of #25

**Comment by michaelschattgen** [comment]
The reason why we don't want to add an API call is because Aegis works completely offline and doesn't require any network permissions. We are not changing that.

**Comment by Giwayume** [comment]
How about allowing for a companion app to handle the API call and communicate back to Aegis in that case?

**Comment by Giwayume** [comment]
I've seen other apps like Mihon take this approach, they delegate functionality they don't want to support in the base app to "extension" apps which must be manually trusted.

**Comment by michaelschattgen** [comment]
I haven't done enough research on the capabilities and perhaps the limitations of a companion app. However I'm not looking forward to maintaining another app solely for this use case. 

Before we even consider creating a "extension" app I would rather know whether it's even possible to replicate the same API call as the Microsoft Authenticator app does.

**Comment by Giwayume** [comment]
I'm not even suggesting you maintain it, but if the capability is added for an extension app to hook in to the code scanning process and store whatever custom data it needs for that code, anyone could write it.

Like:
1. User installs extension app
2. User opens Aegis app and goes in to settings to enable and "trust" extension app. Show security disclaimer.
3. When a QR code is scanned that Aeigis doesn't know how to handle, ask each extension app if it is able to handle it. Prompt the user "X extension wants to handle this QR code"
4. Add some hooks to communicate with extension app as necessary to retrieve codes or store things in the vault.

I agree knowing the technical feasability behind what needs to be done to retrieve codes from Microsoft would help inform how an extension API would be designed.

**Comment by vineet131** [comment]
@Giwayume @weissnix4711

For the benefit of anyone who stumbles on this thread.

I had this same problem today, and unfortunately there are no helpful articles on Google about how to get around this. But I poked around and found the way of how to use 2FA on Hotmail/Outlook/Microsoft without using Authenticator app. Comes with no surprises that Microsoft has hidden the option deep down.

1. Click on "My microsoft account"
![Screenshot 2024-10-23 234218](https://github.com/user-attachments/assets/cc4a8919-8800-4a4c-b44b-be46e6747deb)

1. From your settings, go to the Security dashboard
![Screenshot 2024-10-23 235021](https://github.com/user-attachments/assets/0009bdf0-d811-4db9-b934-48bc7fecb611)

3. From the "Ways to prove who you are", click on "Add a new way to sign in or verify"
![Screenshot 2024-10-23 233110](https://github.com/user-attachments/assets/19a985cc-6007-41be-850c-f0af5683034b)

4. Next screen, click on "Use an app"
![Screenshot 2024-10-23 233140](https://github.com/user-attachments/assets/75eb258a-c6c0-49c5-b846-b550ee8d534d)

5. Finally click on "Set up a different authenticator app"
![Screenshot 2024-10-23 233155](https://github.com/user-attachments/assets/933717f8-169c-4cfb-aadc-61187e8a1525)

6. Then you can just set up the TOTP normally with Aegis or whatever app you choose. I have confirmed that it works.

Hope this helps, cheers.

**Comment by Weissnix4711** [comment]
To add to that, I was unable to access my account settings before I enabled their proprietary 2FA app. So you may have to use the app once, but then you should be able to re-enable the traditional TOTP from security settings.

#559 #588

**Comment by rafalgrasman-nxp** [comment]
> [@Giwayume](https://github.com/Giwayume) [@Weissnix4711](https://github.com/Weissnix4711)
> 
> For the benefit of anyone who stumbles on this thread.
> 
> I had this same problem today, and unfortunately there are no helpful articles on Google about how to get around this. But I poked around and found the way of how to use 2FA on Hotmail/Outlook/Microsoft without using Authenticator app. Comes with no surprises that Microsoft has hidden the option deep down.
> 
> 1. Click on "My microsoft account"
>    ![Screenshot 2024-10-23 234218](https://github.com/user-attachments/assets/cc4a8919-8800-4a4c-b44b-be46e6747deb)
> 2. From your settings, go to the Security dashboard
>    ![Screenshot 2024-10-23 235021](https://github.com/user-attachments/assets/0009bdf0-d811-4db9-b934-48bc7fecb611)
> 3. From the "Ways to prove who you are", click on "Add a new way to sign in or verify"
>    ![Screenshot 2024-10-23 233110](https://github.com/user-attachments/assets/19a985cc-6007-41be-850c-f0af5683034b)
> 4. Next screen, click on "Use an app"
>    ![Screenshot 2024-10-23 233140](https://github.com/user-attachments/assets/75eb258a-c6c0-49c5-b846-b550ee8d534d)
> 5. Finally click on "Set up a different authenticator app"
>    ![Screenshot 2024-10-23 233155](https://github.com/user-attachments/assets/933717f8-169c-4cfb-aadc-61187e8a1525)
> 6. Then you can just set up the TOTP normally with Aegis or whatever app you choose. I have confirmed that it works.
> 
> Hope this helps, cheers.

No doesn't help, the admin of the M365 domain disabled *all* but MS MFA.
There are no options _at all_ to use a different authenticator app or to add a different MFA. Using the Proprietary MS MFA is mandatory..
