### ISSUE TITLE
Add a button to change the view mode right in the entry list

### ISSUE THREAD

**Issue by jirkacapek123** [beemdevelopment/Aegis#1500]

**Comment by michaelschattgen** [comment]
Why would you ever want to change the view mode without going into the settings? How do you think this feature would look like?

**Comment by jirkacapek123** [comment]
> Why would you ever want to change the view mode without going into the settings? How do you think this feature would look like?

Because going into settings is just another few steps that aren't needed . I would just like a button that lets you change view mode, a few other apps have it and it's an amazing quality improvement that would be pretty easy to add.

**Comment by alexbakker** [comment]
How often do you switch view modes? And if it's more often than once in the lifetime of an Aegis install: Why?

**Comment by jirkacapek123** [comment]
> How often do you switch view modes? And if it's more often than once in the lifetime of an Aegis install: Why?

Of course pretty often, I don't understand how you make it out to be completely useless feature, it has it's use for some users.

**Comment by alexbakker** [comment]
Help us out here. We're trying to understand the use case. Why are you switching view modes pretty often?

**Comment by jirkacapek123** [comment]
> Help us out here. We're trying to understand the use case. Why are you switching view modes pretty often?

For example when I change the font size via quick settings on Android 14 I would like a different layout without going to settings. And the same applies when I change the screen density via MacroDroid. I think that makes the use case more clear to everyone.

**Comment by michaelschattgen** [comment]
Closing this as we don't see the use case here.
