### ISSUE TITLE
Feature Request: Time correction for TOTP tokens

### ISSUE THREAD

**Issue by Matgoeth** [beemdevelopment/Aegis#1502]
Helo beemdevelopment team! I posted a review on google play store and someone of you was kind enough to reply to me, but reviews aren't really great to discuss, so I decided to post here.

It is probably a niche usecase, but I want to be transparent: I manually set my phone time 5 minutes early in order to be more organized. This however creates a big issue when using TOTP tokens, which are time-sensitive. Google Authenticator has option to make correction with what is considered to be a "standard time" which saves my bacon and allows my phone to be "ahead of schedule". I would love to switch to an alternative like Aegis, but there's no correction function like this.

I'd love to get correction function just like Google Authenticator has or even option for Aegis to specify the timezone that it should "correct time to". Manually setting this up (by saying e.g. correct time by 5 minutes and 2 seconds) would be more tedious but I would still be super-happy. One of your devs replied to me that it'd require an internet access privilege, which of course can be the case but it can still be an optional one (if user doesn't decide to do so they may deny it), it's all about giving user the choice.

Thank you for taking time and looking at my Feature Request! I recognize it's something that a few users would want, but it'd be spectacular if you could take a look at it!

**Comment by michaelschattgen** [comment]
Thanks for creating this PR and elaborating on the review, this is definitely a better way to discuss this.

This is an interesting use case I haven't thought about before. 

> One of your devs replied to me that it'd require an internet access privilege, which of course can be the case but it can still be an optional one (if user doesn't decide to do so they may deny it), it's all about giving user the choice.

Unfortunately this is not the case, as soon as we 'require' internet permission, it is granted. Android considers these permissions a 'normal permission' which means they are granted on install time, meaning the user doesn't have a choice.

The only way I see this working is by adding a 'manual sync' option which allows you to set the correct time(zone) but it will definitely be a really niche feature.

**Comment by alexbakker** [comment]
We've thought about this some more and concluded that this can't work reliably without a synchronized clock. Adding an option to manually offset the time by 5 minutes in Aegis is not going to help with that. The clock on your device will quickly start drifting if you disable synchronization. So much so that within just a week of having disabled synchronization the clock on my device already drifted away from reality by ~10 seconds.

And since Aegis is not going to request the internet permission to do synchronization itself, the clock on your device simply needs to be in sync.
