### ISSUE TITLE
App keeps crashing if entered big integer in time

### ISSUE THREAD

**Issue by MRVMV** [beemdevelopment/Aegis#152]
I had copied some bug number (I think 30000) and pasted it in seconds when adding a token and the apps crashed and keeps crashing as I'm trying to enter it...
I have a backup surely and I just restored my tokens...
Anyway I think you should make all inputs have rules...

**Comment by alexbakker** [comment]
Thanks for the report. I'm able to reproduce this. We'll look into it.

**Comment by ammarraisafti** [comment]
I also found a crash on the application, can you open my ticket.  How do you respond to this problem.

https://github.com/beemdevelopment/Aegis/issues/150

**Comment by alexbakker** [comment]
@ammarraisafti Please keep the conversations in issues on topic. There's no need to remind us about your issue. We'll get to it.

**Comment by ammarraisafti** [comment]
Fine, I will wait for him.  Thank you very much for your time.

**Comment by michaelschattgen** [comment]
Just letting you know that we've fixed this and that it's available in Google Play as an open beta. If you would like to test this version please visit our [Google Play Store beta page](https://play.google.com/apps/testing/com.beemdevelopment.aegis) and enroll as beta tester.

Please let us know if you have any questions regarding this new beta.
