### ISSUE TITLE
Android Widget Support 

### ISSUE THREAD

**Issue by the-mentor** [beemdevelopment/Aegis#1520]
I want to fully get rid of authy but the only reason I keep it around is because it supports an android widget (see attached screenshot)

I really hope Aegis will add it so I can get rid of Authy for good. 

~~![authy_homescreen_widget_android_506.jpg](https://github.com/user-attachments/assets/30b1710d-de1b-46e3-896f-c5200991fc37)

~~

Thanks in advance
-DM

**Comment by michaelschattgen** [comment]
Duplicate of #1193.
