### ISSUE TITLE
Export Text file (.TXT) wrong

### ISSUE THREAD

**Issue by pepa65** [beemdevelopment/Aegis#1521]
### Version

3.2

### Source

Google Play

### Vault encryption

Yes

### Device

Samsung Galaxy M12

### Android version

Android 13

### Steps to reproduce

Export to `Text file (.TXT)`

The resulting file with URLs on each line has the `name` field (`otpauth://totp/NAME?...`) wrong. Instead of the `name` as it is found in the JSON file, it has `issuer%3Aname`.

Incidentally, importing from `WinAuth` format is also broken. The name is always set to `WinAuth` instead of the NAME (the string between `otpauth://totp/` and `?`).

### What do you expect to happen?

Using the `name` field (as in the JSON) for the NAME (the string between `otpauth://totp/` and `?`).

Also, when importing from `WinAuth` format, use the NAME field for the name (and not "WinAuth").

### What happens instead?

As described above.

**Comment by alexbakker** [comment]
> The resulting file with URLs on each line has the name field (otpauth://totp/NAME?...) wrong. Instead of the name as it is found in the JSON file, it has issuer%3Aname.

Aegis behaves correctly here. Take a look at the spec to learn more: https://github.com/google/google-authenticator/wiki/Key-Uri-Format#label.

> Incidentally, importing from WinAuth format is also broken. The name is always set to WinAuth instead of the NAME (the string between otpauth://totp/ and ?).

We do this because WinAuth doesn't have the concept of issuer and name. It just has a name per entry. Since the default name for an entry in WinAuth is usually the name of the service (e.g. Google), we use the "name" part of the URI as the issuer and set "WinAuth" as the name.

**Comment by pepa65** [comment]
OK, I see you are following Google's app... The (official?) spec says: https://www.ietf.org/archive/id/draft-linuxgemini-otpauth-uri-01.html#name-label-entry-required

But I guess what you do for the label is not strictly wrong...

I do think you are breaking the spec by ignoring the official optauth `label` field on import and replacing it with `WinAuth`. So anybody importing entries through the preferred standard of interchange will have all its entries named `WinAuth`??

Is there another way to import through otpauth URIs that is different from the way you handle WinAuth?

**Comment by alexbakker** [comment]
> OK, I see you are following Google's app... The (official?) spec says: https://www.ietf.org/archive/id/draft-linuxgemini-otpauth-uri-01.html#name-label-entry-required

This is just some random draft submitted to the IETF.

> I do think you are breaking the spec by ignoring the official optauth label field on import and replacing it with WinAuth

The label field is stored as the issuer in case of a WinAuth import. I explained why we do this.

> Is there another way to import through otpauth URIs that is different from the way you handle WinAuth?

Yes, you can avoid the WinAuth-specific behavior by choosing the "Plain text" option during import.

**Comment by pepa65** [comment]
So plain text is an alternative way to import otpauth URIs? How are the fields handled??

**Comment by alexbakker** [comment]
Yes. It behaves exactly as you'd expect. The issuer is stored as the issuer, and the name/label is stored as the name.
