### ISSUE TITLE
(Feature request) some sort of total count of tokens

### ISSUE THREAD

**Issue by valtoree** [beemdevelopment/Aegis#1522]
Hi as per title,
Would love to see a total number count of how many tokens exist please.
Well done dev/s 
Keep up the great work
❤️

**Comment by michaelschattgen** [comment]
We show a count of total entries at the bottom of the entries list, is this not sufficient enough?

**Comment by valtoree** [comment]
Ah didn't see that. Thank you, was what I was after. If not too much trouble can you put it at the top with title bar? Thanks again for everything.

**Comment by michaelschattgen** [comment]
Of course! We don't see the need to put the total amount of entries at the top of the list as it will clutter the UI a bit more too. Is there a specific use case for this?

**Comment by valtoree** [comment]
Hi thanks for reply. The reason being, quality of life improvement. That is, to verify the total number of entries and compare with a backup phone with the same data. As time goes on, more and more entries will be populated and sometimes I forget to make sure the backup phone has being updated. In case I lose my main phone.
