### ISSUE TITLE
Vault documentation for Slots (type 1) missing fields

### ISSUE THREAD

**Issue by pepa65** [beemdevelopment/Aegis#1523]
### Version

2.3

### Source

Google Play

### Vault encryption

Yes

### Device

Samsung Galaxy M12

### Android version

Android 13

### Steps to reproduce

My Encrypted JSON Aegis Vault file has the fields `repaired: true` and `is_backup: false`, they are missing in https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md

### What do you expect to happen?

Add those fields to the documentation.

### What happens instead?

They are not there.

**Comment by alexbakker** [comment]
Thanks, merging this into #1279.
