### ISSUE TITLE
Min and Target SDK

### ISSUE THREAD

**Issue by Jeffrey2307** [beemdevelopment/Aegis#1525]
Hey,

i saw that the App has Target SDK on 34 and Minimum SDK on 21 and I wanted to ask if you could make Target SDK to 35 for Android 15 and Minimum SDK to 23/24/26/28/29/31? (Higher is always better)

A higher Minimum SDK version implies that your app supports fewer Android versions, minimizing compatibility issues. Because higher SDK means also Versions which are supported better. It makes the work easier. because Android 12 (SDK 31) is the last version that receives security patches. Further more, the less minSdk, the more internal compatibility layers, techniques etc. For example, lower SDK versions require v1/v2 signing, have somewhat different optimization levels, etc.

**Comment by alexbakker** [comment]
Bumping the target SDK version to 35 is currently in review: #1516. If maintaining Aegis for older Android versions becomes too burdensome, we'll consider bumping the minimum SDK version, but we currently don't really have a reason to do so.
