### ISSUE TITLE
Inconsistent Filename Pattern in Export Feature (aegis.json format)

### ISSUE THREAD

**Issue by larry868** [beemdevelopment/Aegis#1526]
### Version

v3.2

### Source

Google Play

### Vault encryption

Yes

### Device

samsung galaxy note10 lite

### Android version

Android 13

### ROM

no

### Steps to reproduce

Open the Aegis app and navigate to the export feature.
Choose the "OK" option to save the file on the smartphone.
Observe the filename pattern generated.
Repeat the export process, but this time select the "Share" option.
Note the filename pattern generated for the shared file.

### What do you expect to happen?

The filenames generated by both "OK" (save) and "Share" should follow the same pattern for consistency and predictability. I would expect the filename pattern "aegis-export-YYYYMMDD-HHMMSS.json" so including date and time.

### What happens instead?

The filename pattern generated by the "OK" option differs from that of the "Share" option.
With "ok" the filename pattern is "aegis-export-YYYYMMDD-HHMMSS.json" so including date and time.
With "share" the filename pattern is "aegis-export-88888888888888888888.json" so with a dummy number generated.

**Comment by alexbakker** [comment]
I don't really agree that this is a bug, but making this more consistent certainly can't hurt!

**Comment by larry868** [comment]
ok to reclassify this item, to a requested feature ?
