### ISSUE TITLE
[feature] put encryption, digits and seconds under an advanced group when entering manual token

### ISSUE THREAD

**Issue by MRVMV** [beemdevelopment/Aegis#153]
I think you should make digits default have a value of 6 and seconds a value of 30 as most providers uses these settings and also hide these options with an advanced button

**Comment by Wilker-a** [comment]
maybe just having default values filled in should be enough

**Comment by alexbakker** [comment]
This was implemented in f4bdf4645baaa798784ba8c42c05d716313b1259.
