### ISSUE TITLE
Request for support QR code from TeamViewer

### ISSUE THREAD

**Issue by seiferflo** [beemdevelopment/Aegis#1532]
**Steps :**
- Create a Teamviewer account (free) via [account.teamviewer.com](https://account.teamviewer.com)
- Login to the account then go the second authenticator section (via the profil on the top right, edit profil, authentication, two factors) or via [web.teamviewer.com](https://web.teamviewer.com/settings/profile/authentication)
- Open Aegis app on Android, then click plus and Scan QR Code
- Alternative : enter manually the secret code given by Teamviewer via Aegis

**Result :** The QR Code nor the secret code aren't recognized by Aegis. 

**Request :** Is it possible to support that QR code in the app please? Thank you for your consideration.

Current applications supporting that QR Code: 
[Duo Mobile](https://play.google.com/store/apps/details?id=com.duosecurity.duomobile)
[Authenticator Plus](https://play.google.com/store/apps/details?id=com.mufri.authenticatorplus)
[Google Authenticato](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2)
[Microsoft Authenticator](https://play.google.com/store/apps/details?id=com.azure.authenticator)
[WatchGuard AuthPoint](https://play.google.com/store/apps/details?id=com.watchguard.authpoint&hl=en)

**Comment by michaelschattgen** [comment]
Thanks for your report. I can't seem to reproduce it and the QR code seems to be working just fine for me. What do you mean with "The QR code isn't recognized by Aegis"? Does Aegis not scan the QR code at all for you or do you get an error message?

Either way; I noticed that Teamviewer shows their secret code with spaces, could you enter this secret manually into Aegis without the spaces? That also works fine for me.

**Comment by seiferflo** [comment]
Well that's interesting... When I point the camera in front of the QR Code, nothing happens. I tried different browsers even my laptop screen. Phone isn't rooted or anything just a regular S10+ with plenty or others Aegis codes.
However, I did manage to make it work by entering manually the secret code with spaces... 
Thanks and sorry for taking some of your time, I should have thought about it.

**Comment by michaelschattgen** [comment]
Don't worry about it! I'm glad it eventually worked for you.

Do you have any browser extensions (dark mode) by any chance that invert the colors of a website? Sometimes this can mess up the QR code that's being shown by the website.
