### ISSUE TITLE
Search with filter enabled

### ISSUE THREAD

**Issue by ptruman** [beemdevelopment/Aegis#1536]
I've just moved to Aegis from AndOTP (slow I know!) - and it's ticking all the boxes except for one thing that AndOTP used to do that was really handy for a clean UI....

I have my 2FA codes grouped by category, and I had one set to default, which AndOTP always loaded on startup - which Aegis does - however, if I searched in AndOTP - I could find any 2FA code, including those outside the filter/view I had selected.

If I want to search in Aegis, I have to disable the filter first.
Could search be expanded to show "everything" and not just the display filter? (or have a display v search filter)

**Comment by michaelschattgen** [comment]
Makes sense, I like this idea. What do you think @alexbakker

**Comment by alexbakker** [comment]
@michaelschattgen Sounds good to me.
