### ISSUE TITLE
REGRESSION: Invalid steam tokens are generated 

### ISSUE THREAD

**Issue by Holbormon** [beemdevelopment/Aegis#1537]
### Version

3.3-beta1

### Source

GitHub

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 8

### Android version

Android 15

### ROM

GrapheneOS

### Steps to reproduce

1. Have a steam secret registered on a version < 3.3-beta1 (using `steam` as the token `Type`)
2. Ensure the tokens generated prior to 3.3-beta1 are working against steam login
3. Update to 3.3-beta1
4. Generate a steam token

### What do you expect to happen?

A steam token valid for the 2FA process to be generated.

### What happens instead?

An invalid steam token is generated. The invalidity in question has been tested directly against the steam login, but can also be seen at a quick glance because valid steam tokens are supposed to contain letters as well, but the tokens generated with 3.3-beta1 are strictly numerical.

**Comment by alexbakker** [comment]
Thanks for the report. We're aware of the issue and a fix is pending review: #1535.
