### ISSUE TITLE
Some general improvements 

### ISSUE THREAD

**Issue by Gammachange** [beemdevelopment/Aegis#1539]
Hide group when search focus is enabled, and  "`No Group"` if not in use 

- Notice : "i'm no't english speaker su forgive me if that no clear" 
- thanks in advance

**Comment by michaelschattgen** [comment]
What exactly do you mean? Do you want the search filter to ignore the group filters at all? If so, that's already suggested in #1536 and will be implemented at some point.

**Comment by Gammachange** [comment]
@michaelschattgen that good idea  **"i'm no't sure if that what i'm  looking for**", but i wana to be focus on the entry, and not show me the groube at all in the ui while i'm searshing  
Thanks again

**Comment by Gammachange** [comment]
Closeshttps://github.com/beemdevelopment/Aegis/pull/1545#issue-2688592364
