### ISSUE TITLE
Intercept otpauth:// scheme (used by Google Authenticator and other TOTP apps)

### ISSUE THREAD

**Issue by MRVMV** [beemdevelopment/Aegis#154]
Some apps on mobile (like Facebook) doesn't allow you to copy token but just show you the qr code (for other devices) and give you a button to go the otpauth:// uri (for this mobile) which Aegis doesn't intercept...
So it would be nice if aegis can directly process these uris

**Comment by michaelschattgen** [comment]
Just letting you know that we've implemented this and that it's available in Google Play as an open beta. If you would like to test this version please visit our [Google Play Store beta page](https://play.google.com/apps/testing/com.beemdevelopment.aegis) and enroll as beta tester.

Please let us know if you have any questions regarding this new beta.
