### ISSUE TITLE
Double Tap copy doesn't work( opy to clipboard)

### ISSUE THREAD

**Issue by ibrahimjelliti** [beemdevelopment/Aegis#1543]
### Version

v3.3

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Mix Fold 3

### Android version

hyperOS 1.0.15.0.UMVCNXM

### Steps to reproduce

in Settings, Set desired xopy behavior to double tap, back to main view double Tap any account.
the app got minimized without OTP token copied

### What do you expect to happen?

OTP code being copied to clipboard 

### What happens instead?

code not being copied

**Comment by michaelschattgen** [comment]
We can't seem to reproduce this. Could you share some of the customization options you've been using? Show next code, tap to reveal, highlight etc etc
