### ISSUE TITLE
Codes not shown if tiles mode is combined with hidden account names

### ISSUE THREAD

**Issue by Gammachange** [beemdevelopment/Aegis#1544]
### Version

3.3

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

SAM-A15

### Android version

android 14

### Steps to reproduce

Update from goole play store and open the app
I try clear the app data and emport code again " didin't work"

https://github.com/user-attachments/assets/76196843-c33a-44ac-a5c4-2a41a250ec19

### What do you expect to happen?

Everything sould work as except

### What happens instead?

The app its not shwo the code at all.

**Comment by michaelschattgen** [comment]
I assume this was introduced today with #1542 which seemed like a very innocent code change. We will make a new release as soon as possible, but could you try a different view mode instead of tiles for now? Does that help?

**Comment by Gammachange** [comment]
@michaelschattgen  I see its now work in deffrent view,  thank you su much
![Screenshot_20241124_202203](https://github.com/user-attachments/assets/4109c1d0-eb6a-4ce7-a721-3bf3ca2bda05)

**Comment by alexbakker** [comment]
Thanks for the report. [v3.3.1](https://github.com/beemdevelopment/Aegis/releases/tag/v3.3.1) is out with a fix!

**Comment by Gammachange** [comment]
@michaelschattgen Thank you su much i have  upadate the app on play store now its work perfect
