### ISSUE TITLE
UI elements overlap with system UI with Android 15's edge-to-edge enforcement

### ISSUE THREAD

**Issue by cillyvms** [beemdevelopment/Aegis#1549]
### Version

v3.3.1

### Source

GitHub

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 8

### Android version

Android 15

### Steps to reproduce

1. Install Aegis on Android 15 or newer which enforces edge-to-edge
2. Add enough entries to vault so they don't all fit on screen (if not using your real vault)
3. Browse through different screens, potentially with 3-button navigation

### What do you expect to happen?

Aegis adapts to the system UI by using `WindowInsets`

### What happens instead?

Some UI elements are rendered behind system UI.

In the vault activity the "Showing n entries" text is partially behind the navigation hint.
| Portrait | Landscape |
| -------- | --------- |
| ![Screenshot_1](https://github.com/user-attachments/assets/7007489d-9485-47eb-8942-1868160358b6) | ![Screenshot_3](https://github.com/user-attachments/assets/fe88464b-ee4d-4f6a-9eda-6127d2db6c17) |

The same issue occurs in the settings activity (notice how the ripple animation is behind the navigation hint).
| Portrait | Landscape |
| -------- | --------- |
| ![Screenshot_2](https://github.com/user-attachments/assets/b23134c5-3536-4d1e-b057-0abc1f33f92b) | ![Screenshot_4](https://github.com/user-attachments/assets/52c80825-f4d6-41c3-ae68-0bf36facc816) |

The issue becomes worse if the user chose 3-button navigation instead of gesture navigation, as much more space is taken up by it.
| Vault | Settings |
| -------- | --------- |
| The "Showing n entries" text can be barely seen behind the navigation bar ![Screenshot_5](https://github.com/user-attachments/assets/299dfcd8-3471-42ee-8f43-46c14f463fe3) | ![Screenshot_6](https://github.com/user-attachments/assets/8ae77835-930a-4ca1-ab39-30f6fede72a9) |

In landscape mode another issue occurs where the navigation bar obscures the overflow menu in the appbar.
![Screenshot_7](https://github.com/user-attachments/assets/50c3ddb7-9f7e-461f-9e04-84a893e1eb8e)

This should hopefully be solved by consuming the `WindowInsets` provided by the system and adding margin/padding to the lists so they have enough extra space to scroll, so no UI element is stuck behind system UI. I'm not sure why the appbar doesn't adjust itself however.

I can open a PR for this adding the insets to the lists.

**Comment by michaelschattgen** [comment]
Thanks for the detailed report, I noticed this myself too with the latest version on my phone. Feel free to take a shot at this if you'd like!

**Comment by cillyvms** [comment]
Great! I'll look at adding the insets then.
