### ISSUE TITLE
Can't access Android vloud backup from a different device

### ISSUE THREAD

**Issue by Marco-Leal** [beemdevelopment/Aegis#1554]
### Version

3.3.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Phone 1: Xiaomi Mi 10T Pro/ Phone 2: HUAWEI P20 Lite

### Android version

Phone 1: 12 / Phone 2: 9

### Steps to reproduce

Phone1:
1 - Was already logged onto my Google account.
2 - Installed Aegis with password encryption and biometric unlock.
3 - Added a token.
4 - Activated Android cloud backups on Aegis.
5 - Forced a cloud backup manually on the Google Drive app
6 - Confirmed that the backup was available on the Backups tab of Google Drive

Phone2:
1 - Was already logged onto my Google account, same one as above.
2 - Installed Aegis with password encryption. Same exact password as on Phone1. Didn't activate biometric unlock because I don't use it on this phone.
3 - Activated Android cloud backups on Aegis.
4 - Activated cloud backups on the phone itself (weren't active until then). The "Back up now" option was greyed out after activating so this phone hasn't yet attempted a backup. It will only do it after being idle for 2 hours while charging.
5 - Confirmed that I could see the backup generated by Phone1 on Google Drive.

### What do you expect to happen?

Phone2 should get access to the encrypted vault generated by Phone1 since I'm using the same Google Account and also the same encryption password.

### What happens instead?

Aegis on Phone 2 not able to either detect or open the vault. No tokens imported.

**Comment by alexbakker** [comment]
Android will only restore backups when you set up a new Android device and log into your Google account. It is not a mechanism to sync across devices.
