### ISSUE TITLE
[feature] Keep in notifications feature

### ISSUE THREAD

**Issue by MRVMV** [beemdevelopment/Aegis#156]
I use 2FA for every single service that support it and I use incognito browsers on my device a lot so I have to keep changing apps, copying an pasting codes and things like this

I suggest adding a feature (first time in otp apps) named Keep in Notifications or Notify

It would be a simple one just a button in the menu for the item which shows a notification with the OTP so you can simply write it down when the service requests it
The notification should have two buttons, copy and done/clear

The most common usage for this is that time doesn't pass and code changes while you are changing apps and then the service gives you an error

On the other hand I don't have to wait for the next code everytime I see time is less than 10 seconds

**Comment by MRVMV** [comment]
And sorry for being too much active and adding a lot of issues and comments in the same time but I just loved this app and wants it to be better!

**Comment by p0358** [comment]
> On the other hand I don't have to wait for the next code everytime I see time is less than 10 seconds

Though most of services allow you to use previous one or even more codes, so you should still be fine using that code. It never happened not to work for me.
But overall an interesting idea.

**Comment by Wilker-a** [comment]
it would be nice to maybe have a widget like Authy currently has, too

**Comment by michaelschattgen** [comment]
Closing this issue as we unfortunately don't have plans to implement this.
