### ISSUE TITLE
Bulk import of Google Authenticator QR code export fails with success snackbar

### ISSUE THREAD

**Issue by JoshuaEN** [beemdevelopment/Aegis#1560]
### Version

3.3.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Samsumg Galaxy S23+

### Android version

14

### Steps to reproduce

1. Create 2 or more items in Google Authenticator version 7.0
2. Go to Menu -> Transfer codes -> Export codes
3. Select the two items and click next
4. Screenshot the export QR code (cropped to just the code)
   Example (test data, not real account info): ![Screenshot_20241202_091114_Authenticator](https://github.com/user-attachments/assets/528321de-2646-48c6-8dc7-b4cf1a518ec9)
6. In Aegis, use the scan image feature and select the screenshot

Note how Aegis says "Added 2 new entries to the vault" but nothing is actually added.

### What do you expect to happen?

The exported codes to be added, or an error to be displayed.

### What happens instead?

Aegis says "Added 2 new entries to the vault" but nothing is actually added.

### Log

[debug.log](https://github.com/user-attachments/files/17979240/debug.log) (nothing stood out to me in there, but figured it didn't hurt to include the log)

Additional notes:
- Single code exports from Google Authenticator are imported correctly (it appears to be going through the normal "scan and add" flow).
- Google Authenticator is able to import the QR code.
- Going through the "Scan QR code" flow in Aegis also says "Added 2 new entries to the vault" but nothing is actually added. Though in that case it also says "Scanned 1/1 QR codes" before showing the added snackbar.
- I saw #802 and #1185 , among others, but these seem to involve an com.google.zxing.NotFoundException error message being shown, so I figured this may be a different issue (potentially related to Google Authenticator's recent update to 7.0).

Thanks!

**Comment by alexbakker** [comment]
The fix for this has been released as part of [v3.3.2](https://github.com/beemdevelopment/Aegis/releases/tag/v3.3.2)!

**Comment by JoshuaEN** [comment]
Thank you for fixing this so quickly. I was able to successfully import all of my codes after the update.
