### ISSUE TITLE
[Feature Request] Copy / Edit on entry click

### ISSUE THREAD

**Issue by KomelT** [beemdevelopment/Aegis#1565]
Currently, clicking on an entry doesn't do anything. I would expect that clicking would lead to copying the code or editing the entry.

**Comment by KomelT** [comment]
I can try and create a pull request if this is interesting.

**Comment by michaelschattgen** [comment]
Have you tried Settings -> Behaviour -> Copy tokens to clipboard?

Also for editing, tap and hold -> edit icon in the top left.
