### ISSUE TITLE
Ability to manage groups

### ISSUE THREAD

**Issue by sconim** [beemdevelopment/Aegis#1570]
Add a section in settings to manage groups: add, delete

**Comment by michaelschattgen** [comment]
We already have a way to do this through "Settings -> Appearance -> Edit groups".

**Comment by sconim** [comment]
Thank you, Mike! Don't you think it's somewhat miss categorized? I didn't find it as I wasn't thinking it should be under Appearance. Would it, maybe, be a better fit under Behavior?

**Comment by michaelschattgen** [comment]
Of course, no worries! I agree that 'Appearance' isn't the best place but I'm also not entirely sure if 'Behaviour' is any better. Maybe its own category would be a better option.

What do you think @alexbakker?

**Comment by sconim** [comment]
You could also remove it from settings altogether, and add it to the main menu as filtering, next to sorting.

**Comment by ByteAfterlife** [comment]
> We already have a way to do this through "Settings -> Appearance -> Edit groups".

Thanks so much! I was wondering where it was.
