### ISSUE TITLE
To support protocol: ms-msa

### ISSUE THREAD

**Issue by DictoDictov** [beemdevelopment/Aegis#1573]
Cat not set 2-step verification with Aegis for my Live.com account. It says I need Microsoft Authenticator but I want to use Aegis.

The code is kinda look like:
_**ms-msa://code=M.C523_SN1.2.U.**_[something like UID]_**&uaid=**_[another UID]**_&expires=-351961904_**

**Comment by michaelschattgen** [comment]
Duplicate of #1493

**Comment by DictoDictov** [comment]
Here it is yours "the best" authenticator! Fack you, lazy ussholes.
