### ISSUE TITLE
FreeOTP v2.X: Aegis could not import 23 tokens

### ISSUE THREAD

**Issue by p-fruck** [beemdevelopment/Aegis#1579]
### Version

v3.3.2

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 8a

### Android version

Android 15

### ROM

GraheneOS

### Steps to reproduce

- Export token froms FreeOTP v2
- Import into Aegis

### What do you expect to happen?

Aegis already mentions there might be issues importing some token. However, I'd expect it to import some/most of the tokens. Also, I could not find any information why some token could not be imported and how I might fix the issue

### What happens instead?

Not a single token is imported

### Log

The following message is printed 23 times:
com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: javax.crypto.AEADBadTagException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT

I thought this was due to a wrong password, but using a wrong password the error only appears once

**Comment by alexbakker** [comment]
As the prompt you saw mentions, FreeOTP 2 has some corruption issues that can make "some **or even all**" entries unrecoverable in exports. I wrote a more extensive explanation about the corruption issue (and others) here in case you're interested: https://github.com/freeotp/freeotp-android/issues/283#issuecomment-2381379029. The authors of FreeOTP should be able to fix the issues with an update, but it looks like the app is mostly unmaintained so I wouldn't hold my breath.
