### ISSUE TITLE
Error when importing from Authy

### ISSUE THREAD

**Issue by coggy9** [beemdevelopment/Aegis#160]
I'm getting an error when importing tokens from Authy. It said it failed to import 12 tokens, and the log just has lots of 
```org.json.JSONException: No value for originalName``` errors. Some of the tokens that failed to import are standard OTP tokens, like Google and Facebook.

Using a OnePlus 3T on Android 9.

**Comment by alexbakker** [comment]
Thanks for the report. Apparently the ``originalName`` field is not set for any of your Authy tokens. I'm assuming you used the "Import from app" option and not "Import from file". Is that correct?

**Comment by coggy9** [comment]
Yes, that is correct.

**Comment by RX14** [comment]
new format seems to just have "name", not "originalName".
