### ISSUE TITLE
Misleading 'invalidated fingerprint' message

### ISSUE THREAD

**Issue by wvffle** [beemdevelopment/Aegis#162]
# The problem
I was a bit confused after reading that I have to go to the `Settings -> Fingerprint` and re-add a fingerprint. I basically did it in android settings.

# Possible solution
Change `Settings -> Fingerprint` to `Aegis -> Settings -> Fingerprint`

**Comment by alexbakker** [comment]
Hah, I guess you're right, the wording is indeed a bit confusing. Thanks for the patch. We'll take a look at it soon.
