### ISSUE TITLE
Cannot select downloaded image as icon

### ISSUE THREAD

**Issue by Iambecomeroot** [beemdevelopment/Aegis#166]
When I go to add an icon for an account, my only options are pictures I have taken with the camera. I want a picture I downloaded from the internet, not some random picture. I put the downloaded icons in the same folder and even tried converting them to jpg. I am on Lineage OS and I think the app is opening the "Galleries" app, which only shows pictures taken with the camera. Maybe it would be good to open a "File chooser" not an "Image chooser".

**Comment by michaelschattgen** [comment]
Thanks for your contribution. It sound like this is a problem with the file picker in LineageOS and I don't think implementing a generic file picker on our side is the way to fix this issue. Do you have this problem with other apps as well?

**Comment by Iambecomeroot** [comment]
Other apps (like "mail") open a different file picker where I can select any file I like. Aegis opens "galleries".

**Comment by michaelschattgen** [comment]
Mail opens the file picker since you can pick different file formats as attachments in your email, this is normal behaviour. Aegis only supports images, hence the image picker.

I'm curious of what picker LineageOS opens when other apps want to read an image (i.e. messaging apps).

**Comment by Iambecomeroot** [comment]
It seems to me that it opens the "Galleries" app. How can I test it?

**Comment by michaelschattgen** [comment]
I'm not sure if we're on the same page. We want to know if other apps (with image import feature) running on LineageOS do have the same behaviour. If so, it's not an issue with Aegis but with LineageOS.

You can check this by opening an image picker in other apps, do these apps show the same 'Galleries' picker?

**Comment by Iambecomeroot** [comment]
I may have been doing something wrong. I tried again today and everything worked. I was able to select any png file in `/storage/emulated/0/Pictures`. Putting a bunch of icons in a folder under there worked perfectly. Sorry for the inconvenience.

**Comment by michaelschattgen** [comment]
No problem! We're glad it eventually worked out for you.
