### ISSUE TITLE
Wrong OTP displayed for 7-digit tokens

### ISSUE THREAD

**Issue by Esselans** [beemdevelopment/Aegis#175]
When the code is 7 digits long, the app shows 2 groups of 4 duplicating the middle number. I've imported the database from andOTP. Will try adding a fresh verification to see if the bug is on the importing feature.

For example: **Twitch**
andOTP generates: **9 800 315**
Aegis generates the same number but show: **9800 0315**

So the "middle number" it can be the 4th digit or the 5th digit. That number will be always the same so when I type the code it has an extra number, but using the copy/paste it is ok (7 digits instead of 8).

Some 'real' examples:

![1](https://user-images.githubusercontent.com/12036503/62932290-3e54ce00-bd96-11e9-9825-1adae044140b.png)
![2](https://user-images.githubusercontent.com/12036503/62932291-3eed6480-bd96-11e9-9379-43404af3444b.png)
![3](https://user-images.githubusercontent.com/12036503/62932292-3eed6480-bd96-11e9-903e-3cf979054107.png)
![4](https://user-images.githubusercontent.com/12036503/62932294-3eed6480-bd96-11e9-879d-c35783e1b73b.png)

Keep in mind that tapping on the code and selecting Copy it has generated the correct code. This seems to be a visual issue.

**Comment by michaelschattgen** [comment]
This is bad. Thanks for your detailed explanation. We will fix this as soon as possible.
