### ISSUE TITLE
Show Only Individual Accounts?

### ISSUE THREAD

**Issue by 0pLuS0** [beemdevelopment/Aegis#178]
Hello,

I read online, and saw a commit, at least I believe it was a commit for March of this year, so that when you open Aegis you can have it only show the account you want to access, not all of them at once?

What happened to this, will this be implemented still?

Thanks

**Comment by alexbakker** [comment]
Is "Tap to reveal" setting what you're looking for?

**Comment by 0pLuS0** [comment]
I'm not using this at the moment now, so I'll have to get back to this if I ever need it again...

Thanks

**Comment by alexbakker** [comment]
Alright. I'll close this for now.

**Comment by Wilker-a** [comment]
thinking about it makes me picture an interface similar to Authy — one big panel shows an extended version of the selected account logo with a big button to copy.

something like this: ![[a poorly-made sketch of a mockup screen]](https://user-images.githubusercontent.com/10854855/64223164-2eb63a00-cea9-11e9-8882-aab39ff6bfb8.jpg)
