### ISSUE TITLE
Blizzard Authenticator Support

### ISSUE THREAD

**Issue by roshavagarga** [beemdevelopment/Aegis#179]
Is this possible?

**Comment by alexbakker** [comment]
Did you try extracting the secret and entering it into Aegis?

**Comment by roshavagarga** [comment]
How would one go about doing that? Secret extraction I mean? Also, blizz uses 8 digit codes, not sure if that's an issue.

**Comment by alexbakker** [comment]
It looks like Blizzard Authenticator uses its own deformed version of TOTP. Can you try setting up https://github.com/jleclanche/python-bna and importing the otpauth URL into Aegis?

**Comment by roshavagarga** [comment]
I don't actually run Linux on my PC, so I have no idea how to make that work on Windows...

**Comment by alexbakker** [comment]
Python works the same on Windows as it does on Linux for most things. Unless python-bna does something platform specific, it should just work.

I'll give python-bna a shot at some point, unless you beat me to it.

**Comment by michaelschattgen** [comment]
I will try to extract my own secret from the Blizzard launcher using python-bna myself later this day.

**Comment by roshavagarga** [comment]
Feel free to notify me when you've tested this out so that I can close this. Can't set up python-bna on my own atm.

**Comment by michaelschattgen** [comment]
Sorry! I've tested it and its works fine in Aegis. Although you need to install and set up python-bna yourself in order for this to work.

**Comment by roshavagarga** [comment]
Thanks for the info! I'm guessing there's no way that can be done via the app itself, since nobody has gone through the motions of turning python-bna into a module/library?

**Comment by michaelschattgen** [comment]
The reason why we don't support this method is because Python-BNA does some network requests to Blizzard endpoints. Aegis currently doesn't have any networking functionality and we would like to keep it this way from a security standpoint.

What is the reason why can't setup python-bna yourself? If you think it's too difficult to set-up, we can try to wrap python-bna into an executable which should make it easier for you to run.

**Comment by roshavagarga** [comment]
Mostly your latter point, yeah, I'm finding setting up Linux just for python-bna to be hard for most people. An executable would be better and I understand why you don't want to have Aegis change its permissions, didn't know python-bna required network access :)

**Comment by alexbakker** [comment]
Right, that would be too hard for most people. What I meant was that you don't actually need to install Linux. It should also work on Windows. @michaelschattgen tested this and it turns out that it does.

I've wrapped python-bna in an executable using PyInstaller: [bna.zip](https://github.com/beemdevelopment/Aegis/files/3574542/bna.zip). Want to give it a shot?

**Comment by Iolaum** [comment]
I just got it working. Steps were:

1. Get Blizzard Authenticator app and enable it
2. Get serial number and restore code from app
3. Install `python-bna`, in my case by cloning the [repo](https://github.com/jleclanche/python-bna) and installing locally with `pip3 install --user -e .`
4. Restore authenticator with `bna restore --set-default $SERIAL $CODE`
5. Get secret with `bna show-secret` and manually add it to AEGIS.
6. Verify that both authenticators give the same code and after that uninstalled Blizzard Authenticator.

Note: I tried step 5 by producing an image with `bna show-url | qrencode -o ~/Desktop/bnet.png` but trying to scan the image resulted in Aegis authenticator crashing. I am running it on LineageOS 16.0 with latest version from F-droid.

**Comment by alexbakker** [comment]
I'll close this. We can't add support for Blizzard's 2FA setup process, but as said, it is possible to import the token into Aegis manually afterwards.

**Comment by ldehaas1612** [comment]
For everyone wondering how to setup Blizzard Authenticator here all these years later, check out this link from the `python-bna` [repo](https://github.com/jleclanche/python-bna) issues: [python-bna issue 38](https://github.com/jleclanche/python-bna/issues/38#issuecomment-1746656464)
