### ISSUE TITLE
Allow storing the database on external storage

### ISSUE THREAD

**Issue by alexbakker** [beemdevelopment/Aegis#18]
Perhaps this should only be allowed for encrypted databases.

**Comment by Zer0-One** [comment]
Can you extend this to "allow the user to choose their own export location for an encrypted database"?

**Comment by rnc** [comment]
Related to #42 and this issue - would the storage model use the Storage Access Framework? Would this not make it easier to support cloud storage providers that register with it ?

**Comment by alexbakker** [comment]
As Android 10 now requires use of the Storage Access Framework for access to external storage, offering an option to store the vault exclusively on external storage is no longer desirable. With the existing export feature and the upcoming backup feature, it is possible to select a spot on external storage to export/backup the vault to, so I'll close this.
