### ISSUE TITLE
Aegis doesn't close using the back button

### ISSUE THREAD

**Issue by michaelschattgen** [beemdevelopment/Aegis#182]
Currently Aegis won't close using the back button when using encryption. The app will show the 'Unlock vault' screen which can't be exited. It would be nice to have Aegis close using the back button when the unlock screen is presented.

**Comment by troyengel** [comment]
Using 1.0-beta1 (Play store beta) this is still a problem. It's my opinion this is a must-have fix to reach 1.0 release, it's quite annoying to deal with on a regular basis. Thanks for your efforts and coding!
