### ISSUE TITLE
Import error from supported apps

### ISSUE THREAD

**Issue by MPeti1** [beemdevelopment/Aegis#185]
Today I installed Aegis Auth from the play store, and I found that I can't import the database of Google Authenticator, nor Steam's database. They both give different error messages, which you can find [here](http://imgur.com/a/TCZfi8y).

I use Android 6.0.1 (MIUI 8), and Magisk 19.3 for root. I gave root access to the app. I checked the database of Google Authenticator (with MiXplorer's database viewer) and the accounts table exists, and it contains all of the OTP entries. The database is located here: ```/data/data/com.google.android.apps.authenticator2/databases/databases```

**Comment by alexbakker** [comment]
Thanks for the report.

The Google Authenticator error looks same as #82. Are there any other files in the ``/data/data/com.google.android.apps.authenticator2/databases`` directory, besides the ``databases`` one?

I'm not sure about the Steam one. Perhaps Valve changed the format of that file. I'll take a look.

**Comment by MPeti1** [comment]
@alexbakker sorry for the delay, didn't notice there was a reply.
There's a file called 'databases-journal'. 

I think you could copy every file starting with 'databases' to make sure every file is copied that's needed to read the db properly.

Also, I've taken a look at the referenced issue (actually responded there first) and I use titanium backup too. What does it cause that can cause an issue?


PS: I started to be disappointed that I didn't get any response on the issue, and then I just accidentally checked my Gmail account which I don't usually check to see that my profile is registered with this email not the other lol. I need to do something with it. Sorry once again!

**Comment by alexbakker** [comment]
No worries! I'll prepare a patch to copy all of those files over to see if that fixes it.

**Comment by alexbakker** [comment]
@MPeti1 

Importing from Steam is still working for me. Are you sure you set up Steam Guard on that particular device and not some other one?

**Comment by MPeti1** [comment]
Sorry for the delay! I didn't notice the notification email.
Yes, Steam guard is set up on the same device on which I'm trying to import the credentials.

**Comment by MPeti1** [comment]
I've just cloned the repo and built a debug version to install it to my phone. It seems it is able to import both steam and google auth databases. (although for Authy it doesn't see anything, despite Twitch codes being generated in it)

Fortunately I know of a way to attach a debugger to a non-debuggable app, but then Android Studio claims at some places that bytecode does not match source code (like if minify would be enabled for release, but as I see it isn't), and this leads to method args invisible if execution stops at a breakpoint. If you know which could cause it, it could be of help

**Comment by MPeti1** [comment]
One such class is `com.beemdevelopment.aegis.importersPreferencesFragment`. When I put a breakpoint at `importDatabase`, it will stop execution [4 lines above](https://user-images.githubusercontent.com/9215491/66720515-e9691e80-edfd-11e9-8115-ef70340d8902.png)

stepping in makes it go to `com.beemdevelopment.aegis.importers.SteamImporter#read`, where it seems the lines are in sync with source, but I still can't see the method arguments.

The exception will be thrown here, but I can't read it because I can't see most local variables also. I'm thinking about that being caused by the new Android Studio? I've updated it a few days ago and before I didn't have problems with seeing arguments

**Comment by MPeti1** [comment]
I've checked now and if I build the app from 1.0.2's debug sources it has the problem the same way as the release from google play, so the problem is not caused by somehow the app being release type, and it's already fixed for the next release.

I didn't check for what's the case with Authy though, but it could be an other issue since it doesn't show an error, it just shows an empty account list
