### ISSUE TITLE
Center label if account name and issuer are not set

### ISSUE THREAD

**Issue by malnvenshorn** [beemdevelopment/Aegis#196]
Just a small visual improvement :wink:

**Comment by alexbakker** [comment]
Perhaps we should just not allow having an empty account name AND an empty issuer. It would be hard to tell the difference if you have multiple of those anyway.

**Comment by malnvenshorn** [comment]
> Perhaps we should just not allow having an empty account name AND an empty issuer.

All my entries are without an account name and an issuer, because I chose to use a short password for convenience. If I loose my phone and someone brute forces the password they have a lot of information otherwise.

**Comment by michaelschattgen** [comment]
Closing this issue as we don't have plans to implement this.
