### ISSUE TITLE
Is it Aegis Wordpress and Wordfence compatible?

### ISSUE THREAD

**Issue by danjde** [beemdevelopment/Aegis#199]
Hi Devs,
sorry for the silly question, but is it possible to use Aegis for 2FA Wordpress two-factor authentication system?
And eventually it can be used with Wordfence plugin (https://wordpress.org/support/topic/fake-user-for-all-content/#post-11898159) anyhow without using Google plugins/software?

Many thanks!

Davide

**Comment by michaelschattgen** [comment]
Hi Danjde, thanks for your contribution. 

Wordfence uses the default TOTP algorithm which is supported by many two factor authenticator apps, including Aegis. You should be fine.

I'm closing this issue now but feel free to add comments to this discussion if you have any questions.
