### ISSUE TITLE
Add ability to set default filters

### ISSUE THREAD

**Issue by anLizard** [beemdevelopment/Aegis#204]
I'd like to see a feature to set default filters that are applied when opening the Aegis.

I made a group A for frequently used entries, and a group B for my lesser used entries. I would like to only see group A when I open the app. Right now I have to set the filter for it every time.

That being said, I am loving Aegis, it's simple, pretty, and just works. Keep it up!

**Comment by alexbakker** [comment]
We're glad you like it! This is already planned as part of #27.
