### ISSUE TITLE
Authentication on GitHub fails

### ISSUE THREAD

**Issue by devurandom** [beemdevelopment/Aegis#207]
###### Info

* __Version__: 1.0
* __Source__: F-Droid
* __Vault encrypted__: Yes
* __Android version and ROM:__ Fairphone Open 19.08.1 / Android 7.1.2

###### Steps to reproduce

1. Edit two factor authentication on GitHub
2. Scan QR-Code using Aegis
3. Type code displayed by Aegis into [GItHub 2FA verification page](https://github.com/settings/two_factor_authentication/verify)

###### What do you expect to happen?

Code should be accepted as correct.

###### What happens instead?

`Two-factor code verification failed. Please try again.`

###### Notes

Before editing my 2FA settings, I tried to log in on another machine using Aegis, but the 2nd factor was rejected with `Two-factor authentication failed.`

**Comment by alexbakker** [comment]
Thanks for the report. GitHub 2FA works fine for me with Aegis. Are you sure the system time of your phone is in sync?

**Comment by devurandom** [comment]
Thanks. The time was off by 2 minutes.

**Comment by sitetester** [comment]
I changed to "Automatic date & time" on my Galaxy S8 & it worked

**Comment by Nerfe55** [comment]
I've been trying to authenticate for an hour, the page remains frozen
![error_github](https://user-images.githubusercontent.com/71529136/183237494-48be57ed-2ea6-4b2d-810a-08d9f6dfd79b.jpg)

**Comment by Nerfe55** [comment]
I've been trying to authenticate for an hour, the page remains frozen, try qr code and text message
![error_github](https://user-images.githubusercontent.com/71529136/183237792-d18dbaf0-5d07-47ca-8eee-ac3b94866dac.jpg)

**Comment by alexbakker** [comment]
@Nerfe55 Never share valid 2FA QR codes publicly.

Anyway, sounds like a problem at GitHub. Contact them for support if you're still having issues.

**Comment by Davidrjx** [comment]
same issue with 1password. automatic code filling into box in "Verify the code from the app" always is invalid from browser pulgin

**Comment by michaelschattgen** [comment]
@Davidrjx just like the others above: make sure the time on your devices is set to automatic. Any difference in time can mess up the validity of your tokens.
