### ISSUE TITLE
Persistent notification does not close the database

### ISSUE THREAD

**Issue by Wilker-a** [beemdevelopment/Aegis#217]
###### Info

* __Version__: 1.0
* __Source__: F-Droid
* __Vault encrypted:__ Yes
* __Android version:__ 5.1.1

###### Steps to reproduce

unlock to get the persistent notification, then close by going to Recents/opened apps list and close Aegis

###### What do you expect to happen?

clicking the notification or dismissing it should lock the database and close the notification

###### What happens instead?

nothing happens — database is still open, and because the notification is persistent, it cannot be dismissed. (an option to choose between persistent and "dismiss to lock" could be an option to fix this part.?)

**Comment by michaelschattgen** [comment]
Thanks for your bug report! It might be an wrong assumption that the vault isn't locked. 

It sounds like the notification is just bugged out and warns you about the unlocked state while in fact Aegis is killed and the database is locked already.

I guess Aegis just asks for your password / fingerprint again after closing it from the recents menu, right?

**Comment by Wilker-a** [comment]
at the time i came to report, the database was kept open upon clicking. i tried again now and it is apparently closing now ^^'

the notification still persists tho

**Comment by thebitstick** [comment]
This bug still persists in the latest update??

**Comment by alexbakker** [comment]
We haven't taken a closer look at this yet, so yes, this bug is still present.

**Comment by Wilker-a** [comment]
thank you both \^w\^
