### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by DuMuT6p** [beemdevelopment/Aegis#222]
Hello,
Please consider having a changelog file or use "Releases" to describe whats new in each one. This would help people if they want to help in testing, code or adapt specific functionality.

**Comment by alexbakker** [comment]
Thanks for the suggestion. We've recently started including the changelog in the app (accessible from the About screen), but we'll make sure to add it to the releases on GitHub as well.

**Comment by alexbakker** [comment]
We now also include release notes on the GitHub release page.
