### ISSUE TITLE
Google Play Store - Unable to install on Pixelbook or Dell Chromebook 11

### ISSUE THREAD

**Issue by ScottRFrost** [beemdevelopment/Aegis#226]
Please update Google Play Store options to allow installation on Chromebooks.  I don't see any reason why it wouldn't work.

**Comment by alexbakker** [comment]
Thanks for the report. It appears that the permissions we require also imply requirement of certain hardware features that are unsupported on Chromebooks: https://developer.android.com/topic/arc/manifest#incompat-entries.

We should explicitly define that those hardware features are not required with ``<uses-feature android:name="x" required="false"/>``.

**Comment by ScottRFrost** [comment]
Thanks for considering my feature request!  While I'm working on my ChromeBook, it would be much more convenient to pop open an Android app than to get my phone out of my pocket or backpack whenever I get a 2fa challenge.

Based on how the app works (and the availability of other similar 2FA apps such as 2FAS / Authy / FreeOTP+ / etc on the Play Store for my Chromebook), I'm hopeful that this would just be a manifest / Google Play config file change and not a heavy dev lift.
