### ISSUE TITLE
Remember new entry details after app is locked/unlocked

### ISSUE THREAD

**Issue by vertigo220** [beemdevelopment/Aegis#229]
If you partially fill out the details for a new entry then the app locks, whether due to the screen timing out or switching to another app (which isn't always optional, e.g. if you get a call), when you go back to Aegis and unlock it, it puts you back on the main screen, and everything you just entered is lost. This should be retained as long as the app is in memory.

**Comment by michaelschattgen** [comment]
Closing this issue as we don't have plans to implement this. We don't think this happens often enough to implement a specific case for.
