### ISSUE TITLE
Fingerprint Reader on One Plus closes app

### ISSUE THREAD

**Issue by pomtom44** [beemdevelopment/Aegis#237]
Similar to ticket #81 

On my one plus 5, the fingerprint reader is also the home button.
So when setting up the app, when I try to register my fingerprint it closes the app down.

Work around is to register with just a password, then enable the fingerprint in settings.

Note: It appears that the settings fingerprint reader is the system reader where the setup one is the app reader? Any way to change the setup one to be the same as the settings one?

**Comment by alexbakker** [comment]
Fixed by #240.
