### ISSUE TITLE
codes generated on oneplus 7t pro are always invalid

### ISSUE THREAD

**Issue by Hr46ph** [beemdevelopment/Aegis#241]
###### Info

* __Version__:  1.0.2
* __Source__: (Google Play/GitHub/F-Droid/?) F-Droid
* __Vault encrypted:__ Yes (with fingerprint unlock)
* __Device:__ Oneplus 7T Pro
* __Android version and ROM:__ 10 OxygenOS 10.0.HD01BA

###### Steps to reproduce

Scan QR code, accept default. The code generated is not accepted by applications such as Keycloak, Bitwarden, Firefox Sync.

###### What do you expect to happen?

Working code to enable 2FA on those accounts.

###### What happens instead?

The application tells me the code is invalid.

###### Log

```
If applicable, paste the debug log here.
```

I tried several things:
Scan QR code / accept defaults TOTP, 6 digid, 30 seconds.
Type over the code manually.
Setting other values, HOTP, 60 seconds. Didn't think that would actually work though :).

On my other (rooted) phone I installed Aegis and imported all my accounts from Authy. I exported the database and copied it over to the 7T Pro. Imported it. None of the accounts work.

Restoring Authy backups on the 7T Pro results in unable accounts too, so it may be something with the phone. FreeOTP works though, but FreeOTP+ doesn't.

I checked time is in sync on the phone.

**Comment by alexbakker** [comment]
This is usually a time synchronization issue, but I'm surprised FreeOTP works for you. Is the locale of your phone configured to be an RTL (right-to-left) language, by any chance?

**Comment by Hr46ph** [comment]
I agree, I am aware of time issues with OTP codes but the region and time is correct (and synced with a time source). Im dutch so no RTL.

**Comment by Hr46ph** [comment]
Apologies its false alarm. After rebooting the phone all codes now work.

**Comment by alexbakker** [comment]
Alright, no worries. You had me very confused there for a bit, haha.
