### ISSUE TITLE
Navigation bar isn't black on OxygenOS

### ISSUE THREAD

**Issue by ghost** [beemdevelopment/Aegis#244]
I wasn't sure whether to make this a bug report of a feature request however it doesn't really seem like a feature to me so I decided on bug report.

On OxygenOS (the ROM OnePlus devices use) the navigation bar doesn't turn black when the app is switched to the OLED theme. As pointed out in [this](https://github.com/inorichi/tachiyomi/commit/6ecd7fced8ac03afaf287745de66aeed08f10f09) commit the navigation bar needs to be set to transparent. This will make it completely black on all devices.

**Comment by acolombo25** [comment]
Same on Samsung One UI 2

**Comment by alexbakker** [comment]
Fixed by #301
