### ISSUE TITLE
Save keys when in TWRP

### ISSUE THREAD

**Issue by sander76** [beemdevelopment/Aegis#245]
Sorry for putting this up as a bug, but I am wondering whether I can recover my keys when in TWRP.

Somehow my phone refuses to bootup android. TWRP access is still there and I'd like to factory reset, but hope to be able to save the Aegis keys..

Thanks !

Sander.

**Comment by alexbakker** [comment]
You should be able to grab the vault file from ``/data/data/com.beemdevelopment.aegis/files``.

**Comment by sander76** [comment]
Thanks !
