### ISSUE TITLE
new version/platform port request

### ISSUE THREAD

**Issue by Data-PhiIe** [beemdevelopment/Aegis#246]
I was hoping I could convince you to port a version to the portable apps platform, that way I could use my 2 factor off of my USB device. This would be great, I had a chunk of time where my phone was bricked (It was on its last leg and I was waiting for my Librem 5 to ship) and did not have a device to run the application, so I couldn't use my 2FA. I'm aware of android emulation, but this concept is more convenient, as it can go anywhere a PC is available and they are not being stored on a networked device.
https://portableapps.com/

**Comment by alexbakker** [comment]
Thanks for the suggestion. PortableApps is a platform for Windows applications. Aegis only runs on Android and we don't have plans to port it to other platforms.
