### ISSUE TITLE
Transparency in image/icon displays as black.

### ISSUE THREAD

**Issue by tERyceNzAchE** [beemdevelopment/Aegis#249]
###### Info

* __Version__: 1.0.2
* __Source__: Google Play
* __Vault encrypted:__ Yes (with fingerprint unlock)/Yes/No
* __Device:__
* __Android version and ROM:__

###### Steps to reproduce

Selecting a custom image/icon that is a PNG file with transparent background results in the background displaying in black,

###### What do you expect to happen?

Background should remain transparent, or be converted to white.

###### What happens instead?

Image background is black.

**Comment by DaVoodoo** [comment]
This one is a must. Please.

**Comment by alexbakker** [comment]
PNG icon support is planned in #509.

**Comment by alexbakker** [comment]
I believe this has been addressed in ae0b00573f0b2a0dbcad1c19ed8d0f19bdb9271c.
