### ISSUE TITLE
F-Droid takes over old android tablet (Kobo reader)

### ISSUE THREAD

**Issue by pjkersten** [beemdevelopment/Aegis#256]
###### Info

* __Version__: Latest, I presume. Read on.
* __Source__: F-Droid
* __Vault encrypted:__ No
* __Device:__ Kobo reader
* __Android version and ROM:__ No idea, probably 4.1

###### Steps to reproduce

Open F-Droid, see that F-Droid needs update, start update

###### What do you expect to happen?

An updated F-Droid

###### What happens instead?

A black screen that, no matter what you do, keeps blocking the tablets interface. Even 'home' actions of 'settings' through a pull down are overwritten within milliseconds after starting. Reboots do not work, F-Droid apparently starts right after boot. The device is completely unusable in this state.

###### Log
Unable to take / read log.

**Comment by alexbakker** [comment]
This sounds like a bug in F-Droid, not in Aegis.
