### ISSUE TITLE
Crash with secret "="

### ISSUE THREAD

**Issue by mikini** [beemdevelopment/Aegis#259]
###### Info

* __Version__: 1.0.3
* __Source__: F-Droid
* __Vault encrypted:__ Yes and no (see below)
* __Device:__ Samsung Galaxy S8 (sm-g950f)
* __Android version and ROM:__ Android 7.0, stock ROM NRD90M.G950FXXU1AQK7

###### Steps to reproduce

* install and launch application
* step through wizard either setting up vault encryption or not, tried both with same result
* press plus and choose to add profile manually
* leave evertything default (profile name & issuer can be added seems to not matter)
* input secret "="
* press "Save"

###### What do you expect to happen?

Profile will be saved with empty secret or an error shown to inform about invalid secret.

###### What happens instead?

Application crashes after "save" and keeps crashing on every launch thereafter (if enabled after successful vault unlocking).

###### Log

Can be provided if needed.

**Comment by michaelschattgen** [comment]
That's bad. Nice find, thanks for reporting!
