### ISSUE TITLE
Camera only works after switch to front and back

### ISSUE THREAD

**Issue by ajaeger** [beemdevelopment/Aegis#263]
#163 #### Info

* __Version__: 1.0.3
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Sony XZ2
* __Android version and ROM:__ Pie 9

If I add a new service via QR-Code, I get a black screen with a red line.

###### Steps to reproduce

* Add new service
* Select "QR Code"
* See black screen

workaround:
* Click on camera (switch to front)
* Click again on camera (switch to back)
* It works

###### What do you expect to happen?

To see the QR directly - without using the workaround

**Comment by alexbakker** [comment]
Hopefully fixed by #461.
