### ISSUE TITLE
Improve entry group management

### ISSUE THREAD

**Issue by alexbakker** [beemdevelopment/Aegis#27]
Support for entry groups is fairly basic currently.

- [x] Create a separate DatabaseEntryGroup object for groups
  - [x] Fields: UUID, Name
- [x] DatabaseEntry
  - [x] Refer to groups by their UUID instead of their Name
  - [x] Allow assigning an entry to multiple groups
- [x] EditEntryActivity
  - [x] Allow assigning an entry to multiple groups
- [x] GroupManagerActivity
  - [x] Require the user to click a "Save" button before actually saving any changes
  - [x] Warn about unsaved changes by showing a "Discard changes?" dialog
  - [x] Add the ability to rename groups
- [x] MainActivity
  - [x] Support selecting multiple groups to filter on
  - [x] Persist the selected group filter

**Comment by rmunozrodriguez** [comment]
Persist the selected group filter on exit would be great.

**Comment by claytondaley** [comment]
I'd really like a top-level groups UI element (i.e. two clicks to pick a group vs 3) to complement the "persist group" suggestion above.  I went back to "Authenticator Plus" to see how they do it (atrocious security but I needed groups badly) and I also feel like their menu icon is less fiddly which seems to be due to (1) ~2x the real estate and (2) on the left.  I find the smaller icon jammed up against the right edge (i.e. the lip of my case) a lot harder to use.

**Comment by OmlineEditor** [comment]
> * Allow assigning an entry to multiple groups

in the drop-down list add a box for selection.

![124984265-a9ba7f80-e041-11eb-8631-5ff2d364fb97](https://user-images.githubusercontent.com/13348933/125089259-ebe1d080-e0d6-11eb-82cc-73519fdba36b.jpg)

**Comment by InfiniteCoder06** [comment]
@alexbakker I would be happy to help into this issue 


> Create a separate DatabaseEntryGroup object for groups
> * Fields: UUID, Name

It looks like this has been implemented right?

**Comment by InfiniteCoder06** [comment]
Currently working on Renaming of groups

**Comment by alexbakker** [comment]
> It looks like this has been implemented right?

Indeed, I've updated the task list.

**Comment by InfiniteCoder06** [comment]
@alexbakker Whenever free please do review my PR's

**Comment by alexbakker** [comment]
Now that #1349 is merged, the checklist is complete. Thanks to everyone who contributed to make this happen!
