### ISSUE TITLE
Support for Android Biometrics API

### ISSUE THREAD

**Issue by squabbi** [beemdevelopment/Aegis#281]
I noticed that there was a fingerprint option in the settings. Is it possible to implement Android's Biometrics API to allow for fingerprint and face unlock?

**Comment by michaelschattgen** [comment]
Hi squabbi, thanks for your report. We've implemented the Biometrics API in our latest release which is available on the Google Play Store and F-Droid. Please make sure that you've updated the app.

I'm closing this issue for now but feel free to continue the discussion.

**Comment by guihkx** [comment]
>We've implemented the Biometrics API in our latest release
Wait, wasn't fingerprint unlocking available before, on version 1.0.3? I'm pretty sure I was unlocking Aegis using my fingerprint.

However, after upgrading from 1.0.3 to 1.1 (F-Droid build), the fingerprint unlocking option got disabled when I first started Aegis, and upon trying to enable that option again, I get this error:

```
An error occurred while trying to enable biometric unlock: 
com.beemdevelopment.aegis.vault.slots.SlotException: javax.crypto.IllegalBlockSizeException
```

![Screenshot_20200106-104039](https://user-images.githubusercontent.com/626206/71821724-a2dc3680-3071-11ea-987f-54c96fde2c11.png)

**Comment by alexbakker** [comment]
> Wait, wasn't fingerprint unlocking available before, in version 1.0.3? I'm pretty sure I was unlocking Aegis using my fingerprint.

That's correct. Switching to the Biometrics API just means we now also have face unlock on Pixel 4, in addition to fingerprint unlock on other devices.

> fingerprint unlocking got disabled automatically

Did it show the "A change in your device's security settings has been detected" message? If so, are you sure you didn't change the security settings of your device between the upgrade from 1.0.3 to 1.1? It sounds like you haven't used Aegis in a while.

> and upon trying to enable it again, I get this error

This is odd, we'll have to investigate this further. Are you in a position to obtain a log with ADB?

**Comment by guihkx** [comment]
>Did it show the "A change in your device's security settings has been detected" message?

Yes, it did.

>If so, are you sure you didn't change the security settings of your device between the upgrade from 1.0.3 to 1.1?

Ahhh, I guess that's it. I probably did delete the previous fingerprint I was unlocking Aegis with.

>Are you in a position to obtain a log with ADB?

There you go: https://gist.githubusercontent.com/guihkx/37d22724567b32955d367b49c4bb6d3b/raw/5a4144e174af255de319e23a77c486444285a3c9/adb.log

**Comment by alexbakker** [comment]
Thanks for the log. Your case is pretty similar to this report: https://github.com/beemdevelopment/Aegis/issues/51#issuecomment-480207382, but I'm a bit surprised fingerprint used to work for you at all. Which device and Android version do you have? Are you running a custom ROM? You might want to try reinstalling Aegis (but backup your vault first) and see if that helps.

**Comment by guihkx** [comment]
>Which device and Android version do you have?

Moto E6 Plus, Android 9

>Are you running a custom ROM?

No, I'm running stock.

>You might want to try reinstalling Aegis (but backup your vault first) and see if that helps.

I might have to do that. That's interesting because I'm having the very same problem with KeePassDX:

![Screenshot_20200106-113503](https://user-images.githubusercontent.com/626206/71825185-0e2a0680-307a-11ea-919f-8da3c51f24b5.png)

They have this option to delete the fingerprint encryption keys:

![Screenshot_20200106-113558](https://user-images.githubusercontent.com/626206/71825247-36b20080-307a-11ea-8e24-9fc1dfe13cad.png)

But even after deleting those, it still can't use fingerprint unlocking, and it's the same error I'm getting with Aegis:

```
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper: Unable to encrypt data
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper: javax.crypto.IllegalBlockSizeException
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at javax.crypto.Cipher.doFinal(Cipher.java:2055)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper.encryptData(BiometricUnlockDatabaseHelper.kt:190)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at com.kunzisoft.keepass.biometric.AdvancedUnlockedManager$biometricAuthenticationCallback$1$onAuthenticationSucceeded$1.run(AdvancedUnlockedManager.kt:133)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at android.os.Handler.handleCallback(Handler.java:873)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at android.os.Handler.dispatchMessage(Handler.java:99)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at android.os.Looper.loop(Looper.java:235)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at android.app.ActivityThread.main(ActivityThread.java:6760)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at java.lang.reflect.Method.invoke(Native Method)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper: Caused by: android.security.KeyStoreException: Key user not authenticated
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at android.security.KeyStore.getKeyStoreException(KeyStore.java:839)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:132)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:217)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
01-06 11:38:39.263 16147 16147 E com.kunzisoft.keepass.biometric.BiometricUnlockDatabaseHelper:         ... 10 more
```

I will have to report this to them later, by the way. The only solution I have found so far is to delete the entire app data. 😞

**Comment by guihkx** [comment]
Maybe it's related to this?

https://issuetracker.google.com/issues/65578763

**Comment by alexbakker** [comment]
That issue sounds unrelated, but is certainly also something we've run across before, especially in emulators.

The fact that you encounter the same bug with KeePass tells us there's probably a bug somewhere in the Keymaster implementation on your phone. You may want to consider reporting this to the vendor. As your phone was released in 2019, there's a chance they'll try to fix it.

**Comment by squabbi** [comment]
Whoops, F-droid couldn't update the repo so i never got the 1.1 update. 😅

**Comment by PinkDev1** [comment]
Why is this issue closed? This is still a problem and a solution has not yet been implemented :/

**Comment by rg-demo** [comment]
Since latest Google Pixel 9 update, I am experiencing this issue on my Aegis (work profile), cannot use fingerprint anymore.
Aegis (same device - but personal profile Private Folder) works fine with fingerprint.

I uninstalled Aegis from work profile; however when I go to Play Store to install it again it is as if it does not download anything and uses cached files as it appears available/installed instantly.
