### ISSUE TITLE
Option to change icon colors

### ISSUE THREAD

**Issue by naoliv** [beemdevelopment/Aegis#282]
Are the default icon colors random?

![](https://user-images.githubusercontent.com/982338/71830739-26a01e00-3086-11ea-974c-edac23de9d79.png)

Could we have an option to edit these colors, if possible, please?

**Comment by alexbakker** [comment]
Based on the issuer (or account name if empty), the icon colors are picked from a list of predefined colors. 

https://github.com/beemdevelopment/Aegis/blob/44f3b7860dff791f9d6e639ade6bd894641527a4/app/src/main/java/com/beemdevelopment/aegis/helpers/TextDrawableHelper.java#L12-L32

These colors were picked to fit well with the style of the rest of the app. I don't think it's worth the trouble to allow them to be customized, to be honest.

**Comment by naoliv** [comment]
The colors may fit the app style, but don't you agree that a purple icon doesn't recall Google at all, for example? (nor associate github with an indigo color, etc)

**Comment by alexbakker** [comment]
I agree, but that's what the custom icon feature is for. You can select a custom icon for each entry by tapping the icon in the "Edit entry" screen. We're still working on making that experience better by providing an icon pack for popular services.

**Comment by alexbakker** [comment]
We currently don't have plans to implement this, so we'll close this.
