### ISSUE TITLE
Webapp or windows application or java app...

### ISSUE THREAD

**Issue by mcenal** [beemdevelopment/Aegis#289]
I was wondering if it would be possible to have it run on a PC computer somehow. When I travel I would like to keep 2FA turned on, but because of security reasons across US/Canada/Other borders, I do not necessarily trust those services to try and access my accounts in spite of the laws saying one or another thing. So I want to keep my 2FA phone at home and take a travel one or none at all. I was wondering, if I can have the 2FA run on a non-phone device like a website or a javabox or something else that I could take my personal backup and then run it from there. It would provide also near feature parity with Authy in that regards as it can run in a Chrome App or install on windows or macosx. (Yes I'd be running my own backend backups but that would really help. Even if it didn't allow for editing the data but at least reading and running the 2FA codes.)

**Comment by alexbakker** [comment]
We don't currently have plans to create an official port of Aegis for other platforms. However, as we've said elsewhere, others are free to implement support for importing from Aegis in their own apps. Aegis' vault file format is documented [here](https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md).
