### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by Rakleed** [beemdevelopment/Aegis#290]
It would be nice if you made an iOS app.

**Comment by alexbakker** [comment]
We don't have plans to port Aegis to other platforms.

**Comment by bigjdunham** [comment]
I will +1 this request. Even though you don't have "plans" to port Aegis. Aegis is amazing product and I'd love to see it on other mobile platforms other than Android. (iOS, Linux mobile, etc..)

**Comment by splch** [comment]
It'd be great if you looked into using react native or flutter to cross compile. Then there wouldn't be worries about maintaining multiple large code bases as an smaller group.

**Comment by AzagraMac** [comment]
No plans to bring Aegis to iOS? 

Well, I see it as a very big mistake, moreover, I would consider taking it to desktop platform, for example Ubuntu, Windows.... 


Why limit yourself only to Android users? 
I close the case #796 but I see that the initial case #290 also do not give solutions.

**Comment by alexbakker** [comment]
@AzagraMac We've spent a ton of free time on Aegis and we don't plan on spending even more of it making an iOS version. How could that possibly be a "mistake"? It's a decision.

**Comment by splch** [comment]
@alexbakker If you develop using a cross-compiled framework you only need one codebase. Then you can quickly expand users after some development time

**Comment by BirdInFire** [comment]
@alexbakker I thinks it's a good idea to go on apple, because we can export our otp from our rooted android to guard one app even for steam who is not updated since 1y on iOS.

**Comment by Neustradamus** [comment]
@alexbakker: It is possible to reopen this unsolved ticket?

**Comment by ptman** [comment]
Are you able to promise stability for the backup/export formats in case someone writes a compatible iOS app? How about adding some sort of sync with another app?

**Comment by alexbakker** [comment]
All we can promise, is that as long as the version number in the vault files stay the same, you should still be able to read the vault file regardless of which Aegis version produced it.

If one of the version numbers gets bumped, that means a change to the format has been made that makes it incompatible with a parsers written to be compatible with the previous version.

So far, we haven't had to bump the version number yet.

**Comment by AlecKinnear** [comment]
You do realise of course that iOS users are used to paying for apps and would happily pay you for Aegis, allowing you to stop "donating your time" and be paid for what is a great service to people who would like to use 2FA but won't allow Google onto their devices.

**Comment by mpgharris** [comment]
I would pay 5 pounds for aegis on macbook/ios. Just saying :)

**Comment by alexlambson** [comment]
I'd pay $15 to get off of authy
