### ISSUE TITLE
Dark theme too bright

### ISSUE THREAD

**Issue by Victor-Bo** [beemdevelopment/Aegis#294]
Hey! I really don't wanna judge your project or your tastes. But I don't like the dark theme at all. The cards backgrounds are too bright. In the post below you can see 3 images: what it is like right now and 2 suggestions
https://imgur.com/a/u3HnO4l

**Comment by michaelschattgen** [comment]
Good suggestion! Is this something you can work on?

**Comment by Victor-Bonnelle** [comment]
On theory I can as I know how go change coloris etc but it will be ugly I'm not designer at all

**Comment by michaelschattgen** [comment]
I will change it to the color you used in your first screenshot, alright?

**Comment by Victor-Bonnelle** [comment]
Well I think you should change the separator too it's too bright when using a darker color, but yes, it's alright ^^.

**Comment by ElTopo** [comment]
I personally found "red on black" text with "Dark Theme" is very hard to read. It would be nice for us to have more color choices.

**Comment by SagePtr** [comment]
I suggest adding ability to change the secondary color (which is pink at this moment).
[Google material design](https://www.materialpalette.com/colors) has a decent set of colors, which has 19 base colors (that have different brightness variations) that could be added for radiobutton group or combobox in options.
