### ISSUE TITLE
Codes are not refreshing because of entry with custom period

### ISSUE THREAD

**Issue by marvinlehmann** [beemdevelopment/Aegis#295]
###### Info

* __Version__: 1.1.2
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock) | No
* __Device:__ Honor 8 | Amazon Fire HD 10 (2017)
* __Android version and ROM:__ 8.0.0 (EMUI 8.0.0) | 5.1.1 (LineageOS 12.1)

###### Steps to reproduce

1. Add an entry with a non default period (!=30s).
2. Add an entry with any period.
3. Wait.

###### What do you expect to happen?

Codes will be refreshed.

###### What happens instead?

Codes won't be refreshed. If you select and deselect them, the codes are getting refreshed.

BTW: Furthermore the main progress bar seems to be buggy when you add your first entry and change its period later: progresses to wrong period; stops looping; ..

**Comment by alexbakker** [comment]
Thanks for the report. I can reproduce this. This definitely used to work, so I'll do some bisecting to see which change broke this.

**Comment by alexbakker** [comment]
This issue appears to have been introduced by me in a6a5af781e6ca51c810f458babadfa73d9328538.

**Comment by alexbakker** [comment]
This line was the culprit for the main issue: https://github.com/beemdevelopment/Aegis/pull/296/files#diff-3de2cacdd5a686cdd7110a2f1cbebca1L61-R61. The other buggyness you experienced should also be fixed by #296.

**Comment by marvinlehmann** [comment]
Wonderful! Happy to hear that. =)

Love this app!

**Comment by alexbakker** [comment]
The fix for this has been released as part of v.1.1.3.
