### ISSUE TITLE
flexible export file name (basename + date/time)

### ISSUE THREAD

**Issue by ElTopo** [beemdevelopment/Aegis#297]
Hello, 

Currently, Aegis (as of version 1.1.2) saves export file as "aegis_export" by default:
![photo_2020-01-20_14-39-38](https://user-images.githubusercontent.com/217195/72761983-ba97dc80-3b92-11ea-82b2-69d1fff7b5dd.jpg)

I'd like Aegis uses more obscure names like the more generic "mybackup" without associating the file with Aegis app itself, or at least, Aegis should remember my last edited name, so if I changed "aegis_export" to "mybackup" when I export the vault, the next time Aegis should use "mybackup" as default base name for the export file.
Also, I really want Aegis automatically appends the current date/time in the file name (e.g., mybackup200120 on the day 01/20/2020) to make it easier for me to find the export date/time.

Thanks!

**Comment by alexbakker** [comment]
The [backup feature](https://github.com/alexbakker/Aegis/tree/backups) we're working on will allow you to select a directory where Aegis will store backups of the vault with a timestamp appended to the filename. These backups can be triggered automatically and/or manually.

I think we'll leave the export functionality as it is now, but if we add an option for customizing the prefix of the filename for backups, that would also cover all items of your request. Would you agree?

**Comment by ElTopo** [comment]
@alexbakker  That sounds good enough for me.

btw, I already forked Aegis and added "Quick Save" in the main menu next to "Lock", which saves quick and silent encrypted backups to Download/xa/qs-YYYY.MM.DD-hh:mm:ss (without asking encrypted? / what file name? / in which folder?):
https://github.com/ElTopo/xAegis/tree/lxl
I have no intention to submit pull-requests since your "triggered backups" would be better.
Thanks.
