### ISSUE TITLE
Unable to activate Biometric unlock after biometric change

### ISSUE THREAD

**Issue by Otiel** [beemdevelopment/Aegis#299]
###### Info

* __Version__: 1.1.1
* __Source__: F-Droid
* __Vault encrypted:__ Yes (with password)
* __Android version and ROM:__ Android 9

###### Steps to reproduce

I previously had "Biometric unlock" activated in Aegis without any issue.

I've changed my biometric data in Android settings (namely: I've removed a fingerprint and added another). Aegis then prompted me to enable again the "Biometric unlock", but I'm unable to do so. Nothing happens when I click on the "Biometric unlock" setting.

I've tried to completely disable the encryption then enable it again, but that doesn't change anything.

**Comment by alexbakker** [comment]
I'm surprised that 'nothing' happens. You should see a toast with an error message. Can you obtain a debug log with ADB? Which device do you have? Also, can you try clearing Aegis' app data and go through the setup process again to see if that fixes it? Don't forget to create an export of your vault first.

**Comment by Otiel** [comment]
Thanks for the quick reply!

No toast message. I have a Samsung Galaxy S10e.

The ADB log shows the following:
```
01-22 15:18:00.330 22939 22939 D KeyStore: UserNotAuthenticatedException because of Fingerprint
```

I've tried to clear Aegis app data and set up my vault again:
* Through the "Password" option via the first setup assistant, then trying to check "Biometric unlock" in the settings ⇒ I have the same behavior and error in the ADB log.
* Through the "Biometric" option via the first setup assistant ⇒ I cannot go to the next screen, and I have the same error in the ADB log.

**Comment by alexbakker** [comment]
Interesting, so the biometric prompt is not showing at all? Does biometric authentication work properly with other apps on your device?

**Comment by Otiel** [comment]
Nothing is shown.

>Does biometric authentication work properly with other apps on your device?

Yes, I use it for instance with [KeePassDX](https://github.com/Kunzisoft/KeePassDX).

**Comment by Otiel** [comment]
Any other debug info I could provide?

**Comment by alexbakker** [comment]
> Yes, I use it for instance with KeePassDX.

In that case, I'm at a loss here to be honest. We use exactly the same androidx biometrics library as KeePassDX. I'm afraid you'll have to dig in yourself. Can you attach a debugger and set a breakpoint in ``BiometricSlotInitializer.fail``, to see which error code is returned?

**Comment by jpellegrini** [comment]
This also happened to me after I added a second fingerprint yesterday.

**Comment by jpellegrini** [comment]
> Nothing is shown.
> 
> > Does biometric authentication work properly with other apps on your device?
> 
> Yes, I use it for instance with [KeePassDX](https://github.com/Kunzisoft/KeePassDX).

Did the problem start right after some change in the lock setup (changed pattern, added fingerprint, or anything else like that)? In my case it was.
If so, it could be that KeePassDX did not see the change for some reason (did you install it after you spotted the problem with Aegis?)

**Comment by Otiel** [comment]
> Did the problem start right after some change in the lock setup (changed pattern, added fingerprint, or anything else like that)? In my case it was.

Yes, as I said originally:

>I've changed my biometric data in Android settings (namely: I've removed a fingerprint and added another). Aegis then prompted me to enable again the "Biometric unlock".

---

> If so, it could be that KeePassDX did not see the change for some reason (did you install it after you spotted the problem with Aegis?)

No, KeePassDX saw the change and prompted me as well to perform the biometric setup again in the app, which I did without issue.

**Comment by JonnyHaystack** [comment]
I'm also having trouble with biometric unlock not working in Aegis (it works in everything else).

When I tried to set up Aegis initially using biometric unlock, the app would just exit after finishing the setup wizard. No errors were shown. Reopening the app brought me back to the start of the wizard. Eventually I tried using just a password and that worked first time. I then went into settings and tried to enable biometric unlock there, and that gave me a toast error message, which is more helpful:

![](https://imgur.com/a/5vfE5GH)

**Comment by alexbakker** [comment]
@JonnyHaystack Can you give some examples of other apps with biometric unlock that do work? Does KeePassDX work for you?

**Comment by JonnyHaystack** [comment]
@alexbakker I don't use KeePass but I use Bitwarden, which works fine. Others I use are Money Dashboard, Aprox, Magisk, and MEWconnect. Actually thinking about it now I also couldn't get biometrics working with PayPal, but I don't currently have biometrics issues with any other apps.

**Comment by jpellegrini** [comment]
> @alexbakker I don't use KeePass but I use Bitwarden, which works fine. 
What happens if you add naother fingerprint on the device?
(Just be careful -- if it breaks, you may need to set up 2FA again in all services)

**Comment by alexbakker** [comment]
@JonnyHaystack I asked about KeePassDX specifically, because it uses the combination of biometric authentication and the Android Keystore in (almost) exactly the same way we do. Most apps (like the ones you mention, probably) just show a biometric prompt without any cryptography being involved.

**Comment by JonnyHaystack** [comment]
Hmm I'm not sure if I'm doing something wrong but it doesn't seem to work in KeePassDX. I just downloaded it to test.

**Comment by JonnyHaystack** [comment]
@jpellegrini I tried that. Didn't change anything.

**Comment by alexbakker** [comment]
@JonnyHaystack Thanks for confirming. Which device do you have?

**Comment by JonnyHaystack** [comment]
@alexbakker Galaxy S7

**Comment by Vstory** [comment]
> 我也遇到了生物特征识别解锁在Aegis中不起作用的麻烦（它在其他所有方面都起作用）。
> 
> 当我最初尝试使用生物特征识别解锁设置“宙斯盾”时，该应用程序将在完成设置向导后退出。没有显示错误。重新打开应用程序使我回到了向导的开始。最终，我尝试仅使用密码，并且第一次成功。然后，我进入设置并尝试在此处启用生物识别解锁，这给了我一个吐司错误消息，这更有用：
> 
> ![](https://camo.githubusercontent.com/8916b996598105711f1347d0508da9bbc565f5a1/68747470733a2f2f692e696d6775722e636f6d2f46706c444b6d322e6a7067)
> 
> 编辑：还请注意，我最近根本没有在Android设置中更改过生物特征识别/解锁设置，而我本周只安装了宙斯盾。


#332 
Choosing biometrics in the wizard will also crash.
I cannot select biometrics in the trial interface or the application will crash.

Install "Aegis" for the first time and choose password encryption.After that, I can turn on biometric authentication in the "Aegis" settings, but it didn't take long to prompt that the security settings were changed.
Now I can no longer use biometric authentication in "Aegis", uninstalling and reinstalling has no effect

**Comment by alexbakker** [comment]
The more reports we receive that are similar to this one, the more clear it becomes that some of these devices just have buggy Keymaster implementations. The fact that biometrics in Aegis used to work for @Vstory, broke when they tried to reconfigure it and remains broken after reinstallation of Aegis, means there's something going on here that's out of our hands.

**Comment by Vstory** [comment]
> The more reports we receive that are similar to this one, the more clear it becomes that some of these devices just have buggy Keymaster implementations. The fact that biometrics in Aegis used to work for @Vstory, broke when they tried to reconfigure it and remains broken after reinstallation of Aegis, means there's something going on here that's out of our hands.


I don't know how you did it, but any other app that uses biometrics doesn't have this problem.
for example:
[LastPass](https://play.google.com/store/apps/details?id=com.lastpass.lpandroid)
[Filter Box](https://play.google.com/store/apps/details?id=com.catchingnow.np)
[NZBManager](https://play.google.com/store/apps/details?id=nl.timkatgert.nzbmanager)

**Comment by alexbakker** [comment]
@Vstory There are different ways to use biometric authentication. We use it to protect a symmetric key that is stored in the Android Keystore. See my comment here: https://github.com/beemdevelopment/Aegis/issues/299#issuecomment-591545292. Can you try KeePassDX and see if you can get it to fail in a similar way?

**Comment by Vstory** [comment]
> KeePassDX

Is it this one?
[KeePassDX](https://play.google.com/store/apps/details?id=com.kunzisoft.keepass.free)

**Comment by alexbakker** [comment]
@Vstory Yes.

**Comment by Vstory** [comment]
> @Vstory Yes.


very funny.
[KeePassDX - Advanced-Unlocking](https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking)
- 1.According to the wiki I successfully used biometrics;
- 2.Then, I created a new fingerprint in the system fingerprint.Then go to KeePassDX to unlock the database with biometrics, indicating that the biometric key cannot be read.Prompt need to delete all biometric keys and re-enter.

Next is the point.

- 3.Enter the password directly to unlock the database, then open KeePassDX settings.
- 4.Go to Advanced Unlock and choose to delete the encryption key.
- 5.Exit KeePassDX and try biometric unlock again with the database just now.Biometrics work fine.

**Comment by Vstory** [comment]
> > @Vstory Yes.
> 
> very funny.
> [KeePassDX - Advanced-Unlocking](https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking)
> 
> * 1.According to the wiki, I successfully unlocked the database using biometric authentication in KeePassDX.;
> * 2.Then, I created a new fingerprint in the system fingerprint.Then go to KeePassDX to unlock the database with biometrics, indicating that the biometric key cannot be read.Prompt need to delete all biometric keys and re-enter;
> 
> Next is the point.
> 
> * 3.Enter the password directly to unlock the database, then open KeePassDX settings;
> * 4.Go to Advanced Unlock and choose to delete the encryption key;
> * 5.Exit KeePassDX and try biometric unlock again with the database just now.Biometrics work fine.

#332 

The problem has been resolved, please see:[Adding a new fingerprint displays an error](https://github.com/Kunzisoft/KeePassDX/issues/488)

**Comment by Otiel** [comment]
> The problem has been resolved, please see: [Adding a new fingerprint displays an error](https://github.com/Kunzisoft/KeePassDX/issues/488)

I'm not following... Did you solve this issue with Aegis? If so, can you post here the steps?

**Comment by Vstory** [comment]
> > The problem has been resolved, please see: [Adding a new fingerprint displays an error](https://github.com/Kunzisoft/KeePassDX/issues/488)
> 
> I'm not following... Did you solve this issue with Aegis? If so, can you post here the steps?


The problem has been resolved.

```
I used the Xposed module: [CustoMIUIzer](https://play.google.com/store/apps/details?id=name.mikanoshi.customiuizer) , and used some of these features, which caused this problem.

Skip password verification at startup.
This function allows the device to be unlocked directly with the fingerprint after entering the device without entering the screen password.
When this feature is disabled, everything works fine.
```


I'm not sure if others have used similar applications to modify biometrics.

**Comment by jpellegrini** [comment]
> I'm not sure if others have used similar applications to modify biometrics.

I did not... I have Magisk installed, but the only modules used are busybox, IBM3270 (font), Magisk Manager for recovery mode, and Systemless hosts.
And the phone has no Gapps, maybe that makes a difference?

**Comment by Otiel** [comment]
In my case, no root, no Magisk, no Xposed module...

I simply changed my saved fingerprints through Android settings.

**Comment by Vstory** [comment]
> > I'm not sure if others have used similar applications to modify biometrics.
> 
> I did not... I have Magisk installed, but the only modules used are busybox, IBM3270 (font), Magisk Manager for recovery mode, and Systemless hosts.
> And the phone has no Gapps, maybe that makes a difference?




> > I'm not sure if others have used similar applications to modify biometrics.
> 
> I did not... I have Magisk installed, but the only modules used are busybox, IBM3270 (font), Magisk Manager for recovery mode, and Systemless hosts.
> And the phone has no Gapps, maybe that makes a difference?


What about using magisk's core mode only?

**Comment by Vstory** [comment]
> In my case, no root, no Magisk, no Xposed module...
> 
> I simply changed my saved fingerprints through Android settings.


I can't help it. [Adding a new fingerprint displays an error](https://github.com/Kunzisoft/KeePassDX/issues/488)， J-Jamet's response inspired me.
I turned off the relevant module functions, and everything worked fine.

**Comment by jpellegrini** [comment]
> What about using magisk's core mode only?

Ok - tried it now, and didn't help.

**Comment by alexbakker** [comment]
This seems to be a device-specific bug that we cannot reproduce. Aegis now properly reports when it cannot use biometrics on such devices.

**Comment by Otiel** [comment]
>Aegis now properly reports when it cannot use biometrics on such devices.

What do you mean?

I have v1.2.1 and when I try to enable the "Biometric unlock" option, it just does nothing: the option doesn't become activated, no toast message, still the same thing in ADB log:

`D KeyStore: UserNotAuthenticatedException because of Fingerprint`

**Comment by alexbakker** [comment]
Hmm. If nothing happens when Aegis tries to show the biometrics prompt on your device, there's probably also no error we can catch. I'm wondering if you're running into this issue: https://issuetracker.google.com/issues/154868505.

**Comment by Otiel** [comment]
> https://issuetracker.google.com/issues/154868505.

Is that link content available without any Google login?

**Comment by alexbakker** [comment]
> Is that link content available without any Google login?

It is not. Here's the bug report contents:

```
Code snippet:
// key generation
val keyGenerator = KeyGenerator.getInstance("AES", "AndroidKeyStore")
keyGenerator.init(
    KeyGenParameterSpec.Builder(alias, PURPOSE_ENCRYPT or PURPOSE_DECRYPT)
             .setBlockModes(BLOCK_MODE_GCM)
            .setEncryptionPaddings(ENCRYPTION_PADDING_NONE)
            .setUserAuthenticationRequired(true)
            .setUserAuthenticationValidityDurationSeconds(-1)
            .build()
)
val secretKey = keyGenerator.generateKey()

// cipher initialization
val encryptCipher = Cipher.getInstance(CIPHER_TRANSFORMATION)
encryptCipher.init(Cipher.ENCRYPT_MODE, secretKey)

// biometry prompt invocation
val prompt = BiometricPrompt(activity, executor, listener)
prompt.authenticate(info, CryptoObject(encryptCipher))

BUILD INFO
- Device type: Samsung S10e (SM-G970F)
- OS version: Android 9
- Biometric library version: 1.0.1
- Device security configuration: only one fingerprint added

STEPS TO REPRODUCE
[Be as specific as possible please]
1. Try to authenticate with biometry prompt on Samsung S10e (SM-G970F)

EXPECTED RESULTS
Biometry prompt is shown

OBSERVED RESULTS
Biometry prompt not shown

NUMBER OF TIMES YOU WERE ABLE TO REPRODUCE: 10/10
```

**Comment by Otiel** [comment]
Thanks. Is it mentioned by someone there if the issue is solved in Android 10?

**Comment by alexbakker** [comment]
I'm not sure, this appears to be a device-specific issue in ``androidx.biometric``. It has some quirk handling logic for Samsung devices that seems to not behave as intended: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/biometric/biometric/src/main/res/values/devices.xml. If you want, I can build a debug APK with the latest ``androidx.biometric:biometric:1.1.0-alpha01`` release to see if that fixes it.

**Comment by Otiel** [comment]
Sure, I can try!

**Comment by alexbakker** [comment]
Here it is: https://alexbakker.me/u/hjfi908me9.apk.

**Comment by Otiel** [comment]
Thanks. Do I need to uninstall Aegis stable version first? Or can both run side-to-side?

**Comment by alexbakker** [comment]
It has a different package name, so it can be run side-by-side with the version of Aegis you got from F-Droid.

**Comment by Otiel** [comment]
Tested, and no luck: same behavior.

Thanks anyway for the dev build.

**Comment by Otiel** [comment]
I've upgraded my S10e to Android 10 and biometric unlock now works correctly with Aegis. 🎉 

Not that that would help those who have this issue, but just as information.

**Comment by febb** [comment]
Hi, certainly a humongous jump from this thread back in 2020, then 2023 and last posts on 2024.  
Well, here I am on October 2025, with a Samsung S25 Ultra, with One UI 8.0 (Android 15), fully updated phone (not rooted nor modified) and using Aegis version 3.4.1  regularly within the Samsung's secure folder feature.

I am experiencing exactly the same behavior described on the initial posts of this thread.  Biometric unlock can't be toggled on.  

Upon changing a fingerprint Aegis used to request a re-activation of the biometric unlock via its own settings and even once in a while also asked for a typed password.  Now, the  "Biometric Unlock" feature is completely grayed out.

As mentioned above, I use Aegis withing the Samsung's secure folder and it used to work fine until now.   

To test, I installed a brand new instance of Aegis 3.4.1 in the same phone, out  of the secure folder and, when initially configured  with a password and later on I imported my backup, then afterwards I can enable biometric unlock through the app's settings.   

The above is not the case if I reinstall Aegis within the Samsung's secure folder.  It seems permissions are exactly the same on both, the out of and the within secure folder instances of Aegis.

So far, I can provide any additional information that may be required, of course I'm willing to help any way I can to fix this issue. 

Any one still experiencing this issue with latest Aegis 3.4.1 on a Samsung phone on One UI 8.0 ?  Maybe time to reopen it...?

Thanks in advance.

**Comment by hafzaal** [comment]
> Hi, certainly a humongous jump from this thread back in 2020, then 2023 and last posts on 2024. Well, here I am on October 2025, with a Samsung S25 Ultra, with One UI 8.0 (Android 15), fully updated phone (not rooted nor modified) and using Aegis version 3.4.1 regularly within the Samsung's secure folder feature.
> 
> I am experiencing exactly the same behavior described on the initial posts of this thread. Biometric unlock can't be toggled on.
> 
> Upon changing a fingerprint Aegis used to request a re-activation of the biometric unlock via its own settings and even once in a while also asked for a typed password. Now, the "Biometric Unlock" feature is completely grayed out.
> 
> As mentioned above, I use Aegis withing the Samsung's secure folder and it used to work fine until now.
> 
> To test, I installed a brand new instance of Aegis 3.4.1 in the same phone, out of the secure folder and, when initially configured with a password and later on I imported my backup, then afterwards I can enable biometric unlock through the app's settings.
> 
> The above is not the case if I reinstall Aegis within the Samsung's secure folder. It seems permissions are exactly the same on both, the out of and the within secure folder instances of Aegis.
> 
> So far, I can provide any additional information that may be required, of course I'm willing to help any way I can to fix this issue.
> 
> Any one still experiencing this issue with latest Aegis 3.4.1 on a Samsung phone on One UI 8.0 ? Maybe time to reopen it...?
> 
> Thanks in advance.

Seeing the exact same behavior on a Samsung S24 Ultra. Cannot enable biometrics while inside the secure folder.

I wonder if this is related to the recent security issue Samsung patched in One UI 8,  https://www.sammobile.com/news/one-ui-8-fixes-samsung-secure-folder-major-security-flaw/
