### ISSUE TITLE
Alternative Download Source

### ISSUE THREAD

**Issue by IzzySoft** [beemdevelopment/Aegis#30]
Would you mind providing the APK for those not using Playstore? For example, attach them to your [releases](https://github.com/beemdevelopment/Aegis/releases) (I could then automatically pick and provide them via [my repo](https://apt.izzysoft.de/fdroid)), or even going for the official [F-Droid](https://f-droid.org/) repo?

Thanks for considering!

**Comment by michaelschattgen** [comment]
We are publishing Aegis to F-Droid within the next few days. 

Attaching to our releases is a good idea, we will look into that. Thanks.

**Comment by IzzySoft** [comment]
Thanks for the fast reply – and congrats to your decision on F-Droid! As you haven't yet opened an RFP or MR there, let me know if you need help with that (disclosure: I'm one of the maintainers).

Also, if you want your app in my repo until then (other than a few days, weeks or sometimes even months it takes to get an app integrated with the official repo, it usually takes a few minutes with mine – provided the APK is available; and updates are fetched automatically within 24h of your attaching them to a new tag).

**Comment by alexbakker** [comment]
> Thanks for the fast reply – and congrats to your decision on F-Droid! As you haven't yet opened an RFP or MR there, let me know if you need help with that (disclosure: I'm one of the maintainers).

I'm drafting a PR for fdroiddata here: https://gitlab.com/alexbakker/fdroiddata/tree/aegis. I think the metadata part is mostly done, but I haven't gotten to adding the icon and screenshots yet.

> Also, if you want your app in my repo until then (other than a few days, weeks or sometimes even months it takes to get an app integrated with the official repo, it usually takes a few minutes with mine – provided the APK is available; and updates are fetched automatically within 24h of your attaching them to a new tag).

We'll make sure to attach the APK's to our releases on GitHub. My concern with adding our app to other repositories beforehand is that users will have to reinstall it once it hits the official F-Droid repository, as those APK's will be signed with a different key.

**Comment by IzzySoft** [comment]
I see, so you're doing it straight via MR.

> but I haven't gotten to adding the icon and screenshots yet.

So you will add fastlane or triple-t structures to your repo here I assume? Cool!

> My concern with adding our app to other repositories beforehand is that users will have to reinstall it once it hits the official F-Droid repository

Yes, indeed, a valid point. Most users are aware of that, but not all. Well, up to you: my offer stands, but I understand if you're about ready for inclusion with the official repo that you don't want this now. And if processing at F-Droid is straight (i.e. no complications coming up), it would indeed be unnecessary. If it isn't, we can still see to it then :wink:

**Comment by alexbakker** [comment]
>So you will add fastlane or triple-t structures to your repo here I assume? Cool!

That's the plan!

>Most users are aware of that, but not all. Well, up to you: my offer stands 

Thanks, but I think we're ready to submit the PR tonight, so we'd rather go straight through the official process. We're not in a hurry, so I'm not too worried about it taking a while.

**Comment by IzzySoft** [comment]
OK, cool! Looking forward to your MR then. See you "on the other side" 😄

**Comment by alexbakker** [comment]
I've submitted the pull request: https://gitlab.com/fdroid/fdroiddata/merge_requests/4663.

**Comment by IzzySoft** [comment]
Yupp, I saw – thanks! But could it be you forgot to push the fastlane/triple-t (whichever you use) metadata to this repo here? I can't see such. Ahem, OK, not at the tag. You need to move the tag to a commit that already has them :wink:

**Comment by alexbakker** [comment]
Right. We'll tag a new release tonight. My bad.

**Comment by IzzySoft** [comment]
Happens. But it takes a little time for your MR to be picked up anyway, so I guess "tonight" should be "in-time" 😄

**Comment by alexbakker** [comment]
That was quick! The pull request for inclusion in F-Droid has been merged. I'll leave this open until we have attached APK's the release tags on GitHub. Thanks for your help, @IzzySoft.

**Comment by IzzySoft** [comment]
Gladly! Thanks for your support! I've already included Aegis with [my corresponding app listing](https://android.izzysoft.de/applists/category/named/office_password#group_1142). Enjoy (we do 😄)!

**Comment by rugk** [comment]
BTW you still need to adjust the Readme as the F-Droid build is now there. It still states:
> There are plans to make it available on F-Droid as well.

**Comment by michaelschattgen** [comment]
We are aware of this. We are just waiting for F-Droid to show Aegis properly including our own metadata which isn't the case now.

**Comment by alexbakker** [comment]
This is covered now. The app has been published on F-Droid (metadata issues should be fixed whenever the F-Droid build server decides to pick up the latest tag) and APK's are now available on GitHub as well.
