### ISSUE TITLE
use PIN authentication to start and lock/unlock app (separate from vault encryption)

### ISSUE THREAD

**Issue by thediamondgeezer** [beemdevelopment/Aegis#307]
Please add the option to use a PIN to authenticate in order to start and lock/unlock the app. This is separate from vault encryption, which requires a password.

Currently, the password used to start and lock/unlock the app is the same as the one used to encrypt the vault and there is a trade-off for ease of use, especially if the vault encryption password is long and complex (as it should be).

andOTP and AuthenticatorPlus do that very well currently.

**Comment by alexbakker** [comment]
Duplicate of #54.
