### ISSUE TITLE
Confirm password not enforced when show password is checked

### ISSUE THREAD

**Issue by msoose** [beemdevelopment/Aegis#309]
###### Info

* __Version__: 1.1.4
* __Source__: (Google Play/GitHub/F-Droid/?) F-Droid
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ N/A
* __Android version and ROM:__ Android 9.0 / LineageOS 16.0

###### Steps to reproduce

Set password, and proceed to change the password. When checking off `Show password` the confirm box is not enabled, and it's not enforced. The OK button is immediately enabled and the text box for `Confirm password` is disabled.

###### What do you expect to happen?

Although I believe this is by design, like almost every other application I have used (web, native, mobile, desktop, etc...), I expect the `Confirm password` text box to stay enabled and allow me to type in my password a second time while still ensuring it matches to the above `Password` text box.

###### What happens instead?

When checking off `Show password` the confirm box is not enabled, and it's not enforced. The OK button is immediately enabled and the text box for `Confirm password` is disabled. This allows the user to immediately change the password without any verification that the password was typed correctly using the `Confirm password` text box. Even though the user can plainly see the password, this is still dangerous.

###### Log

N/A

**Comment by alexbakker** [comment]
You're right that this is by design. It was inspired by KeePass, which has the same behavior. We'll take this into consideration, thanks! I'll relabel this to be a proposal, as it's not really a bug.
