### ISSUE TITLE
Have tapping on a code copy it rather than open the menu.

### ISSUE THREAD

**Issue by omair94** [beemdevelopment/Aegis#31]
Right now, when you tap on a code, it opens a menu with the options "copy", "edit", and "delete".

Given that after initial setup, users are almost always going to want to copy the code, can you make it so tapping on a code copies it, and long pressing on the code opens the menu?

This is how LastPass Authenticator does it.

**Comment by michaelschattgen** [comment]
Thanks for your contribution! You're right about users mostly wanting to copy the code but we currently support drag and drop which requires a long press.

Maybe we can implement some kind of new drag and drop "mode" so we can use the long press for the "copy", "edit" and "delete" menu.

What are your thoughts on this @alexbakker?

**Comment by alexbakker** [comment]
We could move the whole menu to the Action Bar. A single press would copy the code, a long press shows the menu in the Action Bar by switching to a different ActionMode and a long press when the ActionMode is enabled allows drag and drop.

On a side note, I don't think copying the code is actually that common for most users. If it is, they're probably using 2FA incorrectly.

**Comment by fear-the-beaver** [comment]
Hi! As we discussed on reddit, here're a few workflows that I think about:

- On mobile, user wants to enter 2FA code locally. Copy code button next to the token serves the purpose and the code stays masked.

- On mobile, user wants to enter 2FA code on another device. Tap to reveal code serves the purpose.

- On mobile, user wants to edit / delete token entry. Long tap should reveal menu with option but not reveal the code.

Also, whats wrong with copying the codes? Aegis doesn't provide incognito keyboard to enter codes as KeePass2Android. Back to KeePass, it has the same workflow - you can copy password without revealing it.

**Comment by fear-the-beaver** [comment]
Another suggestion, taping on the revealed code should mask it.

**Comment by rmodi6** [comment]
Another suggestion:
- Copy `code` on single press.
- Open `edit` and `delete` menu on long press.
- Have a button on the right hand side which when dragged up and down changes the position of the item in the list. (Like the one in the Now Playing list of BlackPlayer)

**Comment by Wilker-a** [comment]
the three options on the long press could be revealed at the top bar like a regular interface of multiple selections when you click the icon (or anywhere relevant) or press and hold the item just like in a file explorer for example, and the settings screen could offer an "action on click" and an "action on hold" setting, each having the coices "copy", "reveal", "copy and reveal" and "select"

**Comment by mdmk** [comment]
What about a swipe gesture on entries?
User could define two action (one for swipe left and one for swipe right) without adding buttons that that would clutter the UI.
See Gmail for example of how swipe left/right gesture works.

**Comment by chiraag-nataraj** [comment]
I just want to chime in and say that copying codes is _incredibly_ common. If you're authenticating an app on your phone, it's a lot easier to copy-paste the code than to memorize it, switch apps again, and then enter it...all within the timer.

Personally, I'd be in favor of:

* single-tap = copy
* long-press = menu (Copy, Edit, Delete)
* Bars on the right-hand side of each item for re-ordering

If reordering might be too easy to accidentally trigger, it might be better to have a menu item "Reorder" which then lets you drag the items around.

**Comment by MRVMV** [comment]
This thread just got a little old, but it's too important
I'm one of the people that uses 2FA for every service that support it and I uses incognito browsers a lot so I have a lot of times copying codes... 
I think the most common solution for this is to make
1. Single click copy code
2. Long press selects the item and shows a bar which has (copy, edit, alert (I just suggested this feature) and delete buttons) and in the same time enters a drag and drop mode so you can reorder things)

Copying codes quickly is much more important than reordering items quickly as I will just reorder them much less...

**Comment by rnc** [comment]
+1 , I copy the codes all the time and use KDEConnect ( https://albertvaka.wordpress.com/2016/08/26/kde-connect-1-0-is-here/ ) to copy the code to my computer for entry. I think copy on single press would be very useful.

**Comment by wvffle** [comment]
Maybe implement something like a bunch of email clients did. I mean buttons that reveal on swipe left/right.

Then we could have:
- tap for showing code
- longpress for copying code
- swipe left to show edit/delete buttons
