### ISSUE TITLE
Consider repositioning the login UX to the center/bottom hemisphere

### ISSUE THREAD

**Issue by nodeunit** [beemdevelopment/Aegis#310]
I appreciate Aegis for its simplicity as a TOTP app. However, there is one nitpick about it that routinely bothers me: the login screen.

As far as I can tell, the login field is attached to the margins of the top of the screen. This could pose a problem for people with taller phones, as even with a 16:9 5" screen, it was somewhat awkward for me to reach it.

Anchoring the input field to be closer to the center would streamline the login process and avoid strain.

**Comment by alexbakker** [comment]
Sounds reasonable to me. @michaelschattgen What do you think?

**Comment by alexbakker** [comment]
The password input field and buttons are positioned near the center since 4f6035dc49bce68f34731bfd5a2f6d9d3e9d5020.
