### ISSUE TITLE
Scanning python-bna's QR code crashes the app

### ISSUE THREAD

**Issue by emersion** [beemdevelopment/Aegis#311]
###### Info

* __Version__: 1.1.4
* __Source__: F-Droid
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Pixel 3A
* __Android version and ROM:__ AOSP, 10.0

###### Steps to reproduce

No Battle.net account required.

- Install [python-bna](https://github.com/jleclanche/python-bna)
- Run `bna`
- Run `bna show-url | qrencode -o <output-file>`
- Open the file
- Scan the QR code with Aegis

The URL looks like: `otpauth://totp/Blizzard:EU123412341234:?secret=ASFAS75ASDF75889G9AD7S69AS7697AS&issuer=Blizzard&digits=8`

Adding the profile manually works.

###### What do you expect to happen?

Aegis accepts the new profile.

###### What happens instead?

Aegis crashes.

###### Log

Can provide if necessary.

**Comment by alexbakker** [comment]
Thanks for the report. I get an error when scanning a QR code with that URL. That appears to be a bug, I'll look into it. I can't get the app to crash, though. Could you obtain a log of that?

**Comment by emersion** [comment]
Ah, it seems like it doesn't crash with the sample URL. However with `bna show-url` it does:

```
02-18 20:17:26.762 19938 19938 E AndroidRuntime: FATAL EXCEPTION: main
02-18 20:17:26.762 19938 19938 E AndroidRuntime: Process: com.beemdevelopment.aegis, PID: 19938
02-18 20:17:26.762 19938 19938 E AndroidRuntime: java.lang.NumberFormatException: For input string: "8
02-18 20:17:26.762 19938 19938 E AndroidRuntime: "
02-18 20:17:26.762 19938 19938 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:615)
02-18 20:17:26.762 19938 19938 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:650)
02-18 20:17:26.762 19938 19938 E AndroidRuntime: 	at com.beemdevelopment.aegis.otp.GoogleAuthInfo.parseUri(GoogleAuthInfo.java:142)
02-18 20:17:26.762 19938 19938 E AndroidRuntime: 	at com.beemdevelopment.aegis.otp.GoogleAuthInfo.parseUri(GoogleAuthInfo.java:56)
02-18 20:17:26.762 19938 19938 E AndroidRuntime: 	at com.beemdevelopment.aegis.ui.ScannerActivity.handleResult(ScannerActivity.java:111)
02-18 20:17:26.762 19938 19938 E AndroidRuntime: 	at me.dm7.barcodescanner.zxing.ZXingScannerView$1.run(ZXingScannerView.java:164)
02-18 20:17:26.762 19938 19938 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:903)
02-18 20:17:26.762 19938 19938 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-18 20:17:26.762 19938 19938 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
02-18 20:17:26.762 19938 19938 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7396)
02-18 20:17:26.762 19938 19938 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-18 20:17:26.762 19938 19938 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
02-18 20:17:26.762 19938 19938 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by alexbakker** [comment]
Got it. Thanks.

**Comment by alexbakker** [comment]
It looks like bna outputs a newline after the URL, which is then incorporated in the QR code by your command. The following will produce a valid QR code: ``bna show-url | tr -d '\n' | qrencode -o - | feh -``. I've submitted #318 to make the parsing logic on our end more robust.
