### ISSUE TITLE
Add support for Ripple panic button

### ISSUE THREAD

**Issue by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [beemdevelopment/Aegis#312]
Currently Aegis is not compatible with Ripple, it would be really nice and helpful for both projects if support would be added. Aegis would have an extra layer of security and Ripple would have one more app that has support, and this would incentivize Ripple's devs to continue with their work.

It would be even greater it you could add a setting to delete the entries, not just to hide the app when triggered. A lot of  apps have support for it but only enable this option, which is kind of lame since it can have a bigger potential.

Thanks!

**Comment by alexbakker** [comment]
I get see a couple of different projects when I search for "Ripple panic button". Is this the Ripple app you're talking about: https://guardianproject.info/apps/info.guardianproject.ripple?

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Oh, sorry I didn't give you a link, what a dummy.

Yes, that's the application. The Guardian Project has done a lot of good projects, they were the ones developing Orfox before The Tor Project added real Android support, among other stuff.

**Comment by alexbakker** [comment]
We noticed that the last update of the Ripple app in the Play Store was in 2016. Is it still being maintained actively?

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> We noticed that the last update of the Ripple app in the Play Store was in 2016. Is it still being maintained actively?

On F-droid it says one year ago, and although that's some time I don't think it requires sooo many updates. Also, The Guardian Project some times updates some software that have been without a proper update for some time. 


I'll try to shut out to the developers and see if they are still working on it, I wanted to see if I could convince more people to give it support.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
https://github.com/guardianproject/ripple/issues/13#issuecomment-591441133

It's not dead.

**Comment by michaelschattgen** [comment]
Good to know. We will implement this in the feature.

**Comment by eighthave** [comment]
this is the relevant info for an app like this: https://guardianproject.info/code/panickit, Ripple is just one app in the PanicKit ecosystem.
