### ISSUE TITLE
Localization issue: Missing plural forms

### ISSUE THREAD

**Issue by mKoonrad** [beemdevelopment/Aegis#314]
There is missing plural form in your strings.

https://github.com/beemdevelopment/Aegis/blob/833e75ade14f426ec9d12f39ab3605edcb5cf8d8/app/src/main/res/values/strings.xml#L101
https://github.com/beemdevelopment/Aegis/blob/833e75ade14f426ec9d12f39ab3605edcb5cf8d8/app/src/main/res/values/strings.xml#L133
https://github.com/beemdevelopment/Aegis/blob/833e75ade14f426ec9d12f39ab3605edcb5cf8d8/app/src/main/res/values/strings.xml#L134

You need to add plural forms for:
- few (in most cases 2-4)
- many (in most cases >4)

See grammar rules: https://www.unicode.org/cldr/charts/33/supplemental/language_plural_rules.html#pl

Version: 1.1.4
Source: GitHub

Update:
https://github.com/beemdevelopment/Aegis/blob/e41f200bcd43e35a3c56e0cb31b534154f099f20/app/src/main/res/values/strings.xml#L41

**Comment by michaelschattgen** [comment]
Could you elaborate on this? I don't think the english sentences are missing plural forms.

In fact, singular forms is wrong:

>Read 1 entries

**Comment by mKoonrad** [comment]
@michaelschattgen  I can explain you. In many languages we have declension (something like grammar cases). For example in Polish language we have more than 1 plural forms.
In English you have just 1 plural form:
- 1 entry
- 2 entries
- 5 entries etc.

But for example in Polish language I need to prepare translations:
- 1 wpis
- 2 wpis**y**
- 5 wpis**ów**

Please look again to link and see rules: https://www.unicode.org/cldr/charts/33/supplemental/language_plural_rules.html#pl

Currently I can't prepare correct translations. Do you understand issue now?

**Comment by chiraag-nataraj** [comment]
This sort of stuff is actually what spurred Mozilla to create [Project Fluent](https://projectfluent.org/).

**Comment by mKoonrad** [comment]
@michaelschattgen Not yet here
https://github.com/beemdevelopment/Aegis/blob/98e8a0d97e2463840a41ebbe20aa25952b03fd6b/app/src/main/res/values/strings.xml#L43

**Comment by alexbakker** [comment]
@mKoonrad Whoops. Will be fixed once #558 is merged.
