### ISSUE TITLE
Typo in string

### ISSUE THREAD

**Issue by mKoonrad** [beemdevelopment/Aegis#315]
https://github.com/beemdevelopment/Aegis/blob/833e75ade14f426ec9d12f39ab3605edcb5cf8d8/app/src/main/res/values/strings.xml#L138

Should be `This action will export the vault out of Aegis private storage.`

Version: 1.1.4
Source: GitHub

**Comment by michaelschattgen** [comment]
This is incorrect. Standalone apostrophes can be used with plural proper nouns ending with an s when talking about possession.

Therefore I'm closing this issue. Feel free to continue the discussion though.
