### ISSUE TITLE
Missing unification of names

### ISSUE THREAD

**Issue by mKoonrad** [beemdevelopment/Aegis#316]
https://github.com/beemdevelopment/Aegis/blob/833e75ade14f426ec9d12f39ab3605edcb5cf8d8/app/src/main/res/values/strings.xml#L178
Should be `AMOLED theme`

https://github.com/beemdevelopment/Aegis/blob/833e75ade14f426ec9d12f39ab3605edcb5cf8d8/app/src/main/res/values/strings.xml#L152
Should be `animation duration scale`

Version: 1.1.4
Source: GitHub

**Comment by michaelschattgen** [comment]
I agree with 'Amoled', not with the animation duration scale. It's literally called 'Animator duration scale' in the Android settings.

**Comment by alexbakker** [comment]
Fixed in #319.
