### ISSUE TITLE
Add amoled / true black theme

### ISSUE THREAD

**Issue by michaelschattgen** [beemdevelopment/Aegis#32]

**Comment by michaelschattgen** [comment]
<img width=400 src="https://user-images.githubusercontent.com/7524012/55121024-bdec4400-50f8-11e9-8594-e518fff9a8ab.png">

True black theme now looks like this. I had to add a workaround (59c0ca947dfec842e7b24fcddca34538bcc709d2) for the preference activity due to a bug in androidx preference. Can't really find more about it then this answer: https://stackoverflow.com/a/53924161.

Won't close this issue until we have tested in on API 19.

**Comment by michaelschattgen** [comment]
Just found out that the AuthActivity still uses the dark theme style instead of the amoled theme one. Needs a fix.

**Comment by fear-the-beaver** [comment]
Prior the update I had dark theme enabled. After the update it got set to Light. No problems though applying AMOLED black theme.
