### ISSUE TITLE
Authenticator Plus import

### ISSUE THREAD

**Issue by orangenbaumblatt** [beemdevelopment/Aegis#328]
Since I migrated from Authenticator Plus to Aegis, I wrote a little extension to import its encrypted SQLite database to get a glimpse of Android development.
If it sounds useful, I can do a pull request.

**Comment by alexbakker** [comment]
Absolutely! A pull request would be much appreciated.

**Comment by gaia** [comment]
There is no need for extra code.

1) Export the zip from Authenticator Plus (remember the password)
2) Open the zip exported in 1 (you will need the password from #1)
3) In Aegis: Settings>Import from file>Winauth
4) Point to the _accounts.txt_ file you got when you did #2

Voilá.

@alexbakker Authenticator Plus uses the WinAuth format (and/or the WinAuth format is open source).

**Comment by alexbakker** [comment]
@gaia Most users coming from Authenticator Plus will have their backups in the form of a SQLCipher database. We'll have to support that as well.

**Comment by gaia** [comment]
Please do, because the import in the way I described above named every entry "WinAuth"

**Comment by orangenbaumblatt** [comment]
@gaia Good point with the grouping! I didn't even test that, will check it out today and might add it.

**Comment by orangenbaumblatt** [comment]
@alexbakker I have now added the ability to import groups in PR #338

**Comment by alexbakker** [comment]
This is now implemented, thanks a lot @orangenbaumblatt!

**Comment by gaia** [comment]
thanks guys. would it possible to get notified on this thread once this is pushed the play store?

**Comment by alexbakker** [comment]
You can subscribe to releases on GitHub. Once there's a new release, it usually appears on the Play Store a couple of hours after.

**Comment by EvilAaron** [comment]
I am trying to migrate from Authenticator Plus with groups but am unable to find the working method or entry in import list in Aegis settings.

I tried the WinAuth text file method above but that messes up names and groups. Is this rolled out to Playstore version and I'm dumb and can't find it or not live yet?

**Comment by Daniel15** [comment]
Thank you for this!! I've been using Authenticator Plus for many years, but it seems like it's been abandoned by its developer (last update in December 2018). I think I'm going to switch to Aegis instead.
