### ISSUE TITLE
Add quick sorting options

### ISSUE THREAD

**Issue by Mrfiregem** [beemdevelopment/Aegis#33]
I know you can hold and drag entries to sort them, but having an option in the top bar to sort entries would help with longer lists.

This can include normal/reverse alphabetical, date added, list items in groups next to each other or separate, free sorting like what currently exists, etc.

Maybe even have new entries automatically sorted based on what mode you have selected.

**Comment by michaelschattgen** [comment]
Just finished merging my feature branch to the master branch. We currently support the following quick sort methods:

![image](https://user-images.githubusercontent.com/7524012/55295696-690a3f80-5410-11e9-926e-118f35666eb9.png)

The last sorting option you chose will be saved to the preferences so it will use the same sorting method when you start the app again. We will add more sorting options in the future and this feature will be available in the next update we publish on F-Droid and Play Store.

Closing this issue.
