### ISSUE TITLE
[Feature Request]  Security key can be used to unlock Aegis vault

### ISSUE THREAD

**Issue by adrkable** [beemdevelopment/Aegis#336]
As an alternative to passwords and biometric, it would be nice to be able to unlock the vault using a FIDO U2F security key such as NitroKey, Yubikeys, or OnlyKey. Especially interested in NFC support.

**Comment by alexbakker** [comment]
We're interested in having this feature, but it is currently not on the roadmap. Let us know if you'd be interested in working on this.

**Comment by adrkable** [comment]
I code but I'm not a Java developer ...hmm, this feature request might be enough motivation to start.

**Comment by michaelschattgen** [comment]
Closing this issue as we don't have plans to implement this. If someone wants to take responsibility of implementing this, feel free to restart this discussion.

**Comment by bebotette** [comment]
wanted to raise this feature request again. I believe adding another layer of security to aegis would be really nice. Right now, people can get my fingerprint while I'm sleeping, and they can access OTPs afterward. Among other possible cases.
