### ISSUE TITLE
Header: distinguish timer and top panel

### ISSUE THREAD

**Issue by fear-the-beaver** [beemdevelopment/Aegis#34]
In both Dark and Light modes timer indicator has the same color as the top panel:

![Screenshot_20190327-092214_1](https://user-images.githubusercontent.com/46751130/55079426-863ab900-5072-11e9-996e-50b104852ed2.jpg)

Perhaps, it can be green or red (or any other color different from the blue spectrum).

**Comment by michaelschattgen** [comment]
I don't think green or red would look good, would you mind a darker blue? Like the blue in the statusbar.

**Comment by laurentlbm** [comment]
I don't think blue stands out enough. The accent color (red) would be the obvious choice, but yellow might also work.

**Comment by michaelschattgen** [comment]
Alright, thanks for the suggestions. I will try the accent color within a few hours.

**Comment by Avrution** [comment]
I have no bar on mine using either light or dark.  Not sure if it is related to the notch or something else.

**Comment by michaelschattgen** [comment]
@Avrution, can you attach a screenshot please? (Just make sure to censor the names and tokens).

**Comment by michaelschattgen** [comment]
![image](https://user-images.githubusercontent.com/7524012/55109637-8cfb1780-50d6-11e9-93dc-85499cc2739f.png)

The progressbar looks now like this.

**Comment by michaelschattgen** [comment]
Closing this for now. Fixed the issue.
