### ISSUE TITLE
Can't import any QR Codes anymore

### ISSUE THREAD

**Issue by marc0w** [beemdevelopment/Aegis#346]
Info

* __Version__: 1.1.4
* __Source__: F-Droid
* __Vault encrypted: Yes (with biometric unlock)/Yes
* __Device: Xiaomi Mi 9t Pro
* __Android version and ROM: Lineage OS

###### Steps to reproduce

Scan QR-Code, focus QR Code -> Error: Can not read QR Code

###### What do you expect to happen?

Add new Entry to my vault.

###### What happens instead?

Error message appears.

**Comment by alexbakker** [comment]
Which service generated the QR codes you're trying to scan?

**Comment by marc0w** [comment]
Office 365

**Comment by alexbakker** [comment]
You say that scanning any QR code doesn't work. Which other services did you encounter this issue with?

In the case of Office 365, make sure you select "Setup application without notifications" when configuring 2FA. Aegis is not compatible with Microsoft Authenticator QR codes.

**Comment by robashaw21** [comment]
> Info
> 
> * __Version__: 1.1.4
> * __Source__: F-Droid
> * __Vault encrypted: Yes (with biometric unlock)/Yes
> * __Device: Xiaomi Mi 9t Pro
> * __Android version and ROM: Lineage OS
> 
> ###### Steps to reproduce
> 
> Scan QR-Code, focus QR Code -> Error: Can not read QR Code
> 
> ###### What do you expect to happen?
> 
> Add new Entry to my vault.
> 
> ###### What happens instead?
> 
> Error message appears.
> 
>

**Comment by marc0w** [comment]
Now it works. Sorry, my fault! Thanks a lot for fast replies.
