### ISSUE TITLE
No progress bar

### ISSUE THREAD

**Issue by Avrution** [beemdevelopment/Aegis#35]
This is on a Pocophone F1 - screenshot of the top screen

![Screenshot_20190327-220652_Aegis](https://user-images.githubusercontent.com/38819283/55127095-fc740580-50dc-11e9-8631-8b5e4a0eb57b.png)

**Comment by alexbakker** [comment]
Huh, color me confused. I think we're doing something wrong with the styling of the progress bar, as it is also barely visible on KitKat.

**Comment by michaelschattgen** [comment]
@Avrution, could you try to manually add a new entry with a different amount of seconds than your other tokens? This will result in a progressbar on every token/card. Are those invisible as well?

**Comment by Avrution** [comment]
Correct, still all invisible.  I see each line has a bar, but nothing that moves on them.

**Comment by michaelschattgen** [comment]
We published a new version which changes the way progressbars render. It's not fixed or changed specifically for this issue but there is a chance that it's working correctly for you again. Cany you try it out?

**Comment by Avrution** [comment]
No change on my end with the latest build

**Comment by michaelschattgen** [comment]
What Android version are you running? We still haven't found a way to reproduce this.

**Comment by Avrution** [comment]
9.0 on phone and 7.0 on tablet

**Comment by michaelschattgen** [comment]
I just found out that the progressbar bugs out when you set 'Animation duration scale' to 'Off' in your Android settings. Is that the case? Did you by chance disable animations on your devices?

**Comment by Avrution** [comment]
Bingo - that fixes it.  That is one of those first things I disable on all my devices as I really can't stand the extra lag that animations add.  

It seems even changing that to anything but 1.0 causes an issue as well.

Is this something that can be fixed or will it require the animation duration to be enabled?

**Comment by michaelschattgen** [comment]
Good to hear that the animation scale did the trick! I will try to fix this within a couple of hours without requiring you to enable animations.
