### ISSUE TITLE
issuer is universally set to be "WinAuth" upon import despite issuer being present

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#350]
When importing files in WinAuth format,
`otpauth://totp/Faaaaa2?secret=XXXX&issuer=facebook`
The issuer is universally set to be "WinAuth".

**Comment by michaelschattgen** [comment]
This is done because WinAuth doesn't export issuers, 'Issuer' actually doesn't exist in the WinAuth format. I think we should add a new generic importer option for otpauth urls as @alexbakker suggested [here](https://github.com/beemdevelopment/Aegis/issues/138#issuecomment-611617874).

**Comment by alexbakker** [comment]
Agreed. This is working as intended. Selecting WinAuth when importing otpauth URI files was only suggested as a workaround.

**Comment by jidanni** [comment]
Actually, all you need to do, is, if a issuer field is present, then use it. Else, insert w i n a u t h.

**Comment by robashaw21** [comment]
I don't know what I'm doing. I picked up on quite a bit for just a few days. I possibly may not be doing it correctly.

**Comment by robashaw21** [comment]
I have a email I'm trying to recover. I have the password for a Gmail account signing into Microsoft outlook. And it difficult to recover through google. I have the phone the account was last active. The account was just deleted from phone. I can also sign into Facebook but also need a verification code but no longer have the number.

**Comment by jidanni** [comment]
Actually, one of these import methods, or perhaps all of them should be part of a campaign, that says "we always preserve the user's data 100%" 
okay so how to do this?, well, whenever encountering an unknown field in the input URIs, just put it into the Json as a info: sub value even though you don't know what to do with it, currently in 2020.

**Comment by alexbakker** [comment]
@robashaw21 Please don't ask unrelated questions in random issues. If you have a specific support question about Aegis, create a new issue or send us an email.

**Comment by jidanni** [comment]
You could store the unknown fields in e.g., "extra",

```
                "issuer": "Github",
                "icon": null,
                "info": {
                    "secret": "642GK5EROWKUAEBFRH6FWSMM4FRKS5IA",
                    "algo": "SHA1",
                    "digits": 6,
                    "period": 50
                }
                "extra": {
                    "murfelsbug_factor": "low",
                    "expires": 20241122....,
                    "region": 35
                    "security_level": 7,
                    "team": "blue",
                    "rank": "director"
                    }
```
allowing the user to edit them, somewhere in the "Advanced" part of
"Edit profile". So Aegis would be the first(?) app to guarantee it
preserves all the user's data, no matter upon import, export... even
allowing him to edit all of it. Indeed "not only a TOTP 'computer', but also a TOTP editor!"

Wait, maybe warn about keeping [unnecessary data](https://medium.com/crypto-punks/why-you-shouldnt-scan-two-factor-authentication-qr-codes-e2a44876a524) with the codes.
