### ISSUE TITLE
Missing ellipsis for long key upon eyeball press

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#351]
When editing a profile with a long
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
key, push the eyeball button. You will see
`AAAAAAAAAAAAAAAAAAAAAAAAA   [EYEBALL]`
It is missing the ellipsis, 
`AAAAAAAAAAAAAAAAAAAAAAAAA…  [EYEBALL]`
Without the ellipsis we assume the string is only as long as it looks.

**Comment by alexbakker** [comment]
This is how Android EditText's work by default. I can't think of any app that has ellipsis enabled for their EditText's.

**Comment by jidanni** [comment]
Perhaps tell upstream (Android ?) that the user sees plenty of whitespace where an ellipsis would have been, making him think that there is nothing to "ellipse".

**Comment by alexbakker** [comment]
Please file a bug upstream if you'd like to see ``ellipsize`` support in EditText.
