### ISSUE TITLE
Name just becomes user name upon WinAuth import

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#352]
I imported WinAuth string
otpauth://totp/E%E5%93%87%E5%93%87%E5%8F%AB%3Ajidanni?secret=MMMMM
which corresponds to
otpauth://totp/E哇哇叫:jidanni?secret=MMMMM
The result was as if I simply imported
otpauth://totp/jidanni?secret=MMMMM
1. Well if all /.*:/ are stripped, then how am I (jidanni) going to distinguish my Facebook, Twitter, etc?
2. What happened to the E at front.
3. What happened to the 哇哇叫?

**Comment by alexbakker** [comment]
This is a consequence of the way the WinAuth importer works. As said, selecting WinAuth when importing arbitrary otpauth URI files was only suggested as a workaround. We'll address this properly by adding a separate importer for otpauth URI files.
