### ISSUE TITLE
Call 'edit profile' edit site instead

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#353]
![X0](https://user-images.githubusercontent.com/1230959/78996001-3d1eaf80-7b76-11ea-8aac-47400c6d403a.jpg)
Here, at the top, we see it is called "edit profile". That sounds more like it  refers to our own personal profile. So maybe call it "edit entry" or 'edit site' instead.

**Comment by alexbakker** [comment]
We'll change it to "Edit entry", as that's what we call it everywhere else in the app.
