### ISSUE TITLE
In the menu, instead of just saying filter, say filter by group.

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#356]
In the menu, instead of just saying _filter_, say _filter by group_.
Why? Because half of the app is talking about _filter_, the other half talking about _group_, and nowhere do we (non smart people) figure out the connection.

**Comment by alexbakker** [comment]
That would make the menu look a bit odd. We'll keep it the way it is now. I'm sure people will be able to figure it out.
