### ISSUE TITLE
Metadata fix path

### ISSUE THREAD

**Issue by licaon-kter** [beemdevelopment/Aegis#36]
from `metadata/en-US`
to `metadata/android/en-US`

Ref: https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#changelogs-whats-new

Ref: https://gitlab.com/fdroid/fdroiddata/issues/1579

**Comment by Rudloff** [comment]
Sorry but I think @licaon-kter was wrong. The path needs to be either `fastlane/metadata/android/` or simply `metadata/`. (See [here](https://gitlab.com/fdroid/fdroidserver/blob/d45431aa9ebc05cab96e0f9c196771366854b3fb/fdroidserver/update.py#L882))

Also, I think your files should end with `.txt`: https://gitlab.com/fdroid/fdroidserver/blob/d45431aa9ebc05cab96e0f9c196771366854b3fb/fdroidserver/update.py#L909
(Which would explain why the screenshots worked but not the description.)

**Comment by alexbakker** [comment]
Fixed. Thanks.

**Comment by licaon-kter** [comment]
You are right, I glanced over the fastlane folder, sorry for the mixup.

**Comment by alexbakker** [comment]
No worries! Let's hope F-Droid likes the format better this time.
