### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [beemdevelopment/Aegis#360]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by alexbakker** [comment]
Yes. I had forgotten about this, thanks for creating an issue for it. We should rebase #112 and merge it.

**Comment by Neustradamus** [comment]
@alexbakker, @michaelschattgen: Thanks a lot!
But not complete: https://github.com/beemdevelopment/Aegis/search?q=spongycastle&unscoped_q=spongycastle
