### ISSUE TITLE
Tap to Reveal Tokens Enabled by Default and Better Placeholder Name

### ISSUE THREAD

**Issue by lynn-stephenson** [beemdevelopment/Aegis#361]
Currently Aegis does not hide tokens by default. You have to go into the settings to enable it. Less technical users are less inclined to lock down their app.

I do not want the UX to be ruined or to make the application difficult to use. But Aegis is tainted as a secure 2FA app, and I do not think it will hurt to have tokens hidden by default.

To reduce confusion: "Tap to Reveal", or "Tap to Reveal Token" is a better placeholder than "Hidden".

**Comment by alexbakker** [comment]
Thanks for the suggestion, but we're going to keep the default settings as they are right now. Users who actually have a threat model that requires this feature will look for and find this option in the settings menu.
