### ISSUE TITLE
Entry is duplicated and App Crashes on using our own image.

### ISSUE THREAD

**Issue by vishalnandagopal** [beemdevelopment/Aegis#363]
* __Version__: 1.1.4
* __Source__: F-Droid
* __Vault encrypted:__ Yes (with biometric unlock-No)
* __Device:__ Lenovo Tab 4
* __Android version and ROM:__ Stock Android 8.1

Steps to reproduce
1. Open QR Code scanner and scan any 2FA QR Code. The options menu pops up after successfully scanning it (the one with Account, issuer, SHA-1, etc)
2. Click on icon (the first letter of issuer by default I guess ) and then proceed to insert user icon. from local storage.
3. Click the tick mark and click save. 

What do you expect to happen?
1. Only one entry must be produced/made.

What happens instead?
1. 2 entries are made

The 2 entries are made irrespective of whether you actually select a icon from local storage. That is, even if you go back without selecting an icon, and use default icon, 2 entries are made. If you use a icon from your storage, it makes 2 entries. (I use the icon pack mentioned at the bottom of your README.md). 2 entries are NOT made, when selecting icon by editing the entry, after it has been made.

**IMPORTANT NOTE: Also, the app completely crashes multiple times when you attempt to delete the 2nd entry, after deleting the 1st entry produced by the above means(manual image selection one).** 

(Don't know if crash is only for deleting entries produced in above mentioned way, or app crashes whenever you delete 2 entries one after the other. Don't have QR codes lying around to test this for normal entries, and am definitely not experimenting on my actual entries)

**Comment by alexbakker** [comment]
Thanks for the detailed report. This could explain one of the crashes we've been seeing in the Play Console that we haven't been able to track down yet.

That said, I am unable to reproduce this unfortunately. Is the duplicate entry gone after restarting the app?

**Comment by vishalnandagopal** [comment]
Yes. The entry is deleted after just leaving the app. No need to even restart or lock vault. That is probably why the app crashes on deleting the 2nd entry, since it doesn't exist properly.

**Comment by alexbakker** [comment]
I can reproduce this bug if I enable "Don't keep activities". Looking into it now.
