### ISSUE TITLE
"Copied" animation is triggered when selecting items

### ISSUE THREAD

**Issue by orangenbaumblatt** [beemdevelopment/Aegis#367]
###### Info

* __Version__: Current version from master branch (especially after merging #323)

###### Steps to reproduce

Long-press an item to enter selection mode. Then select/deselect items with a single-tap.

###### What do you expect to happen?

Only selecting/deselecting the items.

###### What happens instead?

The "copied" text appears but the actual code isn't copied (and shouldn't while selecting).

###### Additional info

It seems that in the changes introduced in #323, it isn't checked whether items are tapped to select or to actually copy the code.

**Comment by michaelschattgen** [comment]
Thanks for your contribution! Just pushed an (easy) fix and created a pull request.
