### ISSUE TITLE
Settings to change "Code display format"

### ISSUE THREAD

**Issue by l-marchesi** [beemdevelopment/Aegis#373]
Hi

I am a user of "Authenticator+" but since recently the developer seemed to go away, I was looking for open source alternatives - so I found this awesome project :smile: 

There is actually just one small thing I am missing: I would like to read the codes in group by 2 digits, e. g. "12 34 56" instead of a group by 3 digits like "123 456".

Therefore my proposal would be a setting, where the user can decide about the format of the code.

If you would like, I can try to implement it :smiley:

**Comment by michaelschattgen** [comment]
Good to hear that you like this project! I think this is a good suggestion and we like to see people contribute to our app.

What do you think @alexbakker?

**Comment by alexbakker** [comment]
This is fine with me! I do think we should be careful to not introduce an infinite amount of small customization options like this, though.

**Comment by l-marchesi** [comment]
Implemented the change - feel free to review and give feedback 😄

**Comment by alexbakker** [comment]
abe78370ea41e68ad4b566ab76b3ddcb8b1c077f
