### ISSUE TITLE
QR code scanning from EA / Origin Store Account not possible

### ISSUE THREAD

**Issue by Stefan1200-de** [beemdevelopment/Aegis#376]
###### Info

* __Version__: 1.1.4
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Samsung Galaxy S20
* __Android version and ROM:__ Android 10 (1. April 2020)

###### Steps to reproduce

Activate two factor authentication at the Origin / EA account (https://myaccount.ea.com/). Try to scan the QR code with the Aegis App.

###### What do you expect to happen?

Scanning the QR code successful.

###### What happens instead?

While scanning the QR code it just shows an error message: "An error occurred while scanning QR code". Scanning with the Google Authentificator is working. But I was able to scan the QR code from other accounts (Uplay, Google, etc.).

###### Log

Where is a log?

**Comment by alexbakker** [comment]
Works for me. Are you sure you're not trying to scan the QR code that has a link to the Google Authenticator app in the Play Store? The QR code shown in the next step is the one you want.

**Comment by Stefan1200-de** [comment]
Oh, sorry. I remember that I was fallen into this trap over two years ago. Of course, if works. Great app :)

**Comment by sarvagya1901** [comment]
Bro I still can't access the code. It shows 'invalid code'

**Comment by alexbakker** [comment]
"Invalid code" is not a sentence Aegis would ever display. Can you be more specific?

**Comment by Stefan1200-de** [comment]
> Bro I still can't access the code. It shows 'invalid code'

Don't scan the first QR code, which will be displayed, click on Continue first.
