### ISSUE TITLE
Auto-lock if the app is closed or after a minute

### ISSUE THREAD

**Issue by TobiasDev** [beemdevelopment/Aegis#38]
I feel like the app should "auto" lock when you close it, or when you don't open it for a minute or 30 seconds. At the moment, if I don't press the lockpad button it stays open forever.

**Comment by michaelschattgen** [comment]
Thanks for creating this issue! However, it's a duplicate of #7.

**Comment by michaelschattgen** [comment]
Duplicate of #7

**Comment by TobiasDev** [comment]
Sorry... I really suck at searching, I thought I looked at the issues to make sure I didn't create a duplicate.

**Comment by michaelschattgen** [comment]
No problem! Closing this issue now.
