### ISSUE TITLE
Wrong generationed code

### ISSUE THREAD

**Issue by andrKonan** [beemdevelopment/Aegis#385]
###### Info

* __Version__: 1.1.4
* __Source__: F-Droid
* __Vault encrypted__: both
* __Android version and ROM__: 4.4.2

###### Description or problem
Secret code generator isn't works properly to GitHub and Discord(don't check other).
In FreeOTP code generates correctly but in Aegis code varies from 1 to 6 digits.

###### Addition
Not only Aegis generate code incorrect but andOTP too especially because it generates the same codes.

**Comment by alexbakker** [comment]
This is almost certainly caused by the system time of your device not being in sync. Please check your settings and ensure you've enabled automatic time synchronization.

**Comment by andrKonan** [comment]
Then why FreeOTP works properly?

**Comment by alexbakker** [comment]
Hmm. For a second I thought FreeOTP had time synchronization built-in, but that's Google Authenticator. Which device and ROM are you running Aegis on?

**Comment by andrKonan** [comment]
I use default android 4.4.2 with root and without GAps

**Comment by michaelschattgen** [comment]
How did you get the entry in both Aegis and FreeOTP? Did you just scan the QR code multiple times or did you use the export/import features of both apps?

**Comment by alexbakker** [comment]
> I use default android 4.4.2 with root and without GAps

And what device?

**Comment by andrKonan** [comment]
I scan one qr code.(I will try to export)
Device is Fly IQ4415 Quad

**Comment by alexbakker** [comment]
Thanks for the additional information. It's strange. I took a look at the code of FreeOTP, and as far as I can tell it generate codes in exactly the same way Aegis does. The logic is copied straight from the HOTP RFC.

Could you scan the QR code below and create a screenshot of Aegis showing the code it generated (disable "Screen security" in options first) and report the **exact** time (the time on your device, seconds included, in UTC) when the screenshot was taken?

![](https://alexbakker.me/u/cafonm61qc.png)

**Comment by andrKonan** [comment]
Can you explain please how can I catch seconds?

**Comment by alexbakker** [comment]
There should be an option in Android to show seconds in the status bar. If not, forget about that part, a screenshot with the time as hours:minutes is also fine.

**Comment by andrKonan** [comment]
In the bar firs left numbers are seconds(found one app)
![Screenshot_2020-04-29-12-35-03](https://user-images.githubusercontent.com/52403327/80587009-21d8ee80-8a16-11ea-9e40-de5a10b514b0.png)
![Screenshot_2020-04-29-12-35-39](https://user-images.githubusercontent.com/52403327/80587011-22718500-8a16-11ea-95c1-1c821ad7b512.png)

**Comment by andrKonan** [comment]
FreeOTP(can't make screenshot): 067856
Aegis: 068337
12:48:50

**Comment by alexbakker** [comment]
Thanks for following up. We really do appreciate you going through these tedious troubleshooting steps with us. I used PyOTP as a reference to generate the correct codes for the timestamps that you gave.

```python
>>> otp = pyotp.TOTP("PTGYCJ6L6WTHCJNGCLV65AWCUE")
>>> otp.at(1588156501) # 12:35:01 +2
'972651'
>>> otp.at(1588156537) # 12:35:37 +2
'385055'
>>> otp.at(1588157330) # 12:45:50 +2
'067856'
```

Meanwhile, according to your screenshots and comment, Aegis generated the following codes:

```
973435
385103
068337
```

It looks like only the first 2-3 digits of the code are correct in Aegis, while FreeOTP generated the correct code somehow. This seems to only happen on your device though. I tried this in an emulator running Android KitKat, and Aegis generated the correct codes for all three timestamps.

I really don't know what's going on here.

**Comment by andrKonan** [comment]
Then may be my version of android or application doesn't the same.

**Comment by adityaputra** [comment]
Bumping this issue under Aegis version 2.0 for gitlab.com OTP. Originally imported all my OTP codes from Authy and so far everything works fine except gitlab.com.
I also have tried to re-register 2FA manually for that gitlab.com and the code is still always failing. Anyone has similar issue?

**Comment by Guarmanda** [comment]
I have last aegis version and it doesn't seems to work with google 2fa, the generated code is wrong. 
LineageOS android 15, pixel 8 pro, aegis 3.3.4
