### ISSUE TITLE
Add folders 

### ISSUE THREAD

**Issue by Gabe-hrh** [beemdevelopment/Aegis#387]
I've been using the app for quite some time and as I've used it I've really garnered quite the collection of 2fa codes. It would really be nice to have folders to easily sort out all of my codes.

**Comment by agauvrit-tis** [comment]
Yes that would be a nice improvement as I would like my Pro and Personnal codes to be clearly organized

**Comment by michaelschattgen** [comment]
Closing this issue as we don't have plans to implement this. We do have plans to support labels instead of groups to make the vault easier to organize.
