### ISSUE TITLE
Smaller boxes and text

### ISSUE THREAD

**Issue by TobiasDev** [beemdevelopment/Aegis#39]
I would love to be able to make the boxes, images, text, etc. a bit smaller. At the moment I just feel like everything is incredibly big. Would it be possible to add a size setting? To jump between. I still want to see the images though, so maybe just a smaller image, since the image is way faster to recongnise what the code is for. :)

**Comment by michaelschattgen** [comment]
Great idea! A compact mode is definitely worth adding. Removing the space between the cards will also help.

**Comment by michaelschattgen** [comment]
This is how we think compact mode should be like. Is this what you were looking for? We expect to make some minor changes to this view in the near future + maybe add some more viewmodes.

![image](https://user-images.githubusercontent.com/7524012/55362289-d03ff680-54d9-11e9-8d72-772185e42585.png)


Compact mode will be available in the next version we publish to F-Droid and Play Store in the next few hours.

**Comment by TobiasDev** [comment]
I was thinking more of the same whitespace between, but smaller boxes. Though that does look good as well. :)

**Comment by michaelschattgen** [comment]
Alright, I will add a 'Smaller'-mode today which uses the sizes of the screenshot above but will include the same whitespace as the normal mode. Thanks for your suggestion!

**Comment by michaelschattgen** [comment]
This is what 'Small mode' looks like. It this what you meant?

![Screenshot_1554202232](https://user-images.githubusercontent.com/7524012/55397283-65240d80-5535-11e9-8f28-beed50c4c801.png)

**Comment by TobiasDev** [comment]
Yup! :) That looks awesome.
