### ISSUE TITLE
Fingerprint Unlock Does Not Work On OnePlus 7 Pro

### ISSUE THREAD

**Issue by tehSIRius** [beemdevelopment/Aegis#393]
###### Info

* __Version__: 1.1.4
* __Source__: Google Play
* __Vault encrypted:__ Yes with biometrics
* __Device:__ OnePlus 7 Pro
* __Android version and ROM:__ OxygenOS 10.0.5.GM21BA (Android 10)

Aegis can't be unlocked with fingerprint sensor on the OnePlus 7 Pro. Unlocking with password is working fine. Restarting the device does not fix the issue.

Aegis was installed on Android 9 before update to Android 10. The vault was imported from Nokia 6.1.

###### Steps to reproduce

1. Setup Aegis with biometric unlock
2. Lock the vault and exit app
3. Open Aegis and try to authenticate with fingerprint
4. Aegis says Couldn't unlock vault: Incorrect password. Make sure you didn't mistype your password
5. Press OK and try to authenticate with fingerprint again
6. Aegis crashes

###### What do you expect to happen?

Authenticate with fingerprint

###### What happens instead?

Aegis does not unlock and crashes.

**Comment by alexbakker** [comment]
Thanks for the report. Did fingerprint authentication work previously? If so, did this start happening after you made changes to the security settings of your device? Can you try reconfiguring biometric authentication in Aegis and see if that fixes it?

**Comment by tehSIRius** [comment]
It worked before when I was setting up. I have probably turned off the face unlock after I setup Aegis and that might have broken it. I have turned the face unlock on, turned off biometrics in Aegis, turned face unlock off and re-enabled biometrics in Aegis and they started to work again.

Weird thing is that I saw a message saying Unlocking the vault before the error with wrong password came up. Hope that helps.

**Comment by alexbakker** [comment]
Thanks, that explains it. When you make changes to the security settings of your device, keys in the Android Keystore are invalidated, and Aegis' biometric authentication needs to be reconfigured. Some devices don't properly report that this invalidation happened, so Aegis gets confused about what went wrong. We'll have better error reporting once #378 is merged.
