### ISSUE TITLE
Changes to UI 

### ISSUE THREAD

**Issue by KibaNoOu** [beemdevelopment/Aegis#397]
Hi All, 
A new version of Google Authenticator has been released and IMHO it's really intuitive and you can clearly see the Account name with the matching code.
Would be possible to invert the position of the Code and the Account name and make it bigger?

![GAuth-UI](https://user-images.githubusercontent.com/11923117/81233550-25acd800-8ff7-11ea-9410-d37e56a27968.jpg)

**Comment by michaelschattgen** [comment]
Now that I think about it, it looks more intuitive to have the name above the code since that's what users are scanning for first. This is a big visual change so we have to make sure if this is what we want.

What do you think @alexbakker?

**Comment by alexbakker** [comment]
I think this is certainly something we can play around with. We haven't made any changes to this since the first release of Aegis, if I recall correctly. This change might make the code too small in the "small" and "compact" view modes, though.

**Comment by michaelschattgen** [comment]
I just made a pull request which makes the entries look like this:

![image](https://user-images.githubusercontent.com/7524012/81477189-b281ac80-9216-11ea-82b0-05af1b48a616.png)

Is this what you had in mind?

**Comment by KibaNoOu** [comment]
Yes! If I can advise a small change to further increase the readability, I would increase the font size of both the Account and the Title to something like 18px I don't know how much is now but it seems like 13px.

**Comment by michaelschattgen** [comment]
I used 16sp in the previous screenshot. I now set it to 18sp which will look like this:

![image](https://user-images.githubusercontent.com/7524012/81511374-4e93dc80-9319-11ea-90ee-89a9f2802101.png)

This looks a bit odd but that might be just me. I'm not sure how I feel about this but I think 18sp is the largest fontsize which will look good in Aegis.

**Comment by KibaNoOu** [comment]
> I used 16sp in the previous screenshot. I now set it to 18sp which will look like this:
> 
> This looks a bit odd but that might be just me. I'm not sure how I feel about this but I think 18sp is the largest fontsize which will look good in Aegis.

IMHO it's a lot more readable with that settings, maybe it's the bold font that is too strong?

**Comment by michaelschattgen** [comment]
I'm closing this issue since we already included the overhaul which solves these issues in our latest release (1.2)
