### ISSUE TITLE
Invalid Backup is created 

### ISSUE THREAD

**Issue by vishalnandagopal** [beemdevelopment/Aegis#401]
Whenever I try to export, a backup of 0 bytes is created.

I believe this is related to the last issue I posted, since the app has been crashing a lot since then. I can't revert to default images, use new images, or backup to new device.
Last Issue - #363

**Comment by alexbakker** [comment]
Can you obtain logs for the crashes you're encountering (https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb)? For the 0 byte backup file issue, see: https://github.com/beemdevelopment/Aegis/issues/362, it may be related.

**Comment by alexbakker** [comment]
Do you have the "Don't keep activities" option enabled in Developer Options?

**Comment by vishalnandagopal** [comment]
Sorry for not replying soon.
Yes. i had enabled that option on my device in developer options. 
Also, I tried obtaining logs, but the couldn't get it. There was no output in the terminal.

**Comment by alexbakker** [comment]
No worries. Thanks for reporting back.

This issue will be fixed by #410. The other issue you filed is similar (#363), but I haven't gotten to fixing that one yet. Both issues can be worked around by disabling that "Don't keep activities" option. Is there any particular reason why you have that option enabled?

**Comment by vishalnandagopal** [comment]
I enabled the option in developer options, for better battery. It supposedly works.
My old device had extremely less RAM and battery. So had to enable it. No other choice.
