### ISSUE TITLE
Password reminder happens too often

### ISSUE THREAD

**Issue by xPaw** [beemdevelopment/Aegis#402]
Looking at the code it asks to enter the password every 7 days, which is rather aggressive. And when this is triggered it breaks the fingerprint unlock as you have to either enter the password, or tap the biometric unlock button which adds an unnecessary step.

**Comment by alexbakker** [comment]
How often would you consider reasonable? You can disable the reminder in settings, if you'd like to get rid of it entirely.

**Comment by xPaw** [comment]
Not sure what a reasonable timeframe is, but the other apps that I have seen with password reminds didn't have it happen this often.

**Comment by alexbakker** [comment]
How does once every 30 days sound?

**Comment by xPaw** [comment]
Should be fine.
