### ISSUE TITLE
Authenticator Plus import without depending on SQLCipher

### ISSUE THREAD

**Issue by orangenbaumblatt** [beemdevelopment/Aegis#404]
As mentioned in #388 the possibility of importing encrypted Authenticator Plus databases is bloating the APK too much. This is due to the SQLCiper library shipping binaries for different architectures.

It is possible to use the export functionality to generate an encrypted ZIP archive which contains a plain list of URLs in the standard format described in #138. From here we have two possibilities:

- Letting the user extract the archive and then import using the "Plain text" import from #359. Depending on the default file manager the user might need to install one with support for encrypted archives (the Android "Files" app can't do that, whereas OnePlus's file manager can).

- Extract the archive for the user which might sadly generate another dependency, as extracting encrypted archives seems not possible with native tools.

I personally would opt for the first option, as both don't support keeping categories and implementing the whole extracting stuff just doesn't feel right, as most of the necessary import logic is already there.

**Comment by alexbakker** [comment]
Thanks for writing this up. I would not have too much of an issue with adding a dependency to zip4j, as we may need it for some other planned features as well anyway. It's also much smaller in size than SQLite. I've submitted a PR to make this change: #407.

Sorry that we'll end up removing your work. We should have caught the massive change in APK size earlier.

**Comment by orangenbaumblatt** [comment]
No problem. Thanks for already implementing it.
