### ISSUE TITLE
Bottom Navigation & Auto Dark Mode

### ISSUE THREAD

**Issue by ncodee** [beemdevelopment/Aegis#408]
As devices are getting bigger and bottom navigation becoming a trend, it would be ideal if you could move the top navigation to the bottom as a usability improvement.

Also, if you could add Auto dark mode support for Android 10, that would be great.

Thanks

**Comment by michaelschattgen** [comment]
Thanks for your feature requests. Please make sure to limit 1 feature request per issue so we keep the issues board clear. Auto dark mode was already implemented by @Timbals in #369 and is available in the next release.

As for the bottom navigation; we've tried a bottom navigation multiple times but it makes Aegis lose its look & feel which I don't think is something we want now. We might want to try this again but it's not high on our list of priorities.

**Comment by michaelschattgen** [comment]
Closing this issue as we don't have plans on implementing this anytime soon. As said auto dark mode is already implemented and released.
