### ISSUE TITLE
Logo Library

### ISSUE THREAD

**Issue by ncodee** [beemdevelopment/Aegis#409]
Would be great if Aegis could automatically pull the logos for each authentication entry, or have the ability to manual apply common logo's in-app like Authy offers.

Thanks

**Comment by ukanuk** [comment]
See existing discussion on this at #63, #134, #221, [krisu5/aegis-icons](https://github.com/krisu5/aegis-icons), and [Aegis Icons FAQ](https://github.com/krisu5/aegis-icons/blob/master/FAQ.md#these-icons-arent-integrated-in-the-app)

**Comment by ncodee** [comment]
Hi, thanks

> See existing discussion on this at #63, #134, #221, [krisu5/aegis-icons](https://github.com/krisu5/aegis-icons), and [Aegis Icons FAQ](https://github.com/krisu5/aegis-icons/blob/master/FAQ.md#these-icons-arent-integrated-in-the-app)

I'm aware of this, but as originally stated, it would be nice to have it integrated into the app itself.

**Comment by alexbakker** [comment]
We don't have plans to include icons with the app, but icon packs will soon be supported. See #509.
