### ISSUE TITLE
Add options to hide issuer (and icon?)

### ISSUE THREAD

**Issue by ukanuk** [beemdevelopment/Aegis#413]
There is already an option to hide/show the account name. May we get an option to hide the code issuer? I have icons for all my codes from [aegis-icons](https://github.com/krisu5/aegis-icons), and the issuer just takes up valuable extra screen real estate.

Some users might theoretically want an option to hide the icon, too. For example, maybe they're coming from Google Authenticator which has no icons, and dislike the look of Aegis' default icons but do not want to hassle with adding a custom icon for each code.

Here's a mockup of two existing layouts, and how it could look with both issuer and account name hidden (the reduced vertical spacing is from removing the account/issuer but maintaining top and bottom whitespace margins).

Modified layout from #397
![image](https://user-images.githubusercontent.com/59303202/81760417-16032700-9502-11ea-9702-ec689278511c.png)

Modified layout of my current setup
![image](https://user-images.githubusercontent.com/59303202/81761531-21a41d00-9505-11ea-8f8d-7e2aa33a2867.png)

**Comment by michaelschattgen** [comment]
Closing this issue as we don't have plans on implementing this. We don't want to support an endless amount of customization options. We also don't want our users to rely on the icons since future code changes might change the way Aegis sorts the entries for example.
