### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by johnbrz** [beemdevelopment/Aegis#414]
why is the application not updated since January if patches and new functions have been added since then?

Shouldn't there be a more flexible update cycle?

**Comment by alexbakker** [comment]
We release a new version when we think the whole package of features and bug fixes is stable enough to release. There is no strict update cycle, so it couldn't be more flexible than it is now.

The upcoming release had taken longer than usual, but we'll probably move back to more regular updates after that. We've been planning to do a beta release for a while and it'll probably happen this week.
