### ISSUE TITLE
First time setup does not require confirming password if "show password" box is checked

### ISSUE THREAD

**Issue by lwolff** [beemdevelopment/Aegis#415]
First time setup does not require confirming password if "show password" box is checked

###### Info

* __Version__: 1.14
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Samsung Galaxy S10e, SM-G970U
* __Android version and ROM:__ Android 10, stock ROM

###### Steps to reproduce

1. Fresh install of app
2. Enable biometric unlock (fingerprint). Note: I did not test this without enabling biometric unlock
3. Type a password and click "show password"
4. Click enter or next without confirming password

###### What do you expect to happen?

A prompt for confirming the password would be expected here.

###### What happens instead?

No prompt, user is taken directly to the main page of the app

**Comment by alexbakker** [comment]
Duplicate of #309.
