### ISSUE TITLE
Option to backup to Google Drive/OneDrive/Other Cloud Storage

### ISSUE THREAD

**Issue by DiljotSG** [beemdevelopment/Aegis#42]
As the title says, this feature would provide for peace of mind to users of the application, in addition to exporting to the phone's local storage. 👍

**Comment by alexbakker** [comment]
I would strongly prefer to keep syncing to cloud storage providers outside of the scope of Aegis. It would introduce quite a bit of complexity, especially if we need to support everyone's favorite provider. We would also have to introduce proprietary dependencies in some cases (like Google Drive), which makes this a non-starter, in my opinion.

Once #18 is implemented, you could simply have an external app watch the Aegis folder and let it do the sync for you. Apps like Dropsync, FolderSync and Syncthing come to mind. Another option could be to support doing backups with Tasker.

Also, if you're logged into your Google account on your device, you could make use of Android's built-in Auto Backup feature. I would have to check whether we need to do anything special on our end to support that.

**Comment by DiljotSG** [comment]
@alexbakker Fair point!

**Comment by RafhaanShah** [comment]
> 
> Also, if you're logged into your Google account on your device, you could make use of Android's built-in Auto Backup feature. I would have to check whether we need to do anything special on our end to support that.

So does the app currently backup the database using the standard Android backup mechanism? Because I noticed in the manifest you have set
`android:allowBackup="false"` and as I understand [from here](https://developer.android.com/guide/topics/data/autobackup), it needs to be true to use the system backup?

**Comment by PopeRigby** [comment]
> It would introduce quite a bit of complexity, especially if we need to support everyone's favorite provider.

If you use WebDAV, I believe most providers support that. It shouldn't be too complex. [Joplin](https://github.com/laurent22/joplin) does it.

**Comment by alexbakker** [comment]
We're continuing this discussion in #258.
