### ISSUE TITLE
Unable to restore backup

### ISSUE THREAD

**Issue by temp-strongthany** [beemdevelopment/Aegis#420]
###### Info

* __Version__: 1.1.4
* __Source__: GooglePlay
* __Vault encrypted:__ Yes (with biometric unlock) Yes
* __Device:__ LG G6
* __Android version and ROM:__ Android 9 & VS98830a

###### Steps to reproduce

A detailed list of reproduction steps.

###### What do you expect to happen?

* Unable to unlock using biometrics
* Add new fingerprint to allow finger to be read
* open app
* informed biometrics have changed and forced to use password.

I have an encrypted backup of database, though I do not know the password for that one either. Is there a tool I could use to get back in? I know roughly the parameters for what my password was so I could restrict it down to that and make it more feasible for me to get in.

Thank you.

**Comment by alexbakker** [comment]
As you've discovered, if you've forgotten exactly what your password is, there is no way to obtain the contents of the vault. If you still remember your password for the most part, you could try to brute force your way in. The vault format is documented here: https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md#format
