### ISSUE TITLE
Password strength indicator when signing up

### ISSUE THREAD

**Issue by shermansiu** [beemdevelopment/Aegis#421]
It would be great to see the strength of your password as you're creating a password for the Aegis vault! This can deter users from using weak passwords for their vaults.

**Comment by alexbakker** [comment]
Sounds like a good idea to us! Dropbox has a nice library for this that we could use: [zxcvbn](https://github.com/dropbox/zxcvbn). It's probably better than anything we can come up with ourselves. I think there are some Java implementations of it as well.
