### ISSUE TITLE
Navigation Bar Color White?

### ISSUE THREAD

**Issue by DaVoodoo** [beemdevelopment/Aegis#422]
The Navigation Bar Color stays white even in **Dark** and **Amoled** mode although the phone is in _**dark mode**_. Other apps have a Dark  Navigation Bar. Can this be fixed? (See screenshots.)

Aegis:
<a href="https://imgur.com/DoAce3A"><img src="https://i.imgur.com/DoAce3Al.png" title="source: imgur.com" /></a>

Gmail:
<a href="https://imgur.com/TSFvQBw"><img src="https://i.imgur.com/TSFvQBwl.png" title="source: imgur.com" /></a>

**Comment by alexbakker** [comment]
Please fill out the bug report template.

**Comment by DaVoodoo** [comment]
Done. 

Sorry, was not sure whether it was a bug or an enhancement.
