### ISSUE TITLE
Generate QR Codes for Export

### ISSUE THREAD

**Issue by squabbi** [beemdevelopment/Aegis#424]
Usually I like adding OTPs into Aegis on my Android phone, but I would have to copy the tokens to import them to another app (say on iOS).

Having an option to export as QR codes or to view a particular entry’s QR code to quickly scan with another device would be neat. 

I can kind think of this as a security issue, but I’d like to hear what you think of this.

**Comment by DaVoodoo** [comment]
I like this idea.
