### ISSUE TITLE
App starts with white screen

### ISSUE THREAD

**Issue by astarq** [beemdevelopment/Aegis#426]
When opening the app the screen is white, then it changes to the applied theme. (Amoled in my case). Maybe because, while my phone has a native dark theme, it's different from the one bundled with android 10.

This isn't exactly a bug, but surely it should be fixed?

Device: Samsung Galaxy S8+, Android 9

**Comment by DaVoodoo** [comment]
Just noticed the same on my S10e.

**Comment by michaelschattgen** [comment]
If you have selected system default as theme, Aegis now starts with a dark screen. Can you confirm this for us?

**Comment by astarq** [comment]
It does yes!
