### ISSUE TITLE
Can't change entry icons

### ISSUE THREAD

**Issue by pudup** [beemdevelopment/Aegis#427]
Trying to change icon via the standard method has a menu show up telling me if I have "No app that can perform this action"

My phone doesn't have the standard gallery installed but instead has simple gallery. The default file manager is however installed as well as MaterialFileManager. Running LiquidROM Pie.

**Comment by pudup** [comment]
![Screenshot_Android_System_20200521-234943](https://user-images.githubusercontent.com/35901162/82592056-d1c1f780-9b8f-11ea-88cb-392f05970a78.png)


Here's a screenshot

**Comment by alexbakker** [comment]
I installed Simple Gallery, and it does show up as an option next to the regular gallery app on my device.

![Screenshot_20200522-082810](https://user-images.githubusercontent.com/2387841/82638145-85fe6500-9c06-11ea-8231-6e298d72cfec.png)

**Comment by pudup** [comment]
That's strange. I'll try installing  photos.

**Comment by pudup** [comment]
Google photos doesn't show up either. Must be a problem specific to my setup. I'll see what I can do.

**Comment by pudup** [comment]
I couldn't figure it out. I imagine it's probably related to having the stock gallery removed.

For now I used another phone to add icons.
