### ISSUE TITLE
Thanks for submitting the first translation! A small part seems to be missing though:

### ISSUE THREAD

**Issue by ferhadnecef** [beemdevelopment/Aegis#43]
Thanks for submitting the first translation! A small part seems to be missing though:

```xml
<string-array name="authentication_methods">
    <item>Нет</item>
    <item>Пароль</item>
    <item>Отпечаток пальца</item>
</string-array>
```

Other than that, this looks good to me.

_Originally posted by @alexbakker in https://github.com/beemdevelopment/Aegis/pull/41#issuecomment-478269282_

**Comment by michaelschattgen** [comment]
Thank you very much for translating our app! I will add these to the strings file.
I just added: 

- Issuer (A to Z)
- Issuer (Z to A)
- Account (A to Z)
- Account (Z to A)
- Custom

Would it be possible for you to translate these as well? Thanks!
