### ISSUE TITLE
Aegis improvements and theme bug.

### ISSUE THREAD

**Issue by gohanko** [beemdevelopment/Aegis#447]
### Improvement
- Option to allow unlock methods to be shown automatically. E.g if user choose biometrics, the fingerprint prompt is shown if password, the keyboard is shown.
- Option to turn off password reminder.

### Theme bug in Amoled dark mode.
- The password reminder has the same background color as the main activity. Sometimes users are confused because they don't realize the "Password" and "Biometrics" button is behind that reminder. This led to user thinking the ability to use biometrics doesn't exists even though they have set it up in the app.

### Note
I can work on these features, but I want to know what people think.

**Comment by alexbakker** [comment]
>  E.g if user choose biometrics, the fingerprint prompt is shown if password, the keyboard is shown.

This is already the case, unless the password reminder is shown. Does this not work for you?

> Option to turn off password reminder.

This already exists.

> This led to user thinking the ability to use biometrics doesn't exists even though they have set it up in the app.

There's already a proposal for this: #383.

**Comment by gohanko** [comment]
That was my bad. I did not check properly. Seems like I missed the password reminder option. Disabling that fixes a lot of stuff.
