### ISSUE TITLE
Support importing from FreeOTP+

### ISSUE THREAD

**Issue by schneekluth** [beemdevelopment/Aegis#45]
Import json backup from FreeOTP+ is not possible.

**Comment by alexbakker** [comment]
That's correct. Importing from FreeOTP+ is not supported yet.

**Comment by alexbakker** [comment]
We'll repurpose this issue to track adding support for this.

**Comment by GR412** [comment]
I'd also like to see this as I have a FreeOTP+ JSON backup file that I would like to import in to this app.
