### ISSUE TITLE
Feature request: remove duplicate entries

### ISSUE THREAD

**Issue by ElTopo** [beemdevelopment/Aegis#453]
Hello, 

I am currently using Aegis 1.1.4 from Google Play Store.

Recently I found that after exporting and importing data between my Android devices, there are duplicate entries that appeared displaying exactly the same codes.

Here's a screenshot showing duplicate entries:
![Screenshot_20200604-124627](https://user-images.githubusercontent.com/217195/83805308-7d754800-a664-11ea-897c-880a8e39c063.png)

Please add a tool to remove duplicate entries and keep just one for each account.

Thanks.

**Comment by alexbakker** [comment]
Would #276 work for you?

**Comment by rnc** [comment]
@alexbakker I would agree with @ElTopo . If I import my latest FreeOTP+ backup I get duplicate entries - a merge would be really useful here.

**Comment by alexbakker** [comment]
We think that an automatic cleanup of duplicates is too sensitive to errors. We're considering doing some duplicate detection and displaying a warning in the import view if any duplicates are found.

**Comment by ElTopo** [comment]
@alexbakker How about giving us a "clean up duplicates" button so we can at least manually do it?

**Comment by 3xploiton3** [comment]
> 

need this feature very soon, google authenticator already notice user when duplicate entries detected

**Comment by wksantiago** [comment]
A much needed feature lets do it.

**Comment by wksantiago** [comment]
Any progress?
