### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by Vstory** [beemdevelopment/Aegis#471]
###### Info
* __Language__ : English
* __Version__: 1.2-beta5
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)  Yes
* __Device:__ Xiaomi Note 3
* __Android version and ROM:__ Android 9 ,MIUI 12 20.6.11

###### Steps to reproduce

Select two accounts to transfer items.Long press the icon in the upper right corner to make it pop up toast.Toast is the same, this should not be the same toast.

###### Log

![Screenshot_2020-06-16-17-24-41-278_com beemdevelopment aegis_Mosaic_17_25_29](https://user-images.githubusercontent.com/20795557/84758149-a815b800-aff7-11ea-9392-b8a6530a8e58.jpg)

![Screenshot_2020-06-16-17-24-45-138_com beemdevelopment aegis_Mosaic_17_25_39](https://user-images.githubusercontent.com/20795557/84758175-ae0b9900-aff7-11ea-84ed-069e6a7939a1.jpg)

**Comment by michaelschattgen** [comment]
Thanks for your report! My bad, will fix it ASAP.
