### ISSUE TITLE
Localization not included

### ISSUE THREAD

**Issue by R3gi** [beemdevelopment/Aegis#473]
###### Info

* __Version__: 1.2
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Xiaomi Mi A2 Lite
* __Android version and ROM:__ 9 stock

###### Steps to reproduce

1. Switch language to Czech
2. Go to Aegis settings
3. Notice untranslated strings

Go to Crowdin translation project
Notice that there are two strings files included for translation. One is fully translated in Czech, the second was omitted because it is duplicit. It seems certain strings which are translated on Crowdin are not included in the app.

###### What do you expect to happen?

The app will be updated with localized strings.
It will be clear what should be translated. There won't be any duplicated files included for translation on Crowdin.
Existing translations should be merged into one file (currently in master folder at Crowdin).

###### What happens instead?

Certain translations are not included in the app.
Strings file is duplicated on Crowdin. Translators don't know if it is really necessary to localize both files.

**Comment by alexbakker** [comment]
We've made some improvements to the way we handle translations with Crowdin. The Czech translation will be included in the next version of Aegis. If you're still seeing issues, please let us know.
