### ISSUE TITLE
Incomplete import from Microsoft Authenticator

### ISSUE THREAD

**Issue by lenwhite** [beemdevelopment/Aegis#477]
###### Info

* __Version__: 1.2
* __Source__: Google Play
* __Vault encrypted:__ No
* __Device:__ Oneplus 6
* __Android version and ROM:__ Android 10, Oxygen OS 10.3.2, stock rooted with magisk

###### Steps to reproduce

Settings -> Import from app -> Microsoft Authenticator -> OK

###### What do you expect to happen?

All Microsoft Authenticator entries shown

###### What happens instead?

Of the 11 entries in Microsoft Authenticator, only first 7 are displayed; the remaining 4 are not. Only the first 7 entries are imported. 

Manually adding a new TOTP based OTP into Microsoft Authenticator and re-running the import also does not show the new entry. 

In the PhoneFactor sqlite file, all 11 entries are present and the 4 missing entries are all TOTP based. No issues encountered when manually adding the oath_secret_key from these 4 entries to Aegis.

**Comment by alexbakker** [comment]
Thanks for your report. This issue has the same underlying cause as #82 and will be fixed by #474. If you're willing to test that fix with a debug APK (https://alexbakker.me/u/1fknqezzye.apk), I'd appreciate it!

**Comment by lenwhite** [comment]
Apologies for the delay, I've tested the fix and it fixes this bug.

**Comment by alexbakker** [comment]
Great! No worries.

**Comment by alexbakker** [comment]
This was fixed by #474.
