### ISSUE TITLE
Show code in 4-digit grouping (only for 8 digits codes like Battle.net)

### ISSUE THREAD

**Issue by Skimige** [beemdevelopment/Aegis#480]
I think dividing code from the middle is nice too, as this can also apply to 6 digits codes.
This would be a better looking, and easier to remember them temporarily, IMO.

**Comment by alexbakker** [comment]
We plan to offer a list of options to customize the code grouping. We'll also include the option requested in #822.

**Comment by alexbakker** [comment]
Implemented by #992.
