### ISSUE TITLE
Allow Long-press Drag and Drop reordering

### ISSUE THREAD

**Issue by h1dden-da3m0n** [beemdevelopment/Aegis#482]
Hello there!
First of all, great work with Aegis, love the app so far after switching from the long-outdated RedHat FreeOTP.
I have stumbled over on minor OCD triggering issue though and would like to open this feature request/proposal to fix it or at least discuss this.

My "issue" is related to the entry ordering and the inability to reorder entries manually. Other OTP applications, be that the Google Authenticator or the ancient FreeOTP I am migrating from, allow their users to drag and drop the entries manually, yet this seems not to work in Aegis.
As far as I can tell the "Custom" ordering in Aegis only orders the entries according to the times they got added, yet does not allow the manipulation of that order.
I sadly realized this a bit too late and messed up my "Custom" ordering of my entries by not following my original order from FreeOTP, but by which service I could migrate easies.

I know my issue isn't a high priority issue in any way; maybe it is even just me who would love to reorder his entries in the "Custom" order manually. Still, I wanted to open this request/discussion.

I hope I could present my request and its origin at least somewhat concisely, but should I have missed something obvious or should there be any more context needed, feel free to let me know.

Thank you for reading and maybe considering this, but definitely keep up the great work!

---

I am sorry should I have missed an already existing issue regarding this request, but my search in the open and closed issues didn't yield anything similar.

**Comment by michaelschattgen** [comment]
Hi, thanks for your report! Although it might be a bit confusing, we already support reordering your entries with long press drag and drop. Hold the item you want to move until it's selected, then hold it again and drag it to your preferred place.

Please let us know if this works for you, then we'll close this issue.

**Comment by h1dden-da3m0n** [comment]
Hey Michael.

Fist Thank you for the swift reply, and yeah the that was precisely the feature I was looking for with this.
Usually, I am better with figuring out features by myself (a bit disappointed in myself now -.-).
Anyway, I'll close this as this is already a working feature 🎉.

---

If I had on comment though, maybe copy the indicator that the google authenticator uses in the selected state (it's a small three horizontal bar icon that appears to the very left of the selected entry) that would make this a bit easier to find.
But then again these are just my two cents.

**Comment by Zeklandia** [comment]
Maybe I'm missing something, but when I do this, it just scrolls the list. In the past I was able to reorder accounts.

**Comment by h1dden-da3m0n** [comment]
@Zeklandia What version of the app are you on?

**Comment by Zeklandia** [comment]
1.3 (via Play Store)

**Comment by Zeklandia** [comment]
I think there might be an issue with the highlight or copy when tapped settings, because after toggling those and restarting the app, I was able to re-order accounts. Notably, the little handles appeared after long-pressing the entries, which wasn't happening earlier.

**Comment by h1dden-da3m0n** [comment]
Okay i now tried to reproduce what you described (activated copy on tap and restarted) it still worked fine for me (same version 1.3 playstore) :thinking:

But if it now works reliably for you great, but if you find a way to reproduce a non working behavior be sure to open a bug report.

**Comment by Zeklandia** [comment]
I can't get it to happen reliably, but I believe I've isolated the problem. It's not those settings, it's the chosen sort method, which for some reason will behave as if it is sorted (prevents re-ordering) when set to custom. Though this only seems to happen across updates or after long periods of inactivity (weeks). Toggling the sort from custom to something else and back to custom fixes it.

**Comment by michaelschattgen** [comment]
Thanks for coming back to us on this topic. Unfortunately I can't seem to reproduce this on my phone running Aegis 1.3. I might test this tomorrow on an emulator with different versions, it could be an update which causes this.
