### ISSUE TITLE
Import Battle.net Codes from various sources

### ISSUE THREAD

**Issue by yoshimo** [beemdevelopment/Aegis#483]
It would be great if you could handle 

- The official Battle.net Authenticator ( https://play.google.com/store/apps/details?id=com.blizzard.bma )
- The Restore code from https://account.blizzard.com/security
- The backup xml from https://bitbucket.org/sednogmah/foobma/src

**Comment by alexbakker** [comment]
> The official Battle.net Authenticator ( https://play.google.com/store/apps/details?id=com.blizzard.bma )

Someone could look into whether that's possible. It'll require root access, just like the other importers that read from other app's internal storage.

> The Restore code from https://account.blizzard.com/security

Is it possible to derive the secret from this restore code, without connecting to the internet? My guess would be no.

> The backup xml from https://bitbucket.org/sednogmah/foobma/src

This seems like too much of a niche tool to add support for.

**Comment by yoshimo** [comment]
If you turn Wifi Off, the Battle-net Mobile App can't finish the restore Process.
I'll have a look at the recorded traffic later. Have to throw out the js and other html crap first.

Maybe to niche that particular tool, but it seems rather straight forward
- Serial, Clockskew and a token. 
Maybe similiar to how the official app or a WinAuth would store it.
I need to dig up the AppData first, seems to be buried between Webcache and Analytics somewhere.

**Comment by yoshimo** [comment]
Blizzards Mobile App stores it in
/data/data/com.Blizzard.bma/sharred_prefs/com.blizzard.bma.AUTH_STORE.xml 

There are  just a few lines:
`
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <int name="com.blizzard.bma.AUTH_STORE_HASH_VERSION" value="20402009" />
    <long name="com.blizzard.bma.AUTH_STORE.CLOCK_OFFSET" value="-149" />
    <string name="com.blizzard.bma.AUTH_STORE.HASH">numbersandletters</string>
    <long name="com.blizzard.bma.AUTH_STORE.LAST_MODIFIED" value=">Number outside the UnixTimeStamp<" />
</map>
`

**Comment by beerisgood** [comment]
Another good source:
https://github.com/andOTP/andOTP/wiki/Shared-secrets#battlenet

**Comment by 07416** [comment]
> This seems like too much of a niche tool to add support for.

"Niche tool" when the authenticator is near-mandatory for [some of the largest games in the world](https://en.wikipedia.org/wiki/Blizzard_Entertainment#Games)?

**Comment by alexbakker** [comment]
@07416 Don't quote me out of context. I was obviously talking about https://bitbucket.org/sednogmah/foobma/src, not Battle.net Authenticator itself.

**Comment by 07416** [comment]
@alexbakker I apologize, to be frank the main reason for commenting was to bring more attention towards the feature request.

I'll delete the comment.

**Comment by alexbakker** [comment]
We currently don't have plans to implement this feature ourselves, but if anyone is interested in picking this up, let us know. Note that we're just talking about importing from the Battle.net Authenticator Android app here.

**Comment by JordanPlayz158** [comment]
I have made a solution for importing Battle.net Authenticator and would like to know if you are still interested in having the importer, if so, I can make the importer, here is the repository of the java implementation https://github.com/JordanPlayz158/BMA-TOTP

**Comment by alexbakker** [comment]
Does that read a file from the internal storage of the Battle.net Authenticator app? If so, sure! A pull request would be welcome.

**Comment by JordanPlayz158** [comment]
It is implemented to read the AUTH_STORE file (which is located at `/data/data/com.blizzard.bma/shared_prefs/com.blizzard.bma.AUTH_STORE.xml`) so all I need to do is rather than have it ask for a file, have it grab the file using root although will the apache codec dependency be an issue (or perhaps android has base 16 to base 32 classes like it appears it has an xml parser)

**Comment by alexbakker** [comment]
> It is implemented to read the AUTH_STORE file (which is located at /data/data/com.blizzard.bma/shared_prefs/com.blizzard.bma.AUTH_STORE.xml)

Sounds good.

>  will the apache codec dependency be an issue (or perhaps android has base 16 to base 32 classes like it appears it has an xml parser)

Let's try to avoid adding additional dependencies. You can use Aegis' ``Hex`` and ``Base32`` wrapper classes. With regards to XML, try to see if the utility function we have for parsing shared preferences files suffice. Otherwise, please directly use the XML parser package included with Android (org.xmlpull).
