### ISSUE TITLE
Wrong export filename

### ISSUE THREAD

**Issue by Jonas1312** [beemdevelopment/Aegis#495]
###### Info

* __Version__: 1.2
* __Source__: Google Play
* __Vault encrypted:__ Yes
* __Device:__ honor 5C
* __Android version and ROM:__ 7.0 

###### Steps to reproduce

1) Export encrypted backup to google drive
2) The backup works but the name is badly formatted (double `.json`):

![Captueeeere](https://user-images.githubusercontent.com/15847892/85926616-d53c5300-b8a0-11ea-8284-0746a9ff4e5f.PNG)

###### What do you expect to happen?

`aegis-export-20200627-175319.json`

###### What happens instead?

`aegis-export.json-20200627-175319.json`

**Comment by alexbakker** [comment]
Yeah, that's a little embarrassing. Will be fixed by #493.
