### ISSUE TITLE
After typing the password - app crashes

### ISSUE THREAD

**Issue by allendema** [beemdevelopment/Aegis#496]
###### Info

* __Version__:  1.2
* __Source__: @F-Droid
* __Vault encrypted:__  Yes
* __Device:__ Pixel
* __Android version and ROM:__ Android 10

###### Steps to reproduce
1. Close the app.
2. Open the app, type the password 

###### What do you expect to happen?

... Vault to be opened.

###### What happens instead?
App goes in crash loop, and thus vault can't be opened.

**Comment by alexbakker** [comment]
Thanks for your report. Could you obtain a log of the crash with ADB (https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#bug-reports) and share it here?

**Comment by allendema** [comment]
I currently can't do it.
But if i want to scan a QR Code from the widget thing, it works well for some time then it crashes.

**Comment by alexbakker** [comment]
> But if i want to scan a QR Code from the widget thing, it works well for some time then it crashes.

So, you can unlock the app when using the app shortcut to scan a QR code, but not when opening the app normally? When does it crash in that case?

It's still a bit unclear to me. Can you provide an exact list of steps you take to reproduce the crash? From start (the app is killed and opened for the first time) to finish (the app crashes).

**Comment by allendema** [comment]
I cleared the cache and all data of Aegis.
Now it seems to work as it should.


The issue was that app crashed, below steps to reproduce:

1. Install and open the app, choose the option that u want to have a password.
2. Close the app.
3. Open the app and type the password.
4. App crashes .
5. Repeat step three.

If i open the "Scan a QR Code" widget, i can scan QR Codes for like 15 seconds but the vault is not unlocked.
After this time app crashes.

**Comment by allendema** [comment]
Also if 9999 is set as the time to generate a new key, app crashes.
Try to reopen it, crashes again.

**Comment by alexbakker** [comment]
> Also if 9999 is set as the time to generate a new key, app crashes.
> Try to reopen it, crashes again.

Can you create a separate issue for that?

**Comment by alexbakker** [comment]
> I cleared the cache and all data of Aegis.
> Now it seems to work as it should.

Am I correct in assuming that you can no longer reproduce the crash after clearing cache/data of Aegis?

**Comment by allendema** [comment]
>
> Am I correct in assuming that you can no longer reproduce the crash after clearing cache/data of Aegis?

That's correct. 
I don't understand why it happend in the first place.

**Comment by alexbakker** [comment]
Caused by #500.
