### ISSUE TITLE
Can't select two or more entries

### ISSUE THREAD

**Issue by allendema** [beemdevelopment/Aegis#497]
###### Info

* __Version__:  1.2
* __Source__:  F-Droid
* __Vault encrypted:__ Nk
* __Device:__ Pixel
* __Android version and ROM:__ Android 10

###### Steps to reproduce
Go to your entries and try to select more than two of them.

###### What do you expect to happen?

All wanted entries should be selected and then user should choose an action like deleting them.

###### What happens instead?
Only one entry is selected.

**Comment by michaelschattgen** [comment]
Thanks for your report. It seems to be working fine for me. Do note that your second entry requires a single tap instead of a long press.

**Comment by allendema** [comment]
I think i tried that before, now it's working. 🌝
