### ISSUE TITLE
Can't translate themes and view modes in settings

### ISSUE THREAD

**Issue by zaggo0** [beemdevelopment/Aegis#50]
In the settings screen the 'Theme' and 'View mode' settings, and its available options, are not translatable.

![259b82](https://user-images.githubusercontent.com/1347792/55440445-e9af7400-55a7-11e9-998e-359c3355277b.png)
![702039](https://user-images.githubusercontent.com/1347792/55440446-e9af7400-55a7-11e9-9d24-4fb5f43bd634.png)

**Comment by michaelschattgen** [comment]
Thanks for bringing this to our attention.
