### ISSUE TITLE
If code refresh time is set to "9999" - Aegis crashes

### ISSUE THREAD

**Issue by allendema** [beemdevelopment/Aegis#500]
###### Info

* __Version__:  1.2
* __Source__: F-Droid
* __Vault encrypted:__ Yes 
* __Device:__ Pixel
* __Android version and ROM:__ Android 10

###### Steps to reproduce

1. Create a new manual entry 
2. Give other details, but set time to generate a new key to "9999" seconds.

###### What do you expect to happen?
New code should be generated when the entered time is up.

###### What happens instead?
Aegis instantly crashes.
I reopened Aegis, gave the password and it crashed again and again to the point where i just cleared all the app data.

This issue is possibly the cause of #496

**Comment by alexbakker** [comment]
Thanks. As you think that this is what caused #496, I'll close that one.
