### ISSUE TITLE
Add support for SVG icons

### ISSUE THREAD

**Issue by Keysuke** [beemdevelopment/Aegis#501]
Hi,

Currently, the application automatically restarts when trying to set an SVG icon.
Since [aegis-icons](https://github.com/krisu5/aegis-icons/) comes with SVG icons, can you support this format?

Thanks.

**Comment by krisu5** [comment]
SVGs in the aegis-icons are for production and [for editing background color](https://github.com/krisu5/aegis-icons/blob/master/FAQ.md#how-can-i-make-icon-with-different-background-color)

**Comment by Keysuke** [comment]
Hello @krisu5,

Thank you for your work.
I have been using your PNGs on Aegis.

Since the SVG format has many advantages over PNG (size, scalability,...) and is supported on most modern systems (including Android), why should we stick to using the PNG format only?

Besides, adding support on Aegis for this format would also remove the need of exporting to PNG after editing.

**Comment by krisu5** [comment]
> Since the SVG format has many advantages over PNG (size, scalability,...) and is supported on most modern systems (including Android), why should we stick to using the PNG format only?

That's true, I agree. I was making sure. :)

IIRC, Android can't use SVGs as is on the app. It has to be converted to "drawable" XML first. But I'm not developer, so I'm not 100% sure.

**Comment by alexbakker** [comment]
SVG icons will be supported as part of #509.

**Comment by alexbakker** [comment]
#509 has been merged.
