### ISSUE TITLE
Provide an alternate method of selecting icons

### ISSUE THREAD

**Issue by rnc** [beemdevelopment/Aegis#505]
While I did try unpacking the zip from https://github.com/krisu5/aegis-icons as I didn't want those icons to litter my stock Gallery (Samsung S10e) I placed a .nomedia file within it. I would like to see an alternate file browsing method, ideally also able to browse connected cloud storage for the icons.

**Comment by alexbakker** [comment]
I think we can simply send along a ``ACTION_GET_CONTENT`` intent in addition to ``ACTION_PICK``.
