### ISSUE TITLE
How about a /sdcard/Aegis directory?

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#506]
How about a tidy /sdcard/Aegis directory, where
aegis-export.json-*-*.json
could be put, instead of jumbling it into Downloads.

**Comment by michaelschattgen** [comment]
I'm not sure if I understand you correctly. You are free to choose what folder to export to.

**Comment by jidanni** [comment]
Yes, but if you have a look around your /sdcard, you will see that many apps have their own folders. That keeps things tidy.

**Comment by michaelschattgen** [comment]
You are able to create the folder yourself in the same filepicker, it's not something we need to implement to make this possible for you. Besides that, we use the [Storage Access Framework](https://developer.android.com/training/data-storage/shared/documents-files) which makes it impossible for us to create folders on /sdcard misschien. Aegis can't get permissions to folders (or files) without explicitely asking the user first, anyhow you should create this folder yourself.

I'm closing this issue but feel free to continue the discussion.
