### ISSUE TITLE
Enabling fingerprint fails with IllegalBlockSizeException

### ISSUE THREAD

**Issue by vuori** [beemdevelopment/Aegis#51]
On latest F-Droid build, attempting to enable fingerprint unlock results in an IllegalBlockSizeException popup. logcat shows success from FingerprintService followed by `E keystore: getAuthToken failed: -3`.

Let me know if I can somehow gather additional logs or try different crypto parameters somewhere. Device is Xperia XZ running 8.1, fingerprints are working for device unlock.

**Comment by michaelschattgen** [comment]
Thanks for opening this issue. We weren't aware of this and we will look into it.

**Comment by alexbakker** [comment]
Do you have multiple fingerprints registered on your device?

I can reproduce similarly strange behavior on an API 23 emulator with 2 fingerprints enrolled (not on API 27, though). Steps:
1. Enable fingerprint with Finger 1
2. Disable fingerprint
3. Enable fingerprint with Finger 2

Looking a bit more closely, it seems that authenticating a Cipher for a KeyStore key with the FingerprintManager goes fine. When it actually tries to use the Cipher it goes "Ha! Gotcha!" and throws an ``IllegalBlockSizeException`` with ``KeyStoreException "Key user not authenticated"`` as the cause.

**Comment by vuori** [comment]
Yes. I tried removing all but one and rebooting, but unfortunately trying to enable fingerprint authentication fails with the same error popup.

Logging the underlying exception might be helpful. The keystore error code -3 shown in logcat would be `INCOMPATIBLE_PURPOSE` assuming it's a return code from the keymaster HAL, which sounds pretty weird.

**Comment by alexbakker** [comment]
> Yes. I tried removing all but one and rebooting, but unfortunately trying to enable fingerprint authentication fails with the same error popup.

Hmm. Does fingerprint work with other apps on your device, apart from system apps and device unlock? If you're not sure, here's an example app you can try: https://github.com/googlesamples/android-FingerprintDialog. I can provide a build of that if needed.

> Logging the underlying exception might be helpful.

Yeah, we definitely need to do more logging so that users don't have to attach a debugger to be able to submit useful bug reports. For now, I wrote a quick patch that logs any exceptions that occur during fingerprint registration through the settings: https://github.com/alexbakker/Aegis/tree/issue-51. A built APK is available here: https://alexbakker.me/u/ls3pn5ho6e.apk. It has a different package name than the production one, so there's no risk of losing anything.

> The keystore error code -3 shown in logcat would be INCOMPATIBLE_PURPOSE assuming it's a return code from the keymaster HAL, which sounds pretty weird.

That's really weird, indeed. We pass ENCRYPT and DECRYPT as the purposes when generating the key: https://github.com/beemdevelopment/Aegis/blob/6d93b78f9af3c0fa802e11a6ecb881dabab2c1ab/app/src/main/java/com/beemdevelopment/aegis/crypto/KeyStoreHandle.java#L53-L61 It's a 256-bit key for symmetric encryption, so we can't and don't use it for anything else. I don't want to be too quick to blame your device, but maybe this is a bug in the HAL implementation?

**Comment by vuori** [comment]
It's entirely likely that the HAL is buggy. The FCS on this device was 6.0.1 and I suspect that not much time was spent on validating keystore internals after that.

Anyway, I'll collect logs from the new build tomorrow and try to get Android Studio set up soon. It has been in my todo for a while anyway.

**Comment by vuori** [comment]
Log from AegisDev:

```04-05 12:10:33.015   710   710 D keystore: AddAuthenticationToken: timestamp = 64801165 (10216939135109693440), time_received = 40185
04-05 12:10:33.015  1037  1037 V FingerprintService: onAuthenticated(owner=com.beemdevelopment.aegis.debug, id=1305372842, gp=0)
04-05 12:10:33.019  1037  1037 V FingerprintService: Done with client: com.beemdevelopment.aegis.debug
04-05 12:10:33.147   710   710 E keystore: getAuthToken failed: -3
04-05 12:10:33.156 23846 23846 E Aegis   : com.beemdevelopment.aegis.db.slots.SlotException: javax.crypto.IllegalBlockSizeException
04-05 12:10:33.156 23846 23846 E Aegis   :      at com.beemdevelopment.aegis.db.slots.Slot.setKey(Slot.java:68)
04-05 12:10:33.156 23846 23846 E Aegis   :      at com.beemdevelopment.aegis.ui.PreferencesFragment$RegisterFingerprintListener.onSlotResult(PreferencesFragment.java:701)
04-05 12:10:33.156 23846 23846 E Aegis   :      at com.beemdevelopment.aegis.ui.Dialogs$2.onAuthenticated(Dialogs.java:207)
04-05 12:10:33.156 23846 23846 E Aegis   :      at com.beemdevelopment.aegis.helpers.FingerprintUiHelper$2.run(FingerprintUiHelper.java:121)
04-05 12:10:33.156 23846 23846 E Aegis   :      at android.os.Handler.handleCallback(Handler.java:790)
04-05 12:10:33.156 23846 23846 E Aegis   :      at android.os.Handler.dispatchMessage(Handler.java:99)
04-05 12:10:33.156 23846 23846 E Aegis   :      at android.os.Looper.loop(Looper.java:164)
04-05 12:10:33.156 23846 23846 E Aegis   :      at android.app.ActivityThread.main(ActivityThread.java:6499)
04-05 12:10:33.156 23846 23846 E Aegis   :      at java.lang.reflect.Method.invoke(Native Method)
04-05 12:10:33.156 23846 23846 E Aegis   :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
04-05 12:10:33.156 23846 23846 E Aegis   :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-05 12:10:33.156 23846 23846 E Aegis   : Caused by: javax.crypto.IllegalBlockSizeException
04-05 12:10:33.156 23846 23846 E Aegis   :      at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
04-05 12:10:33.156 23846 23846 E Aegis   :      at javax.crypto.Cipher.doFinal(Cipher.java:1741)
04-05 12:10:33.156 23846 23846 E Aegis   :      at com.beemdevelopment.aegis.crypto.CryptoUtils.encrypt(CryptoUtils.java:82)
04-05 12:10:33.156 23846 23846 E Aegis   :      at com.beemdevelopment.aegis.db.slots.Slot.setKey(Slot.java:64)
04-05 12:10:33.156 23846 23846 E Aegis   :      ... 10 more
04-05 12:10:33.156 23846 23846 E Aegis   : Caused by: android.security.KeyStoreException: Key user not authenticated
04-05 12:10:33.156 23846 23846 E Aegis   :      at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
04-05 12:10:33.156 23846 23846 E Aegis   :      at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:132)
04-05 12:10:33.156 23846 23846 E Aegis   :      at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:217)
04-05 12:10:33.156 23846 23846 E Aegis   :      at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
04-05 12:10:33.156 23846 23846 E Aegis   :      ... 13 more```

So user is authenticated but then not actually authenticated… This might make sense if there's a problem with purpose handling in the keymaster. I'll try to get the Google sample code running during the weekend and see what happens.

In addition to device unlock, Play Store fingerprint auth works, but I don't think I have tried any other 3rd party apps that use fingerprint auth before.

**Comment by alexbakker** [comment]
That looks very similar to the exception I got in the emulator, which is also known to have wonky support for fingerprints. I'm curious to see whether Google's example app works for you.

**Comment by vuori** [comment]
I tested the sample app and it fails essentially in the same way. Tweaking the purpose bits has no effect, trying to set things like `setUserAuthenticationValidityDurationSeconds` throws an exception in the key generation phase.

Looking at AOSP sources indicates that the keystore error is indeed coming directly from the keymaster, which is Qualcomm binary blobs all the way down. It seems that protecting symmetric keys with fingerprints is broken on this device (and will never get fixed since it's an obsolete SoC).

I can try other things if you have ideas, but if not this issue can be closed.

**Comment by alexbakker** [comment]
Thanks for the update. When we need to start digging into binary drivers is about where I lose all hope. Sorry we couldn't help you here. (I'm glad it's not our bug though)
