### ISSUE TITLE
Ask for password on import & export only

### ISSUE THREAD

**Issue by marzooqy** [beemdevelopment/Aegis#512]
Hello, I wonder if you could make it possible to only require the password when importing or exporting the data. This way the backup would be encrypted, but the user won't have to input the password every time he opens the app.

**Comment by ashakoor** [comment]
go to Settings -> Security -> Encryption and disable it, or use fingerprint/other biometric authentication.

**Comment by marzooqy** [comment]
But this way, the backups won't be encrypted.

**Comment by ashakoor** [comment]
You could add a password before you make a backup, or encrypt the backups yourself

**Comment by marzooqy** [comment]
Yes, that would work for me. Although having this as a setting would be a little more convenient.
