### ISSUE TITLE
Support for push-notifications when TOTP is requested

### ISSUE THREAD

**Issue by Neuro-NX** [beemdevelopment/Aegis#518]
It would greatly improve the overall sign-in user experience to have a working implementation of 2FA push-notifications, as to avoid the step of needing to manually open the vault, scan the list and copy the token. [LastPass Authenticator has this feature](https://support.logmeininc.com/lastpass/help/lastpass-authenticator-lp030014#PushNotifications) but it would rarely, if ever work for most people.

**Comment by alexbakker** [comment]
Thanks for the suggestion, but how do you expect Aegis to implement this feature? 

TOTP and HOTP work entirely offline. Aegis does as well. LastPass implements something proprietary alongside of that. As I understand it, you log into the LastPass browser extension and it detects when you need to enter an OTP for a website of one of the (few) supported services. It then notifies your device for confirmation. To replicate this feature, we would need to create and sign our users up to our own centralized service. We'd also have to write a similar browser extension and send notifications to users through that service. That just doesn't seem desirable (or realistic, for that matter).

> LastPass Authenticator has this feature but it would rarely, if ever work for most people.

Why does it not work for most people? In what way do you think Aegis could implement it differently?

**Comment by Neuro-NX** [comment]
> [To replicate this feature] We'd also have to write a similar browser extension and send notifications to users through that service. That just doesn't seem desirable (or realistic, for that matter).

Fundamentally, seeing as the token is just a string that can be copied to the clipboard, it may just be a matter of finding out how to share data between two apps.

Android has a native way to do this called [intents](https://developer.android.com/training/sharing). 

> In some cases, you can start an activity to receive a result, in which case the activity also returns the result in an Intent. For example, you can issue an intent to let the user pick a personal contact and have it returned to you. The return intent includes a URI pointing to the chosen contact.

With that, here is a conceptual approach that would require investigating further.

1. User signs into account in a browser
2. Server makes request for OTP 
3. User uses browsers native share button and selects Aegis app to share the current URL to.
4a. Aegis activity checks for a match between URL and OTP issuer. **https://facebook.com** matches **Facebook** (credentials).
4b. Or, us an intent activity to show the user's vault list, once unlocked, and have them manually select the required entry.
5. Aegis then copies the token to the clipboard when the user selects the vault entry.
6. Then Aegis redirects user back the browser
7. The token is then automatically inserted (autofill) into the input field with the help of the native accessibility  service. [This](https://developer.android.com/guide/topics/text/autofill-services#sms-autofill) applies to SMS-OTP but it may be helpful.

**Comment by alexbakker** [comment]
OK, so push notifications are off the table? This sounds a lot different than what you initially proposed.

The new approach you describe would only work for users who have to log in through a web browser, on the same device that they have Aegis installed on. This feature would be fairly difficult to discover, as I expect no users would think to 'share' the current URL with Aegis. The matching of the URL to the issuer would be fairly error-prone. Also, using the accessibility service for this purpose is no longer allowed.

Using the [Autofill service](https://developer.android.com/guide/topics/text/autofill-services) may be a more suitable solution. We can create a new issue for that and discuss it separately, if you want.

**Comment by Neuro-NX** [comment]
I have made a separate proposal #524 to continue the discussion on possibly using AutofillService.
