### ISSUE TITLE
Incorrect token for imported authy

### ISSUE THREAD

**Issue by lunarmuricata** [beemdevelopment/Aegis#52]
I previously imported authy via andotp which I then imported into aegis, then I noticed that the token was wrong. Could you please consider adding authy support next for those 2fa which only option is via authy such as twitch, thanks.

**Comment by alexbakker** [comment]
I'm not very familiar with the internals of Authy, so I'm not sure if we can support their tokens, unless they use one of the standard algorithms. How did you import your Authy tokens into andOTP and what kind (HOTP/TOTP) are they?

**Comment by lunarmuricata** [comment]
https://github.com/puddly/android-otp-extractor i used this to import the tokens into andotp. and i believe theyre totp

**Comment by alexbakker** [comment]
Ok, so that should work. Are the tokens you're seeing in Aegis different than in andOTP?

**Comment by lunarmuricata** [comment]
yes they are different from andotp. although andotp tokens are different from the official authy app, they work in the twitch website unlike aegis.

**Comment by lunarmuricata** [comment]
oh wait im dumb. just realize ive typed them in sorry for wasting your time 😅
