### ISSUE TITLE
Aegis doesn't seems to be able to use biometric sensor on Pixel 3a

### ISSUE THREAD

**Issue by Porkepix** [beemdevelopment/Aegis#530]
###### Info

* __Version__: 1.2.1
* __Source__: (Google Play/GitHub/F-Droid/?) F-Droid
* __Device:__ Pixel 3a
* __Android version and ROM:__ 10

###### Steps to reproduce

Just go through first run assistant or in settings for biometry

###### What do you expect to happen?

Be able to use the biometric sensor.

###### What happens instead?

Biometry settings are grayed out and doesn't seems to be usable, or even detected by Aegis.

###### Additional information

I don't plan on using biometry, but seeing it grayed out made me crate this issue. However it's completely possible that it's tied to biometry usage on system level and that if user doesn't use it for system, then Aegis have no access to it. No idea on that point.

**Comment by alexbakker** [comment]
> However it's completely possible that it's tied to biometry usage on system level and that if user doesn't use it for system, then Aegis have no access to it.

That's correct. Users have to configure biometrics in Android settings before they can use that option in Aegis.

**Comment by Porkepix** [comment]
@alexbakker So, it's impossible for any application to be able to use/provide fingerprint reader abilities if the user isn't already using it with the system? Quite a shame if that's the case :(

**Comment by alexbakker** [comment]
That's correct.
