### ISSUE TITLE
Add translation link

### ISSUE THREAD

**Issue by linsui** [beemdevelopment/Aegis#533]
It seems that you are using Crowind for translation but I can't find a link. Could you please put the link in readme and F-Droid meta data (and somewhere else) ? Thanks!

**Comment by R3gi** [comment]
The About screen inside the app is usually the best place 😉

**Comment by allendema** [comment]
Add/make a Matrix room link too, to better solve issues.

**Comment by alexbakker** [comment]
I've added a link to Crowdin the README and created [a merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7176) to get it added to F-Droid.

We've also created [a Matrix room](https://matrix.to/#/#aegis:matrix.org). Feel free to join it!
