### ISSUE TITLE
Add support for pin instead of password

### ISSUE THREAD

**Issue by michaelschattgen** [beemdevelopment/Aegis#54]

**Comment by alexbakker** [comment]
I'm against this. Users will expect that their 4-6 digit PIN's are securely encrypting their vault, but in reality this would be trivial to brute force. One would need 20 random digits to get close to 64 bits of entropy, at which point you're better off using a password or passphrase anyway. Of course people are already free to enter a short password or PIN, but I think we should definitely not encourage it by adding a PIN option.

On this subject, I think it would be nice to give users an estimation of their password strength. A good algorithm to use for this would be [zxcvbn](https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation) from Dropbox.

**Comment by drkui** [comment]
Preferably, I would like the option to encrypt my vault with a long and strong password and then use a 4 digit pin to unlock the app, rather than using my fingerprint.

If after an x amount of failed attempts in entering the pin, it would require my password.

**Comment by glocalglocal** [comment]
Missing PIN support is the one issue stopping me from switching from Authy. My device doesn't have a fingerprint reader and I can't imagine having to enter a really strong password with special characters etc on the small screen of my mobile phone several times every day. A PIN allowing up to x attempts (like in Bitwarden and other apps) is a reasonable compromise.

**Comment by burruplambert** [comment]
I agree with drkui and  glocalglocal. It would be a great feature. Long password for vault encryption and shorter PIN for unlocking the app just like BitWarden does it.

**Comment by alexbakker** [comment]
There are plans to add support for setting a separate password for backups: #121. I think that feature will accomplish most of what you're after. I'm still not a fan of recommending this practice by adding explicit PIN support, though.

**Comment by drkui** [comment]
I think glocalglocal's situation sums it up nicely. A long password entered everytime to access their vault VS not using anything at all isn't really ideal. 

That and I personally don't like using the fingerprint scanner (if available in the phone at all) for anything vital.

**Comment by glocalglocal** [comment]
For a user who can't or won't use a fingerprint scanner, currently the options are:
a. Enter a long and random password complete with special characters every time
b. Set a weak password that is easy to tap
c. Use a password manager which will hold both the site and the Aegis password in the same place. If that's not bad enough, let's not forget that Bitwarden and other managers themselves give you access via a PIN.
d. Use Authy or similar that gives you access with a PIN. 
e. Forget about 2FA altogether. 

I very much doubt there are many, if any, Aegis users opting for (a). I reluctantly choose (d) until Aegis offers PIN access. All bank apps I am familiar with offer PIN access and revert to password login if you fail to enter the correct PIN several times. I think banks have good reasons for this strategy.

**Comment by thediamondgeezer** [comment]
The absence of this feature is what's keeping me from deploying Aegis unfortunately. I don't see where the problem where other apps have successfully implemented an encrypted vault AND a PIN screen lock/unlock.

**Comment by MarkoXD** [comment]
I'd love to see ability to unlock an app with the PIN. Not the vault, just the app.

**Comment by alexbakker** [comment]
@MarkoXD How would that work? In that scenario, the user provides the PIN to unlock the app, but the vault itself is encrypted with a password. How do we decrypt the vault?

**Comment by MarkoXD** [comment]
> @MarkoXD How would that work? In that scenario, the user provides the PIN to unlock the app, but the vault itself is encrypted with a password. How do we decrypt the vault?

I mean, if you already offer ability to not encrypt the vault, you may as well provide PIN protection. It's certainly safer than no protection, but it's not "hard" protection as it's with password. You could mention that in the app itself; just give people a choice.
I'd also recommend the password/PIN entering limit. Like, if you enter PIN/password three times incorrectly, you can try again in 1 minute. After three failed attempts again, 5 minutes and etc. You can even ask for an e-mail address during setup, so people could verify their identity somehow.

There could be a PIN for opening the app, and a password for decrypting the vault an option for people who want the strong security of the app.

**Comment by thediamondgeezer** [comment]
> @MarkoXD How would that work? In that scenario, the user provides the PIN to unlock the app, but the vault itself is encrypted with a password. How do we decrypt the vault?

Ask the andOTP devs, they implemented it perfectly.

**Comment by alexbakker** [comment]
@MarkoXD 

> I mean, if you already offer ability to not encrypt the vault, you may as well provide PIN protection. It's certainly safer than no protection, but it's not "hard" protection as it's with password. You could mention that in the app itself; just give people a choice.

PIN protecting plain texts vaults is something different than what you described earlier. I'm not a fan of the latter in particular. Giving users a choice is usually good, but not when it comes to security. Please see the earlier comments in this issue and #212.

@thediamondgeezer 

> Ask the andOTP devs, they implemented it perfectly.

andOTP does not have the feature he's describing.

**Comment by MarkoXD** [comment]
> @MarkoXD
> 
> > I mean, if you already offer ability to not encrypt the vault, you may as well provide PIN protection. It's certainly safer than no protection, but it's not "hard" protection as it's with password. You could mention that in the app itself; just give people a choice.
> 
> Giving users a choice is usually good, but not when it comes to security. Please see the earlier comments in this issue and #212.

By that logic, there shouldn't be an option to leave vault unencrypted in the first place. 😉

**Comment by alexbakker** [comment]
@MarkoXD Again, please read the earlier discussion about this. There a big different between:
1. Users having to choose between no security or great security.
2. Users having to choose between no security, a little security, medium security and great security.

It's not that I don't trust you to know to advantages and disadvantages of the different options, but the average user is a different story.

Anyway, what we _may_ end up doing is provide an option for which keyboard to show when unlocking the vault (regular or numeric). That way, we're not encouraging PIN as an option, but still make the experience more pleasant for users who do choose to use enter a PIN as the password. This is just an idea and is not set in stone yet, though.

**Comment by MarkoXD** [comment]
> @MarkoXD 

> Anyway, what we _may_ end up doing is provide an option for which keyboard to show when unlocking the vault (regular or numeric). That way, we're not encouraging PIN as an option, but still make the experience more pleasant for users who do choose to enter a PIN as the password. This is just an idea and is not set in stone yet, though.

THAT would be awesome! The vault would be encrypted and I could get rid of the small numeric keyboard. Would love to see that implemented ASAP... 👍 😃

**Comment by Xeunyx-Cypher** [comment]
Then a question arise for me, How does the Authy works with a PIN for unlocking the app only and has Strong Master Password Encryption for the VAULT? (also as Bitwarden) 
What disadvantage do they have? Because to unlock my Aegis everytime with my (long + Strong) Password is pretty irritating as I do not want to compromise my vault encryption with a 4 digit numerical password.

I would be glad to have insights on this matter :)

**Comment by alexbakker** [comment]
@Xeunyx-Cypher 

Would a combination of #510 and #121 work for you?

> How does the Authy works with a PIN for unlocking the app only and has Strong Master Password Encryption for the VAULT?

After entering your master password in the Authy app once, the secrets for your tokens are stored in plain text on your device from that point forward.

> also Bitwarden has similar option too

I'm not familiar with how Bitwarden works, but hopefully they implement that feature is a bit more securely than Authy.

**Comment by Xeunyx-Cypher** [comment]
Yeah! If it can be implemented as you stated in #121. That would be really **GREAT** ! Separate password/PIN for unlocking the app and a Strong Master Password for my Encryption while backing up. Really appreciate the efforts <3

**Comment by Xeunyx-Cypher** [comment]
> I'm not familiar with how Bitwarden works, 

They let you set a PIN for locking the application once you successfully logged in with your Master Password. So you don't have to unlock the app with your Master Password everytime.

> but hopefully they implement that feature is a bit more securely than Authy.

I hope so too!
