### ISSUE TITLE
Let back button lock+close Aegis instead of returning to lock screen

### ISSUE THREAD

**Issue by mdmower** [beemdevelopment/Aegis#541]
It would make a lot of sense if tapping "back" locked and closed Aegis instead of returning to the Aegis lock screen. How often do people think "I finished reading my TOTP code, now I would like to go back to the Aegis lock screen" compared to "I finished reading my TOTP code, now I'd like to securely exit Aegis"? In the (rarer) former case, reaching the lock screen is still possible by re-opening Aegis.

A couple of comments:

- The "home" key performs as you'd expect, defocusing Aegis in a manner than does not require re-unlocking if Aegis regains focus. So, I don't think its behavior should be modified.
- The closest issue I could find to this feature request is bug report #182 (fixed in #192) which described an inability to close the app when at the lock screen. Sorry if this has already been requested and I didn't find the original issue.

**Comment by linsui** [comment]
When I want to file a issue I find this. I hope that I can lock Aegis when I tap home. I hardly ever need to input another 2FA code after I input one. 
The behavior of the back button is weird. I have to tap it three times to leave Aegis and lock it.

**Comment by alexbakker** [comment]
Fair enough!

> I hope that I can lock Aegis when I tap home. I hardly ever need to input another 2FA code after I input one.

See #334. We'll probably tackle both of these at the same time.
