### ISSUE TITLE
Immediately proceed to biometric unlock when app is launched

### ISSUE THREAD

**Issue by Retew** [beemdevelopment/Aegis#542]
I'm an owner of a phone with FOD (fingerprint on display). I have fingerprint unlock configured in Aegis, but I can't use FOD unless special field pops up. To make it appear I have to click "biometric" button under the "password" field. It is pretty annoying. Password manager autofill suggestions also get in the way. I would like my app to Immediately proceed to biometric unlock instead since it is configured. At least optionally.

**Comment by alexbakker** [comment]
Your autofill suggestions are probably masking the popup of the password reminder. Try entering your password once and see if it still doesn't prompt for biometrics by default after that.

**Comment by Retew** [comment]
@alexbakker It worked as you expected. Thank you!
