### ISSUE TITLE
Enable auto backup for shared preferences

### ISSUE THREAD

**Issue by JNavas2** [beemdevelopment/Aegis#544]
Please consider using Shared Preferences for app Settings, so they are automatically backed up and restored to/from Google Drive.

As it is now, when I uninstall and reinstall the app, all Settings (e.g., View mode) revert to defaults, rather than what I configured previously. Using Shared Preferences would presumably restore my Settings automatically.

See [Back up user data with Auto Backup](https://developer.android.com/guide/topics/data/autobackup).

Thank you.

**Comment by alexbakker** [comment]
Settings already are saved in shared preferences, but we set ``android:allowBackup="false"``to turn off backups entirely, because we don't want unencrypted vaults ending up on people's Google Drive. We could consider partially enabling that feature, only for the preferences file: https://developer.android.com/guide/topics/data/autobackup#IncludingFiles.

**Comment by JNavas2** [comment]
Sounds great, thank you!

**Comment by JNavas2** [comment]
p.s. When the vault is encrypted, would it not make sense to at least have an option for auto backup of the vault to drive? I for one would really like that.

**Comment by alexbakker** [comment]
Maybe. We'd have to check if that's possible.

**Comment by jovibor** [comment]
> Auto Backup of the vault to Drive

This is really a *must have* feature, along with respective import backup from GDrive.

It was a main reason/feature many people have had chosen Authenticator Plus, that is, sadly, abandoned now.

**Comment by RichyHBM** [comment]
What about deprecating unencrypted vaults, and enabling allowBackup completelly?

**Comment by alexbakker** [comment]
> What about deprecating unencrypted vaults

I don't see that happening. We don't want vaults encrypted with a weak password ending up on Google Drive by default either.

> the other option would be to have a custom backup agent

Yes, after reading into this a bit more, a custom backup agent does seem like the way to go if we decide to implement this.

**Comment by JNavas2** [comment]
@alexbakker 
1. It's one thing to warn users, but another thing entirely to nanny them.
So it's OK to warn me if you think my password is weak,
but don't presume to prevent me from using it as I see fit.
There can be valid reasons for using passwords you may think are weak.
2. I would much prefer standard Google Auto Backup to a custom alternative.

**Comment by alexbakker** [comment]
@JNavas2 

1. Nobody is talking about preventing users with weak passwords from creating backups. I was specifically talking about the __defaults__.
2. Yes, that's also what @RichyHBM and I were referring to with "custom backup agent". See: https://developer.android.com/reference/android/app/backup/BackupAgent.

**Comment by JNavas2** [comment]
@alexbakker 

That's a relief 😌
