### ISSUE TITLE
Please add qrcode compatibility for outlook Microsoft

### ISSUE THREAD

**Issue by 3xploiton3** [beemdevelopment/Aegis#559]
> com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol

I get trouble when scan qr code from outlook

**Comment by alexbakker** [comment]
Make sure you select "Setup application without notifications" when configuring 2FA in Office 365. Aegis is not compatible with Microsoft Authenticator QR codes.

**Comment by Weissnix4711** [comment]
Sorry to bump the old thread, but just to let you know, it seems Microsoft is forcing the use of their proprietary OTP system now, and removed the 'application without notifications' button.

![image](https://github.com/user-attachments/assets/c2c69059-9ad9-43c0-a32c-fdd48d3c0014)

Has there been any attempt to reverse engineer and implement the proprietary system yet, or am I just stuck using their proprietary app now?
