### ISSUE TITLE
Add issuer to confirmation when deleting an entry

### ISSUE THREAD

**Issue by RPavlik1** [beemdevelopment/Aegis#565]
It would be nice if when you delete an entry from Aegis it would prompt the following message.

Delete Entry
"Are you sure you want to delete (insert name of entry here)?"

Maybe have the option to request a password/biometric for deleting an entry as well. User could turn that feature on/off if they would like to. 

Its pretty straight forward now. I figured I would suggest it as I was hesitant to deleting an entry and didn't know if others thought the same. 

Also, great work on the app!
I just came over from google auth and really love the features everyone had implemented!

**Comment by alexbakker** [comment]
Aegis should already prompt you for confirmation before deleting an entry. Does it not do that for you? Either way, I think there are some improvements we can make on the message that is shown, but I wouldn't go as far as asking for password/biometrics.

Thanks for the kind words!

**Comment by RPavlik1** [comment]
> Aegis should already prompt you for confirmation before deleting an entry. Does it not do that for you? Either way, I think there are some improvements we can make on the message that is shown, but I wouldn't go as far as asking for password/biometrics.
> 
> Thanks for the kind words!

It gives a prompt. I was referring to a slight change to the message shown. I should have been more clear, my apologies and thanks for the reply! =)

**Comment by michaelschattgen** [comment]
I agree, the prompt can bit more clear by adding the issuer to the message.

**Comment by alexbakker** [comment]
While we're changing this dialog, let's also add a warning that deleting an entry in Aegis does not disable 2FA on your account.
