### ISSUE TITLE
Wanna add zh-TW language support and maintain zh-rCN

### ISSUE THREAD

**Issue by Jerrylum** [beemdevelopment/Aegis#575]
`zh-TW` a.k.a. `Chinese Traditional`, which we don't support right now.

If someone is planning to add traditional Chinese or is maintaining simplified Chinese, please let me know, thank you.

If there is no objection, I will make pr in a few days.

**Comment by alexbakker** [comment]
Thanks for offering to help with translating Aegis! We use Crowdin for translations and don't accept pull requests for them on GitHub anymore: https://crowdin.com/project/aegis-authenticator. Chinese Simplified is already 100% translated by another contributor, but Chinese Traditional is is still up for grabs, so perhaps you can collaborate with them.
