### ISSUE TITLE
Hide TOTP Codes with Huge Dots - A bit Obnoxiously Looking?

### ISSUE THREAD

**Issue by t-p-tan** [beemdevelopment/Aegis#579]
Hi Aegis dev team! This has been my most favorite TOTP app since last Nov.

I see the latest version (since about early this month I believe) has huge dots as hidden codes. Don't know about other users but it seems a weebit in my face and awkward for me.

Seems to give me perception that the codes will appear bigger than the title when it won't (even though I know it won't). Personally I'd prefer my code to display just big enough for me but not too huge that it is easy to read over the shoulder.

Personally I prefer either a row of simple full stops (... ...) or asterisks (*** ***) with the font size same as the actual codes. Or perhaps you can just shrink the size of the dots to make it look like roughly the size of a number per dot.

Thank you!

**Comment by alexbakker** [comment]
Thanks for the suggestion, but we don't plan on changing this. The current look was based on a suggestion in #475 and we're happy with it. We may revisit this if there are more users who have similar feedback as you.
