### ISSUE TITLE
Google and Plain Import fails

### ISSUE THREAD

**Issue by hey24sheep** [beemdevelopment/Aegis#582]
###### Info

* __Version__: Latest App
* __Source__: (Google Play/GitHub/F-Droid/?) : Google Play
* __Vault encrypted:__ Yes (with biometric unlock)/Yes/No : Yes
* __Device:__ : Honor Play
* __Android version and ROM:__ Stock Android 9 (not rooted)

###### Steps to reproduce

- Export your google auth data
- Scan that QR using another phone
- Save that QR Data into a txt file

- Select option "Import from File"
- Try importing that data as plain text in Aegis, it will fail with error : "com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol:

- Select option "Import from File"
- Try importing using "Google Authenticator", it will fail with error : "com.beemdevelopment.aegis.importers.DatabaseImporterException: android.database.sqlite.SQLiteDatabaseCorruptException:file is not a database (Sqlite code 26 SQLITE_NOTADB):, while compiling: SELECT * FROM accounts, (OS error - 2:No such file or directory) 

NOTE : Tried Importing 1 record and more than 6 records, all failed
NOTE : By default Data is url encoded, so both encoded or decoded fails. Ex: "otpauth-migration://offline?data=...data..%d.."

###### What do you expect to happen?
- Import data from that plain text file

I know this file is a txt file, as generated by QR data, in case of Google Import. So, either a documentation on how to Import from Google + Plain should be given.

**Comment by michaelschattgen** [comment]
Thanks for your report. It seems like you take a couple steps more than needed. Aegis already allows you to scan the QR code from the new transfer feature in Google Authenticator. You don't need to export the QR data first to import it in Aegis, we don't support that.

Just scan the image from Google Authenticator with Aegis and you should be good to go.

**Comment by hey24sheep** [comment]
@michaelschattgen How? I am trying to migrate on same phone. If I do "Scan Image" I get a popup saying "No apps can perform this action"

**Comment by michaelschattgen** [comment]
Can you try taking a photo of the QR code with the other phone, then scan it again from that phone with your main phone with Aegis?

**Comment by hey24sheep** [comment]
That works, thanks. But, still it would be good if there is a guide. It's not clear what is supported or not. 

Feature needed
- File import documentation (file extension for different type of imports)
- Json import
- Scan image how to? Which app is supported?

**Comment by hey24sheep** [comment]
I will create another feature request. Thank you.
