### ISSUE TITLE
The app crashes when I try to export the passwords on Aegis. 

### ISSUE THREAD

**Issue by JuckFannies** [beemdevelopment/Aegis#586]
###### Info

* __Version__: 
* __Source__: (Google Play/GitHub/F-Droid/?) f droid
* __Vault encrypted:__ Yes (with biometric unlock)/Yes/No    biometric 
* __Device:__  oneplus 7 pro
* __Android version and ROM:__ android 10 stock rom

###### Steps to reproduce export passwords

A detailed list of reproduction steps.

###### What do you expect to happen?
I expected the export file, but no such creation happened
...

###### What happens instead?
App crashes. Task closed unexpectedly
...

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment]
As said in our reply to your email: Please check https://github.com/beemdevelopment/Aegis/issues/491 and https://github.com/beemdevelopment/Aegis/issues/577. Is your setup broken in the same way as reported there? If not, could you capture a log of the crash with ADB and share it with us (https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb)?

**Comment by JuckFannies** [comment]
Thank you for the reply
It seems to be the exact same problem. I will try to re download documentsui
Thank you for the response!

-------- Original Message --------

**Comment by JuckFannies** [comment]
I reinstalled Documentsui through adb, but the app file doesn't even open. Any other methods I could use to reinstall documentsUI? Sorry for this. Thanks for the Patience

**Comment by JuckFannies** [comment]
Nevermind, it is working now! Thank you so much!

**Comment by alexbakker** [comment]
I honestly don't know how users get themselves into this situation or how to resolve it, sorry.
