### ISSUE TITLE
Automatic Cloud Backup

### ISSUE THREAD

**Issue by nagha95** [beemdevelopment/Aegis#587]
Add an automatic cloud backup option for the encrypted vault file, to a choice of providers such as Google Drive, OneDrive and Dropbox. The file would sync on any changes or updates.

This would be a pretty nice option and alternative to manual backup and local storage.

**Comment by DaVoodoo** [comment]
I second this proposal.

**Comment by StefanBrand** [comment]
And please don't forget a FLOSS option like Nextcloud or WebDAV in general.

**Comment by alexbakker** [comment]
Duplicate of #258.
