### ISSUE TITLE
Microsoft 2FA

### ISSUE THREAD

**Issue by Imveryweird** [beemdevelopment/Aegis#588]
###### Info

* __Version__: q1.3
* __Source__: (Google Play/GitHub/F-Droid/?) Fdroid
* __Vault encrypted:__ Yes (with biometric unlock)Yes
* __Device:__ Samsung s8+
* __Android version and ROM:__ 8.0 Oreo 

###### Steps to reproduce
Try to add Microsoft account in authenticator either manually or by qr code. It won't work.
###### What do you expect to happen?

... I expect the app to work with all my services. And it has except microsoft.

###### What happens instead?

This error pops up com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol

###### Log

``` is this the debug log? 

com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol

If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment]
Aegis is not compatible with Microsoft Authenticator. See: #559.

**Comment by 07416** [comment]
> Aegis is not compatible with Microsoft Authenticator.

@alexbakker Import for the app is still available in the Aegis settings...

**Comment by alexbakker** [comment]
@07416 Right. Aegis can import regular HOTP/TOTP tokens from Microsoft Authenticator. But it is not compatible with Microsoft's proprietary "PhoneFactor" 2FA solution.

**Comment by the-Arioch** [comment]
Perhaps there can be 

1) an article on Aegis web page for Microsoft, how to set it up
2) a special error message in the Aegis application for Microsoft proprietary QR Code, redirecting to that instruction page

For example there was a screenshot here: https://github.com/freeotp/freeotp-android/issues/109

I just set Aegis for live.com - i have to admit, my first attempt failed with this error and i was lost in the cold. ERROR, dead-end.

After googling this ticket i saw there is a hope. Then i googled for that FreeOTP ticket.

Then i entered account settings in live.com and there found the something like "add authenticator app",  and there indeed was a link for non-microsoft authenticars, do not remember specific name and position, and it was in Russian not in English anyway.

However this took quite a googling and on desktop computer.

For non-IT-savvy phone-user it is a dead-end.

So i vote a special case was coded into both Aegis site and app, so this specific error lead users to an actionable tutorial.

**Comment by the-Arioch** [comment]
i was not (never, actually) using Office 365

and there was - to me at least - some technicality, like URI scheme not supported.

perhaps i should have screenshotted it, but was kind of in a hurry.

----

so i think such a short notice would be of little help, it was definitely of no help to me. There to ba a page "for dummies", witch screenshots, URLs, probably updateable as Microsoft would redesign their site time and again.

i'll see later if i can reproduce it to see the exact error.

**Comment by orthzar** [comment]
> Perhaps there can be
> 
>     1. an article on Aegis web page for Microsoft, how to set it up
> 
>     2. a special error message in the Aegis application for Microsoft proprietary QR Code, redirecting to that instruction page
> 
> 
> For example there was a screenshot here: [freeotp/freeotp-android#109](https://github.com/freeotp/freeotp-android/issues/109)
> 
> I just set Aegis for live.com - i have to admit, my first attempt failed with this error and i was lost in the cold. ERROR, dead-end.
> 
> After googling this ticket i saw there is a hope. Then i googled for that FreeOTP ticket.
> 
> Then i entered account settings in live.com and there found the something like "add authenticator app", and there indeed was a link for non-microsoft authenticars, do not remember specific name and position, and it was in Russian not in English anyway.
> 
> However this took quite a googling and on desktop computer.
> 
> For non-IT-savvy phone-user it is a dead-end.
> 
> So i vote a special case was coded into both Aegis site and app, so this specific error lead users to an actionable tutorial.

I just added some [instructions](https://github.com/freeotp/freeotp-android/issues/109#issuecomment-1668510631) to that freeotp-android issue which are relevant to this issue.

In essence, there are two very similar methods to add 2FA/MFA devices to Microsoft accounts, only one of which works with non-Microsoft OTP clients (e.g. FreeOTP, OTPClient, and I would guess also Aegis).

**Comment by cschreib** [comment]
The instructions provided by [orthzar](https://github.com/orthzar) still work, though. You can set up your Microsoft account to use "another authenticator", it's not no longer an option on that specific login page.

One option is here: https://mysignins.microsoft.com/security-info
 - Click "Add sign-in method"
 - Choose "Microsoft Authenticator" (I know, just hold on).
 - Click "I want to use a different authenticator app"

Another, less confusing option is here: https://account.live.com/proofs/Manage/additional
 - Click "Add a new way to sign in or verify"
 - Choose "Use an app".
 - Click "set up a different Authenticator app".

**Comment by Weissnix4711** [comment]
> The instructions provided by [orthzar](https://github.com/orthzar) still work, though. You can set up your Microsoft account to use "another authenticator", it's not no longer an option on that specific login page.
> 
> One option is here: https://mysignins.microsoft.com/security-info

Heads up, this page may not be accessible before you first set up the proprietary 2fa. This is what I had to do, first set up the proprietary 2fa before I could swap it out for Aegis. In fact, it locked me out of all microsoft services before I set up their 2fa app.

> Another, less confusing option is here: https://account.live.com/proofs/Manage/additional

Sadly this doesn't appear to work for organisation managed accounts :(

**Comment by 2gn** [comment]
I've never tried before (I'm going to), but [this guide](https://gist.github.com/chowder/2ead734d60d84d4d15034fcce81aaaf9) might help you find the token which can be used for sane 2FA apps like aegis, although it needs some work. 

Our IT department also disables sane 2FA.
