### ISSUE TITLE
Authy import failing to import some tokens `No value for secretSeed`

### ISSUE THREAD

**Issue by netpro2k** [beemdevelopment/Aegis#589]
###### Info

* __Version__: 1.3
* __Source__: google play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ pixel 4 XL
* __Android version and ROM:__ Stock Android 11

###### Steps to reproduce

Tap "import from app", select "authy", grant root permission. Get "Aegis could not import 12 tokens". Clicking details shows repeated `org.json.JSONException: No value for secretSeed` errors.

All of the proprietary Authy tokens and several standard TOTP tokens imported successfully but the rest of the standard TOTP tokens did not. I do not see a pattern to the tokens that are failing. I tried importing with backups in authy both enabled and disabled as well as pin enabled and disabled.

**Comment by Looooooka** [comment]
Just installed Aegis, hoping to get rid of google auth and authy and...same problem.

**Comment by alexbakker** [comment]
Which services did Aegis fail to import?

**Comment by Looooooka** [comment]
Bitstamp, Binance, Mega.nz, Google, MyHSM a nd many more:

Same error on all of them:

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed

org.json.JSONException: No value for secretSeed
________________________________

**Comment by alexbakker** [comment]
I just tried to reproduce this, but was unable to. Could you share the file that's being imported (first replace the "decryptedSecret", "encryptedSecret" and any other parts that look like sensitive information)?

**Comment by tonyping** [comment]
@Looooooka @alexbakker @netpro2k I ran into the same issue, with "No value for secretSeed" occurring on approximately 2/3 of my services I tried to import. There didn't seem to be any particular rhyme or reason for the errors that really stood out, as they were all 6-digit TOTP. There might be some possible issues with the length of particular seeds, but I haven't had an opportunity to inspect them all in detail.

I ended up just using a root explorer and going into the Authy app folder itself, and copying /data/data/com.authy.authy/shared_prefs/com.authy.storage.tokens.authenticator.xml to my computer. Then I used Notepad++ with the XML tools plugin to escape the characters in the selection, exported the file as CSV, then imported the account logins/seed-value pairs to a KeepassXC database for both a long-term backup and an easier import to Aegis/ Microsoft Authenticator, etc.

If some of this procedure could be automated, I think it would solve this error issue, as well as providing a good way to make an encrypted backup of Authy seeds.

**Comment by ELT4N1N** [comment]
I also got the same issue. I have 2 Nextcloud accounts, one was imported, the other not. After looking into the Authy file, i noticed that all the accounts that could be imported had the accountType "authenticator". All the other ones had other types like "authenticator_red" or "twitter", which i think is a result of changing the icon in Authy.

So i think the importer filters somewhere for "authenticator" and doesn't consider the other types.

**Comment by dalaeance** [comment]
> EDIT: After manipulating the file and changing the accountType of an entry to "authenticator", it was possible to import that entry in Aegis.

+ 1 on this. 

I used a root explorer to copy `/data/data/com.authy.authy/shared_prefs/com.authy.storage.tokens.authenticator.xml` to the non-root part of my phone's storage, then edited the file to change `accountType` from "amazon" and "discord" to "authenticator", and the amount of failed entries was decreased by 2 (from 31 to 29). It seems, for now, this'll have to be the workaround.

Thanks, @ELT4N1N, for that tip.

**Comment by alexbakker** [comment]
Thank you all for following up. The accountType!="authenticator" observation is a good one. I'll take a look at fixing this soon.

**Comment by alexbakker** [comment]
I think #652 will fix this issue. Can someone verify this? APK: https://alexbakker.me/u/7l4l6o20ij.apk

**Comment by ELT4N1N** [comment]
I did a short test and changed some accountTypes back to something other than "authenticator" and was able to import all entries without any error.

Maybe someone should also test it with an original authy file, i don't have mine anymore.

**Comment by dalaeance** [comment]
Works like a charm! Imported all tokens from my original file without issue. The only thing I'd note is that my token for Twitch wasn't imported, but that's an "Authy account", where I get a push notification when I try to log into Twitch.

I'm assuming Aegis can't access those? I could probably fix that by turning off 2FA and re-enabling it as a standard, non-Authy specific token.

-------- Original Message --------

**Comment by cooper5005** [comment]
Happy new year everyone

**Comment by alexbakker** [comment]
@dalaeance Proprietary Authy tokens are stored in a separate file called ``com.authy.storage.tokens.authy.xml``. Aegis should be able to import that as well.

**Comment by dalaeance** [comment]
That's good to know. Thanks for the tip, @alexbakker!
