### ISSUE TITLE
Unrecognized character: 0x20 (space) when scanning QR-codes from Authenticator+ export

### ISSUE THREAD

**Issue by s1gr1d** [beemdevelopment/Aegis#593]
###### Info

* __Version__: 1.3
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Samung Galaxy S8
* __Android version and ROM:__ Android 9 / Samsung One UI

###### Steps to reproduce

1. I scanned a QR code from an Authenticator+ Export to import it into Aegis. 
2. The secret contained spaces and was something like that: `secret=10W4 CYEQ GIWH DE...` (this is obviously not my secret)
3. I got an error pop-up when scanning the QR code (see Log)
4. When adding it manually as text (with spaces), the import works.

###### What do you expect to happen?

The scan and import should work without problems. If there is a problem with space characters, the generator should normalize the secret string.

###### What happens instead?

An error message pops up and the entry cannot be imported.

###### Log

```
com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Bad secret (java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 0x20)
```

**Comment by alexbakker** [comment]
Thanks for the detailed report. If Authenticator Plus includes spaces in the secret, then that makes it invalid base32 and thus an invalid QR code. I wonder how developers come up with this stuff. We've even seen secrets encoded in base32 with dashes instead of spaces. Perhaps we should just give in and try to fix the secrets up before parsing them, like you suggested.

As a side note, you should also be able to import the exported ZIP file from Authenticator Plus directly in Aegis.

**Comment by s1gr1d** [comment]
It is a pity that there is a standard and some are just ignoring it 😬. Instagram has a secret like that (groups of 4 with spaces) and I think Authenticator Plus just saved the string as it is. 
When adding it manually it works just fine. So I think the same string-normalization process from the text import could be used for the QR-code import.

Yes, I know about the text import, thanks :)
I just had already opened the exported HTML page with the QR images and scanned them right away.

**Comment by shaicoleman** [comment]
Google Authenticator Import has the same issue

```
com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 0x20
```

**Comment by alexbakker** [comment]
This fix is included in 1.4-beta2. The final 1.4 release will be published when it's ready.

**Comment by shaicoleman** [comment]
@alexbakker , tried 1.4-beta2, and the error above is happening with that version as well

**Comment by alexbakker** [comment]
@shaicoleman Ah, I misread your reply. That would suggest Google Authenticator is also *storing* the secret in an incorrect format for some services. Could you try again with this debug APK: https://alexbakker.me/u/esik71mgxe.apk (includes the following patch: https://github.com/alexbakker/Aegis/commit/354ff3585c569bb994013336b1d8591006039768)? Does it work now?

**Comment by shaicoleman** [comment]
@alexbakker, yes, it works with that build, thanks

**Comment by alexbakker** [comment]
@shaicoleman Thanks for reporting. I've submitted a pull request.
