### ISSUE TITLE
Allow Adding Multiple OTP Entries to Group

### ISSUE THREAD

**Issue by bettyvschmartz** [beemdevelopment/Aegis#597]
Hi,

It would be good to able to multi-select OTP entries and add them to group. Maybe this would work as a bulk edit option, that would expose the only bulk operations that seem be the OTP generation window/time (which by default is 30 seconds) and the group it belongs to. 

-- BVS

**Comment by alexbakker** [comment]
We'll consider this when we tackle #27, thanks.

**Comment by NumbGnat** [comment]
> It would be good to able to multi-select OTP entries and add them to group.

I second this notion. In addition to Group, users should be able to change the Icon of the selected entries.
