### ISSUE TITLE
Is there any way to copy the text in one step ?

### ISSUE THREAD

**Issue by azoglufatih** [beemdevelopment/Aegis#606]
Hi, there I am not sure if I am right here, 
But I want to ask/request can on the App implement a feature that if I click on the text/code that it copies that because at the time I must hold on to the text then I can click on the copy icon to copy the text.

I hope I was right here.

**Comment by michaelschattgen** [comment]
You're at the right place! Aegis supports copying codes on a single tap. You can enable "Copy tokens when tapped" in the settings menu of Aegis.

**Comment by azoglufatih** [comment]
Wow, such a quick answer, I found it and it worked well thanks a lot. Such a great community 👍
