### ISSUE TITLE
Unable to import from Authenticator Plus

### ISSUE THREAD

**Issue by andrmo** [beemdevelopment/Aegis#607]
###### Info

* __Version__: 1.3
* __Source__: Google Play  
* __Vault encrypted:__ Yes with biometric unlock
* __Device:__ Pixel 4
* __Android version and ROM:__ Android 11 Build  RP1A.201005.004

###### Steps to reproduce

Attempt import from local Authenticator Plus database file

###### What do you expect to happen?

Import succeeds

###### What happens instead?

An error is reported. Detail indicates a Java FileNotFoundException on Accounts.txt after entering the authplus.db password

###### Log

```
If applicable, paste the debug log here.
(Couldn't see a log anywhere)

**Comment by andrmo** [comment]
Hmm - I see that I get the same error if I intentionally specify an incorrect master password for the Authenticator Plus database file. The password I originally specified above is correct, when used as the Master Password inside Authenticator plus.

**Comment by andrmo** [comment]
I've worked it out....

I assumed from the list of apps displayed when importing that Aegis would open the proprietary authplus.db file (the backup database file created from Authenticator Plus). But it looks like Aegis wants to use the more open .zip file created from the Export function of Authenticator Plus. Specifying that file (which does contain Accounts.txt) makes things work.

The wrinkle I had for anyone else seeing this, is that Authenticator Plus is broken for me on Android 11.  Sync via Google Drive doesn't work and neither does the Export feature... which is why I initially didn't try using that file as it was not available to me. Eventually what I did was install Authenticator Plus on an Android 10 device, sync my Authenticator Plus database to that using Drop Box and do the Export from that device, and then moved that .zip file back to my Android 11 device where I have Aegis installed. A bit convoluted, but the end results is good.

**Comment by alexbakker** [comment]
> I assumed from the list of apps displayed when importing that Aegis would open the proprietary authplus.db file (the backup database file created from Authenticator Plus).

It's a logical assumption. It'll be more clear in the next release that we're expecting the .ZIP file. See: #601.

**Comment by SimonKingZA** [comment]
I have found out that Authenticator Plus does something funky when zipping the HTML and txt files together.
Simply extract the .zip elsewhere, and rezip just the Accounts.txt (CAREFUL WITH THE SPELLING).

I know a lot of legacy Authenticator Plus users, so will inform them.

Thanks Alex and Michael for this awesome replacement.

**Comment by alexbakker** [comment]
@SimonKingZA Thanks for reporting this. The issue you're describing appears to have been introduced in d660fbc6d1aa2facfa5358d38782d92b80cb769f by updating zip4j. I'll open a PR to downgrade it.

**Comment by tonylambiris** [comment]
> I have found out that Authenticator Plus does something funky when zipping the HTML and txt files together.
> Simply extract the .zip elsewhere, and rezip just the Accounts.txt (CAREFUL WITH THE SPELLING).
> 
> I know a lot of legacy Authenticator Plus users, so will inform them.
> 
> Thanks Alex and Michael for this awesome replacement.

Between setting up a virtual Android 10 device in Android studio per @andrmo and this, I was able to successfully move my database to Aegis.

Thanks for the help!

**Comment by stieg** [comment]
Android Studio was the key for me as well.  Works well when compared to the alternative of hunting down a phone running Android 10.

Some helpful links:
* https://developer.android.com/studio - Download and main page
* https://developer.android.com/studio/run/emulator#install - How to setup the emulator.  Ensure you grab an image with google play store on it

**Comment by gutschke** [comment]
https://blog.nigelsim.org/2021-01-15-extracting-authenticator-plus/ describes how to open the authplus.db file and import it manually. Given the problems with getting any of the file format from AuthenticatorPlus, it would be amazing if Aegis supported doing this automatically. But in the meantime, the steps described in that blog are viable.

In short, AuthenticatorPlus uses an encrypted SQLite database with a very simple schema.

**Comment by alexbakker** [comment]
We very briefly supported importing Authenticator Plus database files, but removed it after we discovered that it more than doubled the APK size. More context here: https://github.com/beemdevelopment/Aegis/issues/404.

**Comment by EdyTheCow** [comment]
> https://blog.nigelsim.org/2021-01-15-extracting-authenticator-plus/ describes how to open the authplus.db file and import it manually. Given the problems with getting any of the file format from AuthenticatorPlus, it would be amazing if Aegis supported doing this automatically. But in the meantime, the steps described in that blog are viable.
> 
> In short, AuthenticatorPlus uses an encrypted SQLite database with a very simple schema.

Thank you! For anyone coming here to look for a solution, the easiest and fastest method was to use a dockerized solution the blog post above now links to (https://github.com/adiov/authplus-to-andotp-magiculator). All you have to do is provide the authplus.db file which is then converted to andOTP's backup file. Since Aegis supports andOTP, you simply import that file and you're done!
