### ISSUE TITLE
mOTP support

### ISSUE THREAD

**Issue by barni2000** [beemdevelopment/Aegis#608]
Hello,

Any chance to add mOTP support?

http://motp.sourceforge.net/

PS.: I could do more research if you need

**Comment by alexbakker** [comment]
Thanks for your suggestion. Is mOTP widely in use? Which services use it for 2FA?

If this proposal is accepted, would you like to take responsibility for implementing this?

**Comment by barni2000** [comment]
It mostly used for ssh servers, and company VPNs.
I like to implement this but unfortunately i don't have too much time.

**Comment by alexbakker** [comment]
#948 has been merged.
