### ISSUE TITLE
[Q] cli app that can use the db export directly

### ISSUE THREAD

**Issue by eadmaster** [beemdevelopment/Aegis#609]
I've found [this python script](https://raw.githubusercontent.com/beemdevelopment/Aegis/master/scripts/decrypt.py) that can decrypt a db export, but no tool to actually parse and use it to generate a TOTP token. (Basically i am looking for a tool like [andOTP-decrypt](https://github.com/asmw/andOTP-decrypt))

**Comment by alexbakker** [comment]
I think [OTPClient](https://github.com/paolostivanin/OTPClient) can import Aegis backups. Other than that, I'm not aware of any applications that support our format. However, the Python script you found should be fairly easy to extend to support generating OTP's (see: [cryptography.hazmat.primitives.twofactor.totp.TOTP](https://cryptography.io/en/latest/hazmat/primitives/twofactor.html?highlight=totp#cryptography.hazmat.primitives.twofactor.totp.TOTP)), if you don't mind getting your hands dirty.

**Comment by eadmaster** [comment]
thank you for the links, i will check the Cryptography library.

**Comment by eadmaster** [comment]
UPDATE: i've just found out that the OTPClient also include a `otpclient-cli` tool that is exaclty what i was looking for.

**Comment by scollovati** [comment]
I've created this PR https://github.com/beemdevelopment/Aegis/pull/1121 for adding a simple python script for creating TOTP codes from the encrypted vault.
