### ISSUE TITLE
Support adding entry using image of QR code

### ISSUE THREAD

**Issue by laurentlbm** [beemdevelopment/Aegis#61]
When enabling 2FA on a website, using my phone, I of course can't scan the QR code. Most websites give details to add the entry manually, but some, like Kickstarter, don't.

If we could add an entry using a picture of the QR code, you could simply take a screenshot of the website and use that.

**Comment by alexbakker** [comment]
Kickstarter is doing the right thing here, by assuming you're setting up 2FA on a different device than the one you use to access the service. That said, I'm not against adding this if we can reuse the existing QR code library that we're using.

**Comment by alexbakker** [comment]
This was implemented by #66.
