### ISSUE TITLE
Error on export/backup to Nextcloud: java.io.FileNOtFoundException

### ISSUE THREAD

**Issue by wouterVE** [beemdevelopment/Aegis#610]
###### Info

* __Version__: 1.3
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Xiaomi Mi Note 10 lite
* __Android version and ROM:__ MIUI 12.0.1 (Android 10 QKQ1.190825.002)

###### Steps to reproduce

Export or backup the vault to a folder in Nextcloud
###### What do you expect to happen?
Succesful export of the vault

###### What happens instead?

Empty .json file and the following error:

```
java.io.FileNOtFoundException:
Error downloading file:
aegis-export-20201117-083659.json
```

Additiona information: Nextcloud app version 3.14.0 RC2 (I don't think it matters because I have this problem for several months, also on my previous phone - Xiaomi Pocophone F1)

Exporting to a local folder on the phone does work.

**Comment by alexbakker** [comment]
Can you test the following patch: https://github.com/alexbakker/Aegis/commit/d67c17787b97ea7db6d4edf34b05afc10673b103? Here's a prebuilt APK: https://alexbakker.me/u/o4nyslqhpx.apk.

If the issue still occurs, please share capture the log with ADB and share it here.

**Comment by wouterVE** [comment]
i've tested the apk.

Now, making a backup does succeed.
Exporting the vault does result in the same error though.

Do you need the ADB log?  If so, I'll look up thiss weekend how to do this never done it before.

Kr. Wouter

**Comment by alexbakker** [comment]
Thanks for confirming. No need for a log. We'll be able to fix the error you're seeing while exporting with a similar fix.

**Comment by wouterVE** [comment]
Great! You're welcome.

Thanks for fixing the issue.

Kr

Wouter
