### ISSUE TITLE
Greek Translation Fixed and Completed!

### ISSUE THREAD

**Issue by giwrgosmant** [beemdevelopment/Aegis#611]
Hello,
I've fixed many incorrect words/sentences and also completed to 100% the translation in [Greek](https://crowdin.com/project/aegis-authenticator/el#).
Please merge the changes in next update.
Thanks a lot!🙂

**Comment by alexbakker** [comment]
Thanks for helping translate Aegis! Before we release an update, we always pull the latest translations from Crowdin first. No need to worry about that.
