### ISSUE TITLE
I can't import Steam over WinAuth

### ISSUE THREAD

**Issue by unLieb** [beemdevelopment/Aegis#612]
I 've been using Aeagis for a while now, and so far I'm satisfied. 

However, I still have one problem, and that is Steam. 

I still have Steam on WinAuth. Now I wanted to import this. 

However, it doesn't really work. So you can import it yourself, but the code will only contain numbers. In Steam the code consists of letters. 

Is this a bug, or is importing Steam via WinAuth not supported, or is it just me?

**Comment by alexbakker** [comment]
What does the Steam entry in the WinAuth export look like? Be sure to mask the secret before sharing anything here.

Can you try changing the type of the entry in Aegis to "Steam"? I'm assuming it's "TOTP" now.

**Comment by unLieb** [comment]
> Can you try changing the type of the entry in Aegis to "Steam"? I'm assuming it's "TOTP" now.

Ahhhhhh YES! That was it! Now i'm happy with this! Thanks dude!
