### ISSUE TITLE
Verifivation code is invalid (error) 

### ISSUE THREAD

**Issue by MadRafa** [beemdevelopment/Aegis#613]
* __Version__: 1.3
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Redmi Note 7
* __Android version and ROM:__ MIUI 12.0.2 (Android 10 QKQ1.190910.002)

###### Steps to reproduce

Import tokens from andOTP and adding new accounts. 

I decided to give it a try to Aegis and imported a few accounts from andOTP to Aegis. But now the code that Aegis shows me doesn't work to login in any of the accounts. I thought that it may be a problem of the imported files so I tried going into one of my accounts that don't have 2-factor enable and see if I can add new accounts, It doesn't let me do that either, after scanning the QR code and entering the 6-digit code always gives error. 

**UPDATE**: I thought I was doing something wrong but then I tried to experiment adding the account I was trying to add to Aegis (and was giving error) to andOTP and it was successfully added to with zero issues. So I don't think I'm doing something wrong. 

###### What do you expect to happen?

Successfully import accounts from other Authentication apps and successfully adding new accounts into Aegis. 

###### What happens instead?

"Verification code is invalid" error every time I try to login or add new accounts.

**Comment by alexbakker** [comment]
Can you do a comparison between the entries in andOTP and Aegis? Are the secrets (and the other parameters) the same? If not, how do they differ? Can you compare the codes the apps are showing for the same entry (at the same time)? How do they differ?

**Comment by alexbakker** [comment]
No response. Closing.
