### ISSUE TITLE
OpenPGP support for encrypted backups

### ISSUE THREAD

**Issue by bmarwell** [beemdevelopment/Aegis#614]
Hi,

I'm coming from andOTP and would like to request encrypted backups via OpenPGP, so I can only decrypt them via a Yubikey.

Not in a hurry, but definitely a great feature andOTP had there.

Thanks in advance! 🙂

**Comment by lynn-stephenson** [comment]
You can export the vault to a non-encrypted file, and then encrypt it with [Open Keychain](https://www.openkeychain.org/).

**Comment by alexbakker** [comment]
We don't have plans to implement this. See: #105. Also related: #336.
