### ISSUE TITLE
Yandex

### ISSUE THREAD

**Issue by williamson91** [beemdevelopment/Aegis#617]
Please add 2FA support on Yandex. Thanks for the great app!
https://play.google.com/store/apps/details?id=ru.yandex.key
https://passport.yandex.ru/profile

**Comment by alexbakker** [comment]
Can you elaborate a bit more? What would you like Aegis to support, specifically? Does Yandex use a proprietary 2FA algorithm that you'd like Aegis to support? Or do you just want to be able to import entries from the Yandex Key app itself?

**Comment by williamson91** [comment]
I just want to use Aegis instead of Yandex.Key. So that Aegis can generate 8 digit letters as Yandex.Key.
Is import like with Steam? I managed to do this via rooted Android x86 on VirtualBox. If that's the only way, then so be it.
We need the support of Yandex itself, and not other tokens from there. Others I have already driven in manually. The only problem is with Yandex itself.

**Comment by alexbakker** [comment]
I took a quick look, but it seems that Yandex uses their own proprietary solution that requires communication with their servers from the app to configure 2FA. We won't be implementing support for this.

**Comment by williamson91** [comment]
Thank you for your answer and your work. If it's difficult, then don't.
