### ISSUE TITLE
Search doesn't search "name"

### ISSUE THREAD

**Issue by Daniel15** [beemdevelopment/Aegis#625]
###### Info

* __Version__: 1.3
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Samsung Galaxy S10
* __Android version and ROM:__ Samsung stock Android 10

###### Steps to reproduce

I have around 80 accounts with two-factor auth. Many of them were originally in Authy, then imported to Authenticator Plus a few years ago, then imported to Aegis this year. A lot of these accounts have "authenticator" as the `issuer` and the site name as the `name`. For example, my 2fac code for Porkbun.com (a domain registrar) appears as `authenticator (Porkbun)` in Aegis.

This is fine, but the search feature only appears to search the "issuer" field, not the "name" field. Searching for "authenticator" finds it, but searching for "Porkbun" has 0 results. I can edit all of them to be formatted correctly, but going through 80 accounts and manually editing them one by one is a hassle.

###### What do you expect to happen?
Search should search both fields. Even for codes that properly use the issuer and name (where the `issuer` is the site name and the `name` is the username or email address), it's useful to be able to search for a username or email address and see all two-factor accounts associated with that email address

###### What happens instead?
Search for "Porkbun" has 0 results

###### Log
N/A

**Comment by alexbakker** [comment]
Try enabling "Search in account names" in settings.

**Comment by Daniel15** [comment]
Doh. I completely missed that option. So simple! Thank you :)

**Comment by alexbakker** [comment]
@michaelschattgen Perhaps we should just do this by default? (And maybe even remove the option entirely)
