### ISSUE TITLE
Improve clarity and arrangement

### ISSUE THREAD

**Issue by fdw** [beemdevelopment/Aegis#628]
I have a lot of entries in Aegis, and it's getting cumbersome to get the right one. I had hoped that groups would help with this, so that I could narrow the search space considerably. However, the only way I've found to filter by group requires three touches.

I could imagine that having tabs for groups would help a lot. Alternatively, the main view could be ordered by group first, and then by account or issuer.

**Comment by N1029676** [comment]
I came to propose the same. Two possible ways to solve this:
1. Add an option to sort by groups in addition to account and issuer. You could then have the group name appear as a headed in the list.
2. Similar to option 1, always group by groups with a header for each but make the header collapsible

**Comment by irq** [comment]
I would love to have tabs. If you could just slide anywhere on the screen to switch between them that would be great as well.

**Comment by XA21X** [comment]
#775 (app shortcuts to launch straight into groups) is an alternative solution, but progress has sadly stalled.

**Comment by bluetiger9** [comment]
A quick way to switch between groups would be really useful. :pray: 

To switch between a small number of groups, like Personal and Work, the group filter feels just too slow:
![image](https://github.com/beemdevelopment/Aegis/assets/62890262/e083efe2-681a-42b1-810c-986b9661ce61)

In fact is so cumbersome, I prefer not using the group filter at all...
