### ISSUE TITLE
Can't import Json file 

### ISSUE THREAD

**Issue by sergiodevelop78** [beemdevelopment/Aegis#629]
###### Info

* __Version__: 1.3
* __Source__: (Google Play/GitHub/F-Droid/?) FDroid
* __Vault encrypted:__ Yes (with biometric unlock)/Yes/No.  YES
* __Device: Xiaomi Mi9 
* __Android version and ROM: Android 10

###### Steps to reproduce
A exported json file can't be imported on the app.
It asks me for a password. I enter the password for the original aegis app but it shows password error or incorrect.

I just did a factory reset to my phone and now my json file can't be imported.

Please can you give some advices?

Thanks 

###### What do you expect to happen?
The Aegis app import the json file and recover all the codes.
...

###### What happens instead?
Aegis app shows the password is wrong.
...

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment]
> but it shows password error or incorrect.

Could you clarify? Does it show you an error dialog, or does it tell you that the password is incorrect?

Did you use to unlock Aegis with biometrics, or did you always type in your password? In case of the former, is it possible that you forgot the password (or accidentally entered it incorrectly twice during setup)?

To rule out an issue on Aegis' end, could you open the exported JSON file with a text editor and tell us what the "header" -> "slots" section looks like? Specifically, does the structure of "slots" contain an entry of ``type: 1``?

One last question, do you have the "Don't keep activities" option in developer options enabled?

**Comment by sergiodevelop78** [comment]
> > but it shows password error or incorrect.
> 
> Could you clarify? Does it show you an error dialog, or does it tell you that the password is incorrect?

Hello. It shows No se puede desbloquear la caja fuerte. Contraseña incorrecta.
Translation: can't unlock the security safe.
Incorrect password.

> 
> Did you use to unlock Aegis with biometrics, or did you always type in your password? In case of the former, is it possible that you forgot the password (or accidentally entered it incorrectly twice during setup)?

Before Hard reset, I always used biometrics. The password is correct. I saved on Bitwarden

> 
> To rule out an issue on Aegis' end, could you open the exported JSON file with a text editor and tell us what the "header" -> "slots" section looks like? Specifically, does the structure of "slots" contain an entry of ``type: 1``?

Opened the json file with a text editor and it shows: 

header": {
        "slots": [
            {
                "type": 2,
                "uuid": "xxxxxx",
                "key": "xxxxxxx",
                "key_params": {
                    "nonce": "xxxx",
                    "tag": "xxxxxx"
                }
            },
            {
                "type": 1,
                "uuid": "xxxxx",
                "key": 
...
...
...
...
Xxxx are values I substituted for the original values.

> 
> One last question, do you have the "Don't keep activities" option in developer options enabled?

It's disabled.


Thanks

Sergio

**Comment by alexbakker** [comment]
Thanks for the extra info. The password slot seems to be present, so that can't be the problem. Another thing you can do is use [aegis-tools](https://github.com/alexbakker/aegis-tools#usage) to try to decrypt the vault (also try the ``--unsafe`` option).

I really don't know what to tell you, we're not aware of any bugs that would render the correct password unable to unlock the vault. Are you able to reproduce this? So, by starting from scratch in Aegis, use the password you have stored in Bitwarden, export the vault, reset Aegis and then try to import the vault file.

**Comment by sergiodevelop78** [comment]
> 
> 
> Thanks for the extra info. The password slot seems to be present, so that can't be the problem. Another thing you can do is use [aegis-tools](https://github.com/alexbakker/aegis-tools#usage) to try to decrypt the vault (also try the `--unsafe` option).
> 
I followed the steps on Windows10, but can't execute the aegis-tools. How do I Install it ?

> I really don't know what to tell you, we're not aware of any bugs that would render the correct password unable to unlock the vault. Are you able to reproduce this? So, start from scratch in Aegis, use the password you have stored in Bitwarden during setup, export the vault, reset Aegis and then try to import that new vault file.

Ok, I start from scratch in Aegis, put the same password (the same stored on Bitwarden), exported encrypted, and ok.
Then, delete the App, reinstalled, and after that, imported the new aegis backup, put the password and worked.

**Comment by sergiodevelop78** [comment]
I executed the aegis-tools command, with --unsafe option, and this is the result:

python aegis_tools decrypt-vault --unsafe --input aegis-export-20201107-135223.json > db.json
Password:
Traceback (most recent call last):
  File "C:\Users\Sergio\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Sergio\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "aegis_tools\__main__.py", line 2, in <module>
    main()
  File "C:\Users\Sergio\AppData\Roaming\Python\Python37\site-packages\aegis_tools\__init__.py", line 135, in main
    args.func(args)
  File "C:\Users\Sergio\AppData\Roaming\Python\Python37\site-packages\aegis_tools\__init__.py", line 89, in _do_decrypt
    _write_output(args.output, db)
  File "C:\Users\Sergio\AppData\Roaming\Python\Python37\site-packages\aegis_tools\__init__.py", line 20, in _write_output
    print(data)
  File "C:\Users\Sergio\anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>

**Comment by sergiodevelop78** [comment]
also.

python aegis_tools decrypt-vault --input aegis-export-20201107-135223.json > db.json
Password:
Traceback (most recent call last):
  File "C:\Users\Sergio\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Sergio\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "aegis_tools\__main__.py", line 2, in <module>
    main()
  File "C:\Users\Sergio\AppData\Roaming\Python\Python37\site-packages\aegis_tools\__init__.py", line 135, in main
    args.func(args)
  File "C:\Users\Sergio\AppData\Roaming\Python\Python37\site-packages\aegis_tools\__init__.py", line 88, in _do_decrypt
    db = decrypt_vault(data, password, safe=not args.unsafe)
  File "C:\Users\Sergio\AppData\Roaming\Python\Python37\site-packages\aegis\vault.py", line 53, in decrypt_vault
    raise VaultError("unable to decrypt the master key with the given password")
aegis.vault.VaultError: unable to decrypt the master key with the given password

**Comment by sergiodevelop78** [comment]
I have tried to change the last character of the saved password, and it worked!
So finally it was not a Bug, but only that the password was not correct.

Apologies for the inconvenience caused.

Cheers,
