### ISSUE TITLE
Auto-Backup config/encrypted vault via SFTP/FTPS/WebDav/etc.

### ISSUE THREAD

**Issue by AbramTTP** [beemdevelopment/Aegis#630]
I see a few feature requests for other stuffs such as settings.

Even though I don't really add or edit my entries often, I think it would be also great if I can define an SFTP connection from Aegis so that it auto-creates encrypted .json backup and backup to a directory I wish on my NAS directory via SFTP.

Meanwhile for each update to Aegis entries, at least now it has a share button which I can use to upload to Synology Drive app. Before this I have had to save on a phone storage, and open Drive or a file explorer to copy it onto my NAS.

Yes, Currently I have a NAS at home and I also connect my KeePass to it, so my WinAuth, Aegis and KeePass kdbx are stored in there.

Thank you!

**Comment by alexbakker** [comment]
Aegis doesn't have permission to access the internet, and we'd like to keep it that way. So it's unlikely that we'll ever directly support any such protocol.

That said, Aegis does support automatically backing up the vault through Android's Storage Access Framework (SAF). Cloud provider apps can expose cloud storage through this interface, allowing other apps to write to it without having to add support for the protocol themselves. Nextcloud is an example of an app that supports this. Most other apps only support a small portion of SAF, unfortunately, but hopefully that will improve in the future.

I've been experimenting with an app that exposes WebDAV storage through SAF, to make automatic Aegis backups to WebDAV possible. It's up on GitHub in case you're interested: https://github.com/alexbakker/webdav-provider. No promises as to whether I'll ever finish/release this app, though.

**Comment by MrElliwood** [comment]
Please do not implement this request, no matter how useful this feature might be for some people. Giving network permissions to a security App would allow it to steal the 2FA secrets. I'm not saying this is going to happen, but I prefer syncing my encrypted backup using other services (I've set up NextCloud to do it). Don't add potential security issues when there is an existing solution that works just fine!

**Comment by AbramTTP** [comment]
Good point. As I said these days there is also a share button to any applications exposing storage access via Android File Explorer, so for example you can still choose Solid Explorer, Synology Drive, Google Drive etc. to redirect.

**Comment by AbramTTP** [comment]
Good point. As I said these days there is also a share button to any applications exposing storage access via Android File Explorer, so for example you can still choose Solid Explorer, Synology Drive, Google Drive etc. to redirect.
