### ISSUE TITLE
Crash when setting icon with Aegis 1.4-beta2

### ISSUE THREAD

**Issue by alanorth** [beemdevelopment/Aegis#632]
###### Info

* __Version__: 1.4-beta2 (42) 735c0867268dc18cc93d70e0c1d8cde852bfcb6f
* __Source__: GitHub
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Nokia 7.1
* __Android version and ROM:__ Android 10 (November 1, 2020)

###### Steps to reproduce

1. Open Aegis
2. Unlock with password or fingerprint
3. Open one TFA and click the generic image
4. Navigate to icon in Downloads folder and select
5. Press "Save"
6. Aegis crashes (but the icon appears correctly when I restart Aegis)

###### What do you expect to happen?

Aegis doesn't crash.

###### What happens instead?

Aegis crashes.

###### Log

```
$ adb logcat -c
$ adb logcat '*:E'
--------- beginning of crash
12-16 10:33:52.124 12526 12641 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
12-16 10:33:52.124 12526 12641 E AndroidRuntime: Process: com.beemdevelopment.aegis, PID: 12526
12-16 10:33:52.124 12526 12641 E AndroidRuntime: java.lang.IllegalArgumentException: Invalid URI: content://com.android.providers.downloads.documents/document/4311
12-16 10:33:52.124 12526 12641 E AndroidRuntime:        at android.provider.DocumentsContract.getTreeDocumentId(DocumentsContract.java:1236)
12-16 10:33:52.124 12526 12641 E AndroidRuntime:        at com.beemdevelopment.aegis.vault.VaultBackupManager.createBackup(VaultBackupManager.java:3)
12-16 10:33:52.124 12526 12641 E AndroidRuntime:        at com.beemdevelopment.aegis.vault.VaultBackupManager.lambda$scheduleBackup$0$VaultBackupManager(VaultBackupManager.java:1)
12-16 10:33:52.124 12526 12641 E AndroidRuntime:        at com.beemdevelopment.aegis.vault.-$$Lambda$VaultBackupManager$3ptLeG6cD91Qk0tghKDxPZ6BGYk.run(Unknown Source:8)
12-16 10:33:52.124 12526 12641 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-16 10:33:52.124 12526 12641 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-16 10:33:52.124 12526 12641 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
```

I tried to get the critical parts of logcat without disclosing too much personal or unrelated information. Please tell me if there is a better way to capture this crash.

**Comment by alexbakker** [comment]
Thanks for the report. This crash seems related to backups. Does the directory that you selected during backup configuration still exist? What happens if you reselect a location for backups, can you still get the app to crash?

**Comment by alanorth** [comment]
Oh! I set up backups so long ago that I didn't even remember I had set them up. Yes, if I change the backups directory I am able to set icons properly without crashing. Cheers!
