### ISSUE TITLE
Only show secrets for specific passwords or dont show them at all

### ISSUE THREAD

**Issue by brandsimon** [beemdevelopment/Aegis#633]
Good evening,
first of all thank you for your great work and all the time you put in this project.

I have a OTP-Secret which I dont want to leave my phone ever!
First I thought of a solution where I have an option to mark a secret irreversibly as locked-in. With this option set it will never be shown in the edit mask and not exported.
Later I thought it probably is useful for more people to have a password to view OTPs, but not secrets (and probably the edit is forbidden) and one password to edit and view everything.

Do you have any suggestions or other ideas for my initial problem?
Which of these solutions is more beneficial for the project and more likely to get merged?

**Comment by alexbakker** [comment]
Thanks for the kind words!

I'm not convinced having this option would add meaningful security. We already have encryption, so I'm curious what attack you have in mind that would be foiled if we added this option.

Also, what happens if you lose your device? Since the secret is locked in, do you rely on the recovery process of the website to restore access to your account? And if so, where are you storing the recovery code for the website? Wouldn't that be a safe place to store your Aegis vault as well (since that code has just as much, if not more, power than the TOTP secret)?

**Comment by brandsimon** [comment]
@alexbakker 
To be honest, my use-case is basically the other way around. I do not want to use Aegis to authenticate to a website, I want to use Aegis to authenticate the device to me (with the help of a trusted device). So only these two devices share the same secret.
Before entering a password, which can be stolen by an evil maid attack, I want to authenticate the device.

https://en.wikipedia.org/wiki/Evil_maid_attack#Any_unattended_device

**Comment by alexbakker** [comment]
Ah, interesting. There are probably better ways to solve this though, and I don't think Aegis is particularly well suited for this use case. Have you seen [Auditor](https://attestation.app/)?

**Comment by sabi0** [comment]
> I have a OTP-Secret which I dont want to leave my phone ever!

Using for this specific secret an app without edit / export / backup would give you exactly that.
For instance FreeOTP, which is backed up by Red Hat - https://freeotp.github.io/
(FreeOTP storage however is not encrypted. So the secret could be easily uncovered on a rooted phone.)

**Comment by alexbakker** [comment]
Closing this, as this is not really a use case that Aegis is suited for.

**Comment by winterdeaf** [comment]
I would like to reopen discussion on this (and on #1069, which is related).

For ideal security, the 2FA entries should reside on a device and not be exportable at all: this would guarantee that the authentication device cannot be cloned. FreeOTP does this well, but fails to consider backups at all -- devices do get lost or broken, and getting locked out of all your accounts is a high price to pay in the name of this "ideal security".

The next best thing -- and what Aegis does well -- is encrypted backups. This way, if you lose your device, you can still restore from a backup protected by your password.

What should *not* be possible is an unencrypted, silent export of entities: this is what happens with the "Transfer entities" QR (single entities or en masse from the settings), or by editing a 2FA and requesting to show a secret.
If you are forced to unlock your Aegis app (e.g. border search, violent intimate partner, fingerprint cloning), or if you are careless with leaving your device unlocked, all it takes to clone a 2FA is a couple of seconds.

Some ways to mitigate this are, in order of increasing security (but decreasing disruption to existing users):
- Implement #1069 and add a persistent red banner, which can be dismissed after a few hours by biometric authentication or typing the password, whenever an entity is transferred or a secret is shown. Your 2FA can still be cloned, but at least you will know about it.
- Add additional password authentication before showing the QR or the edit entity activity. This would make transfer as secure as backups.
- Disable entity transfer entirely, do not allow to show the secret when adding an entity.

Happy to hear what @alexbakker and the community think about this!

**Comment by Tecol87** [comment]
FreeOTP does support backups now, but has no password or fingerprint lock at all.
