### ISSUE TITLE
Importing from Google Authenticator fails with “Error: App is not installed”

### ISSUE THREAD

**Issue by gustav-b** [beemdevelopment/Aegis#638]
###### Info

* __Version__: v1.4-beta2
* __Source__: GitHub
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Google Pixel 5
* __Android version and ROM:__ 11 (Build RD1A.200810.021.A1), rooted with Magisk 21.1

###### Steps to reproduce
1. Go to Settings
2. Select “Import from app”
3. Select “Google Authenticator”
4. Prompt for giving root access to Aegis is shown, select “Grant”

###### What do you expect to happen?

Aegis should import from Google Authenticator

###### What happens instead?

Error message `Error: App is not installed` pops up.

##### Additional information
This import works in version v1.3 (also installed from GitHub APK) on same device. Google Authenticator app version is 5.10.

**Comment by alexbakker** [comment]
Thanks for the report. This will be fixed by #634.
