### ISSUE TITLE
An error occured while reading QR code

### ISSUE THREAD

**Issue by Dasonic** [beemdevelopment/Aegis#64]
No matter what QR code I scan to add 2FA (Tried multiple sites such as Discord, GitHub, Facebook) I get the error "An error occurred while reading QR code" repeatedly, and I can't add anything.

Device: Pocophone F1
OS: LinageOS

**Comment by alexbakker** [comment]
This is a bug I introduced in 0.3.2. It was fixed in 0.3.3. Which version are your using?

Unfortunately, F-Droid is still serving 0.3.2 as the latest version.

**Comment by Dasonic** [comment]
Ah that would explain it. Downloaded from F-droid. When will it be updated on F-droid?

**Comment by michaelschattgen** [comment]
Version 0.3.3 is already built by F-Droid but it hasn't been published yet. 
Besides that, F-Droid is down for a few hours now so I don't expect it to be published anytime soon.

Sorry for the inconvenience. We will update this issue whenever we see Aegis is published.

**Comment by alexbakker** [comment]
It's live.
