### ISSUE TITLE
Invalid code for Firefox account

### ISSUE THREAD

**Issue by 736b** [beemdevelopment/Aegis#640]
###### Info

* __Version__: 1.3
* __Source__: F-Droid
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Huawei Mate 20 Pro
* __Android version and ROM:__ 10, Stock

###### Steps to reproduce

1. Scan QR code on accounts.firefox.com
2. Enter generated TOTP code
3. Get message "invalid two-step authentication code"

###### What do you expect to happen?
The code should work to enable 2FA.

###### What happens instead?
Code is not accepted.

**Comment by alexbakker** [comment]
This is almost certainly a time synchronization issue. Is your device configured to automatically sync the time? Can you navigate to https://time.is on your device? How much of a difference is there between the time of your device and reality?

**Comment by 736b** [comment]
Oof, you were right. It's a relatively new system and I completely forgot to emerge chrony.
Sorry. :)

**Comment by andreyuhai** [comment]
I've just downloaded Aegis and I was trying to move all my 2FAs to Aegis however for Firefox I couldn't get it to work.
I've got the same issue as the OP. I scan the QR code, I enter the numbers generated but I get "Incorrect Two-Step Authentication Code" error.

I don't have any difference in time between my phone (Samsung A-50) and https://time.is.
