### ISSUE TITLE
Secret is not valid base32

### ISSUE THREAD

**Issue by Zigecek** [beemdevelopment/Aegis#646]
I want add Steam to Aegis, but when I type in my shared secret it will throw error: "Secret is not valid base32."

I'm typing secret in this format: xxxxxxxxxxxxxxxxxxxxxxxxxxx=

**Comment by alexbakker** [comment]
Well, is the secret encoded in base32? Or is it encoded in base64?

**Comment by Zigecek** [comment]
> Well, is the secret encoded in base32? Or is it encoded in base64?

idk, I get it from SDA [https://github.com/Jessecar96/SteamDesktopAuthenticator](url)

**Comment by alexbakker** [comment]
Probably base64 then, as the entry editing screen only accepts base32. When entering details manually, you're responsible for providing them in the correct format. Someone recently wrote a guide for moving from Steam Desktop Authenticator to Aegis: https://github.com/beemdevelopment/Aegis/wiki/Adding-Steam-to-Aegis-from-Steam-Desktop-Authenticator. I haven't tried it myself, but you could give it a shot.
