### ISSUE TITLE
[Privacy] WebView

### ISSUE THREAD

**Issue by duggalsu** [beemdevelopment/Aegis#650]
Opt out of sending metrics to Google when using WebView. Add the following to the manifest -
```
<meta-data android:name="android.webkit.WebView.MetricsOptOut" android:value="true" />
```
https://developer.android.com/guide/webapps/webview-privacy

**Comment by alexbakker** [comment]
I would expect privacy concious users to already have this disabled globally, but having Aegis opt out explicitly can't hurt. Want to submit a PR?
