### ISSUE TITLE
Import backup bug

### ISSUE THREAD

**Issue by LiberWarudo** [beemdevelopment/Aegis#653]
###### Info

* __Version__: 1.4
* __Source__: (Google Play/GitHub/F-Droid/?) F-Droid
* __Vault encrypted:__ Yes (with biometric unlock)/Yes/No Yes
* __Device:__ Redmi 3S
* __Android version and ROM:__ Android 11/Lineage 18.0

###### Steps to reproduce

I exported the vault with and without password and when I tried to import the vault from other device, it give a error "Error: file not found"

###### What do you expect to happen?

Import all my codes

###### What happens instead?

Error: file not found

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment]
Where did you export the vault to? And where did you copy it to on the other device? Aegis directly passes the URI it receives from SAF to ``ContentResolver.openInputStream``, so there's not much that can go wrong on Aegis' end here. Can you try to reboot the device you're trying to import on? Does it work afterwards?

**Comment by LiberWarudo** [comment]
I found the problem, it was Amaze file manager. So I just changed my file manager and imported my codes successfully. Thank you for your attention and sorry for this inconvenience.
