### ISSUE TITLE
Make biometric unlocking easier

### ISSUE THREAD

**Issue by deadmeu** [beemdevelopment/Aegis#656]
I have biometric unlocking enabled to more quickly unlock Aegis but am always presented with a password field to unlock by default. Tapping the "biometrics" text to switch to biometric unlocking wouldn't be a huge issue but I use a password manager and the password field is being parsed causing my password manager to throw extra text on the screen. The "biometrics" text, which I have to tap, ends up being a small target I have to accurately press every time I need to unlock Aegis.
![aegis-unlock-small-button-smaller](https://user-images.githubusercontent.com/12111013/103494606-911da280-4e2f-11eb-82a9-d323312e338b.png)

Whilst there may be an option in my password manager's app to disable this sort of thing for this specific app, I think it would be cleaner if either there was a setting to default to biometric unlocking (or even tie this functionality to the setting which enables biometric unlocking in the first place), or if the app remembered the last used unlocking method and presented that method to the user (I prefer doing it this way).

Thanks for everything so far, I look forward to using Aegis for the foreseeable future :smiley:.

**Comment by alexbakker** [comment]
You're encountering the password reminder. Try entering your password once, After that, you'll be prompted for biometrics by default until it's time for another password reminder. The reminder popup window seems to be hidden by the Autofill popup, but this was fixed in 1.4. Are you still on 1.3?

**Comment by deadmeu** [comment]
Sorry, my mistake. Yes, I was on 1.3 and had not updated to 1.4 yet. The reminder popup definitely clears up my confusion, thanks!
