### ISSUE TITLE
Dark theme is not applied in the "Scan QR code" camera activity

### ISSUE THREAD

**Issue by deadmeu** [beemdevelopment/Aegis#658]
###### Info
* __Version__: master (1bd9cf3) (also tested on 1.4)
* __Device__: Google Pixel 4 (emulator)
* __Android version and ROM__: Android 11

###### Steps to reproduce
1. Open settings
2. Set the theme to a dark theme (either Dark or AMOLED)
3. Open the camera activity with the Scan QR Code function
4. Observe a light theme bottom navigation bar (also when you enter the app switcher the app's preview uses the light theme censor)

###### What do you expect to happen?
The dark theme should persist.

###### What happens instead?
A light theme is applied in the Scan QR Code camera activity.

I'm happy to try and submit a PR with a fix, but I figured that I should open an issue first.

**Comment by alexbakker** [comment]
> Observe a light theme bottom navigation bar (also when you enter the app switcher the app's preview uses the light theme censor)

Nice catch.

> also when you enter the app switcher the app's preview uses the light theme censor

It should turn dark in the app switcher as well if you have dark mode enabled in Android globally. Is there a way to do that from within the app?

> I'm happy to try and submit a PR with a fix

This would be much appreciated!
