### ISSUE TITLE
Error when exporting to unencrypted text file.

### ISSUE THREAD

**Issue by A12341A** [beemdevelopment/Aegis#660]
I am a beta tester. When I tried to do an unencrypted text option an error popped up.

com.beemdevelopment.aegis.vault.VaultManagerException: java.io.UnsupportedEncodingException: java.nio.charset.CharsetICU[UTF-8]

**Comment by alexbakker** [comment]
Please fill out the bug report template.

**Comment by alexbakker** [comment]
OK, so apparently ``StandardCharsets.UTF_8.toString()`` doesn't produce the same result on every platform. Patch: #661. Could you test this APK and confirm that the fix works for you: https://alexbakker.me/u/kptyjyimde.apk?

**Comment by madhav-A12341** [comment]
Issue Description

App crashes during export with text option

Steps to reproduce the issue
1. Open AEGIS App
2. Tap on the elipses
3. Select settings
4. Select export
5. Select Text from drop down menu
6. Tick I understand the risk
7. Click OK.
8. Select the path of export

What's the expected result?

The vault must be exported in plain text format.

What's the actual result?

A popup opens with a message :

com.beemdevelopment.aegis.vault.VaultManagerException:
java.io.UnsupportedEncodingException: java.nio.charset.CharsetICU[UTF-8]

Additional details / screenshot

**Comment by madhav-A12341** [comment]
The AEGISDev APK works fine!
