### ISSUE TITLE
Allow hiding icons

### ISSUE THREAD

**Issue by garemu** [beemdevelopment/Aegis#662]
While I understand why #413 was rejected, I do think allowing hiding icons specifically should be considered. Perhaps this could be considered as part of the "small" view layout (I'm not sure what the differences are between it and "compact" other than a lack of borders between entries), rather than a new individual setting? I like [aegis-icons](https://github.com/aegis-icons/aegis-icons), but I inevitably end up with a mix of nice icons and duplicate generic ones for entries with no unique ones available; I'd rather just hide them than think about it at all or waste space with the default letter ones.

**Comment by alexbakker** [comment]
Implemented by #1013.
