### ISSUE TITLE
Automatically get the icon from the url by parsing the favicon

### ISSUE THREAD

**Issue by elieobeid7** [beemdevelopment/Aegis#667]
Authenticator plus has this feature, for some websites, as soon as you add a site, its logo will show up.

If this feature can be added to aegis, it would be awesome. I guess authenticator plus had a set of icon ready for the popular URLs, but what I would do is parse the favicon for each website, since I know the URL. 

I'm not an android developer so I'm not qualified to submit a pull request but something like [this](https://github.com/ohmae/touch-icon-extractor) or [this](https://stackoverflow.com/questions/54536787/unable-to-get-favicon-from-url-when-mobile-does-not-have-any-internet-or-is-it-p) or [this ](https://stackoverflow.com/a/48943601/1920003) should work I guess.

Authenticator plus feature was good, but as a web developer, I add 2fa to all websites I develop, my websites' icons won't get added automatically, whereas parsing the favicon will work on any website, and most often, the favicon is the logo.

**Comment by alexbakker** [comment]
Thanks for your suggestion, but Aegis doesn't request the internet permission and we currently don't have intentions to change that. See #509 for our plans for icons.
