### ISSUE TITLE
Support importing from ADB backup files (.ab)

### ISSUE THREAD

**Issue by sabi0** [beemdevelopment/Aegis#669]
Obtaining an ADB backup file for an app on non-rooted phone is about 3 times easier than figuring out how to extract the file with the secrets from that archive.

Aegis could offer "Import from ADB backup" option which would make it way easier to migrate to Aegis for non-rooted phone users like myself.

I would then run `adb backup ...` command and give the .ab file to Aegis after selecting which app it is for. And Aegis would take care of figuring out which file is needed and extracting it from the backup.
(It could probably even detect the application automatically by analyzing the contents of the backup.)

Here is for instance an instruction for how to obtain the FreeOTP's `tokens.xml` file:
https://thevaliantway.com/2018/08/freeotp-migration/
(TL;DR: `adb backup ...` + `dd ...` to chop off the first 24 bytes + `printf ...` to prepend the archive signature + `tar`/`gz` to extract the file)

**Comment by alexbakker** [comment]
The next version of Aegis will have the option to participate in Aegis' backup system. See #654. With that feature, you should be able to use ``adb restore`` to restore from a backup created with ADB.

**Comment by sabi0** [comment]
I suppose I did not express my idea clearly enough. (Though the description seems to be rather detailed.)

It was not about restoring from an Aegis'es own backup created with ADB. But about importing secrets from _other apps'_ ADB backups.

Currently I can import FreeOTP secrets from the `tokens.xml` file.
On non-rooted phone it would be quite a bit easier to obtain `freeotp.ab` file.

**Comment by alexbakker** [comment]
My bad, I must have skimmed your proposal too quickly.

While this might be nice to have, I wonder how many users would be served by having this feature, I doubt there are many. If I recall correctly, the .ab format also varies between devices and Android versions, so there's also a maintenance burden involved. If someone would like to take responsibility for implementing and maintaining this, let us know and we'll consider this, but I don't think we will be spending time on this ourselves.

**Comment by sabi0** [comment]
Fair enough.
I wasn't aware that .ab files differ per Android version. Manuals on the internet suggest that by some bytes manipulation they could be turned into regular .tar.gz archives.

And since Aegis already supports importing secrets from various apps' native storage files I thought taking in this "byte manipulation" part could benefit those users migrating to Aegis.

In fact this does not have to be a built-in feature. It could be a standalone app that takes an .ab file, detects if it was created for an app Aegis supports importing secrets from and extracts the corresponding "storage" file. Which could then be imported into Aegis.

As for "how many users would be served", I suppose all those who own non-rooted phones and import secrets from apps' native storage files.
And probably even more. As getting a hold of that storage file requires quite a bit of technical knowledge and e.g. access to Linux to run `dd` / `printf`. So users that were considering switching to Aegis might have turned down this idea because of the secrets transfer high complexity.

**Comment by alexbakker** [comment]
ADB backup files are often encrypted, so it's not just a matter of trimming off some bytes here and there. Decrypting the format is not rocket science, but if this is to be included in Aegis, it needs to work for everyone in all cases. That's why I think it would be quite time consuming to maintain.

> In fact this does not have to be a built-in feature. It could be a standalone app that takes an .ab file, detects if it was created for an app Aegis supports importing secrets from and extracts the corresponding "storage" file. Which could then be imported into Aegis.

If someone from the community would like to create a separate utility for this, we'd be all for that! Happy to help with any Aegis vault format related questions as well.

**Comment by sabi0** [comment]
For the sake of reference (if anyone would be picking this up), here is an open source project to convert ADB backup files into regular .tar archives: https://github.com/nelenkov/android-backup-extractor

It could also be useful for regular users:
- create a backup of your current 2FA app
- convert it to .tar using the tool above
- extract the secrets storage file
- and import it into Aegis
