### ISSUE TITLE
Import error authentication plus data

### ISSUE THREAD

**Issue by csabi23** [beemdevelopment/Aegis#670]
###### Info

* __Version__:  1.4.2
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__Xiaomi Redmi note 4
* __Android version and ROM:__7.0 NRD90M

###### Steps to reproduce

go to setting.
go to import to file
i choice authenticator plus data file (.zip)
i add password
i use biometric unlock
not import the data

###### What do you expect to happen?

restore my authenticator data to aegis authenticator

###### What happens instead?

nothing

###### Log

```
If applicable, paste the debug log here.
```
otpauth://totp/Google:accountName?secret=stripped&issuer=Google&digits=6
otpauth://totp/Dropbox:accountName?secret=stripped&issuer=Dropbox&digits=6

**Comment by alexbakker** [comment]
Please fill out the bug report template. There's a bunch of information missing.

**Comment by alexbakker** [comment]
Can you try disabling "Don't keep activities" in Developer options and report back if that fixes the issue?

**Comment by nstetter** [comment]
@alexbakker, please re-open the issue. I can reproduce the bug. Log is attached.
[debug.log](https://github.com/beemdevelopment/Aegis/files/6075643/debug.log)


###### Info

* __Version__:  1.4.2
* __Source__: Google Play
* __Vault encrypted:__ No
* __Device:__ Realme 6
* __Android version and ROM:__ 10, Stock ROM

###### Steps to reproduce


* Export a backup from Authenticator Plus via Settings -> Backup & Restore -> Export as Text and HTML
* Import from Aegis: Settings -> Import from file -> Authenticator Plus
* Select exported backup from file selector
* Input password for backup archive

###### What do you expect to happen?

Aegis imports the data

###### What happens instead?

Nothing

**Comment by alexbakker** [comment]
@nstetter The fix for this issue is not included in a release yet. Please let us know if you can still reproduce the issue on master.

**Comment by nstetter** [comment]
@alexbakker: Sorry, I didn't know you closed the issue as fixed. I thought you closed it because the original reporter didn't respond.
Could you supply me with a dev build as I am not keen on setting up a build environment right now (I have never built any android apps before) and I don't see your CI saving artifacts publicly.

**Comment by alexbakker** [comment]
@nstetter I guess that was a little unclear, so no worries. Here's an APK for you to test with: https://alexbakker.me/u/ztk5upteo8.apk.

**Comment by nstetter** [comment]
Thanks. It works with the build you sent me.
