### ISSUE TITLE
Importing the vault from Nextcloud results in a "File not found" error

### ISSUE THREAD

**Issue by closewall** [beemdevelopment/Aegis#673]
I backed up my vault to a .json file, but don't understand how to restore it. I can find the export button, but not the import. I cannot find any documentation instructing on what to do.

**Comment by alexbakker** [comment]
The import buttons are right above the export button. Tap the "Import from file" button, select "Aegis" and select the file you'd like to import when prompted.

**Comment by closewall** [comment]
Whoops.
I tried that before but it said "File not found" so I didn't think it was the right option.
Turns out its because I was importing from my Nextcloud backup folder and not local.

**Comment by alexbakker** [comment]
Actually, that _is_ an issue with Nextcloud that we should work around in Aegis. I'll reopen this to track it.

**Comment by colin-axner** [comment]
I ran into the same issue. Importing directly from my connected nextcloud instance results in "file not found"

Short term workaround: download the file and import directly from the location on the local device
