### ISSUE TITLE
Unsuccessful import from SDA

### ISSUE THREAD

**Issue by roshavagarga** [beemdevelopment/Aegis#678]
###### Info

* __Version__: 1.4.2
* __Source__: (Google Play/GitHub/F-Droid/?) GPlay
* __Vault encrypted:__ Yes (with biometric unlock)/Yes
* __Device:__ BQ Aquaris X
* __Android version and ROM:__ Android 10 / LineageOS 17.1

###### Steps to reproduce

Tried importing a json file, as instructed [here](https://github.com/beemdevelopment/Aegis/wiki/Adding-Steam-to-Aegis-from-Steam-Desktop-Authenticator), but I got the following exception:
`com.beemdevelopment.aegis.importers.DatabaseImporterException: org.json.JSONException: Value xxxxxxxxx of type java.lang.String cannot be converted to JSONObject.`

I saved the contents with Notepad++ as a json file directly, hence my confusion to the issue.

**Comment by alexbakker** [comment]
What does the contents of that file looks like (remove any info that looks secret first)? That guide was written by a community member. Neither of us actually use Steam Desktop Authenticator ourselves.

**Comment by roshavagarga** [comment]
Well, basically the only way to root is to use Magisk, which I didn't want to do, so I resorted to using SDA as a go-between for moving to Aegis entirely. The file is basically a long-ass series of what I guess is the secret code, an equals sign and then some more code.

**Comment by Seba0702** [comment]
I wrote that guide, and it works for me. Very weird, it should be the same process for everyone.

**Comment by roshavagarga** [comment]
> 
> 
> I wrote that guide, and it works for me. Very weird, it should be the same process for everyone. Did you name the file as instructed? The json file has to be named something like Steamguard-myConfig.json

Exact same name, down to a T, created the file with Notepad++.

**Comment by alexbakker** [comment]
Ah, apparently Steam Desktop Authenticator also supports encrypting that .maFile. Please make sure you're presenting a plain text .maFile to Aegis.

**Comment by roshavagarga** [comment]
@alexbakker I'd add that they need to click "Manage encryption", enter their current passkey and they just click Accept twice to remove encryption :) Thanks for the help!
