### ISSUE TITLE
Support importing from Duo

### ISSUE THREAD

**Issue by nchristensen** [beemdevelopment/Aegis#68]
Duo stores its TOTP information in its /data/data/ directory. I imported it manually but it may be helpful to users to include it as another import option. Root required of course.

**Comment by zjagoo** [comment]
@nchristensen Can you add some more details on how to import the file?  I tried "accounts.json" and accounts_backup.json" from /data/data/com.duosecurity.duomobile/files/duokit but I was getting an error. Moreover Duo is not listed as an application that the file can be imported from. Did you use andOTP?
Thanks a lot.

**Comment by nchristensen** [comment]
@zjagoo I think there is not a way to import the file currently. I opened the file in a text editor app and wrote down the OTP data (key, refresh time, length, etcetera). Then I chose the manual entry in Aegis and entered that information.

**Comment by Trung0246** [comment]
Hi, can we have a status on how this will be implemented?

**Comment by alexbakker** [comment]
I don't think anyone is currently working on this. Let us know if you'd like to pick this up!

> Seems like scanning the QR code generated exclusive for Duo did not work on Aegis.

This proposal is just about importing TOTP data from the Duo app internal database. Adding support for a proprietary Duo protocol is not planned.

**Comment by Trung0246** [comment]
Is it possible to integrate this library into Aegis: https://github.com/revalo/duo-bypass

**Comment by alexbakker** [comment]
@Trung0246 Aegis cannot support Duo's activation as we don't request the internet permission. The other parts of that library (HOTP, basically) are supported.

**Comment by alexbakker** [comment]
#835 was merged.

**Comment by anibyl** [comment]
@alexbakker can we expect a new release with these changes anytime soon?

**Comment by alexbakker** [comment]
@anibyl I wasn't planning on it as not much has changed since v2.0.2. Are you waiting for your Duo patch to be included in a release? I suppose we could do a small release some time this month.

**Comment by anibyl** [comment]
@alexbakker that would be great, thank you.

**Comment by anibyl** [comment]
@wznmickey when I did this, I needed root access to read this folder.

**Comment by wznmickey** [comment]
I do not have root access. Do you know whether there are any methods?
