### ISSUE TITLE
Codes stopped working

### ISSUE THREAD

**Issue by jwit** [beemdevelopment/Aegis#680]
###### Info

* __Version__: 1.4.2
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)/Yes
* __Device__ : Motorola Moto G8 Power
* __Android version and ROM:__ 10 

###### Steps to reproduce

Login to website, open the app to access a code, enter the code on the website.

###### What do you expect to happen?

Should be logged in to the website

###### What happens instead?

Website says code is invalid. I tried it on 6 different websites. The backup codes do work. 

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment]
This is almost certainly a time synchronization issue. Can you navigate to https://time.is on your device? How much has the clock drifted from reality? A drift of just a couple of seconds can result in outdated codes.

**Comment by michaelschattgen** [comment]
Please make sure the time on your phone is correct, a difference of more than 30 seconds can cause issues with the codes.

**Comment by jwit** [comment]
Looks like you were right. The phone was more than a minute off. I turned off time sync and turned it back on and it's correct now. Thanks.
