### ISSUE TITLE
Face Unlock support

### ISSUE THREAD

**Issue by rzippert** [beemdevelopment/Aegis#681]
According to the app description on https://getaegis.app/ face unlocking should also be an option, however I'm unable to find such feature within the app. All I could do is fingerprint unlocking in the app, but enabling face unlock on the phone itself (not aegis).

Searching through old issues didn't make it clear to me if the face unlock feature was actually available or working at some time. Is there some possible restriction on the device capabilities to make it unavailable just for some users, like non Pixel phones? Perhaps it has not been reimplemented once the biometrics API has been in use?

Thanks,

**Comment by alexbakker** [comment]
If your phone's face unlock feature is integrated with Android's biometrics system (and the implementation is considered secure enough to allow it to guard a key in the Android Keystore), it should just work by setting up biometrics in the app. There is no separate option.

Which device do you have?

**Comment by rzippert** [comment]
Asus Zenfone Max M1 (https://www.gsmarena.com/asus_zenfone_max_(m1)_zb555kl-9097.php). My phone is on Oreo (8.0). I've asked a colleague to test and had the same result as I did but with a Xiaomi Mi 9t (https://www.gsmarena.com/xiaomi_mi_9t-9738.php). He's on Android 10. We both can face unlock the device itself (all storage is encrypted), but in aegis, by enabling biometrics (both at setup and later via the settings menu) we only get a fingerprint option (it just straightly asks for me to touch the fingerprint sensor).

I will try debugging it with Android Studio (actually, I already have it running in the emulator), but would appreciate a little pointer on what to look for, if that's possible.

**Comment by rzippert** [comment]
If you can give me a reference of phones that are known by you to work with the face unlock (nothing fancy, just some models you may have seen working), I might be able to get one to check it too. If it's a cheap model I might even buy one...

**Comment by alexbakker** [comment]
I don't think debugging will get us more information. Apps can't ask Android for a specific type of biometric authentication, they can just ask for secure biometric authentication in general and Android takes care of which sensor to use.

What happens if you disable fingerprint in the settings of Android (make sure you have not forgotten your Aegis password first)? Can you now set up face unlock in Aegis or is the biometric unlock option disabled?

**Comment by IiroP** [comment]
Many Android manufacturers have implemented Face unlock using the selfie camera. That's not, however, usually considered secure enough, so these devices won't support it as a biometric authentication method for apps.

Some technical info of different levels of Biometric Sensors (from Android 11 compatibility definion):
https://source.android.com/compatibility/android-cdd#7_3_10_biometric_sensors

**Comment by carboncopy1** [comment]
@alexbakker. I'm using a Pixel 4 (which only has IR based face-unlock for biometric authentication) on GrapheneOS's latest stable release . Unfortunately, Aegis doesn't appear to support unlocking via this method. When I go into settings the _Biometric Unlock_ option is greyed out. All permissions have been granted to Aegis.

**Comment by alexbakker** [comment]
@carboncopy1 Do you have face unlock configured to unlock your device? That's also a requirement.

**Comment by carboncopy1** [comment]
@alexbakker yes I do. I am using it at the moment. Just checked the app again but still no luck. I may have had face unlock disabled when I installed the app. Do you think this problem might be fixed if reinstall?

**Comment by alexbakker** [comment]
@carboncopy1 Strange, we've heard from multiple users that face unlock in Aegis works fine on their Pixel 4. I wonder if this has something to do with GrapheneOS. Can you attach a debugger and check what ``canAuthenticate`` returns here: https://github.com/beemdevelopment/Aegis/blob/master/app/src/main/java/com/beemdevelopment/aegis/helpers/BiometricsHelper.java? Perhaps we should make that value visible in the UI somehow.

**Comment by carboncopy1** [comment]
@alexbakker Do I have to paste the code that you've linked into an application like termux? I've never used a debugger before.

**Comment by alexbakker** [comment]
@carboncopy1 In that case, it's probably easier to try this APK https://alexbakker.me/u/ihxo1dn0cm.apk, record the log of you navigating to the biometrics settings in the app and share the log here. See our guide on how to capture a log with ADB: https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb.

**Comment by carboncopy1** [comment]
@alexbakker . Thank you for the instructions. 
[debug.log](https://github.com/beemdevelopment/Aegis/files/5949859/debug.log)

**Comment by alexbakker** [comment]
According to the log ``canAuthenticate`` returns ``1`` on your device:

```java
/**
 * The user can't authenticate because the hardware is unavailable. Try again later.
 */
public static final int BIOMETRIC_ERROR_HW_UNAVAILABLE = 1;
```

**Comment by carboncopy1** [comment]
@alexbakker what do you think this means? Is most likely an issue with GrapheneOS?

**Comment by rzippert** [comment]
> When I go into settings the Biometric Unlock option is greyed out. All permissions have been granted to Aegis.

For me it is greyed out while I do not encrypt my database. Once it's encrypted with a password, the biometric unlock becomes available (after all, it should just save this password in the secure store, and allow it to be retrieved through the biometric authentication)...

Isn't that the case with you? Another test that was mentioned was to remove fingerprints from the phone biometrics, leaving only the face unlock option registered. With this the phone should be forced to use face unlock as a biometric option.

Didn't work for my phone (which is a very cheap one, I'm not surprised), but I really believe it should be working at least on the Pixel 4...

**Comment by carboncopy1** [comment]
@alexbakker . I figured out the issue for me. I had not enabled app sign in with face unlock in my Android settings. Now that it has been unlocked, everything works perfectly. Sorry for the confusion. 
@rzippert have you tried this?

**Comment by alexbakker** [comment]
@carboncopy1 Thanks for confirming.

Since this is reportedly working fine on the Pixel 4, I'll close this. We don't have any device-specific code for biometrics, so any device that has a Class 3 face unlock sensor is expected to work.
