### ISSUE TITLE
Biomatric error

### ISSUE THREAD

**Issue by 3xploiton3** [beemdevelopment/Aegis#682]
###### Info

* __Version__: 1.4.2
* __Source__: (Google Play)
* __Vault encrypted:__ Yes (with biometric unlock)/No
* __Device:__ redmi note 5
* __Android version and ROM:__ 10

###### Steps to reproduce

A detailed list of reproduction steps.

###### What do you expect to happen?
After update rom unlock biomatric got error
...

###### What happens instead?
![Screenshot_2021-02-02-23-41-17-619_com.beemdevelopment.aegis.jpg](https://user-images.githubusercontent.com/19517680/106633716-a7935700-65b1-11eb-97df-62e5632caa3a.jpg)
...

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment]
Please report this issue to the maintainer of your ROM.

**Comment by 3xploiton3** [comment]
@alexbakker other app with biometric 
For example ms authenticator work properly,

So i think its because aegis only

**Comment by alexbakker** [comment]
Microsoft Authenticator probably doesn't perform biometric authentication the way we do (i.e. protecting an Android Keystore key with biometric authentication). See #332 and #364.
