### ISSUE TITLE
Browser Extension to receive codes in clipboard

### ISSUE THREAD

**Issue by blurayne** [beemdevelopment/Aegis#684]
Seen on other authenticators.

Chrome/Firefox Extension

1. Tap copy on shown code in app 
2. Browser Extension receives code 
3. Code is copied to clipboard
4. Or better: website is remembered and extension knows where to paste the code and clicks submit (maybe default set? Maybe let user add via spath)

**Comment by alexbakker** [comment]
Duplicate of #674.
