### ISSUE TITLE
Export to remote storage (eg. NAS) 

### ISSUE THREAD

**Issue by darrylgibbs** [beemdevelopment/Aegis#689]
It seems the auto export is only to SD cards. Is it not possible to add a remote location? Or even better yet, have it upload to that location once it becomes available?

**Comment by alexbakker** [comment]
Aegis supports backing up to any Android Storage Access Framework location. If your cloud provider (Nextcloud, for example) participates in this framework, or you have a different client app that does, Aegis will be able to use it for backups. Another common setup is backing up to a folder on your device and having Syncthing sync it to one of your other devices (like a NAS, for example).

There are no plans to add support for specific protocols or cloud providers.
