### ISSUE TITLE
Adding Cross-Platform Support via Syncing

### ISSUE THREAD

**Issue by mbeps** [beemdevelopment/Aegis#691]
Cross-platform support via the web can be added. The current implementation for backing up can be used for syncing.
The backup file will be automatically generated and uploaded into the cloud. Users can host it using services such as Google Drive, OneDrive, Dropbox, etc. The clients will check the drives for any recent backups.

**Comment by alexbakker** [comment]
We currently don't have plans to port Aegis to other platforms. See the existing closed issues about this.
