### ISSUE TITLE
Opening screen biometric unlock

### ISSUE THREAD

**Issue by davemaxd** [beemdevelopment/Aegis#693]
- Version: 1.4.2
- Source: Google Play
- Vault encrypted: Yes (with biometric unlock)
- Device: Xiaomi A2 Lite
- Android version and ROM: Android One 10 

Hi, I am a big fan of the Aegis 2FA app and use it a lot for all my 2FA. Therefore, I open the app quite regular on my phone and have one proposal:
When you open the app the keyboard is automatically activated and preventing me to click the ‘biometric’ unlock link. Steps I take after opening the apps are: 

1.	Remove keyboard (move down)
2.	Click biometric link
3.	Use biometric fingerprint unlock

Proposal: If biometric unlock is activated don’t show the keyboard but directly show the ‘decrypt the fault with biometric screen’, ready to accept you fingerprint. This saves 2 clicks every time. This is normally how other apps work if fingerprint unlock is activated (e.g. protonmail app).

Alternative proposal: move the link for biometric unlock a little higher on the home screen. Allowing you to click the biometric link without moving the keyboard down first. 

Keep up the good work!

**Comment by alexbakker** [comment]
You're probably seeing the password reminder. Try entering the password once. After that, Aegis should prompt for biometrics immediately until it's time for another password reminder.
