### ISSUE TITLE
wiki python-bna usage

### ISSUE THREAD

**Issue by whismerhill** [beemdevelopment/Aegis#695]
I'm unable to complete the wiki guide on bna usage
https://github.com/beemdevelopment/Aegis/wiki
step 2 : "bna new" gives nothing
I did the pip install successfully
(pip3 list shows bna, click & pyotp)
I tried through regular windows command line & through python itself
I also did a search for "bna" and I only find it in libraries e.g.  .\Python38\Lib\site-packages\bna\*.py

Is something missing from the wiki ? 
I guess I'm too much of a newbie maybe ?

Thanks.

**Comment by alexbakker** [comment]
Please ask for support upstream if you're having issues with bna: https://github.com/jleclanche/python-bna.

**Comment by whismerhill** [comment]
I thought I was being a newbie, turns out it was an issue with bna itself. Thanks for pointing me there. @alexbakker
