### ISSUE TITLE
Enlarge "biometrics" authentication button

### ISSUE THREAD

**Issue by avi12** [beemdevelopment/Aegis#698]
I use Android's biometrics authentication instead of a password. If I accidentally let the phone automatically lock on me, it's quite tedious to keep pressing the small "biometrics" button-link.

**Comment by alexbakker** [comment]
You shouldn't have to press that button all the time. Aegis should just prompt you for biometrics immediately. Are you seeing the password reminder by any chance? Try entering your password once. After that, Aegis should prompt you for biometrics by default until it's time for another password reminder.

**Comment by avi12** [comment]
I don't remember setting a password.
I use the biometrics feature every time I want to login.

**Comment by alexbakker** [comment]
In that case, make sure you change the password in settings. It is the primary way of access to your vault.
