### ISSUE TITLE
Add a Tutorial on how to add Steam Authenticator to Aegis

### ISSUE THREAD

**Issue by Bush-cat** [beemdevelopment/Aegis#699]
Steam is not a standard TOTP or HOTP which is why I couldn't figure out how to add it.

**Comment by alexbakker** [comment]
If you have root access, Aegis can directly import from the Steam app. Otherwise, some users have had success following this guide: https://github.com/beemdevelopment/Aegis/wiki/Adding-Steam-to-Aegis-from-Steam-Desktop-Authenticator.
