### ISSUE TITLE
[question] how to make aegis work with my website?

### ISSUE THREAD

**Issue by atesin** [beemdevelopment/Aegis#700]
hi ..  forgive me if i am asking dumb questions ...  this is the first time i know there are apps like this ...  before i thought the way to do it was to **buy** rsa's secureid's

i have a personal website wrote by me (i am not a developer) with some sections secured by login (a minecraft server, a forum, an online password repository for my mother, some others)

i would like to know how to add 2fa for my webpages throught this app, if can be done ... thanks

**Comment by alexbakker** [comment]
This question is outside of the scope of Aegis. We only handle the client side. You'll want to look up [TOTP](https://tools.ietf.org/html/rfc6238) and implement that as additional step in the authentication process of your website. If you do that, and display a [Google Authenticator-compatible QR code](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) for Aegis to scan during the setup process, it will work with Aegis.

**Comment by atesin** [comment]
ok i see ...
...  one more thing ... could you please add this answer to some documentation or faq? .. i imagine there will be a lot of newbies like me that will have the same question

thanks

**Comment by alexbakker** [comment]
The feature list already mentions that Aegis supports TOTP/HOTP and that it is compatible with Google Authenticator

**Comment by atesin** [comment]
aaand...  that *that* is the way you can make aegis work with *your* site.... so go search info about totp algorithm <--- that is not mentioned in the docs

( sorry but i want to have nothing to do with google please ... otherwise i had downloaded google authenticator not aegis )

**Comment by alexbakker** [comment]
The README links to the TOTP RFC, which has all the information you need.

**Comment by atesin** [comment]
thanks for the timely info... you could additionally specify in the readme *** the way to make aegis work with YOUR site is to implement totp *** , i didnt knew that... currently it only says "thousands of services"...

just a little clarity for people like me, that run little services (online gaming, some other project, invention, etc.) and want to secure it but know nothing about 2fa....  it could also help to raise aegis popularity (and spawn some tutorial in the future maybe?)

thanks
