### ISSUE TITLE
Import from Google Authenticator not possible

### ISSUE THREAD

**Issue by l0drex** [beemdevelopment/Aegis#701]
###### Info

* __Version__: 1.4.2
* __Source__: F-Droid
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device__: Honor 8x
* __Android version and ROM:__ Android 10 with EMUI 10.0.0

###### Steps to reproduce

1. Go to settings and select _Import from file_
2. Select Google Authenticator. The message asks to select a copy of _/data/data/com.google.android.apps.authenticator2/databases/databases_ in the internal storage.
3. Search for the directory.

###### What do you expect to happen?

I expected to find a directory _/data/data_.

###### What happens instead?

The directory _/data_ only contains a directory called _immersv_.
I also looked at _/Android/data/_, which contained several folders named _com.google.android..._, but no folder for the Google Authenticator. I then searched through the whole internal storage and the sd card for a folder named _com.google.android.apps.authenticator2_, also with no luck.

Am I missing something?

###### Log

```
If applicable, paste the debug log here.
```

**Comment by l0drex** [comment]
If the file/directory doesn't exist anymore, a solution might be to take screenshots of the Qr codes that the Google Authenticator App can generate and scan them with the app.

**Comment by l0drex** [comment]
###### Some Additional information

- I'm using version 5.10 of Google Authenticator
- I used the app lock feature. I deactivated this after I couldn't find the directory, however nothing changed.

**Comment by alexbakker** [comment]
The directory ``/data/data`` and its children can only be accessed as the root user. If you don't have root access on your device, importing directly from Google Authenticator is not possible. As mentioned, using Google Authenticator's export feature and scanning the QR codes displayed with Aegis will also work.

**Comment by l0drex** [comment]
Oh, that makes sence. I thought that it is possible to do this without root access because it says _requires root access_ only in the option _Import from app_ and not in _Import from file_.

**Comment by sshcrack** [comment]
# Solution for non-rooted devices
I discovered a solution on how to transfer your accounts from _Google Authenticator_ to _Aegis_ **without** having to **root* your device.

## Prerequisites
- Download the release zip file from [scrcpy here](https://github.com/Genymobile/scrcpy/releases/tag/v1.17) [Instruction](https://i.imgur.com/42uQvlG.png)
- Extract the archive you downloaded [Instruction](https://i.imgur.com/OWY7ydu.png)
- [Enable USB Debugging](https://www.kingoapp.com/root-tutorials/how-to-enable-usb-debugging-mode-on-android.htm) on your Phone

## Steps to import
- Execute _scrcpy.exe_ from the folder you extracted the archive to [scrcpy](https://i.imgur.com/EJNVWY6.png)
- Now you should see an window showing up. **If not** take a look at _Troubleshooting_
- Open Google Authenticator
     - Click on the three dots in the top right corner [Corner](https://i.imgur.com/GnBahDo.png)
     - Click on _Transfer accounts_
     - _Export accounts_ (Export)[https://i.imgur.com/N2dQ09K.png]
     - Select the accounts you want to transfer to Aegis
     - Click _Next_
- Now, take a screenshot on your computer from scrcpy
- Open the screenshot you've just taken
- Open Aegis
     - Now, click on the plus (bottom right) [Button](https://i.imgur.com/IKhyxxx.png)
     - Select Scan QR Code
     - Now scan the qr code on your computer and you should be ready to go!
 
# Troubleshooting
## No window pops up for scrcpy
- [Explorer top](https://i.imgur.com/ezTC3d5.png) Click at the top and type cmd and hit enter (Make sure you are in the scrcpy folder)
- A cmd window should pop up
- Now, issue `scrcpy -m1024` and hit enter
- It should work now, if not, contact me

**Comment by sheeepdev** [comment]
Helped a ton! THanks @sshcrack

**Comment by sshcrack** [comment]
> Helped a ton! THanks @sshcrack

yw @sheeepdev
