### ISSUE TITLE
Producing Invalid codes even with time "synced"

### ISSUE THREAD

**Issue by DragonSlayer1514** [beemdevelopment/Aegis#702]
###### Info

* __Version__: 1.4.2
* __Source__: Github
* __Vault encrypted:__ Yes no biometrics
* __Device:__ Fiio M7
* __Android version and ROM:__ Custom 7.0 firmware

###### Steps to reproduce

Install the app
add the secret key

###### What do you expect to happen?
It should produce a code that works
...

###### What happens instead?
 it doesn't produce a working code, but other devices it works
Also, it adds equal signs to the secret when i check the secret key
This also doesn't work on andotp
I have synced the clock because there is not auto time sync option
...

###### Log

```
If applicable, paste the debug log here.
```

**Comment by DragonSlayer1514** [comment]
Also, i am using this android device because 
1. it can't access wifi so it cant be hacked that way
2. even if it does get hacked, aegis is encrypted

**Comment by alexbakker** [comment]
Please navigate to https://time.is on that device and check how much the clock deviates from reality. Even a couple of seconds can result in incorrect codes.

**Comment by DragonSlayer1514** [comment]
Yes, i synced with that, and its almost exaclty on the second

**Comment by alexbakker** [comment]
Since you're experiencing that other authenticator apps also produce incorrect codes, this must be a time synchronization issue. Please double check that the date is also correct.

> Also, are the default settings of sha 1 and 30 seconds normal?

Did you change those settings? Most services use SHA-1 and a period of 30 seconds, so making changes here will likely result in incorrect codes.

**Comment by DragonSlayer1514** [comment]
yes the date is also synced, but i dont change the the advanced settings because i thought it wouldve changed something.

**Comment by DragonSlayer1514** [comment]
Also i forgot to mention, i am able to access internet using ethernet

**Comment by alexbakker** [comment]
Can you try scanning the QR code at https://2fas.com/check-token/? Compare the code Aegis generates to the one displayed on the website. If they're not the same, there's still something wrong with the time settings on your device.

**Comment by alexbakker** [comment]
No response.

**Comment by indeedwatson** [comment]
@alexbakker hi, I don't know if I should make a new issue cause I'm having this same problem, specifically with discord, haven't tried any other apps.

Time was slightly off in my pc and i fixed it. It's 0.5s off in my phone, but I don't know how to fix that (already turned off/on automatic sync multiple times).

However checking the website you provided, the code is right. But no matter what, when I put the Discord code in Discord, it never accepts it as valid.

What can I do?

**Comment by alexbakker** [comment]
The fact that the code displayed on the website is the same as Aegis displays tells us the time on your device is correct. That's all you need. Discord is known to work with Aegis, so something else must be going on here.

Did you already have 2FA enabled for Discord and is it suddenly rejecting codes? Or are you stuck during the setup phase of 2FA for Discord? In case of the latter, try starting from scratch. Remove the entry in Aegis and rescan the QR code that Discord displays during 2FA setup.

**Comment by indeedwatson** [comment]
I was indeed trying to enable it. I removedthe code and then did it via the web interface instead of the standalone app and it worked. Thanks!
