### ISSUE TITLE
Common Site Icons/Logos

### ISSUE THREAD

**Issue by ncodee** [beemdevelopment/Aegis#703]
Could we have icons/logos for common sites integrated into Aegis instead of all of these Icon pack nonesense?

Nearly all 2FA apps on the Play Store have icons for popular sites such as Google, Amazon etc. Any reason why Aegis hasn't implemented it yet?

**Comment by alexbakker** [comment]
See #509 for our plans for icons.

**Comment by ncodee** [comment]
> See #509 for our plans for icons.

I have checked that post, but it's referring to Icon packs. I am asking for popular icons to be implemented inside Aegis without having to download your own icons and import them.

**Comment by alexbakker** [comment]
As [said](https://github.com/beemdevelopment/Aegis/issues/509#issuecomment-739547440) in the linked issue, once icon packs supported has landed, we'll consider including an icon pack by default.
