### ISSUE TITLE
UI Suggestion: Show Total Number of Entries (Either Main Screen or Filter List)

### ISSUE THREAD

**Issue by AbramTTP** [beemdevelopment/Aegis#704]
As I maintain the habit of enabling 2FA for every possible account available, I found myself wanting to suggest this because:

1. Easy to also tally against the total number of my TOTP secret stored in my password database (my password manager does display the number of entries in any entry groups)
2. I have up to 3 authenticators running now: This Aegis on my Android, WinAuth on Windows 10 and Yubikey Authenticator on Fedora which also acts as a backup for all platforms and devices (but limited to 32 entries in the Yubico hardware key so I have to decide on essential accounts only)
3. Some of my TOTPs may not be available on all 3 platforms: TOTPs meant for Linux forums, apps, and so on, won't be on my WinAuth. And only WinAuth supports Blizzard Authenticator. I believe Aegis now has the most entries out of all 3 of my authenticators so it is the closest to the grand total on my password manager.

Maybe at least made it an optional feature listed in settings and that'll also be fine too.

(P/S: I current have 40-50 accounts with 2FA enabled, and from my last inspection I still have 10 more on my password manager marked as "pending 2FA setup".)

**Comment by alexbakker** [comment]
Implemented here: #973.
