### ISSUE TITLE
Root access to move Authy xml file

### ISSUE THREAD

**Issue by outofstep314** [beemdevelopment/Aegis#706]
I am trying to gain root access to move the Authy xml file from my old android device to my new one. I understand I need root access to do this, but I was wondering the best way to go about getting root access? I tried using a few root explorers, but every time I looked into the com.authy.authy directory, there was nothing there.

**Comment by alexbakker** [comment]
Providing support for obtaining root access is not really in the scope of this project. Look into installing Magisk or something similar.
