### ISSUE TITLE
Security Question : how is encryption password stored while using biometric

### ISSUE THREAD

**Issue by Chidhambararajan** [beemdevelopment/Aegis#707]
Thanks for the amazing app

I use this app to stroe my 2fa data securely , I have setup fingerprint biometric in Aegis
I observed that the fingerprint authenciation decrypts vaults temporarily for access

But where is the encryption key stored? is it stored as plaintext somewhere?
If so , can someone get know the encryption key if they had physical access to my device , by reading the device flash or something like that? That would fail the very need of the encrypted 2fa vault

If that is the case , is it advisable to use biometrix authenciation?
If I dont have biometric authenciation enabled , would the encryption password not be stored in device?

**Comment by alexbakker** [comment]
The following document should answer all of your questions: https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md.
