### ISSUE TITLE
Add an option to automatically ask for biometrics instead of clicking on the option.

### ISSUE THREAD

**Issue by ncareau** [beemdevelopment/Aegis#710]
Hello,

Here is a small quality of life improvement I would love to see since I use this app more than 20-25 times a day.

I'm using the biometrics feature to unlock my database. When the vault is locked, and I open the Aegis app, the current behaviour is that I am redirected to the password entry page where there is a very small button to use biometrics. Since the app open the keyboard by default, i sometimes have to scroll to click the biometrics button. 

I would love an option where if activated (this option would be off by default) the app will automatically ask me for my biometrics when the app is opened and the vault is locked. That way, I don't have to scroll down and click the button to open the biometrics login. If the biometrics fails or if I want, I can go back to the password prompt page.

Thank you,
Awesome software btw.

**Comment by alexbakker** [comment]
You're probably seeing the password reminder. Try entering your password to unlock the app once. After that, Aegis will prompt for biometrics by default again.

**Comment by ncareau** [comment]
You're right, it works after entering the password. But i didn't get any reminder or anything. Care to elaborate what the reminder is about ? I didn't have to change it or anything, just reentering it worked.

**Comment by alexbakker** [comment]
Strange, you should have gotten a popup telling you to enter your password. Should look similar to this (old screenshot, but the popup is still there):

[<img width=300 src="https://alexbakker.me/u/115z6be7go.png">](https://alexbakker.me/u/115z6be7go.png)

Are you seeing something different?

**Comment by ncareau** [comment]
Can't really check right now since it's prompting me directly the biometrics, but if I get the same behavior, i'll be sure to make a note and screenshot so that I can verify.

Thank you very much for the information, really appreciate the help.

**Comment by ncareau** [comment]
Hi @alexbakker

Just to update my feedback on this issue. I'm using the AMOLED theme and the message box has a black background on the already black background, making it difficult to see that there is a new message. Also, the message quickly disappear, so that's why i missed it originally. 

Not sure if it requires a change or not, just wanted to share my experience.  Awesome job on the software, thanks again.
