### ISSUE TITLE
Aegis vanishes from recent apps when locking the vault

### ISSUE THREAD

**Issue by DerEnderKeks** [beemdevelopment/Aegis#714]
###### Info

* __Version__: 1.4.2
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Oneplus 5
* __Android version and ROM__: Android 10/OxygenOS 10.0.1

###### Steps to reproduce

1. Open Aegis
2. Unlock vault
3. Press back button/lock device

###### What do you expect to happen?

Aegis should lock the vault and remain in the recent apps

###### What happens instead?

Aegis vanishes from the recent apps.

---

It seems like you do this intentionally, but I'm not sure if the actual behavior is intended. Imo it should just lock the vault while the app remains active, and the unlocking page is displayed again when you return to the app.

https://github.com/beemdevelopment/Aegis/blob/230f21b9f0c242ef5b584a273440cb088fc70e3f/app/src/main/java/com/beemdevelopment/aegis/AegisApplication.java#L158-L167

**Comment by alexbakker** [comment]
Thanks for your detailed report, but this is expected behavior. It's a consequence of the way we had to implement auto lock.

**Comment by DerEnderKeks** [comment]
That kinda sounds like a shortcut to me. I assume it would have been more work to implement it the way I proposed but the current behavior just seems a little odd. That an app vanishes from the recent apps list is just not how you would expect an app to behave..

Shouldn't it be possible to stop the app without removing it from the recent app list? I just tried to manually force stop Aegis and afterwards the app was locked again while still being in the list. This way you could basically keep the current (rather lazy 😉) method of locking the app, while not making the behavior feel weird.

**Comment by alexbakker** [comment]
It certainly does seem like a shortcut, but it's not about unwillingness to do more work. We simply have not found a better way to implement this because of all of the intricacies of activity lifecycle in Android.

If you see an opportunity to replace the existing logic with something that does keep the app in the recent apps list, please submit a pull request.

**Comment by KaKi87** [comment]
Hi,

Any news on this ?

It's really annoying to have to re-open the app from launcher when needing to copy multiple codes in a row while still wanting the app to lock itself after each copy.

Thanks

**Comment by KaKi87** [comment]
> It's a consequence of the way we had to implement auto lock.

How about finding another way that doesn't have this bug ?

I'm not an Android dev so I don't know what those ways would be.

The thing is, I had to disable automatic locking because of this issue.

Thanks

**Comment by alexbakker** [comment]
Did you read the comments above? If we had found another way to do this we would have implemented it.

**Comment by KaKi87** [comment]
Yes I've read, but almost two years have passed since you *have not found a better way to implement this*.
Did anyone check whether there could be one nowadays ?
Thanks

**Comment by michaelschattgen** [comment]
Correct. We have not found a better way to implement this.

As we've said before, we're open for any pull requests from people that have found a better way to do this.

**Comment by KaKi87** [comment]
Turns out this is an issue that Ente Auth doesn't have, so the solution should be in their source code ?

**Comment by alexbakker** [comment]
@KaKi87 Unfortunately their auto locking mechanism is riddled with bugs. I played around with the app for 10 minutes and now I find myself drafting an email to security@ente.io.

**Comment by vishnukvmd** [comment]
Hey @KaKi87, one of the folks working on Ente Auth here.

Please note that Auth's lockscreen unlike Aegis, does not introduce a layer of cryptographic security. It only acts as a barrier to prevent unauthorized access, and does not handle the threat model of someone gaining root access to your device. I haven't looked into the implementation details, but this is a distinction that could be resulting in the current behavior for Aegis.

And thanks to @alexbakker for reporting issues, they've now been fixed 🙏

**Comment by michaelschattgen** [comment]
I don't understand where you got the idea that we don't want to fix this. We can't just magically pull a solution out of thin air. The fact that @alexbakker went into Ente's source code proves my point and shows that we're not unwilling to fix this. We've been very clear about that.

**Comment by KaKi87** [comment]
> I don't understand where you got the idea that we don't want to fix this.

The issue was closed saying *this is expected behavior*.
