### ISSUE TITLE
Biometric unlock greyed out after upgrading from Android 10 to Android 11 (LineageOS)

### ISSUE THREAD

**Issue by fredddd1** [beemdevelopment/Aegis#717]
###### Info

* __Version__: 1.4.2
* __Source__: F-Droid
* __Vault encrypted__: Yes
* __Device__: Nextbit Robin
* __Android version and ROM__: LineageOS 18.1 (Android 11)

###### Steps to reproduce

- Have a working Aegis with biometric unlock on Android 10.
- Upgrade to Android 11.
- No longer have a working Aegis with biometric unlock. :(

###### What do you expect to happen?

For biometric unlock to not be greyed out  in the settings.

###### What happens instead?

Biometric unlock is greyed out. ;(

**Comment by alexbakker** [comment]
If the biometrics option is greyed out in Aegis, Android apparently no longer reports the fingerprint sensor as a strong biometric authenticator. Can you try the following APK: https://alexbakker.me/u/uk5kgaa0vd.apk? It is based on master and has a more recent version of the AndroidX Biometrics library. I don't think it's likely to fix your issue, but it's worth a shot.

If the issue remains, please report it upstream.

**Comment by fredddd1** [comment]
It did not work for me. I also can not unlock the app on first try with password:

- I enter my password
- It keeps showing the loading bar indefinitely
- If I put the app into the background, and forward again, and login again (password still filled in but no longer loading), it unlocks

Has this application been tested on Android 11?

**Comment by alexbakker** [comment]
Thanks for reporting back. One last question before I send you upstream. Did you set up screen lock in the settings of Android and a enroll a fingerprint? That's required in order for apps to be able to use biometrics.

> I also can not unlock the app on first try with password

This is not uncommon when running debug builds.

> Has this application been tested on Android 11?

Yes, the app is widely in use on Android 11.

**Comment by fredddd1** [comment]
> Thanks for reporting back. One last question before I send you upstream. Did you set up screen lock in the settings of Android and a enroll a fingerprint? That's required in order for apps to be able to use biometrics.
> 
> > I also can not unlock the app on first try with password
> 
> This is not uncommon when running debug builds.
> 
> > Has this application been tested on Android 11?
> 
> Yes, the app is widely in use on Android 11.

It was set. But just to be sure I disabled it and enabled it again.

I can unlock my device with my finger just fine. I just can no longer select it in Aegis Authenticator while it was working wonderful before the upgrade.

**Comment by fredddd1** [comment]
Are there any logs I can inspect to see as to why biometric identification is being suddenly rejected on my system?

**Comment by fredddd1** [comment]
Apparently this is an issue with LineageOS for Nextbit Robin and it should be fixed in an update next Sunday:
https://review.lineageos.org/c/LineageOS/android_device_nextbit_ether/+/307314

I will be testing it and closing this ticket if it is indeed resolved.

**Comment by fredddd1** [comment]
Resolved with latest LineageOS update.
