### ISSUE TITLE
Facebook QR Code is not recognized

### ISSUE THREAD

**Issue by jbwyatt4** [beemdevelopment/Aegis#718]
###### Info

* __Version__: 1.4.2
* __Source__: F-Droid
* __Vault encrypted__: Yes (password)
* __Device__: Pixel 3a
* __Android version and ROM__: Android 11, Stock, Android security update on March 5 2021

###### Steps to reproduce

Choose app based 2FA on Facebook.
Facebook shows QR code to scan on my monitor.
Open/unlock Aegis.
Press the plus button->choose 'Scan QR code'.
Get prompted to Allow Aegis to take pictures and record video?->choose 'Only this time'.
Aegis shows my camera output.
Focus camera on the Facebook QR code.

###### What do you expect to happen?

For Aegis to detect the QR code. Or report any errors?

###### What happens instead?

Nothing

Tried moving the camera closer to the screen and pulling back the camera from the screen.

Tried turning the camera 90 degrees.

Tried backing out of the selection and going back into app authentication to make a new QR code.

QR code scanning has worked on this phone with this monitor for almost every website I have tested as I am a recent user. Facebook is the first site I have had trouble with.

###### Log

Please give instructions on how to get the log if needed.

**Comment by alexbakker** [comment]
I tried to create a throwaway Facebook account to try to reproduce your issue, but it was disabled instantly after creation for violating their community standards. Are there other websites where Aegis is having trouble scanning the QR code on your device? I have a device with the same camera (Pixel 3a XL) and am not seeing issues.

**Comment by jbwyatt4** [comment]
Thank you for letting me know.

No other websites have had this issue. I have setup 9 set up so far with Aegis.

**Comment by alexbakker** [comment]
This is kind of hard for us to reproduce unless someone can share a screenshot (for a dummy account, of course) of a QR code that Facebook displays during 2FA setup.

Do you have some kind of dark mode enabled for Facebook that might make the QR code invalid, by any chance?

**Comment by jbwyatt4** [comment]
I tried Facebook's QR code again today and it worked. Both times I believe were in dark mode.

I do not know why it worked this time. Either an issue on Facebook's end or the night color mode for KDE (limits blue light-I think I may have adjusted since I filed this bug)?

Thank you for your help and your time. Closing this issue.
