### ISSUE TITLE
Bad 2 factor or recovery code 

### ISSUE THREAD

**Issue by jpalcantara** [beemdevelopment/Aegis#719]
Hello,

  Apparently the Aegis authenticator does not work with Microsoft Azure and another site.  It pretty much forces you to install Google Authenticator or the Microsoft version in which it defies the purpose of using this application that I use for everything.  

Any thought?

**Comment by alexbakker** [comment]
Can you be more specific about the issue you're seeing?

If you select "Setup an application without notifications" during setup of 2FA for your Microsoft account, you'll be able to use Aegis.

**Comment by alexbakker** [comment]
No response.
