### ISSUE TITLE
Aegis biometrics unusable on Samsung S10e

### ISSUE THREAD

**Issue by RMRubert** [beemdevelopment/Aegis#720]
###### Info

* __Version__:  16Jan2021
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock), but never managed to get it
* __Device__: Samsung S10e SM-G970F
* __Android version and ROM__: Android: 9 | One UI: 1.1 | Kernel: 4.14.85-16668332

###### Steps to reproduce

Open Aegis, select biometric, try to set up. You can't pass the password input.

###### What do you expect to happen?

Use biometrics to create Vault

###### What happens instead?

Can't create vault, app locked on password

###### Log

Not possible

**Comment by alexbakker** [comment]
> You can't pass the password input.

Why not? What happens?

**Comment by RMRubert** [comment]
From the user point of view: you put two passwords. click on the arrow, and the app doesn't do anything. Like it isn't responding or buggy.

**Comment by alexbakker** [comment]
Thanks for clarifying. There was a known device-specific issue in ``androidx.biometrics`` where the biometrics prompt would not be shown. That library has since been updated, so this will be fixed in the next release of the app.
