### ISSUE TITLE
Entering password second time is not visible during encrypted backup

### ISSUE THREAD

**Issue by fredddd1** [beemdevelopment/Aegis#722]
###### Info

* __Version__: 1.4.2
* __Source__: (Google Play/GitHub/F-Droid/?) F-Droid
* __Vault encrypted__: No
* __Device__: Nextbit Robin
* __Android version and ROM__: LineageOS 18.1

###### Steps to reproduce

Try to make an encrypted export and enter the password a second time.

###### What do you expect to happen?

For the password to show up in the box while typing.

###### What happens instead?

It does not appear while the keyboard is up.

**Comment by alexbakker** [comment]
Can you make a screenshot or screen recording of what you're seeing? It's not exactly clear to me what the issue is.

**Comment by fredddd1** [comment]
At this stage I am entering the password a second time for verification. You can see that the text field is not visible during entry because of the keyboard, and you are unable to scroll.

![Screenshot_20210414-150142](https://user-images.githubusercontent.com/80743272/114714477-70b88a80-9d32-11eb-80fc-d4f6ddc37c69.png)

**Comment by alexbakker** [comment]
Thanks for clarifying. I've fixed this by making the dialog scrollable.
