### ISSUE TITLE
Can't change group if the last one is deleted

### ISSUE THREAD

**Issue by orangenbaumblatt** [beemdevelopment/Aegis#723]
###### Info

* __Version__: 2.0-beta1
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: OnePlus 6
* __Android version and ROM__: 10

###### Steps to reproduce

1. Make sure that there are **no** groups and >2 entries (the group button on top is not visible)
2. Put one entry in a new group
3. Filter for that group (one entry is shown)
4. While the filter is active edit the entry and remove the group
5. No entries are shown and the group button is also hidden

###### What do you expect to happen?

All group filters should be removed if there are no groups left.

###### What happens instead?

The group filter remains even if there are no groups left. There is no way to reset the filter other than restarting the app.

**Comment by alexbakker** [comment]
Thanks for the report, I'm able to reproduce this.
