### ISSUE TITLE
[v2.0-beta1] Can't import SVG separately (only with icon packs)

### ISSUE THREAD

**Issue by krisu5** [beemdevelopment/Aegis#724]
###### Info

* __Version__: v2.0-beta1
* __Source__: Github
* __Vault encrypted__: No
* __Device__: Android Studio 4.1.2, custom device (1080x1920 resolution, API 30, with Google APIs, x86)
* __Android version and ROM__: Android 11, no play store

###### Steps to reproduce

1. Add [SVG](https://github.com/aegis-icons/aegis-icons/tree/master/SVG) to download folder or whatever
2. "Add new entry", add text to "Name" field
3. Select SVG from the download folder

###### What do you expect to happen?

Icon to show up as it is, possible to save the entry with icon.

###### What happens instead?

Icon preview just looks white. After pressing checkmark at right, app crashes and reopens.

**Comment by alexbakker** [comment]
This is an oversight on my part. Will implement this for the next beta release. Thanks for the report!
