### ISSUE TITLE
[v2.0-beta1] Icons from the iconpack turn into grey after scrolling

### ISSUE THREAD

**Issue by krisu5** [beemdevelopment/Aegis#725]
###### Info

* __Version__: v2.0-beta1
* __Source__: Github
* __Vault encrypted__: No
* __Device__: Android Studio 4.1.2 and 4.1.3, custom device (1080x1920 resolution, API 30, with Google APIs, x86)
* __Android version and ROM__: Android 11, no play store

###### Steps to reproduce

1. Download [iconpack](https://github.com/aegis-icons/aegis-icons/releases/tag/2021-04-10)
2. Import it
3. "Add new entry", add text to "Name" field
4. Go to "pick a icon" dialog
5. Scroll back and forth

###### What do you expect to happen?

Icons to stay the same

###### What happens instead?

Some of the icons turn into dark grey circles after scrolling past them or already is dark gray. When selecting the icon, it shows normally.

Sometimes it fixes self momentarily or different set of icons turn into dark gray.

Icon shows correctly on the dialog when searching by the name.

**Comment by alexbakker** [comment]
Thanks for the report. I must have missed this while making the switch to CircleImageView to work around a different issue. If I change the icon card back to using a regular ImageView, the issue disappears.

I'd like to get rid of CircleImageView and use ShapeableImageView from Material Components instead eventually. If we see this issue in other places in Aegis as well, we'll have to prioritize that.
