### ISSUE TITLE
Scan QR Code Not Working on v2.0-beta1

### ISSUE THREAD

**Issue by tERyceNzAchE** [beemdevelopment/Aegis#726]
###### Info

* __Version__: v2.0-beta1
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock: Yes)
* __Device__: Samsung S20 FE
* __Android version and ROM__:  Android 11

###### Steps to reproduce

Adding a new entry by scanning QR code launches the camera, but fails to detect the QR Code being displayed on the screen.
Tried with both rear and front camera.

###### What do you expect to happen?

QR Code should be detected/decoded.

###### What happens instead?

Screen continues to show a live image.

**Comment by alexbakker** [comment]
Is this the first time you're seeing this problem, or was it also present in a previous release?

**Comment by tERyceNzAchE** [comment]
I did not encounter this issue in the previous release.

**Comment by arnoudius** [comment]
I'm currently experiencing the same issue. It does start the camera but it doesn't seem to recognize the QR code.

**Comment by alexbakker** [comment]
Can everyone who's seeing this issue install the following debug APK (based on [this branch](https://github.com/alexbakker/Aegis/tree/camerax-debugging)): https://alexbakker.me/u/ruboavhpb5.apk? Please try to scan [a dummy 2FA QR code](https://dan.hersam.com/tools/gen-qr-code.php) and:
1. Capture a log of you reproducing the issue using ADB.
2. With the QR code in view, press "Capture" at the top left. This will capture what the image analyzer is seeing and store it in your gallery.
3. Share the log and captured image here.

I'm wondering if this has something to do with the resolution. So, please also try the following APK: https://alexbakker.me/u/8yg5afek3o.apk and report whether that improves anything.

@arnoudius Which device do you have?

**Comment by tERyceNzAchE** [comment]
Where is the log stored?

**Comment by alexbakker** [comment]
@tERyceNzAchE See https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb for how to capture a log using ADB.

**Comment by tERyceNzAchE** [comment]
Tried both builds, neither fixes the issue.

**Comment by alexbakker** [comment]
Thanks for letting me know, but that doesn't help much, please also provide the other information I asked for.

**Comment by tERyceNzAchE** [comment]
Here are the 2 QR code images:
https://wormhole.app/GpKO3#SLKGYfXSVvh0i6XJ4MgJEg

Unable to capture log files.

**Comment by arnoudius** [comment]
I captured a debug log + image while trying to reproduce this issue using the first debug app (ruboavhpb5.apk), see results below. I also tried the second debug app (8yg5afek3o.apk), and when I use that one, it's seems be working again for me! 

- [debug.log](https://github.com/beemdevelopment/Aegis/files/6320649/debug.log)
- [Image captured](https://user-images.githubusercontent.com/1765231/114927225-88c30380-9e31-11eb-84e5-8b1713e7cf04.jpg)
- [QR code used](https://user-images.githubusercontent.com/1765231/114927855-39c99e00-9e32-11eb-9580-348b8c78a97d.png)

I'm using a Oneplus 5t running LineageOS 17.1.

**Comment by tERyceNzAchE** [comment]
Tested again, this time with debug log.

[1618521837245](https://user-images.githubusercontent.com/53383122/114940292-78416780-9df6-11eb-9302-bf2aee718f29.jpg)
[debug.log](https://github.com/beemdevelopment/Aegis/files/6321205/debug.log)

**Comment by alexbakker** [comment]
Thank you both for sharing your results. At least we now know that we're not getting corrupt images from CameraX and that the resolution that was selected is reasonable. That doesn't make the situation any less confusing though, and it doesn't help that I'm a little out of my depth when it comes to QR code scanning.

I may be able to get a hold of a OnePlus 5t, so hopefully I'm able to reproduce the issue with that and work on a solution from there. Will keep you posted.

**Comment by damajor** [comment]
Same issue on Samsung S5 (klte) with LineageOS and latest Aegis from FDroid.

**Comment by alexbakker** [comment]
We've purchased a second-hand OnePlus 5T and were able to reproduce the issue. Could you guys test scanning a QR code with the following debug APK and report back: https://alexbakker.me/u/4makb5vvdn.apk?

It's based on this patch: https://github.com/alexbakker/Aegis/commit/36cffa1b9a4cb648292dee8e31403563b992a60f. For certain resolutions the image data that CameraX gives us contains padding on certain devices and ZXing doesn't support that. By removing the padding, hopefully the issue will be gone for everyone.

**Comment by tERyceNzAchE** [comment]
> We've purchased a second-hand OnePlus 5T and were able to reproduce the issue. Could you guys test scanning a QR code with the following debug APK and report back: https://alexbakker.me/u/4makb5vvdn.apk?
> 
> It's based on this patch: [alexbakker@36cffa1](https://github.com/alexbakker/Aegis/commit/36cffa1b9a4cb648292dee8e31403563b992a60f). For certain resolutions the image data that CameraX gives us contains padding on certain devices and ZXing doesn't support that. By removing the padding, hopefully the issue will be resolved for everyone.

Working for me!
Samsung S20 FE / Android 11

**Comment by Brian-Chow** [comment]
This is also working for me -- I don't have access/recall which QR's were giving me issues before, but the test one posted above did not scan with the production build and did with the sideloaded apk.

Thank you!

**Comment by damajor** [comment]
Seems working with the latest apk you have provided. But I was surprised that it still brings the camera instead of the barcode scanner I have installed. Anyway if it is builtin I am satisfied :)

**Comment by arnoudius** [comment]
It's also working again for me, when using the latest debug app. Thanks for looking into this / fixing the issue :)

**Comment by alexbakker** [comment]
Excellent! Thank you all for reporting back. We'll do a couple of other small unrelated bug fixes and release a v2.0-beta2 soon.

**Comment by alexbakker** [comment]
[v2.0-beta2](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta2) is out!
