### ISSUE TITLE
add support for sharing text to Aegis

### ISSUE THREAD

**Issue by pokegamer5547** [beemdevelopment/Aegis#729]
since the share image is not supported  by all browsers, having the ability to long press and share key to Aegis would be great. because copying key to clipboard is not good for security.

**Comment by alexbakker** [comment]
Sounds good to me. Feel free to send a patch!

**Comment by pokegamer5547** [comment]
> Sounds good to me. Feel free to send a patch!

I'm not an developer actually so ig I can't really help :/ I really want to tho because I'm so interested usually in supporting open source apps.

**Comment by alexbakker** [comment]
Implemented by #961.
