### ISSUE TITLE
App Unresponsive To Fingerprint Scan and Does Not Recognize Correct Typed Password

### ISSUE THREAD

**Issue by FreddyFlint** [beemdevelopment/Aegis#733]
Info

Version: 1.4.2 
Source: F-Droid
Vault encrypted: Yes (with biometric unlock) Yes
Device: Google Pixel 3
Android version and ROM__: Android 11, GrapheneOS Build # RQ2A.210405.005.2021.04.22.20

Steps to reproduce
1. Click on Aegis icon to start app.
2. App opens to "Unlock the vault" page and displays field for alpha/numeric password input. At the bottom of the page there is a message that says, " A change in your device's security settings has been"
3. Touch fingerprint reader on back of phone. No response from app.
4. Input password manually into field (copy and pasted from Keepass). Message displayed that reads, "Couldn't unlock vault. Incorrect password. Make sure you didn't mistype your password."

A detailed list of reproduction steps.
See above.

What do you expect to happen?
I expected the app to open with either the fingerprint scanner or the manual entering of the password.
...

What happens instead?
App unresponsive to fingerprint scan and doesn't verify correct password entered. 

...

###### Log

```
If applicable, paste the debug log here.
```

**Comment by FreddyFlint** [comment]
> Is that all you see? Does it not display the full "_A change in your device's security settings has been detected. Please go to 'Aegis -> Settings -> Security -> Biometric unlock' to disable and re-enable biometric unlock._" message?

This is correct, the full message that I see is " A change in your device's security settings has been" the rest is truncated. In addition "AEGIS AUTHENTICATOR" is superimposed over the truncated message. I did rescan my fingerprint recently as I was frequently getting times when the fingerprint reader was not authenticating it. Unfortunately I deleted the original one. Am I correct in assuming I can't get into the menu you're describing unless I can actually get into the app?

> We are not aware of any bugs that would render the correct password unable to unlock the vault. Are you 100% sure the password is correct? When was the last time you unlocked Aegis with your password? Or is this your first time entering it since initial setup of Aegis?

I am 99.9% sure that the password is correct. It is the password that I used when I originally set up the app and cut and pasted it from Keepass into the app. I checked in Keepass to see if there was a history of the password being changed and it has not been. I certainly used the app for sometime with that password before I switched on the biometrics. I do not remember ever changing the password. It's been about a couple of weeks since I used the app and I can't remember if I changed the fingerprint before or after I rescanned my fingerprint.

Thanks for your quick reply and your help with this issue.

**Comment by alexbakker** [comment]
> Am I correct in assuming I can't get into the menu you're describing unless I can actually get into the app?

That's correct.

> I am 99.9% sure that the password is correct. It is the password that I used when I originally set up the app and cut and pasted it from Keepass into the app. I checked in Keepass to see if there was a history of the password being changed and it has not been. I certainly used the app for sometime with that password before I switched on the biometrics. I do not remember ever changing the password. It's been about a couple of weeks since I used the app and I can't remember if I changed the fingerprint before or after I rescanned my fingerprint.

Strange. It [wouldn't be the first time](https://github.com/beemdevelopment/Aegis/issues/629#issuecomment-747056237) someone made a mistake even though they're using a password manager though. I don't really know what to tell you. Do you have a backup file of your vault that you could inspect?

**Comment by FreddyFlint** [comment]
> Strange. It [wouldn't be the first time](https://github.com/beemdevelopment/Aegis/issues/629#issuecomment-747056237) someone made a mistake even though they're using a password manager though. I don't really know what to tell you. Do you have a backup file of your vault that you could inspect?

I do have a backup file from last December. How would I go about trying to open it? It's currently on a NAS device. I can certainly get it onto the phone, but to which folder on the phone? And how would I point the app to it if I can't get into the app settings?

**Comment by alexbakker** [comment]
You can install the following APK and try to import the vault backup file there: https://alexbakker.me/u/y69zexp5a9.apk. It's a debug build of v1.4.2 and it has a different package name, so it will not overwrite your current Aegis installation.

Also, could you open the backup vault file with a text editor and describe to us what the "header" -> "slots" section looks like? Specifically, does the structure of "slots" contain an entry of type: 1?

**Comment by FreddyFlint** [comment]
> You can install the following APK and try to import the vault backup file there: https://alexbakker.me/u/y69zexp5a9.apk. It's a debug build of v1.4.2 and it has a different package name, so it will not overwrite your current Aegis installation.

Cool. I'll work on this tomorrow and will report back my results.

> Also, could you open the backup vault file with a text editor and describe to us what the "header" -> "slots" section looks like? Specifically, does the structure of "slots" contain an entry of type: 1?

Here's a redacted copy/paste of the code in the file. If there is a particular value you need let me know.

{
    "version": 1,
    "header": {
        "slots": [
            {
                "type": 2,
                "uuid": "*****",
                "key": "*****",
                "key_params": {
                    "nonce": "*****",
                    "tag": "*****"
                }
            },
            {
                "type": 1,
                "uuid": "*****",
                "key": "*****",
                "key_params": {
                    "nonce": "*****",
                    "tag": "*****"
                },
                "n": 32768,
                "r": 8,
                "p": 1,
                "salt": "*****",
                "repaired": true
            }
        ],
        "params": {
            "nonce": "*****",
            "tag": "*****"
        }
    },
    "db": "*****"

**Comment by alexbakker** [comment]
Thanks, that's the structure we'd expect. Let us know how the import of your backup vault file goes.

**Comment by alexbakker** [comment]
Any luck?

**Comment by alexbakker** [comment]
No response.
