### ISSUE TITLE
Support PIN code for unlocking vault

### ISSUE THREAD

**Issue by Javanmardi** [beemdevelopment/Aegis#736]
Aegis offers Password and Fingerprint to unlock the vault. Password is stronger and deployed to encrypt the vault and Fingerprint is handy in most situations. But sometime Fingerprint just won't work (slightly sweaty or dirty hands in summer or cold days in winter) therefore I believe it is necessary to have a PIN code option.
And yes it is less secure but there is no need to encrypt the metadata with it; you can ask the user to unlock vault with password after each system (Android) restart and use the PIN within the session so each restart requires the password.

At last, I must mention great app folks. Full feature set and nice looks.

**Comment by alexbakker** [comment]
Thanks for the kind words!

With the "Use PIN keyboard on lockscreen" option enabled, using a PIN should be a little more user friendly. We don't have plans to support or encourage usage of a PIN beyond that.

**Comment by Javanmardi** [comment]
> Thanks for the kind words!

My pleasure. It was true by the way.


> We don't have plans to support or encourage usage of a PIN beyond that.

I usually generate random strings for my password though I thought it might be the case for others. I kind of like the Bitwarden approach for PIN by the way.

**Comment by RobinSchapendonk** [comment]
> I usually generate random strings for my password though I thought it might be the case for others. I kind of like the Bitwarden approach for PIN by the way.
yeah same, I wish Aegis would have this feature
