### ISSUE TITLE
Allow search to find Issuer

### ISSUE THREAD

**Issue by keganlance** [beemdevelopment/Aegis#738]
When searching, the app doesn't look for matches with the Issuer, this is very useful for people with many accounts.

**Comment by alexbakker** [comment]
It actually does look for issuers. Are you sure you don't mean account name?

**Comment by keganlance** [comment]
My bad, I mean the account name indeed! Thanks

**Comment by alexbakker** [comment]
Thanks for clarifying. There's an option to enable search in account names calles "Search in account names".

The next version (currently in beta) won't have that option anymore, as Aegis will look for both the issuer and account name by default.
