### ISSUE TITLE
Biometrics prompt not showing at launch

### ISSUE THREAD

**Issue by ncodee** [beemdevelopment/Aegis#741]
###### Info

* __Version__:  2.0-beta2
* __Source__: Google Play
* __Vault encrypted__: Yes
* __Device__: Pixel 2XL
* __Android version and ROM__: Android 11

###### Steps to reproduce

Launch Aegis app

###### What do you expect to happen?

The fingerprint prompt should be automatically prompted, instead of having to press 'or tap here to use biometrics' every time you launch the app.

###### What happens instead?

Does not open biometrics/fingerprint prompt on app launch.

**Comment by alexbakker** [comment]
You're probably seeing the password reminder. Try entering your password once. After that, Aegis will start prompting for biometrics by default again until it's time for another password reminder.

**Comment by ncodee** [comment]
Just to update, no message was shown when being logged out using 'Password Reminder'.

**Comment by SirLupus** [comment]
> It should show a popup saying: "Please enter your password. We occasionally ask you to do this so that don't forget it.". Was that not happening on your device?

Was not happening for me, too. Lol, I was a little annoyed after clicking on "use biometrics" for months I wanted to open a feature request. Search first for biometrics and stumbled over this issue. Seems I was not alone with this issue.

Can confirm that after entering your password manually, it will now show the biometrics screen as intended.

**Comment by ncodee** [comment]
@alexbakker Could this issue be reopened with the confirmed issue above?
