### ISSUE TITLE
Request support for this app

### ISSUE THREAD

**Issue by TinkMingKing** [beemdevelopment/Aegis#743]
https://github.com/HyperSine/forensic-qqtoken
If there is any need, I will help.

**Comment by alexbakker** [comment]
What, specifically, would you like Aegis to support?

**Comment by TinkMingKing** [comment]
QQ Security Center app, in the link is its dynamic password algorithm, I hope to support it, I can provide the required files, it is a bit like steam, using my own algorithm.

**Comment by TinkMingKing** [comment]
> What, specifically, would you like Aegis to support?

QQ Security Center app, in the link is its dynamic password algorithm, I hope to support it, I can provide the required files, it is a bit like steam, using its own algorithm.

**Comment by alexbakker** [comment]
We don't have plans to implement this, sorry.
