### ISSUE TITLE
Add option for single undated backup file

### ISSUE THREAD

**Issue by alerque** [beemdevelopment/Aegis#745]
I understand where the current system of multiple dated backup files comes from and this might be a reasonable default for most people, but for my use case it is profoundly obnoxious. My backup location versions every incoming file anyway and has a system of snapshots at decaying frequencies. Additionally I save copies of by OTP key data it Git at manual intervals that matter.

Having a minimum of 5 dated json file names coming and going is just producing notification noise and extra work for me to find the current one to manually archive. Could there be a "zero" option that just overwrites a single backup file?

(I say this having just having discovered that the last 3 weeks worth of backups for my andOTP keys were corrupt due to a bug affecting that app on my version of Android. If that was just a single backup file I would have been screwed out of having anything at all, so I realize my idea **should NOT** be the default. My backups snapshots did save me and I was able to rewind to just before the corruption started and only lost one token for good, for an account for which I had recovery keys.)

**Comment by alexbakker** [comment]
A similar proposal was rejected previously (see: #712). I think your use case is more compelling though. What we could do is introduce a "Versioning strategy" option where you can configure either "None" or "x number of versions" . The latter being the default and "None" coming with a set of warnings.

**Comment by alerque** [comment]
That would be an agreeable resolution for my use case.

**Comment by himanshu-mahendra-jain** [comment]
@alexbakker @r3dh3ck Thanks for adding this. It works great for single backup / individual export. Can it be added for auto backups?

**Comment by alexbakker** [comment]
@hj-collab This is an option specifically for automatic backups.
