### ISSUE TITLE
can not import 2FAS app's *.json to Aegis

### ISSUE THREAD

**Issue by leo2n** [beemdevelopment/Aegis#747]
---
name: "Bug report"
about: "Create a report to help us fix a bug"
labels: bug
---

###### Info

* __Version__:  1.4.2
* __Source__: (GitHub)
* __Vault encrypted__: No
* __Device__ Xiaomi Mi 9T Pro:
* __Android version and ROM__: Android  10  and MIUI Global 12.0.5 Stable

###### Steps to reproduce
1. Export `keys.json` file from 2FAS App.
2. Open Aegis, click: "Import from file" --> "Plain text", nothing imported and return Aegis homepage.
3. Click "Import from App", 2FAS not in this list

###### What do you expect to happen?
Could you tell me how to import from 2FAS to Aegis? Thank U very much!
...

###### What happens instead?
Directly return to Aegis homepage and nothing imported
...

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment]
Importing from 2FAS was not supported in v1.4.2. It is supported in v2.0 (currently in beta).

**Comment by leo2n** [comment]
Thank You very much !!!
