### ISSUE TITLE
Is there anywhere to donate?

### ISSUE THREAD

**Issue by krathalan** [beemdevelopment/Aegis#75]
Pretty much title. Liberapay (https://liberapay.com/) would be great.

**Comment by alexbakker** [comment]
Thanks for the suggestion. We may start taking donations at some point in the future, but we want to let Aegis mature a bit first before doing so.

**Comment by alexbakker** [comment]
We now have [a page](https://www.buymeacoffee.com/beemdevelopment) on Buy Me A Coffee! If you'd like to support our work, feel free to do so.
