### ISSUE TITLE
Outline for Issuer on Add new entry / edit entry is cut off when system font size is set to Small

### ISSUE THREAD

**Issue by justsomemate** [beemdevelopment/Aegis#751]
###### Info

* __Version__: 2.0
* __Source__: Google Play
* __Vault encrypted__: Yes
* __Device__: Google Pixel 4a
* __Android version and ROM__: 11 / Stock (Build number RQ2A.210505.002)

(I also tested on a Nokia 6.1 with the same result)

###### Steps to reproduce

1) (Android Settings) > Display > Advanced > Font size > Set to Small
2) Open Aegis
3) Go to add an entry manually or edit an existing entry

###### What do you expect to happen?
The text field outline for all text fields is displayed properly.

###### What happens instead?
The text field outline for Issuer is cut off.
<img src="https://user-images.githubusercontent.com/80608392/119768308-0a20a380-be7e-11eb-8c97-56902fdd4ea1.png" width="200"/>

Setting the font size to Default, Large, or Largest, the outline is displayed correctly.

**Comment by alexbakker** [comment]
Thanks for the report. That's odd. Does this also happen to the fields under 'Advanced', or is it just the 'Issuer' field?

**Comment by justsomemate** [comment]
Only with "Issuer".
I just tested the font size setting with all of the display size settings. It happens when the font size is set to Small if the display size is set to Small, Default, or Large (but not Larger).
In all combinations, all of the other field outlines display correctly.

**Comment by christantoan** [comment]
Something to add from my experience.
If the field was pre-populated (i.e. editing an entry), emptying the field makes it move to the correct position (the outline is inline with the Group field)
