### ISSUE TITLE
Can't see all Groups

### ISSUE THREAD

**Issue by SubSolar0** [beemdevelopment/Aegis#755]
I have a lot of groups and can't see them all now with the new UI update. There's some that don't all fit on one screen and I can't scroll down or anything.

**Comment by alexbakker** [comment]
Thanks for the report. We'll have to make that sheet scrollable

**Comment by SubSolar0** [comment]
> Thanks for the report. We'll have to make that sheet scrollable

Thank you! I'm an IT provider for hundreds of companies so I have a Group for each client. Right now since I can't scroll I have to just use the search function.
