### ISSUE TITLE
Icon pack import issue

### ISSUE THREAD

**Issue by Kelvino9** [beemdevelopment/Aegis#757]
###### Info

* __Version__: 2.0
* __Source__: F-Droid
* __Vault encrypted__: Yes
* __Device__: Redmi Note 4
* __Android version and ROM__: 10 / AOSiP 10

###### Steps to reproduce

Import an icon pack zip file that has a file name with upper case letters, e.g. aegis-icons_SVGs_v20210524.zip

###### What do you expect to happen?

Icon pack should be imported successfully and listed correctly in the icon pack list.

###### What happens instead?

Icon pack is grayed out in the file manager and cannot be selected for importation unless you rename the zip file to all lower cases.

###### Log

```
If applicable, paste the debug log here.
```

**Comment by entrapta-dev** [comment]
* Version: 2.0
* Source: F-Droid
* Vault encrypted: Yes
* Device: Moto G5 Plus
* Android version and ROM: 8.1.0

I had no issues importing the icon pack.

**Comment by alexbakker** [comment]
This sounds more like an issue with your file manager than an issue in Aegis.

**Comment by sparevermicelli** [comment]
Version: 2.0
    Source: F-Droid
    Vault encrypted: Yes
    Device: Huawei P20 Lite
    Android version and ROM: 9

Same issue:
zip file is greyed out, I can't import it. Rename also didn't help.

**Comment by alexbakker** [comment]
Hm, I wonder what happens if we remove the ``application/zip`` MIME type filter from the intent. See: https://github.com/beemdevelopment/Aegis/blob/ad0088eca6af02bf7a8e494da1e27ab555e51c78/app/src/main/java/com/beemdevelopment/aegis/ui/fragments/IconPacksManagerFragment.java#L147

Can someone try to remove that and report back?

**Comment by alexbakker** [comment]
Is this issue still reproducible?

**Comment by sparevermicelli** [comment]
I just got a new phone - same issue.

 Samsung S21 5G - Android 11
