### ISSUE TITLE
Blank text when trying to delete an entry with no issuer.

### ISSUE THREAD

**Issue by edent** [beemdevelopment/Aegis#758]
###### Info

* __Version__: 2.0
* __Source__: F-Droid
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: OnePlus 5T
* __Android version and ROM__: 10

###### Steps to reproduce

Select some entries and try to delete them.

The pop-up doesn't have the entry names on it

<img src="https://user-images.githubusercontent.com/837136/120466092-93603a80-c396-11eb-924f-e16744245797.png" width="512" />

Going into one of the codes shows that it has a Name, but no Issuer (this entry was imported from an external source).

<img src="https://user-images.githubusercontent.com/837136/120466087-922f0d80-c396-11eb-9a5b-808c52622dad.png" width="512" />

###### What do you expect to happen?

In there is no issuer, display the entry's Name.

###### What happens instead?

The info message has missing text.

###### Log

N/A

**Comment by alexbakker** [comment]
Thanks for the report. Want to submit a patch?

**Comment by edent** [comment]
The root of the issue appears to be 

https://github.com/beemdevelopment/Aegis/blob/80bf5bc854984914c1d3b5c28c6ab9b4f30cf0ed/app/src/main/java/com/beemdevelopment/aegis/ui/dialogs/Dialogs.java#L69

That (eventually) calls

https://github.com/beemdevelopment/Aegis/blob/80bf5bc854984914c1d3b5c28c6ab9b4f30cf0ed/app/src/main/java/com/beemdevelopment/aegis/vault/VaultEntry.java#L113

So it might be worth changing that to return `getName()` if it is null. What do you think?

**Comment by alexbakker** [comment]
I would suggest to change ``Dialogs.showDeleteEntriesDialog`` to take a list of ``VaultEntry`` instead of a list of strings. Then you can place the logic in that function instead changing the return value of ``getIssuer()``

**Comment by edent** [comment]
That's a bit beyond my Java skills. Sorry!

**Comment by alexbakker** [comment]
No problem!
