### ISSUE TITLE
Fuzzy Match between Issuers in Token and in Icon Pack

### ISSUE THREAD

**Issue by ukanuk** [beemdevelopment/Aegis#761]
###### Info

* __Version__: 2.0
* __Source__: F-Droid
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Samsung Galaxy S21
* __Android version and ROM__: 11

###### Steps to reproduce

1. Create a token, and modify the issuer name to include a suffix. For example, I might create a token with the issuer name `Nintendo Japan`.
2. Import an icon pack with a matching issuer. For example, aegis-icons includes a Nintendo icon listed in `pack.json` with this info.
```
        {
            "filename": "SVG/Nintendo.svg",
            "category": "1. Apps & Sites",
            "issuer": [
                "Nintendo"
            ]
        }
```

3. Edit the token icon.
4. Nothing appears under "Suggested", so type "Nintendo" in the search bar and select the icon that appears.

###### What do you expect to happen?

Aegis should suggest the Nintendo icon when the token issuer name contains the pack issuer name.

###### What happens instead?

Aegis does not suggest the Nintendo icon when the token issuer name contains the pack issuer name. But it does in fact suggest the opposite - if I change token issuer to `Ninten`, then Aegis does suggest the appropriate icon.

###### Log

N/A

**Comment by ukanuk** [comment]
I think the problem is this function in `app/src/main/java/com/beemdevelopment/aegis/icons/IconPack.java`. 

- Easiest fix would be to invert the direction of the `contains()` comparison.
- Best fix would be to do a fuzzy match (for example with the Levenshtein distance), and create a ranked list of top suggestions.

```
        public boolean isSuggestedFor(String issuer) {
            return getIssuers().stream()
                    .anyMatch(is -> is.toLowerCase().contains(issuer.toLowerCase()));
        }
```

**Comment by alexbakker** [comment]
Hm, I'm afraid that we'll just get the opposite problem if we invert the direction of the contains comparison. Feel free to experiment with using a simple fuzzy search function and see if you can better results than the current situation. I'd like to keep this simple though. It's fine if we can't immediately suggest the right icon in all cases.

**Comment by ukanuk** [comment]
How about simply checking both the regular and inverted `compare()`. 

I don't actually need fuzzy match at this time, and just adding the inversion would be great for now.

**Comment by alexbakker** [comment]
Sure, that also works for me.
