### ISSUE TITLE
Screen rotation cancels group selection

### ISSUE THREAD

**Issue by mmolitor87** [beemdevelopment/Aegis#762]
###### Info

* __Version__: 2.0
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Pixel 5
* __Android version and ROM__: 11

###### Steps to reproduce

A detailed list of reproduction steps.

1. Click Groups
2. Select Group
3. Rotate device
4. Group selection is canceled

###### What do you expect to happen?

Group would remain selected through rotation.

###### What happens instead?

Group selection is removed.

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment]
Thanks for the report. I'm able to reproduce this.

**Comment by Hacker437** [comment]
@alexbakker Please check this also.

**Comment by alexbakker** [comment]
@Hacker437 This is still reproducible.

**Comment by Hacker437** [comment]
> @Hacker437 This is still reproducible.

Can you please share screen recording of it?

**Comment by 3Goldjungen** [comment]
If you rotate the screen, both spinner (Types, Hash) lost the entries. After rotation only the selected entry is still available, all other are gone.

**Comment by Hacker437** [comment]
@alexbakker Ok

**Comment by Hacker437** [comment]
@3Goldjungen Thanks..

**Comment by InfiniteCoder06** [comment]
@alexbakker I cannot reproduce this issue in the latest release

**Comment by alexbakker** [comment]
@InfiniteCoder06 It's still reproducible. Select a group to filter on, don't click Save but dismiss the dialog. Rotate the device and watch the group filter get reset.

**Comment by InfiniteCoder06** [comment]
> @InfiniteCoder06 It's still reproducible. Select a group to filter on, don't click Save but dismiss the dialog. Rotate the device and watch the group filter get reset.

Yeah since we are not clicking on save, it shouldn't save right?

**Comment by alexbakker** [comment]
Not clicking Save should still apply the filter. It just doesn't remember the filter across app restarts.
