### ISSUE TITLE
Recording time and date for last login

### ISSUE THREAD

**Issue by ArenaL5** [beemdevelopment/Aegis#765]
Some websites show you the time and date of your current and last session, sometimes just after logging in, to allow you to check for suspicious activities you don't remember. GitHub, for example, has a full security log:

![securitylog](https://user-images.githubusercontent.com/37388405/120898649-4e006f00-c61b-11eb-8deb-8ad70299871c.png)

But I won't remember the last time I logged into a website for long, especially if it's a website I seldom log into. I'd like to propose using Aegis as a reminder.

The simplest method I can think of is remembering only one timestamp and replacing it manually with the current time and date, like in this (crude) mockup:
![mockup](https://user-images.githubusercontent.com/37388405/120899130-aafd2480-c61d-11eb-8b85-9a48e2fa257d.png)

With this method, just after you log into an account, you would tap into your authenticator code (if you hadn't already), then check your last session date and time, and if they match, just tap the blue button to record this session's date and time. Repeat for every login. If your timestamp doesn't match the website's last timestamp, your account has been probably not-very-stealthily hijacked.

There are some problems with this method (the user has to be aware of timezone problems, it only detects a very specific kind of attack) and it's much less convenient on websites that don't show you your last session, but on those that do (like `europa.eu`) it could help detect these attacks with very little effort.

**Comment by alexbakker** [comment]
I personally think this is a *very* niche use case and I'm not convinced it should be Aegis' responsibility (Why not your password manager, for example?). That said, after #760 is merged, we'll have have the concept of "using" a token by tapping it. How about we also persist the timestamp at which the last "use" occurred and expose that somewhere in the entry editing activity? I don't think we'd be interested in adding the elaborate feature you're describing, but maybe this would be a good compromise.

While we're at it, it may also be good to start persisting the timestamp of creation and the last edit of an entry.

**Comment by ArenaL5** [comment]
> I personally think this is a _very_ niche use case and I'm not convinced it should be Aegis' responsibility (Why not your password manager, for example?).

I realise now every answer I could give boils down to "I use Aegis on one device at a time and no software password managers". It's a niche setup, but there's really no right application to implement it. Having a separate application is inconvenient and using an existing application leads to that question.

> How about we also persist the timestamp at which the last "use" occurred and expose that somewhere in the entry editing activity? I don't think we'd be interested in adding the elaborate feature you're describing, but maybe this would be a good compromise.
>
> While we're at it, it may also be good to start persisting the timestamp of creation and the last edit of an entry.

This would be perfect, actually. As long as users can see the last use before tapping it (or else it will be pointless) it'll be easier for them, too.

**Comment by alexbakker** [comment]
We currently don't have plans to implement this. This is such a niche feature and even if we display this as a "last use" timestamp, it's not always going to be accurate.
