### ISSUE TITLE
Creating multiple files with tokens (work, home, other tokens)

### ISSUE THREAD

**Issue by OmlineEditor** [beemdevelopment/Aegis#766]
for ease of use, you need to make it possible to select several files with tokens (work, home, other tokens). when starting the application, we choose which container or file with tokens to use. If you have a lot of tokens it will make it easier for you to improve your work. splitting into several files as it is done in the application KeePassDX:
https://f-droid.org/ru/packages/com.kunzisoft.keepass.libre

**Comment by alexbakker** [comment]
If you'd like to organize your tokens, you can put them in separate groups and filter on them. No need for separate files!

**Comment by OmlineEditor** [comment]
separate files are more convenient. I can transfer tokens for work to my work colleague. I cannot put my personal and work files into one file, I need to make a backup and transfer to another person only part of the data and not all.
having different files it is easier to make access to very private data (banks, the main Google account) and to files that are not critical, for example, in forums and not important sites.

KeePass has folders, tags, and other conveniences, but it has the ability to make different files.  not all people are comfortable using one database.

**Comment by alexbakker** [comment]
We currently don't have plans to implement this, so we'll close this.
