### ISSUE TITLE
using a monospaced font to display code

### ISSUE THREAD

**Issue by OmlineEditor** [beemdevelopment/Aegis#767]
now it looks ugly when you click on the token and the numbers are shown in other places. the font jumps and numbers jump when circles and numbers are shown.
make a monospace font so that the circles and numbers appear as if in one place without shifting and without stitching.
![now](https://user-images.githubusercontent.com/13348933/120936685-c34e6b80-c711-11eb-80f4-eeae85e16c61.JPG)

**Comment by alexbakker** [comment]
I don't think a monospaced font will fit all that well with the rest of the style of the app. If you'd like, you could try to switch the entry card to a monospaced font and share a screen recording of what that looks like? Perhaps you can prove me wrong.

**Comment by OmlineEditor** [comment]
we do not need a combination, we need the circles and numbers to coincide in places, but now this is not possible due to the font. circles take up more space than numbers. make the place for the circle coincide with the place for the number.

**Comment by OmlineEditor** [comment]
monospaced font only for the token code, we do not touch all other fonts.

**Comment by alexbakker** [comment]
> monospaced font only for the token code, we do not touch all other fonts.

I understand. What I meant is that I don't think a monospaced font for the tokens will fit all that well with the rest of the style of the app. Feel free to experiment and share your results though.

**Comment by OmlineEditor** [comment]
did it quickly for review.

now it's ugly, look how the numbers don't match the circles:
![do](https://user-images.githubusercontent.com/13348933/121024703-250fe380-c7ad-11eb-9cf1-3a78af91972e.gif)

if you use a monospaced font then it is more beautiful:
![posle2](https://user-images.githubusercontent.com/13348933/121025307-b0897480-c7ad-11eb-8ee9-d3aebcc753ce.gif)



monospaced font is used in another application, it is your competitor, it is prettier. make nice use of a monospaced font.
![unnamed](https://user-images.githubusercontent.com/13348933/121025038-7029f680-c7ad-11eb-82cd-7eae1d9a0481.jpg)

**Comment by alexbakker** [comment]
Thanks for giving this a try and sharing your results. This confirms my suspicion that the monospaced code just looks out of place when looking at the style of the rest of the app. I tried applying the monospace font in the actual app (instead of photo-shopping it in), and there we'd have the additional issue of the space being larger between the 2 digit groups, resulting in an odd look.

We'll stick with the current font. For what it's worth, with Android's default font, the jump between hidden and revealed is far less noticeable.

**Comment by OmlineEditor** [comment]
I have not used a monospace font in reality. this is just an example. here is real, in real monospace font there is no problem with grouping numbers. I didn’t use a real font. I didn't have your circles. Please open a ticket and make a real monospace font
![real](https://user-images.githubusercontent.com/13348933/121089364-b56f1800-c7ef-11eb-89d1-5732f2a25477.gif)

**Comment by OmlineEditor** [comment]
I do not know which you use the font and therefore I just placed the numbers on the previous photos on top of the circles, on the previous photos a monochry font without spaces symbols. Now everything is done normally, there are symbols of spaces, but only the circles are different. Please open a ticket and make a real monospace font
![2m](https://user-images.githubusercontent.com/13348933/121236892-1f92c600-c89f-11eb-981a-6f7f6ca42b4e.gif)

**Comment by OmlineEditor** [comment]
> Thanks for giving this a try and sharing your results.

please open the ticket and make a monospaced font. see new photos
