### ISSUE TITLE
another type of characters to hide the token code

### ISSUE THREAD

**Issue by OmlineEditor** [beemdevelopment/Aegis#768]
Is it possible to add an option to select a symbol to hide the token code in the settings? now there are only circles. is it possible to add bold minus symbols as in the application FreeOTP+? 
it improves perception and helps people who have switched from another application feel better.
you can add a square, minus, or any other big character the user wants. It's simple, make it possible for the user to choose the symbol they like.

**Comment by alexbakker** [comment]
Thanks for the suggestion, but we're happy with the way this currently looks (still considering #672 though), so I don't think we'll be adding an option for this. We also want to keep the number of unnecessary customization options to a minimum.
