### ISSUE TITLE
Support configurable password reminders

### ISSUE THREAD

**Issue by JohnNeville** [beemdevelopment/Aegis#769]
It may just be me but I can almost never remember my password when using biometric unlock. The password reminder is helpful and I have eventually remembered to the point that I can get it after a couple tries but it isn't frequent enough for me to remember it cold. 

Can we add a frequency setting that is something like a "High, Normal, Low" option or Bi-weekly, monthly, quarterly?

**Comment by alexbakker** [comment]
I agree that the current password reminder interval is a bit too long. Aegis used to show a reminder once every week, but naturally someone thought that was too frequent (#402).

In general we try to keep the amount of customization options to a minimum, but I think adding an option for this is justified.

**Comment by johseg** [comment]
I would also like to have this with an option "never" as I have my password in a password manager and it's very long and complex. I have a good backup concept for this, so it doesn't help me remembering this, it's just annoying. Thanks
