### ISSUE TITLE
Bad secret invalid input length

### ISSUE THREAD

**Issue by lrosique** [beemdevelopment/Aegis#771]
###### Info

* __Version__: 2.0
* __Source__: Google Play
* __Vault encrypted__: Yes with biometric unlock
* __Device__: Android
* __Android version and ROM__: Not relevant

###### Steps to reproduce

I wanted to test the interface of Aegis (I'm comparing it with other apps), so I generated a random 2FA QR code to add.

1) Go to https://stefansundin.github.io/2fa-qr/ (2FA QR code generator)
2) Configure with "Time based TOTP" + "secretkey" + "Test 2FA"
3) Scan the QR code with Aegis Auth

###### What do you expect to happen?

The QR code is added (it worked with 2FA Authenticator)

###### What happens instead?

QR code is refused with an error and not added to my vault

###### Log

Error happened while trying to read the QR code : "com.beemdevelopment.aegis.otp.GoogleAuthInfoException : Bad secret (java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 9)

Of course if I change the secret key length it will still crash (with length = secret key)

**Comment by alexbakker** [comment]
If the secret has a length of 9 characters, it cannot be valid base32, so Aegis is right to reject it. If you supply a valid base32 string, Aegis will be able to decode it.

**Comment by lrosique** [comment]
ok i understand, but even with an input length of 32 (comprised of numbers) it crashes (character not recognized : "1").

The only case where it works is with a key like "abcdefghijk..." (32 chars). Is it normal for "12345678901234567890123456789012" not working due to numbers (and length if not 32) ?

**Comment by alexbakker** [comment]
> Is it normal for "12345678901234567890123456789012" not working due to numbers (and length if not 32) ?

Again, that string is not valid base32. Some of the characters in there are not part of the base32 alphabet.
