### ISSUE TITLE
Provide option to batch assign icons to existing 2FA entries

### ISSUE THREAD

**Issue by rcdailey** [beemdevelopment/Aegis#773]
As a user, I'd like a way to batch assign icons to my existing 2FA entries when I switch to or import an icon pack.

### Description

The goal is to save user time: When a user has multiple (e.g. 30) entries, it is very tedious to set each one manually. This is due to two factors: Each entry is edited one at a time, and the UX for switching icons is not optimized for doing this efficiently (options are in deeply nested menus and require multiple taps from the user).

Any batch operation will be imperfect because user preferences for icons are nondeterministic. Worst case, this allows the user to assign a majority of icons to entries so that they only need to go back and edit/customize a few entries they are unhappy with. This still saves significant time and improves the usability of the app icons feature.

### Acceptance Criteria

The below acceptance criteria is subject to change by the development team as necessary and reasonable. The initial goal of this list is to give this feature request some substance.

- Aegis makes a reasonable attempt to assign a default icon to each 2FA entry where reasonable. Examples:
  - Only one icon exists for a service: Choose that one
  - Multiple icons exist for a single service: Choose an application-defined default, such as the first icon in the list. The specific choice algorithm here is irrelevant; only the outcome is important.
- Batch icon assignment is not automatic. Not every user may want to do this, especially those with only a handful of 2FA entries. A conveniently accessible manual option will be provided to the user to batch assign a specific icon pack. Specific UX design is left open to the developer of this user story.
- Appropriate documentation is written instructing users how to use this new feature, including but not limited to:
  - Specific icon-choosing behaviors, such as when icons cannot be chosen automatically and under what conditions this can occur.
  - Explanation and disclaimer stating that automatic icon assignment is imperfect by design. Instruct the users that they can still manually edit icons after batch assignment if they are unhappy with specific icon choices.

### References, Links

- Related to #509 (Icon Packs)

**Comment by beyond9thousand** [comment]
Why has this not been implemented? Importing backups from other apps is such a pain if I have to set the icon for each entry manually, it makes no sense

**Comment by alexbakker** [comment]
@beyond9thousand The answer to this question is almost always the same across open source projects: The authors and contributors of the project spent time implementing other things because they considered them higher priority or more fun to work on.

This issue is an accepted proposal, so if you'd like to see this feature sooner rather than later, get cracking on a patch.

**Comment by beyond9thousand** [comment]
I would if I could have, but thanks for the response! I'll be looking forward to having this added in a future release :)
