### ISSUE TITLE
Support the non-standard Authy TOTP algorithm

### ISSUE THREAD

**Issue by puddly** [beemdevelopment/Aegis#776]
Authy's server-side validation currently accepts codes generated according to RFC 4226 but it may be useful to directly use the Android app's slightly bizarre (why?) algorithm:

 1. The counter value is normally represented as a 64-bit big-endian integer when passed into HMAC-SHA1. Authy instead *directly uses the counter value as a base-10 ASCII string*. For example, the counter 12345678 would not be represented as `\x00\x00\x00\x00\x00\xBC\x61\x4E`, but as the bytes `12345678`.
 2. The OTP secret is normally decoded from its base32 representation when it's used as the HMAC-SHA1 key. Authy decodes the base32-encoded secret *and then re-encodes it as lowercase ASCII hex*. For example, the secret `AEBAGBAFAYDQQ` would not be decoded into `\x01\x02\x03\x04\x05\x06\x07\x08`, but instead the ASCII string `0102030405060708` would be used.

To distinguish these codes from "normal" TOTP codes, I propose using a new URI type:

```
otpauth://authy/...
          ^^^^^
```

You can test out the algorithm yourself with this self-contained Python script that generate pairs of RFC 4226 and "Authy" codes from a given secret: https://github.com/puddly/android-otp-extractor/issues/34#issuecomment-634447781

This is probably an unnecessary change as long as the Authy desktop app is still using RFC 4226 but if that changes in the future, you may find this info useful.

Thank you for the awesome app!

**Comment by alexbakker** [comment]
If Authy's server side still supports proper RFC 4226, I don't really see a reason to spend time implementing their proprietary algorithm.

**Comment by alexbakker** [comment]
So I'll close this for now. Once this becomes relevant we can reopen this. Thanks for the info though

**Comment by phiresky** [comment]
I have imported a 2FA from the authy app, and the resulting codes are different and the server side does not accept the codes from the Aegis app, while it does accept the ones from the Authy app. Could that be an instance of this?

**Comment by phiresky** [comment]
I just tried the python script that @puddly linked above, and I can confirm that that script generates the "correct" code that the Authy app generates that allows me to authenticate the account.

Right now the code from Aegis is working again though so either they are doing something weird from their side or I did something wrong yesterday
