### ISSUE TITLE
Tutanota Mail Bad Secret

### ISSUE THREAD

**Issue by umitseyhan75** [beemdevelopment/Aegis#777]
###### Info

* __Version__: 2.0
* __Source__: Google Play
* __Vault encrypted__: No
* __Device__: Nokia 8 (TA-1012)
* __Android version and ROM__: Android 9 / 1 October 2020 Security Patch

###### Steps to reproduce

1. Click red plus button
2. Select QR Code option
3. Taking the image of produced QR Code

###### What do you expect to happen?

Getting the secret code.

###### What happens instead?

Bad Secret Error

###### Log

```
com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Bad secret (java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 0x130)
```

**Comment by alexbakker** [comment]
I just created a Tutanota account to test this and Aegis is able to scan the QR code that is presented. Are you trying to scan a QR code generated by Tutanota, or did you generate one yourself?

**Comment by umitseyhan75** [comment]
I scan the Tutanota's QR code that generated at their web site. I mean, I used my phone to scan my laptops screen. Now I tried Android app of Tutanota and there was an option like "add to auth app". I am not using the English version of app so I do not now the excat sentence there. And susccesfully added the secret code to Aegis this time.
Can you please try to add it from their web site as I did to be sure?

**Comment by alexbakker** [comment]
> Can you please try to add it from their web site as I did to be sure?

That's exactly what I did.

**Comment by umitseyhan75** [comment]
Is there any other information that I can provide to you to adress this issue at your side?

**Comment by alexbakker** [comment]
If you could, provide us with an example Tutanota QR code that makes Aegis exhibit the issue when scanned. Make sure it's not valid anymore for any valuable accounts, though.

**Comment by umitseyhan75** [comment]
![Adsız](https://user-images.githubusercontent.com/43583375/122099348-950c1280-ce1a-11eb-8d67-13e316d293bc.png)

**Comment by alexbakker** [comment]
Aegis is able to scan that QR code on my device.

**Comment by umitseyhan75** [comment]
Is there any other thing I can do?

**Comment by alexbakker** [comment]
Can you install a debug APK (https://alexbakker.me/u/iy7igkgs4n.apk), capture a log with ADB (see: https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb) while you try to scan the QR code and share the log here?

**Comment by umitseyhan75** [comment]
PC terminal gives this `pid $(adb out of range` when I try to use `adb logcat --pid=$(adb shell pidof -s com.beemdevelopment.aegis) > debug.log`

**Comment by alexbakker** [comment]
Just try the following then:

```
adb logcat -c
adb logcat > debug.log
```

**Comment by umitseyhan75** [comment]
Here is the file.
[debug.log](https://github.com/beemdevelopment/Aegis/files/6682284/debug.log)

**Comment by alexbakker** [comment]
Looks like the QR code decodes correctly on your device as well. So I really don't know what's going on here. When do you get the error dialog, exactly? Right after scanning the QR code, or when trying to save the new entry?

**Comment by umitseyhan75** [comment]
Right after scanning the QR code a message pops up like "an error has been occured".
![ss](https://user-images.githubusercontent.com/43583375/122675272-53e07d80-d1e1-11eb-97cb-f037973ceea8.png)

**Comment by alexbakker** [comment]
I'm wondering if this has something to do with your locale. What happens if you set the language of your device (and Aegis) to English and try to scan the QR code again?

**Comment by umitseyhan75** [comment]
I changed the Aegis's (not the dev one) language to English and not the system language now and tried again to scan. And yeah, it works like a charm.

**Comment by alexbakker** [comment]
So this is a pretty bizarre bug. We're upper-casing the secret before passing it to the base 32 decoder. But because Java's ``toUpperCase()`` method acts differently depending on which locale is set, the secret will become invalid base32 if it contains an ``i`` and Turkish is set as the locale.

https://github.com/beemdevelopment/Aegis/blob/c977b9a064fab4e7d5d96df6f41e1362d823f12b/app/src/main/java/com/beemdevelopment/aegis/encoding/Base32.java#L12

I've fixed this in 327b7ccbaeb00cee496c3f6b32498ec1d052f84d. Could you double check that this fixes the issue for you as well? The following APK will install beside your regular Aegis installation, so that nothing gets overwritten while testing: https://alexbakker.me/u/d018oc7sri.apk.

**Comment by umitseyhan75** [comment]
Yes. Now it works. Waiting for the next update then.
Thank you for your effort, best wishes.

**Comment by alexbakker** [comment]
Thanks a lot for patiently helping us debug this.

We've tagged [v2.0.1](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0.1), which contains the fix for this issue. Should be live on Google Play shortly.
