### ISSUE TITLE
add support to import json files

### ISSUE THREAD

**Issue by dddw** [beemdevelopment/Aegis#778]
after exporting my aegis setting to a factory reset phone I couldn't import the json backup file.
Which gave me an anxious couple of minutes before figuring out that the .json file couldn't be opened, and also I couldn't see the file in the standard android file tool. 
I worked it out, but thought it was suboptimal.
Furthermore this function is the most important reason (and being open source) I chose for aegis.
Maybe when choosing to export to non-encrypted simple save standard to a file similar to this: $date-unencrypted-json.txt ?
Keep up the great work!

**Comment by alexbakker** [comment]
> I couldn't import the json backup file

Why not? What happened?

> Maybe when choosing to export to non-encrypted simple save standard to a file similar to this: $date-unencrypted-json.txt ?

There already is an option to export to a plain TXT file.

**Comment by dddw** [comment]
ha not saying it didn't work. However... on a brand new phone the standard android file manager doesn't display the .json extention. So for a minute I got the false impression that I wasn't able to reimport my 2FA codes back into Aegis.
I'm probably not the only one having this and thought I'd suggest an improvement

**Comment by alexbakker** [comment]
Thanks for clarifying. The standard file manager of Android actually does display files with the .json extension, so I'm not sure what happened on your device. Either way, the things requested here are already supported.
