### ISSUE TITLE
Allow exporting of specific group(s)

### ISSUE THREAD

**Issue by dkogias** [beemdevelopment/Aegis#779]
I manage a lot of work-related accounts with 2FA.  Being able to export only work-related entries will help with sharing access with colleagues.

There are workarounds for this of course (export to old device, delete all non-work entries, then export from there) but that's kludgy.

**Comment by alexbakker** [comment]
I think it would be fine to add this as an option to the export dialog. Feel free to submit a patch!

**Comment by alexbakker** [comment]
Implemented by #1014.
