### ISSUE TITLE
Unlocking phone always immediately brings up Aegis

### ISSUE THREAD

**Issue by meelten** [beemdevelopment/Aegis#78]
Even though I don't lock my phone with Aegis app open, when I unlock it it always immediately bring up Aegis instead of my home screen or whatever app I had open while locking screen. I don't think it suppose to happen but can't find anything in settings that would cause this behavior.

**Comment by alexbakker** [comment]
Nice catch! This probably happens because we launch AuthActivity right after the phone is locked. I'll take a look this weekend.
