### ISSUE TITLE
add a note field (annotation)

### ISSUE THREAD

**Issue by OmlineEditor** [beemdevelopment/Aegis#782]
sometimes when there are several accounts on the same service, it would be useful to use the notes to understand what this or that account is used for. additional data will help a lot. a simple username is not enough, you need more data. add a note field.

**Comment by alexbakker** [comment]
I think this idea is fine. Feel free to submit a patch!

**Comment by OmlineEditor** [comment]
> Feel free to submit a patch!

I am not a programmer, I do not know how to make this function for android.

**Comment by modelorona** [comment]
I can attempt this, if that's alright.

**Comment by OmlineEditor** [comment]
> I can attempt this, if that's alright.

this is an open project and I think any help is welcome. I think the program developer will accept help. I have seen several merges from other users

**Comment by alexbakker** [comment]
@modelorona That would be great, thanks!

Just to clarify though: The note should only appear in the EditEntryActivity. We don't really have room to display it in the entry list.

**Comment by OmlineEditor** [comment]
> Just to clarify: The note should only appear in the EditEntryActivity. We don't really have room to display it in the entry list.

yes, only when editing there will be additional fields for explanation.
I hope this field will be available when importing and exporting?

**Comment by modelorona** [comment]
@alexbakker Understood. 

@OmlineEditor I'll check out the import/export functionality.

**Comment by alexbakker** [comment]
1e6175854cb94a319dd80742480de13c136354e2
