### ISSUE TITLE
Import password prompt string is unclear

### ISSUE THREAD

**Issue by ataraxia937** [beemdevelopment/Aegis#784]
This is minor. When importing an encrypted backup in Aegis format, the password prompt reads: "Please enter a password". The phrasing implies to me that I'm meant to make up a new password, a free choice. But of course I'm meant to enter the password used to encrypt the backup. I suggest something like "Please enter the backup password" for clarity.

**Comment by alexbakker** [comment]
Agreed.

**Comment by moesheyab** [comment]
What would an appropriate title for the dialog be? Would "Enter the import password" with a message underneath "Please enter the password associated with this import file"

**Comment by alexbakker** [comment]
Yeah, something like that.

**Comment by alexbakker** [comment]
Fixed by #875.
