### ISSUE TITLE
"time correction for codes" function is essential

### ISSUE THREAD

**Issue by pein0saga** [beemdevelopment/Aegis#785]
2FA on some sites is always incorrect because of  time sync errors. It is driving me crazy.

Same function from Google: "The codes that Google Authenticator generates depend on the correct time on your Android device. If your verification codes generated by Google Authenticator aren’t working, it might be because the time on your Android device is incorrect."

**Comment by alexbakker** [comment]
Adding time sync functionality to the app itself would require us to request the internet permission, and we don't have plans to do so. The automatic time synchronization functionality in Android should keep the clock in sync. If the clock keeps drifting, please report this issue to the manufacturer of your device.

**Comment by pein0saga** [comment]
I tried "time correction for codes" in google authenticator and it actually wouldn't work at all. I finally solved the time sync error by    
correcting my router (I cleared  all JFFS custom scripts on my merlin router and  sync error was gone )
