### ISSUE TITLE
one account in two or more groups

### ISSUE THREAD

**Issue by OmlineEditor** [beemdevelopment/Aegis#786]
currently, one account can only be written to one group and assigned one value.
please make it possible to record and add an account to two or more groups, make a multi-selection.

**Comment by alexbakker** [comment]
See: #27.

**Comment by OmlineEditor** [comment]
> See: #27.

you do not understand me.
I need to select multiple groups to record in the create menu.
open request
![Screenshot](https://user-images.githubusercontent.com/13348933/124984265-a9ba7f80-e041-11eb-8631-5ff2d364fb97.jpg)

**Comment by alexbakker** [comment]
Yes, that's one of the items on that list: "Allow assigning an entry to multiple groups"

**Comment by OmlineEditor** [comment]
> Yes, that's one of the items on that list: "Allow assigning an entry to multiple groups"

are you closing the ticket because I have a duplicate?
I didn't understand the reason for the closure

**Comment by alexbakker** [comment]
Yes, your suggestion is already planned in the accepted proposal that I linked to.
