### ISSUE TITLE
Space required for dutch string

### ISSUE THREAD

**Issue by Jeroen96** [beemdevelopment/Aegis#787]
###### Info

* __Version__: 2.0.1
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: OnePlus 7
* __Android version and ROM__:  Android 11/ Oxygen OS 11.0.1.1

The following string for [Dutch translatations](https://github.com/beemdevelopment/Aegis/blob/master/app/src/main/res/values-nl-rNL/strings.xml) needs a space between  ```<b>%s</b>niet```
``` xml
 <string name="delete_entry_explanation">Deze actie schakelt 2FA voor <b>%s</b>niet uit. Om te voorkomen dat u de toegang verliest, zorg ervoor dat u 2FA hebt uitgeschakeld of dat u een alternatieve manier hebt om codes voor deze dienst te genereren.</string>
```

**Comment by alexbakker** [comment]
Thanks for reporting this. Translations are maintained on Crowdin: https://crowdin.com/project/aegis-authenticator. If you'd like, you can apply the fix there.
