### ISSUE TITLE
Invalid OTP code

### ISSUE THREAD

**Issue by mendess** [beemdevelopment/Aegis#788]
###### Info

* __Version__: 2.0.1
* __Source__: F-Droid
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Xiaomi Redmin Note 9S
* __Android version and ROM__: Android 10 and MIUI 11.0.3

###### Steps to reproduce

A detailed list of reproduction steps.

Open app
Unlock
Click the `+` button
Select 'QR Code'
Scan the qr
Add without changing anything
Enter the code on the website

###### What do you expect to happen?

2FA is setup correctly

###### What happens instead?

Invalid OTP code

###### Other information

This is for software being developed by my company.

Link format in the scanned qr: `otpauth://totp/admin?secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&issuer=MyCompany&algorithm=SHA256&digits=6&period=30`

Authy and 2FAS authenticator both work, but aegis has the wrong codes

**Comment by alexbakker** [comment]
Are you sure you're actually using SHA256 in the back end? I believe both Authy and 2FAS ignore that parameter and default to using SHA1.

What happens if you replace it SHA256 with SHA1 in the URI, generate a QR code and scan it with Aegis? Are the codes that are produced correct now?

**Comment by mendess** [comment]
I changed the stored config of the OTP to use different encryption algorithms, hope it's equivalent to your suggestion. But it still doesn't work.

**Comment by alexbakker** [comment]
The next suspect would be the time on your device. Is it in sync? How far off is the clock according to https://time.is?

If the time is in sync, I don't know what could be going on here. Could you share a valid dummy URI generated by your application for us to test with?

**Comment by mendess** [comment]
I have checked the time yes. Was the first thing I thought of.

I guess this is what you need? otpauth://totp/admin?secret=DMGOS43GCEXDO4PRELA5OQ4IXYPNBTGH&issuer=MyCompany&algorithm=SHA256&digits=6&period=30

**Comment by alexbakker** [comment]
Thanks. I created a QR code for that URI. Scanned it with Aegis and changed SHA256 to SHA1. Scanned it with 2FAS as-is. Both apps generate the same code on my device. So I don't really know what to tell you, this appears to be working as expected.

**Comment by mendess** [comment]
Yeah, I tested again and it does indeed happen. I must have tested wrong. Thanks for the support!
