### ISSUE TITLE
Option to Disable Automatic Refresh for Selected Code

### ISSUE THREAD

**Issue by bitscuity** [beemdevelopment/Aegis#789]
I would like to add a feature to the app that enables users to pause the updating of the selected entry.

Most of the time when using Aegis, I only wish to generate just one code. There is, in my opinion, no reason to automatically refresh a code once the timer runs out. On top of that, it's a little annoying to have a code change when I'm halfway through reading it. This feature will solve that.

If a user has this setting enabled, the selected item in the entry list would not automatically refresh when the timer runs out. When the item loses focus (either by selecting a different entry or after the "tap to reveal" countdown ended), it will once again be subject to the periodic updates.

I think this option will be most useful in combination with the "tap to reveal" functionality. It will ensure that only one code is shown to the user. After all, isn't that what "tap to reveal" is all about?

Thoughts?

**Comment by alexbakker** [comment]
Thanks for your suggestion. We think this is a good idea.

Let us know if you have any questions while working on the implementation. There are already a lot of different features and bits of functionality in the area of tapping on entries, so I think this could be tricky.

**Comment by alexbakker** [comment]
3464f93c3959e54902893f128794d8185734ef46
