### ISSUE TITLE
When deleting an entry, please show its name in the confirmation dialogue

### ISSUE THREAD

**Issue by JimBreton** [beemdevelopment/Aegis#792]
If the name of the entry about to be deleted were shown right in the confirmation dialogue this would help prevent mistakes (deleting the wrong entry), and seems like it should be easy to implement.

Thank you!

**Comment by alexbakker** [comment]
This should already be the case. Can you share a screenshot of the dialog you're seeing?

**Comment by JimBreton** [comment]
Sure, thanks - it shows the 'Issuer' but not the 'Name' field.  If you have multiple entries from the same issuer (e.g., multiple Firefox accounts) the deletion dialogue does not distinguish which one is being acted upon.  Adding the little bit of extra info could prevent catastrophe.
![Screenshot 2021-07-31](https://user-images.githubusercontent.com/45986932/127742961-21b50e79-28de-4954-9346-e00eb445c779.png)

**Comment by alexbakker** [comment]
I see, thanks for clarifying. We'll consider this.

**Comment by alexbakker** [comment]
@Hacker437 Sure! What solution do you have in mind? We need to make sure to do this in a way that the dialog is still readable.

**Comment by Hacker437** [comment]
I will make a pull request and shot the dialog screenshot

**Comment by Hacker437** [comment]
@alexbakker Here Are the ScreenShots.Any Suggestions
![Single Entry Delete](https://user-images.githubusercontent.com/68219142/131449451-bd7bea90-e96c-4648-86de-040834d7c859.jpg)
![Multiple Entry Delete](https://user-images.githubusercontent.com/68219142/131449444-2c92f7d9-6c45-46da-ad5b-840d09a33654.jpg)

**Comment by alexbakker** [comment]
I would suggest making the list a bit more concise, just: Issuer (Name).

And with bullet-like list item indicators instead of "->". So for example:
- Google (test@example.com)
- GitHub (test2@example.com)

**Comment by Hacker437** [comment]
Thanks for the suggestion

**Comment by alexbakker** [comment]
#845 was merged.
