### ISSUE TITLE
Text is cutoff because of small display

### ISSUE THREAD

**Issue by keppo070** [beemdevelopment/Aegis#794]
###### Info

* __Version__:  2.0.1
* __Source__: (Google Play)
* __Vault encrypted__: Yes (with biometric unlock)/No
* __Device__: Jelly 2
* __Android version and ROM__: 10

###### Steps to reproduce

I use the app in the Dutch language. Jelly2 is very small android phone. Screen size is 3inch and resolution is 480*854.  The main screen the text is cut off in a strange manner and continued on the next line. I cant make a screenshot because its prohibited.

it is a minor issue en probably not very common because of the small device

###### What do you expect to happen?

The main screen should say: 
Ontgrendel 
de kluis

###### What happens instead?

Because of the small screen it says: 
Ontgrend
el
de kluis

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment]
That's an extremely small screen size you have there. Are any elements actually invisible (preventing you to use the app) or does it just look a little off? If you disable the "Screen security" setting in Aegis, you should be able to take screenshots.

**Comment by keppo070** [comment]
As far as I noted there are no elements missing. Even the generated codes are on 1 line. It is just off like you said. If the lettertype is smaller than everything would be ok.

So no big issue. just cosmetics
![Screenshot_20210810-135919](https://user-images.githubusercontent.com/8713528/128863657-1c573598-40eb-4257-9fb2-7594e4418465.png)

**Comment by vladimirkosolapov** [comment]
Same with the Russian language on a 1080x2340 screen.

<details>
  <summary>Click to expand</summary>
  <img alt="Screenshot" src="https://user-images.githubusercontent.com/34649010/130199919-9207655f-7061-443b-b27d-ded6eba243bd.jpg"/>
</details>

This seems to be easy to fix simply by reducing the size of the lettering or increasing the padding on the sides.

**Comment by digitalheir** [comment]
Proposed method of dealing with small screens; see https://github.com/beemdevelopment/Aegis/pull/968

![image](https://user-images.githubusercontent.com/178797/186969477-d1f8c50e-d8ee-43c5-ae53-28fd8255681b.png)

**Comment by digitalheir** [comment]
Alternatively, we could totally over-engineer an adaptive algorithm that uses [`TextView.getLineEnd()`](https://developer.android.com/reference/android/text/Layout.html#getLineEnd(int)) to detect if a `TextView` wraps in the middle of a word, & autosize by iteratively stepping to a smaller font size. But this bucket-based method seems to work fine as well.
