### ISSUE TITLE
Synchronize clock with NIST servers

### ISSUE THREAD

**Issue by ZettaPloom** [beemdevelopment/Aegis#797]
_I looked up guidelines about feature requests but didn't found any. Hope this doesn't get closed due to that._

I noticed the app uses the system clock to generate the OTPs but it is not reliable. Several times my clock is unsynchronized —even if the automatic time is enabled— and I'm using codes that are already expired.

**The feature request is to implement the time using NIST servers by default and if there is no internet connection it should use the system clock.**

Thank you for reading my words.

**Comment by alexbakker** [comment]
Thanks for the suggestion, but we don't have plans to do this. See my reply here: https://github.com/beemdevelopment/Aegis/issues/785#issuecomment-873884940
