### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by rch3579** [beemdevelopment/Aegis#799]
Is there any feature where you have to call/email a user when their password is being changed so that they could give consent to it? That would be a great feature to have. I appreciate the unforgiving nature of the app you've developed. My fear is that someone may stumble onto the app on my phone while it's open and out of sheer amusement and sabotage, change the password. With all due respect, your app doesn't even require that I input the old password in order to change it to a new password. 

I wish to continue to use this app; I have a lot of valuable wallets that require 2FAs provided by it. Also, what would be your opinion on seed phrases? Like what most cryptocurrency wallets have? In case the user accidentally inputs the wrong key in the password they've created and is oblivious to the fact.

If you take the time to read this I thank you for doing so.

- rch3579

**Comment by alexbakker** [comment]
> Is there any feature where you have to call/email a user when their password is being changed so that they could give consent to it?

No. Aegis is local-only and there is no infrastructure in place that would allow us to control whether or not someone can change their password. There are no plans to change that.

> My fear is that someone may stumble onto the app on my phone while it's open and out of sheer amusement and sabotage, change the password. With all due respect, your app doesn't even require that I input the old password in order to change it to a new password.

Users already need to enter their password/biometrics to decrypt the vault and unlock the app. Once they do, the crown jewels are exposed. Changing the password to the vault isn't all that interesting to an attacker. 

I would advise you to enable all options under "auto lock". That'll make sure Aegis automatically locks as soon as you leave the app. If someone were to actually leave their phone somewhere in public with Aegis opened and unlocked, I'd say they have some operational security issues to work on.

> Also, what would be your opinion on seed phrases? Like what most cryptocurrency wallets have? In case the user accidentally inputs the wrong key in the password they've created and is oblivious to the fact.

It would not be possible to regenerate the vault based on a seed.

But in case you're talking about generating mnemonic phrases to encrypt backups with, something like that is being proposed in #692.
