### ISSUE TITLE
Unable to set account photo

### ISSUE THREAD

**Issue by iammexan** [beemdevelopment/Aegis#80]
I tried to set an custom account image but it didn't work. Tried it repeatedly and also by cropping the photo but it doesn't work anyway.

**Comment by alexbakker** [comment]
We're going to need some specifics in order to reproduce this. What are the exact steps that you took to try to set a custom account image? Which image did you select? Did the app show an error? Did the app crash?

**Comment by iammexan** [comment]
Steps:
  1. Tap "Edit" on the account
  2. Tap on the image ( first letter of acc name, say F for Facebook)
  3. Tap Android system
  4. Tap any of the gallery apps 
  5. Choose photo
  6. Preview of the photo comes where the acc image was(F)
  7. Tap "SAVE"
  8. Returns to the home page but the image is not applied.

No crash at all. It just didn't work.

**Comment by alexbakker** [comment]
Thanks for the detailed steps. The UX is a bit confusing here. You need to tap the "check" icon in the bottom right corner to apply the image. We should probably show a prompt if the user tries to click "Save" while they're still in the image editing mode.

**Comment by iammexan** [comment]
That totally worked. I completely overlooked the check mark I guess. I suggest to keep the "save" button inactive while in editing mode and only after clicking the check mark it activates. Maybe also implement the prompt thing in the wizard.

It was a silly mistake but yet you helped me out. Thanks a lot.
