### ISSUE TITLE
Please help out a noob

### ISSUE THREAD

**Issue by GitAlexToTheGreek** [beemdevelopment/Aegis#800]
Hi there 👋

I may not be correctly grasping the concept of using a 2FA authenticator app...

Specific scenario:

- Researched what to do about the T-Mobile breach. 

- Found a WaPo article which included the following: 

> Rethink two-factor authentication
If you’re even mildly security-conscious, you might already have two-factor authentication enabled on some of your online accounts - and that’s good thinking. Here’s the rub, though: If you’re concerned your data has been compromised as part of this breach, it might be time to rethink how you use 2FA.

> Let’s say an attacker manages to obtain your name, date of birth and Social Security number  - if they luck out and find your address and reused password in other data dumps, that might be enough to give them access to your T-Mobile account. If that happens, you could be vulnerable to what’s called a SIM-swap attack, in which the hacker manages to switch control of your phone number to a phone they control. That’s definitely bad, but what could make it worse is if the verification codes sent by services like Amazon, Twitter and many banks are delivered via text message. In that case, the keys to your online kingdom could be ferried straight to someone else.

> One possible fix: Lee suggests using, whenever possible, authenticator apps from companies like Google and Microsoft that live directly on your phone. “Just having the text or the email that goes to the device is not as secure as having that authenticator app,” he said. “We always recommend to consumers that they use that, and to businesses that they offer that."

- Searched for "open source 2FA app", installed & set up Aegis and now have the opportunity to use it while signing up to make a credit freeze with Equifax.

- Here's the reason for this help thread: on the page where it's asking to send a verification code, it only gives the options to select phone or email. And in the Aegis app, my option appears to be clicking the red plus, then either scanning a qr code, scanning an image or manually setting up an entry with info I'm not familiar with and don't believe is provided by the issuing website's verification page.

- Is this a scenario where using such an authentication app (Aegis, Google, MS, etc) _only_ works if the issuing website in question actually lists a specified option to 'use Aegis Authenticator app", or "use Google Authenticator app", etc?

I must be missing something obvious.
I checked the faqs but didn't find the answer. 

Any feedback would be appreciated!

**Comment by alexbakker** [comment]
If the website you're setting up 2FA for does not offer TOTP/HOTP, it's not going to work with Aegis. Since Equifax is asking for your phone number, I'm guessing they only support SMS 2FA.

Usually websites that do support TOTP will tell you to install Google Authenticator. In those cases, it's guaranteed to also work with Aegis.

**Comment by GitAlexToTheGreek** [comment]
Hi Alexander, 

Thanks for the feedback.  

> Usually websites that do support TOTP will tell you to install Google Authenticator. In those cases, it's guaranteed to also work with Aegis.

So in this case, T-Mobile uses GA for example... 

![Screenshot_20210820-082606_Chrome](https://user-images.githubusercontent.com/59787873/130261634-fb6ba183-eca8-4ee7-b287-f250ccaf807d.jpg)

![Screenshot_20210820-082847_Chrome](https://user-images.githubusercontent.com/59787873/130261699-22341d90-0228-4df3-a9c4-be7add082a43.jpg)

**...how would I use Aegis at this particular point?**

**Comment by alexbakker** [comment]
You would scan the QR code that T-Mobile presents with Aegis instead of Google Authenticator. Once that's done, Aegis will give you a code to enter.

**Comment by GitAlexToTheGreek** [comment]
> You would scan the QR code that T-Mobile presents with Aegis instead of Google Authenticator. Once that's done, Aegis will give you a code to enter.

Ok, I'll give that a go - thanks again.
