### ISSUE TITLE
Migrate Pages Slowly to Kotlin

### ISSUE THREAD

**Issue by Hacker437** [beemdevelopment/Aegis#804]
I would help in migrating

**Comment by alexbakker** [comment]
Thanks for offering to help, but we currently don't have plans to rewrite Aegis in Kotlin. I personally start any new Android projects in Kotlin, but since Aegis already has a fairly mature code base in Java, there's little value in rewriting it just for the sake of having it in Kotlin.

**Comment by Hacker437** [comment]
@alexbakker We won't start from scratch but I use Android studio and It automatically converts code to kotlin

**Comment by Hacker437** [comment]
@alexbakker I will migrate the ui in kotlin and make a pull request

**Comment by alexbakker** [comment]
@Hacker437 To be extra clear: We don't currently have plans to invest time in a rewrite of Aegis in Kotlin. So that also means that we won't be reviewing pull requests that rewrite (parts) the code base in Kotlin.

**Comment by Hacker437** [comment]
@alexbakker Ok, Understand.Will be helping in other proposal accepted issues
