### ISSUE TITLE
Minimize or Close app after copying OTP

### ISSUE THREAD

**Issue by jerryn70** [beemdevelopment/Aegis#805]
Minimize or Close the app after copying the OTP

This will help to save some time and quickly paste the code and it also help to avoid one back button press . So we no longer need to press the back button or minimize button manually to hide or close the app . For reference you can check the andOTP app. 
<img src="https://i.imgur.com/RzzqqkV.jpg" width="300"/>

**Comment by Hacker437** [comment]
Thanks for the Idea.
@alexbakker I will make a PR soon about this Proposal

**Comment by alexbakker** [comment]
@Hacker437 I appreciate the enthusiasm, but I would suggest waiting for a proposal to be accepted before submitting a pull request. If we end up rejecting the proposal your work might go to waste.

**Comment by Hacker437** [comment]
@alexbakker Ok

**Comment by youdontneedtoknow22** [comment]
> @Hacker437 I appreciate the enthusiasm, but I would suggest waiting for a proposal to be accepted before submitting a pull request. If we end up rejecting the proposal your work might go to waste.

any news about this? This feature from andOTP is really good and someone already said they can make a PR for it.

**Comment by alexbakker** [comment]
@youdontneedtoknow22 Thanks for the reminder. We've moved this proposal to accepted.
