### ISSUE TITLE
StartActivityForResult Deprecated In some Cases

### ISSUE THREAD

**Issue by InfiniteCoder06** [beemdevelopment/Aegis#807]
Can I make a Pull Request Resolving this?

**Comment by alexbakker** [comment]
Sure! I'm not familiar with the new API yet, but if you are, feel free to submit a patch that addresses this.

**Comment by Hacker437** [comment]
@alexbakker Know about the new API. A pull request comming in few days

**Comment by NumbGnat** [comment]
Just trolling through open issues this evening... It sounds like this was on-track to be fixed... Was it, or didn't @Hacker437 get finished?

**Comment by Hacker437** [comment]
@NumbGnat I was lil busy, I am student of intermediate so not having much time on working with A
egis.
