### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by gitti14** [beemdevelopment/Aegis#809]
2 questions:
1) given that Aegisndoes not have any internet related permissions, how can the aegis app "sync" (like Google auth does) to align the time of the Aegis app and the time of the service providers for which I use the 2fa?  
2) when I make a backup of all my 2fa keys to local storage will this backup file be encrypted already?

**Comment by Hacker437** [comment]
@gitti14 
For Question Number 1 -> It does not connect to internet to Sync Time Instead it uses your System Time
For Question Number 2 -> @alexbakker Will Answer

**Comment by alexbakker** [comment]
> given that Aegisndoes not have any internet related permissions, how can the aegis app "sync" (like Google auth does) to align the time of the Aegis app and the time of the service providers for which I use the 2fa?

Like @Hacker437 said, Aegis uses the system time.

> when I make a backup of all my 2fa keys to local storage will this backup file be encrypted already?

Yes, exports and backups are encrypted by default. There are also ways to export in plain text, but Aegis will warn you if you're trying to do so.

**Comment by gitti14** [comment]
@alexbakker @Hacker437 thanks to both of you

**Comment by jerryn70** [comment]
alexbakker my backup format looks like this (see attached image) , is it encrypted ? Im asking this bcoz when i was using andOTP the￼

backup file extention was json.aes

**Comment by alexbakker** [comment]
Backup files are always encrypted. You can check by opening the file in a text editor. If the "header" is not empty and everything under "db" is a bunch of gibberish, it's encrypted.

**Comment by jerryn70** [comment]
@alexbakker this is the opened backup file using text editor . Pls check its encrypted or not.

![](https://i.imgur.com/QOM3zF0.jpg)

**Comment by alexbakker** [comment]
@jerryn70 Yes, it's encrypted. I've removed the image.

**Comment by jerryn70** [comment]
@alexbakker thank you.

**Comment by alphanerdgen** [comment]
> Backup files are always encrypted. You can check by opening the file in a text editor. If the "header" is not empty and everything under "db" is a bunch of gibberish, it's encrypted.

@alexbakker "header": {

That's it. Just a curly bracket. Should there be more text? Oh, and everything after "db" gibberish.

Sorry, if it's a stupid question. I'm not a coder, just a Foss enthusiast. Migrated to Aegis from andOTP today.
