### ISSUE TITLE
Share option for time based codes

### ISSUE THREAD

**Issue by kurmachu** [beemdevelopment/Aegis#814]
I'd like to be able to share the current code of an entry to the system share sheet. This could be done with a button added to the single item selected menu, where copy and edit are (as well as delete and share which persist even when selecting multiple entries). This can be used to, for example, share to a clipboard-sharing app to easily enter on another device.

**Comment by michaelschattgen** [comment]
Just doing a bit of housekeeping in our GitHub issues. Closing this issue because we don't see the need for this especially since Android 13 and up already allows the user to share their clipboard to other apps/contacts upon copying.
