### ISSUE TITLE
Add setting to focus search on app start

### ISSUE THREAD

**Issue by 0xedward** [beemdevelopment/Aegis#821]
It would be awesome for quick access if we could have a setting functionally equivalent to [andOTP's "Focus search on app start"](https://github.com/andOTP/andOTP/pull/658) where immediately upon unlocking the vault, the search bar is focused, and the keyboard displayed for the user to search for items

**Comment by alexbakker** [comment]
Thanks for the suggestion. We think this is a good idea. Feel free to submit a patch!
