### ISSUE TITLE
Allow disabling Code Group Size

### ISSUE THREAD

**Issue by char-cole** [beemdevelopment/Aegis#822]
This app is really great, but the Code Grouping frustrates me and makes me seriously consider looking for another authenticator. It may seem strange, but I actually find it to be a significant speed bump and source of frustration. If I had the option to _not_ split up the digits, it would be a big usability and QOL improvement for me (and at least a few others, I hope).

I imagine this would entail converting the boolean "pref_code_group_size" to an integer, but I don't know Java so I can't say with confidence that I would be able to make the PR myself.

**Comment by alexbakker** [comment]
Thanks for the suggestion. There's already another issue open requesting more customization for digit grouping, and we'll include your request there as well. See: https://github.com/beemdevelopment/Aegis/issues/480#issuecomment-925051488. Feel free to submit a patch!
