### ISSUE TITLE
Network permission issue 

### ISSUE THREAD

**Issue by ha7sh** [beemdevelopment/Aegis#825]
I dont know why this app disappeared from the network permissions
I tried re installing several times but it is always disappeared from the network permissions 
The thing i tried to disable the data and wifi for this app 
But when i go to the Network Permissions there is no app called Aegis 

I am using android version 11 

If anyone knows whats happening please mention

**Comment by michaelschattgen** [comment]
There is nothing to disable, Aegis doesn't request network permissions. You can't disable permissions apps don't ask for.
