### ISSUE TITLE
Filter by "no group"

### ISSUE THREAD

**Issue by strugee** [beemdevelopment/Aegis#826]
I would love the ability to filter for entries I haven't placed into a group (for example, this would be useful if you wanted to group all your entries and wanted to see which entries you missed). I have code implementing this, although localization breaks it so it's not ready for a PR yet.

If this seems interesting I'd love to chat about how to fix my implementation :P

**Comment by l2extasy** [comment]
Is this something still taken into consideration? Found myself missing the exact same functionality.

**Comment by alexbakker** [comment]
The PR isn't active anymore, but with [this patch](https://github.com/beemdevelopment/Aegis/pull/830#issuecomment-952365358) someone could drag it across the finish line

**Comment by CristianAUnisa** [comment]
What's missing from the patch? I tested it and it's working

**Comment by alexbakker** [comment]
The patch should be complete, I just hadn't thoroughly tested it yet!
