### ISSUE TITLE
Make Motorola bottom gesture navigation bar transparent in system default dark Amoled mode

### ISSUE THREAD

**Issue by ghost** [beemdevelopment/Aegis#827]
Hi,

I have noticed that bottom bar on Motorola Android phone is not transparent in system default dark Amoled mode and instead it uses color. That bottom navigation should be transparent I think and programs like Google Messages, Google Play, Viber and other apps are setting the bar transparent.

Here is one screenshot of that issue in the app, spot the bottom bar:

<img src="https://user-images.githubusercontent.com/59034981/137410592-2e8cf816-35f9-4e29-bd9f-0b59b00cbbb6.png" width="350">

I have tested this on Android 10. Is there a chance to consider changing this please? This might affect other navigation systems as well, which should depend on the launcher.

### Version Information

    App Version: 2.0.2
    Android Version: Android 10

**Comment by InfiniteCoder06** [comment]
@alexbakker I have tested the latest release build and it seems to be working fine

**Comment by alexbakker** [comment]
Glad to hear it!
