### ISSUE TITLE
Browser integration or allow for adding to Android quick panel

### ISSUE THREAD

**Issue by ghost** [beemdevelopment/Aegis#828]
Usually, I am in a browser when I get challenged for my otp. It would be nice if there was an auto complete from Firefox.

Alternatively, bitwarden exposes shortcuts that can be added to the Android shortcut panel. It would be nice to have a similar ability with Aegis.

**Comment by jacksongoode** [comment]
I had the exact idea where the codes could be quickly access from the tile and copied without going into the app.
