### ISSUE TITLE
Support for Authenticator Plus

### ISSUE THREAD

**Issue by kvhnuke** [beemdevelopment/Aegis#836]
HI!
I love your project.
I use Authenticator Plus and as you know it is not currently getting any updates and while I was trying to migrate I realize with latest Android I cant even use the "Export as Text and HTML" which the format Aegis needs.
during my research I found this tutorial https://blog.nigelsim.org/2021-01-15-extracting-authenticator-plus/
It will be awesome if someone can implement it

Thank you

**Comment by neheb** [comment]
@alexbakker just hit this. Those steps don't work. Getting java.lang.String cannot be converted to JSONObject.

Format is:

```
otpauth://totp/x%40email.com?secret=Y&issuer=Z
```
