### ISSUE TITLE
Sync backups to cloud storage

### ISSUE THREAD

**Issue by CrendKing** [beemdevelopment/Aegis#848]
I have a Pixel 6 with Android 12. I have the following apps installed:
* Aegis
* Google Drive
* Google Photos
* Microsoft OneDrive
* [MiXplorer](https://forum.xda-developers.com/t/app-2-2-mixplorer-v6-x-released-fully-featured-file-manager.1523691/)

<details>
<summary>This is what I see when I try to select "Directory for backup files":</summary>

![Aegis](https://user-images.githubusercontent.com/975235/141742549-d683cfee-2294-4ba9-93cd-ce4c7838b5ae.jpg)
</details>

<details>
<summary>This is what I see when I try to send a file attachment from the Messages app (built-in in the OS):</summary>

![Message](https://user-images.githubusercontent.com/975235/141742565-89cd8e1b-a2ae-44f1-9f33-a0a5b786a6e8.jpg)
</details>

Notice that all the storage providers but MiXplorer is missing in Aegis. Is it because Aegis does not support some sort of SAF API in the newer Android version, and only MiXplorer still provide old version? Or am I doing something wrong?

Unfortunately I don't find a way to let MiXplorer provide access of Google Drive or OneDrive to Aegis.

For reference, issue #258 should have completed the cloud syncing feature?

**Comment by CrendKing** [comment]
[Keepass2Android](https://github.com/PhilippC/keepass2android)'s system file picker also includes Google Drive and OneDrive, so it's not specific to just Google stuff.

**Comment by daks** [comment]
I think this has already been answered in https://github.com/beemdevelopment/Aegis/issues/630#issuecomment-746134134

> Aegis doesn't have permission to access the internet, and we'd like to keep it that way. So it's unlikely that we'll ever directly support any such protocol.

I agree with this: having no internet access is a security feature for a TOTP application

**Comment by Hacker437** [comment]
> I have a Pixel 6 with Android 12. I have the following apps installed:
> 
> * Aegis
> * Google Drive
> * Google Photos
> * Microsoft OneDrive
> * [MiXplorer](https://forum.xda-developers.com/t/app-2-2-mixplorer-v6-x-released-fully-featured-file-manager.1523691/)
> 
> This is what I see when I try to select "Directory for backup files":
> This is what I see when I try to send a file attachment from the Messages app (built-in in the OS):
> Notice that all the storage providers but MiXplorer is missing in Aegis. Is it because Aegis does not support some sort of SAF API in the newer Android version, and only MiXplorer still provide old version? Or am I doing something wrong?
> 
> Unfortunately I don't find a way to let MiXplorer provide access of Google Drive or OneDrive to Aegis.
> 
> For reference, issue #258 should have completed the cloud syncing feature?

@CrendKing Actually its a problem with MiXplorer and not Aegis

**Comment by CrendKing** [comment]
Could you explain a bit? If MiXplorer is the culprit, why does it only affect Aegis?

**Comment by alexbakker** [comment]
This actually doesn't have anything to do with MiXplorer. The reason you're not seeing Google Drive or OneDrive when selecting a directory for backups in Aegis, is because those apps don't have full support for SAF. Specifically, they don't have support for the ACTION_OPEN_DOCUMENT_TREE intent. See also: #759

If you try creating a one time export of your Aegis vault, at least Google Drive should appear as an option.

**Comment by CrendKing** [comment]
OK. Is there a chance Aegis add support to these "crippled" storage providers, as the other apps do? It'd great if Aegis can automatically backup to these online storage without manual intervention.

**Comment by Hacker437** [comment]
> This actually doesn't have anything to do with MiXplorer. The reason you're not seeing Google Drive or OneDrive when selecting a directory for backups in Aegis, is because those apps don't have full support for SAF. Specifically, they don't have support for the ACTION_OPEN_DOCUMENT_TREE intent. See also: #759
> 
> If you try creating a one time export of your Aegis vault, at least Google Drive should appear as an option.

Ohh.

**Comment by Lumute** [comment]
I have the same problem, would it be possible to implement some kind of workaround where the folder is chosen using the ACTION_OPEN_DOCUMENT? like maybe not choosing a folder but a file same as when when you do a single export, then always use the same file and overwrites every time, no need to keep last X as there is file version history built into Google Drive...

**Comment by alexbakker** [comment]
> Does Aegis require ACTION_OPEN_DOCUMENT_TREE because of the "Number of versions to keep" feature?

Yes.

> Can Aegis, for example, make an option for the "Number of versions to keep" of "infinite", and drop the requirement of ACTION_OPEN_DOCUMENT_TREE in that case?

Yes, there's an existing feature request for this: #745.

**Comment by CrendKing** [comment]
Thank you! Hope you could add the arguments here to the consideration of that ticket. Looking forward to the progress.

Have a nice day!
