### ISSUE TITLE
Please, take from Crowdin the catalan translation to be included with the compiled app

### ISSUE THREAD

**Issue by caos30** [beemdevelopment/Aegis#853]
I see that the catalan translation is at 100% on Crowdin. Can you add it to the next update of the app. Thanks a lot!! it's a simple but wonderful app.

**Comment by alexbakker** [comment]
We always include the latest changes from Crowdin when we release a new version. No need to ask separately!

**Comment by caos30** [comment]
Thanks for your quick answer @alexbakker , but i can assure you that the catalan translation IS NOT in the current choosable languages on settings of Aegis on my version (2.0.2) downloaded yesterday from F-Droid. Can be an issue with that version on that app store?

**Comment by alexbakker** [comment]
Right. 2.0.2 was released on September 15th. The majority of the Catalan translation work was done in November. So, it hasn't gotten a chance to be included in a release yet.

**Comment by caos30** [comment]
Ok, thanks for all your kindly attention. I supposed that on every new version of the app are included the new changes on translations. It was my error not to look the dates, as you did. My apologies.

**Comment by caos30** [comment]
My friends, catalan language continue not being included in the list of languages to be choosed in the settings section (Language). My translation to catalan and my first ask in this issue was in Nov. 2021, and i see that the last release (2.0.3) was in March 2022. Now we are on September 2022 and i see that catalan language continue not appearing in the settings.

I appreciate your effort and your time with this app, but if you are not able to include in the code of the app the hours of translation that you ask and offer to us, please close the request for translation. Which obviously would be very sad for all.

I suspect that it was a minor lapsus, i suspect that the translation texts to catalan are included in the package release but you forgot to add catalan to the list on settings. It's a shame that so many hours of translation work are lost for such a small thing.

Cheers!
Sergi

**Comment by alexbakker** [comment]
2.0.3 only included a small patch to fix the 2FAS importer. Nothing else has changed since 2.0.2, so the Catalan translation is  also not included yet.
