### ISSUE TITLE
Locked out of app

### ISSUE THREAD

**Issue by hirnidrin** [beemdevelopment/Aegis#854]
###### Info

* __Version__: latest
* __Source__: F-Droid
* __Vault encrypted__: Yes (with biometric unlock: No)
* __Device__: Samsung A3
* __Android version and ROM__: 10, lineage_a3xlte

###### Steps to reproduce

1. Install app, setup with numeric password for vault encryption.
1. Enable "Settings >Security > Use PIN keyboard on lockscreen".
1. Close app, open app, unlock with PIN -> ok. 
1. Use app repeatedly, all fine.
1. Switch off "Settings > Security > Encryption".
1. Switch on "Settings > Security > Encryption", provide alphabetic password.
1. Close app, open app -> numeric PIN keypad shows up (see step 2) -> **cannot enter alphabetic password**

Seems I am **LOCKED OUT**, did not find a way to switch keyboard mode, also copy-paste the alphabetic password into the PIN entry input box does not work. Anything I can do to unlock?

###### What do you expect to happen?

When (re-)enabling Encryption (step 6), always automatically reset the "Use PIN keyboard" setting (step 2).

**Comment by alexbakker** [comment]
Thanks for reporting this. I'm able to reproduce and will push a fix for this shortly, which will be included in the next release.

As a workaround, can you try entering the wrong password 3 times? Aegis should fall back to the regular keyboard.

**Comment by hirnidrin** [comment]
Workaround successful! Outstanding support, thanks a lot. 2 beers on me 🍻
