### ISSUE TITLE
Is there any chance of a Desktop version?

### ISSUE THREAD

**Issue by Wolf-lbh** [beemdevelopment/Aegis#855]
I really want to stop using Authy but one feature keeps me tethered to them and that is the fully functional desktop version. This way I don't need my phone to log into my accounts when I'm at my computer. Also god forbid anything happens to my phone I won't have to go through some horrible backup process which can't even begin to happen until after I find/fix my phone. What if I lose my phone and need to wait to buy an entirely new one? I wouldn't be able to use any authentication services until then if not for the desktop version of Authy. I'm begging you to please make a desktop version so I can finally be free of Authy.

**Comment by Hacker437** [comment]
Duplicate of #165

**Comment by alexbakker** [comment]
Indeed.
