### ISSUE TITLE
Emulate a Virtual Keyboard

### ISSUE THREAD

**Issue by JoshuaFern** [beemdevelopment/Aegis#856]
Hi, I'm new to Aegis but I think a cool and unique feature would be to emulate a virtual keyboard through something like usb or bluetooth. The user would just select an account and the 2fa token would be sent over the air or wire and automatically entered into the second device.

One of the biggest enemies to security is inconvenience. While it may be trivial to enter the token yourself, any small improvement in convenience can go a long way to encouraging the long term use and wide spread adoption of 2fa.

See https://github.com/tejado/Authorizer for an example implementation.

**Comment by alexbakker** [comment]
While this sounds fun to implement, I don't think we should spend time on this. Typing 6 digits is just not a very big inconvenience. In fact, I'd bet typing would still be faster than connecting your phone via USB or messing with Bluetooth until it finally connects. I think we'd be able to count all users of this feature on one hand.

In addition: To emulate a USB keyboard, we'd need to acquire root access, fidget with configfs to get the USB controller in the right mode and then pray that the user's device even supports the hacks we're applying. Bluetooth would be similarly brittle, as the majority of devices don't support the HID device profile.

If we're ever going to look at USB or Bluetooth, it might be worth it for CTAP. Depending on how their story for software authenticators evolves.
