### ISSUE TITLE
Support importing totp from Bitwarden

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [beemdevelopment/Aegis#858]
Bitwarden allows to export json, and csv. It would be good to support importing/stripping the totp codes from these files.
json would be far easier than CSV.

json example: "totp": "JVN3SXK7PFP44WDWSHAP4VVVFUSSGI6N"

**Comment by alexbakker** [comment]
Sounds good to me. Feel free to submit a patch.

**Comment by CristianAUnisa** [comment]
I could work on this, it will take some time tho because I'm on vacation during Easter

**Comment by PedroMarquetti** [comment]
> I could work on this, it will take some time tho because I'm on vacation during Easter

I wish I could help, because I love this app... but don't know how to even begin coding a solution...

**Comment by CristianAUnisa** [comment]
Neither do I, and I develop software for a living 🤣
To be fair, it shouldn't be that hard; I'm reusing stuff that's already coded in Aegis.
