### ISSUE TITLE
Add an option to use biometric authentification by default

### ISSUE THREAD

**Issue by pums974** [beemdevelopment/Aegis#859]
Everything is in the title.

In general, if one activate biometric authentification, one would want to use every time.

**Comment by alexbakker** [comment]
You're probably seeing the password reminder. Try entering your password once. After that, Aegis should start prompting for biometrics by default again.

**Comment by pums974** [comment]
Oh. Okay you're right.

I'm sorry, I didn't paid enough attention.

Thank you !
