### ISSUE TITLE
Crash when enabling encryption on Android 12

### ISSUE THREAD

**Issue by ChaosNicro** [beemdevelopment/Aegis#860]
As descussed on Matrix, my Xiaomi Mi 11 lite 5G (Renoir) running LeOS-S GSI crashes consistently when enabling encryption after the "set password" dialog is confirmed. A logcat filtered for the PID of Aegis is attached. I can provide more info as needed.
[debug.log](https://github.com/beemdevelopment/Aegis/files/7776910/debug.log)

**Comment by alexbakker** [comment]
Thanks for taking the time to capture a log of the crash. This is basically exactly the same issue as #114, but your device is not exactly low-end. Does your ROM set a very small heap size limit, perhaps? What happens if you set ``android:largeHeap="true"`` in Aegis' app manifest?

**Comment by ChaosNicro** [comment]
Thank you muchly for pointing me in the right direction. "dalvik.vm.heapsize" was indeed set to 36m in the gsi I use, where 512m was appropriate for my device. I was able to change it and actually resolved issues with other apps as well. Needless to say everything works as expected now.
