### ISSUE TITLE
Allow to configure default group to select at startup

### ISSUE THREAD

**Issue by justanotheranonymoususer** [beemdevelopment/Aegis#861]
Ideally, I wanted to have folders, but I saw the devs are against. That sad.

At the very least, please allow to configure default group to select at startup, or alternatively, remember the group I selected for next launch.

There are codes for accounts I use extremely rarely, and I don't want to see them most of the time.

**Comment by Hacker437** [comment]
@justanotheranonymoususer Saving groups for the next launch is already present in Aegis. U just have to click on the save button in the group filtering dialog.

**Comment by justanotheranonymoususer** [comment]
Thanks. Not very intuitive ("save" what?), but it works.
