### ISSUE TITLE
Can't register the specific format correctly

### ISSUE THREAD

**Issue by ttodua** [beemdevelopment/Aegis#863]
When registering at bitforex.com, it gives qr-codes, which are registered by AEGIS in a bit unexpected format:
in "Name" field it shows:
`Bitforex:ZZZZZZZ@gmail.com:123456789` 
and in "Issuer" field it's empty.
So, I think you'd might address that, so issue field and name was filled correctly.

**Comment by alexbakker** [comment]
Can you share the full contents of the URI stored in the QR code, so that we have an example to work with? Make sure to replace the secret with something like XXXX first.

**Comment by alexbakker** [comment]
No response.

**Comment by ttodua** [comment]
Sorry, I missed. I can't share the QR code of my account, so if you tried yourself (it's free to sign up there), you would have seen that behavior yourself.
