### ISSUE TITLE
Please accept $XNO (Nano) donations

### ISSUE THREAD

**Issue by avndp** [beemdevelopment/Aegis#864]
Migrated from Authy and in love with Aegis.
Would like to donate Aegis using Nano (https://hub.nano.org/). Please allow me to!

It is as simple as installing [Natrium Wallet](https://natrium.io/)  and pasting the address at Github. Just like [how LibreTorrent is doing](https://github.com/proninyaroslav/libretorrent) at their donations tab.

Thanks.

**Comment by alexbakker** [comment]
We're glad you like Aegis! Sure, I've pasted our Nano address below. It can now also be found by clicking the sponsor button.

```
nano_1aegisc559b1x4p3839egnu579jkd4htpidy14eo9e31gzqmwuafypnj4q94
```

Thanks for offering to donate!
