### ISSUE TITLE
Automatic Backups directly to Google Drive

### ISSUE THREAD

**Issue by HarshXharsH** [beemdevelopment/Aegis#866]
Automated on device backups are good but having a way to store encrypted backups exported automatically to a google drive folder or such would be incredibly useful in case a device is lost.
It can be manually implemented by mounting a google drive folder and exporting to that currently.

**Comment by alexbakker** [comment]
We don't have plans to allow Aegis to access the internet. So all we can hope for is that the Google Drive app gets full support for SAF in their DocumentsProvider at some point. Once it does, backups from Aegis to Google Drive will be supported automatically.

**Comment by krisu5** [comment]
Alternative solution: https://play.google.com/store/apps/details?id=com.ttxapps.drivesync&hl=en&gl=US

**Comment by 3xploiton3** [comment]
or use [mixplorer ](https://forum.xda-developers.com/t/app-2-2-mixplorer-v6-x-released-fully-featured-file-manager.1523691/)then setup automatic backup
