### ISSUE TITLE
Improved decrypt.py

### ISSUE THREAD

**Issue by loxley** [beemdevelopment/Aegis#867]
I have done some changes to the `decrypt.py` program making it able to display the following:

* Continuous TOTP displayment
* Generation of `otpauth://` uri when to restore accounts
* Countdown until next TOTP
* QR code generation when to restore accounts

Its living here currently:

https://github.com/loxley/Aegis/blob/add-totp-codes/docs/decrypt.py

https://github.com/loxley/Aegis/commit/8d2e72eb9d0863864638e19804bb6c986e189859

Let me know if you think its a good fit for making a PR.

**Comment by alexbakker** [comment]
Cool! Perhaps it's an idea to maintain this in your own separate repository? The ``decrypt.py`` in this repo is really only meant to accompany the vault format documentation to show how one would parse the format. I think adding other features to it might make this less clear.
