### ISSUE TITLE
Biometrics setup fails

### ISSUE THREAD

**Issue by TotallyNotInUse** [beemdevelopment/Aegis#870]
###### Info

* __Version__: 2.0.2
* __Source__: Google Play
* __Vault encrypted__: Yes (no biometrics)
* __Device__: Samsung Galaxy Note 10 Lite
* __Android version and ROM__: Android 11 CRDroid GSI

###### Steps to reproduce

1. Enable face unlock in device settings (but no fingerprint)
2. Try to enable biometrics unlock
3. Confirm face
4. Error popups

###### What do you expect to happen?

That biometrics enables correctly

###### What happens instead?

Error

###### Log

```
com.beemdevelopment.aegis.vault.slots.SlotException: javax.crypto.IllegalBlockSizeException
```

**Comment by alexbakker** [comment]
What is the message that Aegis displays in the dialog (above the "Details" part)?

**Comment by TotallyNotInUse** [comment]
The message says:
`An error occurred while trying to enable biometric unlock. Some devices have poor implementations of biometric authentication and it is likely that yours is one of them. Consider switching to a password-only configuration instead.
`
I also uploaded the full log:
[logcat.txt](https://github.com/beemdevelopment/Aegis/files/7883968/logcat.txt)

**Comment by alexbakker** [comment]
Thanks for the info. Like the message says, some devices have a poor implementation of biometric unlock, and it looks like yours is one of them. It's also possible that this is caused by the custom ROM you're using.

I'm afraid a password-only configuration is the only option for you.
