### ISSUE TITLE
Missing "Facebook" issuer when import from FreeOTP `tokens.xml`

### ISSUE THREAD

**Issue by PeterDaveHello** [beemdevelopment/Aegis#871]
###### Info

* __Version__: 2.0.2
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Pixel 6
* __Android version and ROM__: Android 12 (official, updated to 2021/11)

###### Steps to reproduce

Extract `tokens.xml` from FreeOTP, and import to Aegis, everything looks good enough, except the "Facebook" issuer is missing. However, other issuers like 'Google' or 'GitHub' were processed properly.

I checked `tokens.xml` manually, the data doesn't seem to be wrong: `<string name="Facebook:accountname">`, also tried some tools like https://gitlab.com/stavros/freeotp-to-andotp-migrator and https://gitlab.com/sid-the-sloth/conversion-scripts/-/blob/master/freeotp-xml-to-json.js, looks like they can process the data correctly, so I'm not sure that's wrong with the Aegis import process.

###### What do you expect to happen?

I expect Facebook account has the Facebook issuer data, just like the other issuers.
...

###### What happens instead?

The issuer 'Facebook' is missing.

BTW, there are also some other accounts with the missing issuer, but I can't recognize them easily, because I use a few email addresses or accounts with many services, when the issuers are missing, I need some more time to confirm which of them are missing, but hopefully, maybe the Facebook example would be enough to dig the problem.
...

**Comment by alexbakker** [comment]
The importer logic doesn't look at the ``name`` attribute of the XML tag, but at the ``issuerExt`` and ``label`` fields in the JSON that it contains. Could you check if those have the "Facebook" and "accountname" as their values?

**Comment by alexbakker** [comment]
No response.
