### ISSUE TITLE
Sometimes exporting json or txt (unencrypted) creates a 0 byte file

### ISSUE THREAD

**Issue by mdkberry** [beemdevelopment/Aegis#872]
###### Info

* __Version__:  2.0.2
* __Source__:  Google Play
* __Vault encrypted__:  (Biometric unlock, plus pin access, and it using an encrypted vault)
* __Device__: Samsung J5 fully updated with Android vrs 9
* __Android version and ROM__: Andoird vrs 9 (not sure of ROM but it is standard build not rooted or anything)

###### Steps to reproduce

I plug a USB-A stick into the android device (with an adaptor)
then export from Aegis app in json and then txt format (both unencrypted)

###### What do you expect to happen?

files exported should both have data in them

###### What happens instead?

one will sometimes have data, the other not ( 0 bytes)

 It has varied between json and txt so far which one shows the error.

when I go back into it and download the failed one, it then works on the second attempt. This has happened twice out of two times using it. I put the USB into a computer to check the file size so it is removed from the Android device before the attempt was repeated.

###### Log

no debug log saved at this point

**Comment by alexbakker** [comment]
I think this is unlikely to have something to do with Aegis. Is this also happening if you export the internal storage instead of the USB stick? Could you capture a log with ADB of when the 0 byte file is written?

**Comment by mdkberry** [comment]
_"Is this also happening if you export to internal storage instead of the USB stick?"_
 
I dont want to save the file onto the phone for security reasons so saving directly to the SD card only, but will see if I can find another to test it on. 
 
 _"Could you capture a log with ADB of when the 0 byte file is written?"_

I'll have to look into how to do that and come back to you.

**Comment by mdkberry** [comment]
I tested this using an SD card and so far it has been working fine. So I think you are correct - this is likely something to do with the USB or Android, not Aegis. I guess you can close this ticket. thanks.
