### ISSUE TITLE
Add Entry button not always selectable via d-pad

### ISSUE THREAD

**Issue by jtlinux** [beemdevelopment/Aegis#874]
###### Info

* __Version__: 2.0.2
* __Source__: APK via F-Droid
* __Vault encrypted__: Yes
* __Device__: Sonim XP3plus
* __Android version and ROM__: 11 (Stock Sonim ROM)

###### Steps to reproduce

(Device does not have touch screen; it has a d-pad, enter button, and button that opens the menu [Lock, Settings, About])
1. Add a couple of TOTP entries into the vault (this will make the entries take up more space than the screen is big; this will enable scrolling)
2. Go down the list using the d-pad to reach the Add Entry button
3. When you reach the bottom, the Add Entry button disappears (I assume this is a feature so that the button gets out of the way)
4. Because the Add Entry button disappeared, it is no longer selectable, so you cannot add any more entries to the vault

###### What do you expect to happen?

At the point when the Add Entry button is hidden, pressing d-pad down will make it reappear and focus on it.
Or, possible to add Add Entry option to the menu?

###### What happens instead?

Pressing d-pad down does not make the Add Entry button reappear, and it is unselectable when hidden. Unable to add new entry.

**Comment by alexbakker** [comment]
> I assume this is a feature so that the button gets out of the way

Indeed.

I suppose we could listen for ``KeyEvent.KEYCODE_DPAD_DOWN`` and make the entry button reappear.

**Comment by jtlinux** [comment]
If possible, I'd appreciate it a lot. Thank you!

**Comment by CristianAUnisa** [comment]
@alexbakker what do you think about not hiding the Add Entry button when a key has been pressed and permit the hiding again when input is coming from the touch screen?

**Comment by alexbakker** [comment]
@CristianAUnisa Sure, that sounds reasonable.
