### ISSUE TITLE
Allow showing account name below the issuer

### ISSUE THREAD

**Issue by mperry2** [beemdevelopment/Aegis#876]
Showing the account name next to the issuer still cuts off most of account name where it can't be viewed. Seeing the full account name can be important when you have many accounts from the same issuer.

Please add a setting that will allow showing the account name below the issuer. Maybe the existing setting could be changed to allow three options to choose where to place the account name relative to the issuer name:

- None
- Right
- Below

The parentheses should be removed when shown below.

**Comment by dsamersoff** [comment]
I concur the proposal because I have exactly the same problem - many accounts from the same issuer and it's hard to distinguish between them.

The option to show name instead of issuer or show name before the issuer or show name on the separate line is strongly desired.

**Comment by NumbGnat** [comment]
I'll vote for this as well. I have found myself attempting to hold my finger down, hoping to scroll the entry left and right, because I wanted to see more information.

**Comment by Dvlnst** [comment]
I would love this feature too. When there are multiple entries with the same Issuer it's a disaster. I hope you will consider and implement it as soon as possible.

Regards.
