### ISSUE TITLE
Time syncing issue when using AWS MFA

### ISSUE THREAD

**Issue by elieobeid7** [beemdevelopment/Aegis#878]
###### Info

* __Version__: 2.0.2
* __Source__: (Google Play)
* __Vault encrypted__: Yes (with biometric unlock)/Yes
* __Device__: Google Pixel 4a
* __Android version and ROM__: Stock android, version 12

###### Steps to reproduce

I added the 2fa code manually, this is how AWS generates it's code in organizations, no QR code, just some key

When signing in to AWS, it says 

This issue started occurring yesterday, before that I didn't have any 2FA issues to get into my account, I keep getting this

`Your authentication information is incorrect. Please try again` . 

[Source](https://stackoverflow.com/questions/50378652/aws-iam-error-your-authentication-information-is-incorrect-please-try-again)

If I keep trying, AWS will tell me that my device is out of sync and ask me to resync the 2fa and then give me the error again. The devops tried to reset the 2fa multiple times, I will be able to login one time or twice, but then AWS will say that my device is out of sync eventually.

Then the devops team asked to use google authenticator which worked fine.

The AWS servers are India Mumbai,  I'm in Dubai.  Devops told me that my aws is in Dubai and that there's no timezone issue, AWS should be able to know where I'm at.

Maybe AWS is generating its 2fa codes faster or slower than google authenticator? how to debug that?

**Comment by alexbakker** [comment]
Aegis doesn't do any time synchronization on its own. It relies on Android's system time to be correct. If AWS reports that Aegis is generating incorrect codes, it's almost certain that your device's time is not in sync. Can you navigate to https://time.is on your device? How far has the clock drifted?

**Comment by elieobeid7** [comment]
![photo_2022-01-22_21-16-29](https://user-images.githubusercontent.com/660142/150648802-ea125dde-83e0-4193-804c-50663cda6263.jpg)

That's strange, I have work on monday, I'll retry to login to AWS account using both google authenticator and Aegis, I don't think 0.4 seconds is enough to cause issues

**Comment by Hacker437** [comment]
@elieobeid7 Since you have added to both Aegis and Google Authenticator compare the codes between them once.

**Comment by elieobeid7** [comment]
I exported the 2fa from google authenticator back to Aegis and it's working fine, can't reproduce the error, so I'll close the ticket for now and reopen it if it happens again

**Comment by pein0saga** [comment]
> I tried "time correction for codes" in google authenticator and it actually wouldn't work at all. I finally solved the time sync error by  correcting my router (I cleared  all JFFS custom scripts on my merlin router and  sync error was gone )

_Originally posted by @pein0saga in https://github.com/beemdevelopment/Aegis/issues/785#issuecomment-1510387591_
            
If you are encounting time problems and using customed router firmware, just check your scripts on router or NTP server
