### ISSUE TITLE
Unable to import Aegis backup file to Android 12 CalyxOS

### ISSUE THREAD

**Issue by Glitterbo** [beemdevelopment/Aegis#879]
* __Version__: 2.0.2
* __Source__: F-Droid
* __Vault encrypted__: Yes (with biometric unlock)/Yes
* __Device__:Pixel 5
* __Android version and ROM__:12 CalyxOS 3.1.0

###### Steps to reproduce

A detailed list of reproduction steps.
Install Aegis from F-Droid, setup biometric unlock and add password to vault. Click import file for back up from settings and select Aegis backup from download folder in the phone added via USB lead from a backup off a Samsung S21 on Android 12. On selecting the file, get the attached image and it won't go any further. Have also tried adding an unencrypted vault with the same result.

![1](https://user-images.githubusercontent.com/98190488/150604129-b71c179f-9f95-4437-b756-f5d781912927.jpg)

###### What do you expect to happen?
Import to be successful and all entries then visible in the app
...

###### What happens instead?
Error message as attached above
...

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment]
Could you inspect the file you're trying to import? Does it looks similar in structure compared to: https://github.com/beemdevelopment/Aegis/blob/master/app/src/test/resources/com/beemdevelopment/aegis/importers/aegis_encrypted.json? And if not, what are the differences?

**Comment by Glitterbo** [comment]
Hi and thanks for the help.

I am not sure tbh as not too sure how to get what you have there.

I also tried importing to the S21 it was created on and it fails in exactly the same way?

I eventually got it to work by exporting the txt file and importing that to the other phone.

the only thing it lost was the grouping but have now manually done that.

Thanks again.

**Comment by alexbakker** [comment]
> I am not sure tbh as not too sure how to get what you have there.

I just meant to open the file (the one you're trying to import into Aegis) in a text editor and see what it looks like.
