### ISSUE TITLE
add a bundle of favicons in the app

### ISSUE THREAD

**Issue by sheikh-azharuddin** [beemdevelopment/Aegis#880]
The andotp app has a nice feature..it has bundle of app favicons in the database which gets added automatically to new entries based on the site or domain..thus making it easier to identify.

So why not add same thing in aegis?

![Screenshot_20220127-121458854](https://user-images.githubusercontent.com/58127841/151307626-3f302596-df9f-4b46-854c-f656435c6ac1.jpg)

**Comment by krisu5** [comment]
Aegis already has icon pack feature, which basically is the same thing: https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#with-icon-pack

**Comment by alexbakker** [comment]
Indeed. You can download @krisu5's great icon pack and import that into Aegis. There are currently no plans to ship an icon pack along with Aegis.
