### ISSUE TITLE
Add icon Tip

### ISSUE THREAD

**Issue by nikhilbadyal** [beemdevelopment/Aegis#881]
In the icons section. Along with aegis-icon. Add a link to [this repo](https://github.com/alexbakker/aegis-simple-icons). There are 2000+ icons here.

**Comment by alexbakker** [comment]
Thanks for the suggestion, but I don't think we should advertise that one in the app. The pack contains a lot of icons for companies/services that don't support 2FA. The icons are also automatically generated and don't have the same level of polish as the ones in aegis-icons.
