### ISSUE TITLE
Error Scan QR Code AOL.com

### ISSUE THREAD

**Issue by 3xploiton3** [beemdevelopment/Aegis#883]
###### Info

* __Version__: 2.0.2 (50)
* __Source__: (Google Play)
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: redmi note 5
* __Android version and ROM__: 10

###### Steps to reproduce

A detailed list of reproduction steps.

Cannot read QR Code from aol 2fa

**Comment by alexbakker** [comment]
This looks like an invalid QR code.

**Comment by 3xploiton3** [comment]
> This looks like an invalid QR code.

its not invalid QR Code, i have tested with google authenticator its work well

**Comment by alexbakker** [comment]
Compare the QR code you shared to the valid example below. See what's going on here? The colors in your image are inverted, which makes it an invalid QR code.

![image](https://user-images.githubusercontent.com/2387841/153392795-6dbac62c-f72b-4961-a16b-9f99c78421db.png)

Google Authenticator probably first tries to decode the QR code regularly. And when that fails, it inverts the image and tries again. I suppose we could do that as well to handle this case, but I really wish people would just stop making random variations of QR codes that make them invalid.
