### ISSUE TITLE
Easy to click button for deleting/locking database

### ISSUE THREAD

**Issue by Bugaddr** [beemdevelopment/Aegis#886]
Apps like keepassdx https://github.com/kunzisoft/keepassdx have a small button on the bottom part, which is easy to see and press incase of emergency to close database, which seems usefull for some cases. I knew aegis already have this button on top menu but it would be good if you are able to see lock button easily for sudden reflex action to lock/delete database. Alternatively or along with lock button an option to lock/delete database can be provided (in auto lock) by using volume keys twice or thrice.

**Comment by alexbakker** [comment]
I don't think we need another lock button in the app. If you'd like to lock the app in an emergency, consider enabling auto lock in the settings of Aegis. That'll allow you to have Aegis lock the app when you turn off your screen.

> An option to lock/delete database can be provided (in auto lock) by using volume keys twice or thrice.

This would be too easy to do accidentally in my opinion. Instead, consider using [Ripple](https://play.google.com/store/apps/details?id=info.guardianproject.ripple).
