### ISSUE TITLE
do not show codes at app startup

### ISSUE THREAD

**Issue by f1-outsourcing** [beemdevelopment/Aegis#891]
I am not sure what the reason is behind showing all codes when opening the app. But I do not really like that some code that I am not using is being shown. I would even argue it is totally the opposite of secure, showing a code to eg banking while you are not even using it. 

Maybe better to have users decide if they want this or not from the settings menu?

**Comment by alexbakker** [comment]
Try the "Tap to reveal" option.

**Comment by f1-outsourcing** [comment]
> Try the "Tap to reveal" option.

Hmmm, I feel a little like an idiot having to ask this. But I am not having this in settings. I checked appearance and beviour, and see only "Highlight tokens when tapped" but that is not working.

PS. using the version in fdroid 2.0.2
