### ISSUE TITLE
2fas Authenticator

### ISSUE THREAD

**Issue by MrComexs** [beemdevelopment/Aegis#892]
###### Info

2.0.2
F-Droid
Yes with biometric
Samsung S10 (SM-G973F/DS)
OneUI 4.0 android 12

Open 2FAS auth
Go to 2FAS backup export the file
open Aegis
go to setting and import & Export
Import from file
select 2FAS Authenticator
select the .2fas file
###### Log
com.beemdevelopment.aegis.importers.DatabaseImporterException: Unsupported schema version: 2
```

**Comment by alexbakker** [comment]
See: fcb7bf032b00781b61e1c8bd46ec4a4357eb7bc8. The fix is not available in a release yet though.
