### ISSUE TITLE
Multiple Steam Accounts Guard Import only imports the first Steam Recovery

### ISSUE THREAD

**Issue by peterge1998** [beemdevelopment/Aegis#894]
###### Info

* __Version__: latest
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: OnePlus 8
* __Android version and ROM__: LOS11 w microg

###### Steps to reproduce

A detailed list of reproduction steps.
Import from steam app with root

###### What do you expect to happen?

Import both steam guard keys

###### What happens instead?

Only the key from the account which was added to steam app first is able to import

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment]
Thanks for the report. You're right, the importer currently doesn't support reading multiple files:

https://github.com/beemdevelopment/Aegis/blob/71eb6b133cc8607787e8b85a1676cbbfca674edd/app/src/main/java/com/beemdevelopment/aegis/importers/SteamImporter.java#L38-L39

**Comment by peterge1998** [comment]
Just in case anyone is facing this problem:
It's possible to extract the TOTP token manually. In `/data/data/com.valvesoftware.android.steam.community/files/` is one file for every steam guard token shown in the app.
I was able to add it to Bitwarden, by copying the part after `secret=` and add it with `steam://` to TOTP.

**Comment by alexbakker** [comment]
Since we won't be able to import from new versions of the Steam app soon, I don't think it's still worth it to spend time to fix this. See: #986.
