### ISSUE TITLE
Fresh install on new device always prompts for password

### ISSUE THREAD

**Issue by zacjohnston** [beemdevelopment/Aegis#895]
###### Info

* __Version__: 2.0.2
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Pixel 5a
* __Android version and ROM__: 12

###### Steps to reproduce

I used Aegis on a Pixel 3a, and recently upgraded to a Pixel 5a. I used Google's "transfer apps " process to copy my apps to the 5a.

Aegis appeared on the 5a, but kept giving me "Incorrect password". No big deal, I changed the password on the 3a, but the 5a still says "Incorrect password".

A simple solution would be to just re-setup Aegis on the 5a and import from backup, but after uninstalling/reinstalling (even after clearing cache and app data, resetting phone etc.), it still prompts for a password.

I can't seem to force Aegis into a fresh setup on the 5a. It's permanently stuck asking for a password.

###### What do you expect to happen?

Install Aegis on new device from scratch.

###### What happens instead?

Aegis always asks for a password.

**Comment by zacjohnston** [comment]
It occurred to me this might be caused by the Android backup system, which I had enabled on the 3a. 

I tried disabling it in the Aegis settings on the 3a, then reinstalled on the 5a. Alas, still asks for a password.

Regardless of the cause, Aegis should offer the user the option of creating a new vault. Aegis is completely unusable on my new phone, so I'll have to set up a different authenticator app until the problem can be solved.

**Comment by alexbakker** [comment]
You're right, the reason your vault keeps getting restored on reinstall of Aegis is likely because you had enabled participation in Android's backup system. That's expected behavior, but if you've forgotten your password this can be a problem.

I'm surprised that performing a "Clear storage" of Aegis doesn't help though. It does for me. Could you double check? We can't really add an option to wipe everything from the lock screen.

**Comment by zacjohnston** [comment]
Thanks, it indeed worked with: "Clear storage --> Open Aegis".
I was previously trying: "Clear storage --> uninstall/reinstall --> Open Aegis", which I assume was restoring the account from Android backup on install.
