### ISSUE TITLE
Ability to quickly copy other attributes (Name, Issuer, Note)

### ISSUE THREAD

**Issue by unoukujou** [beemdevelopment/Aegis#896]
I would find it useful to be able to copy other attributes when the need arises.

Old version had a menu on long-press which would have been a nice place to have options like:

Copy OTP
Copy Name
Copy Issuer
Copy Note
Copy Secret

Without this menu, perhaps there could be copy options show up on a swipe or double-tap or something? Or bring back the long-press menu?

As it is now, if I want to copy the Note of an entry, I have to long-press -> edit -> find the note and long press -> select all -> copy. Meanwhile I'm in "edit mode", if I press something incorrectly during this process I could possibly modify the entry without actually meaning to. So it's kind of a hassle trying to copy other attributes besides the OTP.

**Comment by alexbakker** [comment]
I personally don't really see the need for this, but perhaps I'm missing something. How often do you find yourself copying something other than the code from Aegis? What are you copying? And where are you copying it to?

> Old version had a menu on long-press which would have been a nice place to have options like

I don't recall Aegis ever having a menu on long press of an entry. We used to have a menu pop up when tapping an entry, but that is now tied to other actions like copying the code and highlighting an entry.

**Comment by alexbakker** [comment]
> Since the database is encrypted, I started experimenting with using Aegis like a password manager.

I see. This is really not a supported use case, and I don't think we should be adding features to accommodate it.
