### ISSUE TITLE
Terrible "New User" experience when moving between devices

### ISSUE THREAD

**Issue by tunbridgep** [beemdevelopment/Aegis#897]
###### Info

* __Version__: 2.02
* __Source__: F-Droid
* __Vault encrypted__: Yes, with biometric unlock
* __Device__: Motorola One Vision
* __Android version and ROM__: LineageOS 15

###### Description

The user experience when moving from one device to another is extremely unintuitive. In order to complete the welcome wizard, you have to create a new database, which is fine for new users, but for users with an existing database (such as a user who upgraded to a new phone), you have to create a new database, then import all your old entries manually from a backup. If you wish to keep reusing the same password, you have to manually set the new database to use the same password as the backup one. It would be nice if this was a little easier and more streamlined. I was actually confused for a second on what to do because I was specifically looking for an "import" button in the welcome wizard. I am a power user so I figured it out pretty quickly, but a less experienced user might get very confused that they have to create a new database in order to use their existing one.

###### Steps to reproduce

1. Use Aegis on your old phone
2. Backup your aegis database on your old phone using the exporter
3. Get a new phone (or simply delete aegis and it's data) and transfer the backup over to the new device
4. Install aegis on the new phone
5. In the Welcome to Aegis screen, press next
6. Set a new password for a new vault (set the same password you're used to)
7. Go to settings
8. Import your old vault backup
9. Type the password (even though it's the same as your new one) and press OK
10. Import the vault contents
11. You now have something resembling what you had before

###### What do you expect to happen?

Restoring a backup on a new device/install should be an easy, straightforward experience.

I propose something like this:

1. Use Aegis on your old phone
2. Backup your aegis database on your old phone using the exporter
3. Get a new phone (or simply delete aegis and it's data) and transfer the backup over to the new device
4. Install aegis on the new phone
5. After the first welcome screen (the one with the aegis logo), there's a new screen with 2 buttons, New Database or Restore From Backup
6. press "Restore from Backup"
7. Select the backup file
8. The app will ask for your database password
9. Type it and press OK
10. Aegis is now ready to go in the same way it was when you used it on your other phone

###### What happens instead?

It's clunky as you need to make a new database (and use the same password manually if you want the same experience) and import the entries yourself in the settings menu.

###### More Info

This will make for a much quicker/nicer experience when moving from an old phone to a new one.

Obviously this isn't really a "bug" in the strictest sense, it's more a usability issue. It should probably be considered low priority as a result.

EDIT: In hindsight, I should have probably made this a feature request, not a bug report.

**Comment by alexbakker** [comment]
You're not the only user who got confused by this, so thanks for creating an issue about it. I agree that the setup process for existing users can be improved by letting them import their backup in the setup screen.

**Comment by LeonF1N** [comment]
I second...Thanks for logging this issue, makes zero sense and very counterintuitive. I'm a fan of aegis authenticator and want to continue to support, but please make this experience better as I've upgraded mobile twice in a couple of years and surprised that this is as clunky as it is. Thanks for listening

**Comment by alexbakker** [comment]
Addressed by #925.
