### ISSUE TITLE
[question] how is encryption implemented?

### ISSUE THREAD

**Issue by paolostivanin** [beemdevelopment/Aegis#902]
Hello,
I'd like to add support for Aegis encrypted backup to [OTPClient](https://github.com/paolostivanin/OTPClient/).
In order to do that, I'd need to know how the file is encrypted. Something like https://github.com/andOTP/andOTP/wiki/Backup-encryption would be really helpful.

Thanks a lot :)

**Comment by alexbakker** [comment]
See: https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md

**Comment by paolostivanin** [comment]
cool, thanks a lot :)
