### ISSUE TITLE
TXT file export -> import error

### ISSUE THREAD

**Issue by heydojo** [beemdevelopment/Aegis#903]
###### Info

* __Version__: Aegis 2.0.3
* __Source__: F-Droid
* __Vault encrypted__: Yes Biometric
* __Device__: Redmi Note 7
* __Android version and ROM__: Android 11 - ArrowOS & LineageOS

###### Steps to reproduce

Export the vault
Choose .TXT - (If you choose JSON here it cannot be shared via bluetooth)
Uncheck "Encrypt the vault" (unsure if this is relevant but mentioning anyway) & Check I understand
Tap on OK
Visit the "Downloads" folder containing the exported backup file
Share the backup file via bluetooth with the device you want to transfer the vault to
After successfully accepting the backup file, import it into Aegis on the handset it has been sent to

###### What do you expect to happen?

The vault is imported successfully.

###### What happens instead?

There is an error message on screen with a programming string and the vault is not imported.

To work around the error, I was able to export locally as JSON, then rename the file from .json to .txt so that Android will allow it to be sent via bluetooth, then transfer it to the other device, rename it back to .json from .txt and it then imports successfully.

Weird bug.

**Comment by alexbakker** [comment]
What does the error message say, specifically?

**Comment by CristianAUnisa** [comment]
I'm going to say something stupid, but did you select "Plain text" instead of "Aegis" when importing the file?

**Comment by alexbakker** [comment]
@CristianAUnisa You're right, this likely what went wrong. If you try to import a plain text file as "Aegis", you'll get an error.

**Comment by heydojo** [comment]
> What does the error message say, specifically?

Try it for yourself and you'll be able to see 🤦‍♂️

>I'm going to say something stupid, but did you select "Plain text" instead of "Aegis" when importing the file?

Apologies if English isn't your first language but you did read what I wrote? Right?

>Choose .TXT - (If you choose JSON here it cannot be shared via bluetooth)

> After successfully accepting the backup file, import it into Aegis on the handset it has been sent to

Haven't got time to write bug reports that aren't going to be read properly or answer silly questions\it be implied that there is "user error" here. As a software developer myself, I appreciate it when people report bugs. It helps me to improve my application and I try at least reproduce bugs reported to me before commenting\replying to bug reporters.

Guys, the application is cool. It does have some glaring bugs though. I've tried to help you by reporting one. Please close\delete the report, if you don't care.
Thanks

**Comment by alexbakker** [comment]
@heydojo 

> Try it for yourself and you'll be able to see :man_facepalming:

Do you think I would ask if I was able to reproduce the issue and see the error myself? So I'll ask again, what does the error message say?

**Comment by alexbakker** [comment]
No response.
