### ISSUE TITLE
Cannot backup to Nextcloud anymore

### ISSUE THREAD

**Issue by sblatt** [beemdevelopment/Aegis#906]
###### Info

* __Version__: 2.0.3
* __Source__: F-Droid
* __Vault encrypted__: Yes with biometric unlock
* __Device__: Samsung S21 5G SM-G991B/DS
* __Android version and ROM__:  Android 12 Samsung rom Version Feb 1 2022

###### Steps to reproduce

Settings -> Backup -> Backup Folder -> 3 Lines on top left (Menu) -> open From -> Nextcloud

###### What do you expect to happen?

Display Folder structure from Nextcloud

###### What happens instead?

Error message:
![Screenshot_20220411-152305_Files](https://user-images.githubusercontent.com/250098/162750238-b9769d64-0e01-407c-9f5e-f6160bc18edb.jpg)

"Cannot load content"

**Comment by alexbakker** [comment]
It's actually Android's DocumentsUI that's displaying this error. Not Aegis. These errors usually happen for one of two reasons:
1. Something went wrong while communicating with Nextcloud's DocumentsProvider.
2. Nextcloud's DocumentsProvider returned an error.

Either way, this is not something we can solve on Aegis' side. Try opening the Nextcloud app. Are you still logged in and able to see your files there?

**Comment by sblatt** [comment]
Thank you for your reply.
Nextcloud works just fine.
I just deinstalled aegis and reinstalled it from fdroid, now the Nextcloud
connection works. I guess this solves this for me, at least for the moment.
Thank you again for your work!

Alexander Bakker ***@***.***> schrieb am Mo., 11. Apr. 2022,
20:18:

**Comment by robertmens** [comment]
I'm experiencing the same issue with Aegis 2.0.3 downloaded from Google Play.
Reinstalling did not help for me. The Nextcloud app itself works fine.
Somehow the issue started occurring 3 days ago.
