### ISSUE TITLE
Order alphabetically A to Z is not always enforced correctly

### ISSUE THREAD

**Issue by Radotornado** [beemdevelopment/Aegis#907]
###### Info

* __Version__: 2.0.3
* __Source__: Google Play
* __Vault encrypted__: Yes, with biometric unlock
* __Device__: Samsung Galaxy S20FE SM-G780F/DS
* __Android version and ROM__: 12 and One UI 4.0

###### Steps to reproduce

1. Import two Google accounts via QR code. 
2. Order all tokens alphabetically A to Z
3. Delete one Google account.
4. Add the same account via QR code again.
5. Order all tokens alphabetically A to Z again.

###### What do you expect to happen?

Expected behavior is for all tokens to be alphabetically sorted.

###### What happens instead?

Instead the newly added Google account is a the end of the list. 
If the ''Custom'' order is applied and the Google account is moved manually, and then the alphabetical sorting is applied once again, it is not at the end, but in the middle of the list, again not in the right place.

**Comment by CristianAUnisa** [comment]
Regarding the step 2, are you sorting by account or issuer? A screenshot would be helpful, you can hide sensitive informations

**Comment by alexbakker** [comment]
I wasn't able to reproduce this with the steps provided. Could you share a screen recording of what you're seeing?

**Comment by Radotornado** [comment]
It was not able to recreate it too. Sorting was by issuer.

**Comment by alexbakker** [comment]
I am able to reproduce something similiar in a different way:
1. Sort "Issuer (A to Z)"
2. Change the issuer of an entry in such a way that you'd expect it to get a different spot in the list because of the sorting
3. Notice that the entry is still in the same spot.
