### ISSUE TITLE
Button size not adaptive

### ISSUE THREAD

**Issue by mdmk** [beemdevelopment/Aegis#91]
Language French
Screen 1080p
Android 8.1 Stock (Motorola Moto G4 Plus)

The unlock vault button does not scale correctly (text on two lines)

```
DEVÉROUILLE
R
```

![](https://i.imgur.com/xrvGbIX.png)

**Comment by michaelschattgen** [comment]
Thank you for your contribution. We will fix this.

**Comment by mdmk** [comment]
There is also some text that does not fit (French so much longer than english in some cases).
![](https://i.imgur.com/1PhFTRx.png)

**Comment by alexbakker** [comment]
I'm afraid we can't do much about the dialogs, because the style of those is out of our control. I've fixed the button width in #101 though.

**Comment by mdmk** [comment]
Thanks for fixing the button size.

Can you please test replacing

`Sélectionner l\'application à partir de laquelle vous souhaitez importer une base de données`

by

`Choisir l\'application depuis laquelle importer une base de données`

or

`Choisir l\'app depuis laquelle importer une base de données`

if the first is too long.

This should be significantly shorter (at least in verbatim it is) without losing much sense.

Thanks.

**Comment by michaelschattgen** [comment]
Thank you very much for your work mdmk! I'm thinking about adding some kind of description/message to that specific dialog so we can have "_Sélectionner l'application_" as title and "_Sélectionner l'application à partir de laquelle vous souhaitez importer une base de données_" or something similar as the description between the title and the list of applications.

I prefer this solution because I don't expect French to be the only language that is messing this dialog up.

**Comment by mdmk** [comment]
You're welcome. Glad to see you're so reactive.
That's great to think of the future integration of other languages.

Instead of trying to put more info on the dialog, you could perhaps put it in the previous step, option menu?

That is, lengthen the description here:

![](https://i.imgur.com/PlQCuNE.png)

To be able to shorten the text here:

![](https://i.imgur.com/jTsic8q.png)

Keep things simple in fact.

There could also be a tooltip on selection dialog, but I have no idea of how it should be done following material design guidelines. 

Or the dirty way, there could be a comment in the english template at the end of line so that translators know there is problem here and should keep text short.
That could be an easy (won't)fix for short term if integration of better fix is not possible at the moment.

**Comment by mdmk** [comment]
I found an other field that is too short :

```
Chiffre
s
```

![](https://i.imgur.com/EUfwwAW.png)
