### ISSUE TITLE
Can Aegis restore using recovery code from Google Authenticator app?

### ISSUE THREAD

**Issue by dongryphon** [beemdevelopment/Aegis#915]
I have recovery codes from my old phone and Google Authenticator but I have switched to Aegis on my new phone and would like to use the recovery codes to create a missing entry.

If I enter the recovery code as the Secret in Aegis, I get an error about invalid base32 value.

Can these codes be used to recover the entry?

**Comment by Hacker437** [comment]
@dongryphon You can use Google Authenticator transfer option, By using that option it will generate a QR code, Scan with Aegis App. You will them on the New Phone
