### ISSUE TITLE
Localization errors

### ISSUE THREAD

**Issue by simonporte** [beemdevelopment/Aegis#92]
Translation not applied : `Manage groups`

![](https://i.imgur.com/D0MWmkz.png)

Translation not applied : `Export the database`
String missing in source : `Keep the database encrypted`

![](https://i.imgur.com/a2y5FvA.png)

**Comment by mdmk** [comment]
Here I don't know where the text does come from (external library?) but it should be `mouvement du doigt` and not `mouvement de doigt`.

![](https://i.imgur.com/eKoIlEj.png)

**Comment by alexbakker** [comment]
Good find. These appear to be some leftover hardcoded strings. We'll fix those. As for that last one, my guess would be that's a string from Android itself.

**Comment by mdmk** [comment]
Text not translated here on QR code scanner:

![](https://i.imgur.com/jiA77fY.png)
