### ISSUE TITLE
Possible computer implementation? 

### ISSUE THREAD

**Issue by 737simpilot** [beemdevelopment/Aegis#920]
Is there a computer implementation of this App by chance? I'm wondering if Electron could be used so it could run cross platform in Windows, Linux and OSX? 

This is why I chose Authy early on for cross platform ability. i.e., Android and Windows.

**Comment by alexbakker** [comment]
Duplicate of #165.

**Comment by 737simpilot** [comment]
And wow, didn't realize this was such a requested feature.
