### ISSUE TITLE
Hi，i have a question

### ISSUE THREAD

**Issue by YirunFantasy** [beemdevelopment/Aegis#929]
i used aegis for a while，it's excellent ，
I would like to ask, how does the aegis project stay alive，i like aegis，I also thank you for your dedication and hard work，But I'm afraid the project will stop at any time，For example, 'Microsoft Authenticator' and 'Google Authenticator' don't need to think about survival，I can't make up my mind to transfer all my keys to aegis，thanks

**Comment by alexbakker** [comment]
Thanks for the kind words!

Even if we stop working on Aegis (no intention to do so, though), there really isn't much to worry about. The app would continue to function as before and generate OTP's for you. Also, someone from the community could fork the project and continue development.
