### ISSUE TITLE
"Remove animations" accessibility setting not respected

### ISSUE THREAD

**Issue by lucy** [beemdevelopment/Aegis#930]
###### Info

* __Version__: 2.0.3
* __Source__: F-Droid
* __Vault encrypted__: Yes
* __Device__: Pixel 5a
* __Android version and ROM__: lineage_barbet-userdebug 12 SP2A.220505.002 1851126e65

###### Steps to reproduce

Enable "Remove animations" in the accessibility of the android system settings or equivalently set the window/transition/animator animation scales to off in developer settings.

###### What do you expect to happen?

All my codes display instantly when I open the app.

###### What happens instead?

The codes fade in gradually from the top of the screen. Other parts of the app are also still animated like when tapping on codes.

**Comment by MasterReach1** [comment]
New contributor here! I have found a simple fix for this bug. Please assign me to this issue and I will submit a PR

**Comment by brnl** [comment]
@MasterReach1 you can just submit your PR you don't have to be assigned.

Having that said, I also would love to have the animations (optionally) removed. They're slow and intrusive when changing groups, imho. They also don't respect the Android animation duration settings.
