### ISSUE TITLE
Set icons from installed Apps or Play Store and F-Droid

### ISSUE THREAD

**Issue by neoOpus** [beemdevelopment/Aegis#931]
It would be great if it is possible to set the icons from the installed Apps, a URL to a SVG or ICO files, or from the Play Store and F-Droid... This will make everything OCD level neat for those who intend to get things properly organized...

I am aware of the icon libraries but they lack a lot of icons from many apps and non-US based services.

**Comment by krisu5** [comment]
> or from the Play Store and F-Droid... 

These are not gonna happen, because Aegis is app without online connections for privacy reasons and I don't think devs have changed their minds about it.

**Comment by alexbakker** [comment]
Like @krisu5 said, anything that requires an internet connection is not really an option for Aegis.

Obtaining the icons of installed apps is an interesting idea, but I'm afraid it'd require us to request the [QUERY_ALL_PACKAGES](https://developer.android.com/reference/android/Manifest.permission.html#QUERY_ALL_PACKAGES) permission. I don't think our use case would fall under the "permitted uses" that Google Play stipulates.

**Comment by alexbakker** [comment]
I double checked and as far as I can tell this would indeed require us to request the QUERY_ALL_PACKAGES permission, so we can't implement this.

**Comment by neoOpus** [comment]
OK Thanks.
