### ISSUE TITLE
Google Authenticator export QR code can be imported by camera, but not by picture

### ISSUE THREAD

**Issue by tux3** [beemdevelopment/Aegis#933]
###### Info

* __Version__: 2.0.3
* __Source__: Google Play
* __Vault encrypted__: No
* __Device__: OnePlus 5T
* __Android version and ROM__: 10 (OOS 10.0.1)

###### Steps to reproduce

- In Google Authenticator, go to Transfer Accounts -> Export accounts -> Next. This should display a series of QR codes. 
- Take either a screenshot (if FLAG_SECURE is off) or a photo of the QR codes, save to file.
- In Aegis, use "Scan image" and open the saved image file, this fails with `unsuported protocol otpauth-migration`
- In Aegis, use "Scan QR code" and point at the same files displayed on another screen. This works.

###### What do you expect to happen?

"Scan QR code" and "Scan image" should both be able to import Authenticator export QR codes.  

###### What happens instead?

Scanning from an image file fails with an `unsuported protocol otpauth-migration` error.

---

The reason I ended up importing QR codes from file is I don't have a second device with good enough camera quality  to take pictures of the QR codes with (laptop webcam failed _miserably_), so saving a screenshot on my rooted device was easier for me. I'm aware of the "Import from app" feature, however it fails with "DecodingException: Invalid input length", which is a separate issue!

Note also that I'm filing this as a bug because the functionality seems to "already be there", just unevenly distributed, but this could as well be a feature request. Not sure which is most appropriate.

Thanks

**Comment by alexbakker** [comment]
Fixed by #958
