### ISSUE TITLE
Out of sync timer versus KeePassXC

### ISSUE THREAD

**Issue by 737simpilot** [beemdevelopment/Aegis#936]
I'm not entirely sure if this is a bug or not and I'm not really on the up and up on how TOTP works other than understating a base32 code is used to create a 2FA token at timed intervals.

My issue here is that when I add a base32 string (for lack of the right term) in KeePassXC and also in Aegis to match an account I set 2FA for, the countdown timers are out of sync  between both Aegis and KeePassXC. Thus so are the tokens.  But If I wait - the correct token will render after the time expires in Aegis compared to what is shown in KeePassXC.  I can tell you the tokens do work however.

Again, I' not sure how the algorithm works, but shouldn't the time match another App (program) like KeepassXC? 

###### Info

* __Version__: 2.0.3
* __Source__: Google Play
* __Vault encrypted__: Yes (With password. No biometrics)
* __Device__: Moto G Power 2021
* __Android version and ROM__: Android 11. Not sure about ROM Info needed.

###### Steps to reproduce

Watched the timer in KeePassXC versus the timer in Aegis. Rebooted the phone.

###### What do you expect to happen?

Synchronized timings. 

###### What happens instead?

Out of sync.

**Comment by ElTopo** [comment]
Most likely there's a big difference between your PC's system time and your phone's.
Go to https://time.is and check their system times, and correct them if necessary. 

The key for 2FA to work is that both parties should have correct time. If your system time is way off from the server system of a service, your 2FA codes might be rejected by the server.

**Comment by 737simpilot** [comment]
That was the issue. My PC's time was six seconds off. Thanks!
