### ISSUE TITLE
Add copy button next to entry

### ISSUE THREAD

**Issue by bluezed** [beemdevelopment/Aegis#940]
I just moved over to Aegis from andOTP and so far really like the app.

I have one suggestion though... In andOTP there is a little copy button next to the entry to quickly copy the code without revealing it.

I see Aegis has the tap to copy option, however sometimes I only want to reveal a code without actually copying it or vice versa. Also the long press and then press copy is an option but just one extra step that could be avoided.

Hope you will consider adding this as it's pretty much the only thing I currently miss since moving over.

Thanks!

**Comment by alexbakker** [comment]
We try to have as little clutter in the UI as possible, so a copy button for each entry wouldn't really fit well. I personally find that copying tokens is so rare, that I don't mind long pressing and then tapping the copy button every once in a while.

**Comment by bluezed** [comment]
Shame, guess I'll be looking elsewhere then.
