### ISSUE TITLE
Default to fingerprint if biometric factor enabled

### ISSUE THREAD

**Issue by GNOMES** [beemdevelopment/Aegis#943]
Currently when opening the app after enabling biometric factors I need to click "tap here to use biometrics".

It would be faster as a user if once enabled, if an authorised finger print worked without needing to hit "tap here...", or if an option existed to show the prompt right away (it seems most apps show enter finger print UI on app launch).

**Comment by e00E** [comment]
+1 . Another alternative is to remember and default to the most recently used unlock method.

**Comment by alexbakker** [comment]
https://github.com/beemdevelopment/Aegis/blob/master/FAQ.md#why-does-aegis-keep-prompting-me-for-my-password-even-though-i-have-enabled-biometric-authentication

**Comment by e00E** [comment]
If this comes up regularly as an issue/question then it might be useful to mention in the app that it is defaulting to the password for this reason. Unless this message already exists and we missed that too :) .
