### ISSUE TITLE
Rename "root access" to "rooted phone"

### ISSUE THREAD

**Issue by mrx23dot** [beemdevelopment/Aegis#946]
I tried to import google auth entries, but gave 'root access' error which is ambiguous.

Is rooting really required to import?

###### Info
* __Version__:  20.3

**Comment by alexbakker** [comment]
I think the "root access" wording is accurate.

> Is rooting really required to import?

If you want to directly import from an app's internal directory, root access is required. If you're specifically looking to import Google Authenticator entries, you can use its "Transfer accounts" functionality and scan the QR codes that are shown with Aegis.
