### ISSUE TITLE
Zxing hardwired

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#949]
"com.google.zxing.NotFoundException" is seen with the latest version of the app when choosing Scan Image.
And there is no way to say that we have other scanners installed.

**Comment by jidanni** [comment]
https://stackoverflow.com/questions/10583622/com-google-zxing-notfoundexception-exception-comes-when-core-java-program-execut maybe related.

**Comment by jidanni** [comment]
Samsung Galaxy. Android 12.

**Comment by alexbakker** [comment]
> "com.google.zxing.NotFoundException" is seen with the latest version of the app when choosing Scan Image.

Can you share an image of a QR code that Aegis fails to scan? (Make sure it doesn't contain any secrets that are actually in use)

And there is no way to say that we have other scanners installed.

> Which app offers scanning an image of a QR code and then reports the result back to the requesting app?

**Comment by jidanni** [comment]
All I know is it happened when I was signing up for a id.me account.

So I was forced to use the "binary eye" app.

**Comment by alexbakker** [comment]
Scanning QR codes from images should be a bit more reliable since bd3697659f1509a2c22910da4805fc9b3185a33d. If you're still having trouble with that patch, please share an example image that we can test with.
