### ISSUE TITLE
Update broke Aegis

### ISSUE THREAD

**Issue by krathalan** [beemdevelopment/Aegis#95]
I just updated to Aegis 0.4 last night from F-Droid and Aegis is no longer accepting my password. I have the password saved in a Keepass database; the entry nor the database have been modified since I opened Aegis successfully before the update. The last modification time for my Aegis password was last month, so I know this update broke Aegis for me and it's not me inputting an incorrect password.

Of course I keep backups of my Aegis database. I tried to clear the app's data and restore my Aegis database but I keep getting the message "Couldn't unlock vault: Incorrect password. Make sure you didn't mistype your password."

**Comment by krathalan** [comment]
F-Droid won't let me downgrade for some reason -- something about the packages being different. However if I uninstall 0.4 and reinstall 0.3.3 and restore my backup file everything works fine.

**Comment by alexbakker** [comment]
I'll look into this ASAP.

**Comment by alexbakker** [comment]
I think I introduced a bug in afb9e597110014117722fc8353333b18d3492007 for passwords that encode to UTF-8 as more than 64 bytes. Here's a debug APK with a potential fix for the issue: https://alexbakker.me/u/pqfys2yd8p.apk. Could you try and see if you can import your backup with that one?

**Comment by krathalan** [comment]
> @krathalan
> 
> I introduced a bug in [afb9e59](https://github.com/beemdevelopment/Aegis/commit/afb9e597110014117722fc8353333b18d3492007) for passwords that encode to UTF-8 as more than 64 bytes. Here's a debug APK with a potential fix for the issue: https://alexbakker.me/u/n4olkn7fjf.apk. Could you try and see if you can import your backup with that one?

I can unlock the Aegis debug APK successfully until I import my backup. Then I begin to experience the same issue ("Couldn't unlock vault: Incorrect password. Make sure you didn't mistype your password.").

**Comment by alexbakker** [comment]
@krathalan 

Thanks for the quick response. It's strange. That fix should have worked. Do you have a specific formula that you use to generate passwords in your password manager. If so, could you generate a similar password for me to test with?

**Comment by alexbakker** [comment]
PR #98 should fix this issue. I'll wait for you response before merging it to double check that it also works with your password formula, but I can't think of a reason why it wouldn't.

**Comment by alexbakker** [comment]
Here's an APK for the latest version of that PR: https://alexbakker.me/u/8eh0lzmua6.apk.

**Comment by krathalan** [comment]
> Here's an APK for the latest version of that PR: https://alexbakker.me/u/8eh0lzmua6.apk.

Apologies for the late reply, that APK seems to fix it. :)

**Comment by alexbakker** [comment]
Thanks a lot for the confirmation. We're going to release an update with that fix today.

**Comment by alexbakker** [comment]
Version 0.4.2 has been released! Apologies for the delay. It should be live in the Play Store in a couple of hours.

**Comment by krathalan** [comment]
@alexbakker any guess on F-Droid availability?

**Comment by alexbakker** [comment]
@krathalan No idea to be honest. F-Droid usually runs builds daily, but they're pretty unpredictable and don't give us much insight into their build process. So we'll have to wait and see.
