### ISSUE TITLE
Suggestions for exporting features

### ISSUE THREAD

**Issue by Roiyaru** [beemdevelopment/Aegis#954]
Hello developer.
Is it possible to add a web format (html) to the format of the export function? The web page contains the "Issuer, Username, QR Code" information for each item.

**Comment by alexbakker** [comment]
Sounds good to us!

For anyone who wants to pick this up: We don't really want to add a new dependency for this. This should be possible to implement with some clever string concatenation and use of Guava's HtmlEscapers.

**Comment by Roiyaru** [comment]
I want the ability to export data as QR Code. In order to recognize different QR Code may have to add corresponding account information, such as Issuer and Username; and exporting directly to image may expose the data because of the preview feature of the image. So I thought of exporting to html, I don't know how the developer will handle it, I'm looking forward to it.
通过DeepL翻译 https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by Roiyaru** [comment]
I want the ability to export data as QR Code. In order to recognize different QR Code may have to add corresponding account information, such as Issuer and Username; and exporting directly to image may expose the data because of the preview feature of the image. So I thought of exporting to html, I don't know how the developer will handle it, I'm looking forward to it.
