### ISSUE TITLE
Support otpauth-migration protocol

### ISSUE THREAD

**Issue by xmha97** [beemdevelopment/Aegis#959]
Please support this protocol:
otpauth-migration://offline?data=

**Comment by alexbakker** [comment]
This is already supported. Did you try scanning a QR code with a URI like that encoded in it?

**Comment by xmha97** [comment]
> This is already supported. Did you try scanning a QR code with a URI like that encoded in it?

Yes, I export my OTPs from Google Authenticator.
Take a photo from my phone screen using my tablet.
Trying adding OTPs to the Aegis app using QR code from my tablet.
But this method is not working...

**Comment by alexbakker** [comment]
Can you elaborate a bit more? Which option are you using in Aegis? "Scan QR code" or "Scan image"? In case of the latter, see: #933.

What does "is not working" mean? Does Aegis show an error message? What does it say?
