### ISSUE TITLE
Blank screen on screen locking

### ISSUE THREAD

**Issue by mdmk** [beemdevelopment/Aegis#96]
Android 8.1 Stock (Motorola Moto G4 Plus)
Fingerprints enabled in aegis

I just stumbled upon an interesting scenario.

On Android, screen does turn off after a certain amount of time. Just before the screen does turn off, screen dims. Then screen is off and you have 5 seconds to press power button. If you do so, screen does turn on without the need of unlocking the phone. Else, screen is locked.

Steps to reproduce :
- unlock database
- wait for the screen dimming
- at the exact time the screen turns off, press power button (you have less than half a second, else database unlock screen will be shown as normal when screen turns back on.)
- then aegis screen is blank and app crash if you go on menu (...) 

![](https://i.imgur.com/cRG8kAk.png)

**Comment by alexbakker** [comment]
There appears to be a race condition here. If you're quick enough, ``MainActivity.onResume`` is called before the ``SCREEN_OFF`` event is received. So the vault itself will be locked but ``AuthActivity`` is not launched.

Good catch.
