### ISSUE TITLE
New button disappears

### ISSUE THREAD

**Issue by thany** [beemdevelopment/Aegis#963]
###### Info

* __Version__: 2.0.3
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Galaxy S9
* __Android version and ROM__: LineageOS Android 10

###### Steps to reproduce

1. Have more entries that fit in screen (scrolling neccesary to reach all)
2. Scroll down
3. Scroll up a little bit, but no all the way to the top

###### What do you expect to happen?

New button doesn't disappear, like ever, at all. Why would it??

###### What happens instead?

On (2), the New button has disappeared.
On (3), the New button appears, and disppears again straight away.

**Comment by thany** [comment]
It get's even worse (and weirder) when you scroll up & down randomly. The New button will go totally wacko.

Maybe put the New button at the top or something. There's a fixed button bar anyway.

But at the very least, don't *ever* hide the New button. Why would you do that in the first place? Perhaps the problem you were trying to solve by hiding the New button, is better solved in a different way. Can you please explain which problem is solved by hiding the New button? Then maybe I can help come up with a solution that suits the app better. I think the New button is in the wrong place anyway - all the way bottom-right 🤨

**Comment by alexbakker** [comment]
Hiding the FAB when the users scrolls down is very common in Android apps. It unclutters the screen while the user is scrolling down and prevents accidental presses. We're happy with the way this works now. The positioning of the FAB is also correct.

If you'd like to help improve the logic that controls the FAB to make it a little less glitchy while quickly scrolling up and down, we'd be happy to accept a pull request. Take a look at: https://github.com/beemdevelopment/Aegis/blob/master/app/src/main/java/com/beemdevelopment/aegis/helpers/FabScrollHelper.java and let us know if you see any opportunities for improvement.

**Comment by thany** [comment]
> We're happy with the way this works now.

Who is we? I'm not. It doesn't make sense to put it there. Just because other apps do it, doesn't make it correct. It makes it common. But common is not always correct.

> The positioning of the FAB is also correct.

Well, correct in the sense that the code tells the app to put it there, and it does. So code-wise it's correct, but UX-wise it is not.

> We'd be happy to accept a pull request.

I'm not an app developer, unfortunately.

Seriously though, why not put it near the other buttons? Or rather, why not put the sorting button not in the bottom-right corner? This is of course, bollocks. But I'm only challenging your UX decisions. Decisions seems to be based on commonality, which is not always a great way to decide things.

**Comment by thany** [comment]
Anyway, it was really confusing to me. I was at the bottom, where a new entry would appear, and was like "wait what, where did the New button go??"

I literally took me a few seconds to realise I have to scroll up (not a little bit, because then it would disappear as soon as it appears - and I refuse to believe you are happy with this, as you stated) to get it to show. All the while there would be enough real state in the button bar up top, and in the bottom-right corner, to show a New button.

So you would knowingly and willing confuse users by hiding (or rather, not showing) the New button for no good reason?

**Comment by thany** [comment]
> If FAB is on the left side, it would hide portion of the icon that can be visual indication for some users.
> 
> If FAB is in the center, it would hide portion of 2FA code and issuer name.
> 
> Right side is best compromise. It only hides portion of the account info and I consider most of the time least important info on the screen.

That's why it should be in the button bar up top. Then you don't have to juggle with its positioning. I really don't understand why you'd make it so hard on yourself, when you already have a perfectly function button bar.

> Hiding FAB isn't 100% necessary, but since the FAB comes back from slightest up scroll, I never had actually issue with it.

Then at least fix that it immediately hides itself when not scrolling *all the way* up.

**Comment by krisu5** [comment]
> That's why it should be in the button bar up top. Then you don't have to juggle with its positioning. I really don't understand why you'd make it so hard on yourself, when you already have a perfectly functioning button bar.

Less visually distinct IMO. And thing is that then users would complain about **not** having FAB anymore.

Also screen width might bring some problems.

> Then at least fix that it immediately hides itself when not scrolling all the way up.

I never have seen it worked like that. I have tested how FAB works by myself for dozen and more times.

**Comment by thany** [comment]
Why does it need to be visually distinct? It's not the kind of button you'd typically need every day, so it doesn't need to be so prominently visible all the time. Subtly in the button bar seems fine. Or even in a menu.

Then again, it's in the bottom-right. Not exactly an easy to reach place on the screen, given a portrait one-hand holding situation.

> Also resolution width might bring some problems, there's already 3 visible actions at top bar. If that's the case, then it has to go to "three-dotted" menu when screen is small.

Nah, there's plenty space, even in portrait. The title just says "Aegis" which is only a small name. There's enough space for 8 buttons!

**Comment by krisu5** [comment]
> Why does it need to be visually distinct? It's not the kind of button you'd typically need every day, so it doesn't need to be so prominently visible all the time.

Exactly why: because you need it someday and you know it where it is.

> Or even in a menu.

That's a bad idea, I can tell you that. If users wants add multiple entries, it will harm the experience.

TBH, I'm done here. I'm still agreeing with @alexbakker here, there's barely any good reasons to make this change.

**Comment by thany** [comment]
Then at least go back to the issue at hand: it will disappear when it shouldn't.

**Comment by alexbakker** [comment]
What @krisu5 has said is basically what I'd have to say about this as well.

> Then at least go back to the issue at hand: it will disappear when it shouldn't.

Sure, like I said in my comment, your observation that hiding the FAB is a little glitchy is valid and we can look into improving that.
