### ISSUE TITLE
Import Google Auth db/app

### ISSUE THREAD

**Issue by hung0702** [beemdevelopment/Aegis#966]
###### Info

* __Version__: 2.0.3
* __Source__: Google Play, GitHub (tried both)
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Pixel 6
* __Android version and ROM__: 12.1 (July 5th), Magisk 25201

###### Steps to reproduce

* __Source__: Google Authenticator (5.20R4)
* __Required__: Grant Root to Aegis; Copy G-Auth db to permissive location

1. Import from app or database

###### What do you expect to happen?

Import of 2FA accounts

###### What happens instead?

Both options fail to decode due to invalid characters or lengths, yielding identical logs. Repeated attempts are consistent.

* __Did not help__: force-stop-reopen, clear data, reinstall, reboot

###### Log
15 failed imports, repeats removed for clarity.

```
com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 8

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 59

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 81
```

**Comment by GipsyBeggar** [comment]
I'm having the same issue, none of the entries from GAUTH is being imported successfully.

I receive the errors that @hung0702 got, and also the following:
```
com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: /
com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 0
com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 70
```

**Comment by hung0702** [comment]
Actually I found out on Reddit or Twitter that Google Authenticator changed the storage method and encrypted it. This is expected behavior now and the option should be removed in favor of scanning QR codes into a second device and importing back to the original device after updating.

**Comment by GipsyBeggar** [comment]
That's true, and I can confirm this method is working.

For the sake of future users facing this problem, I'll explain the process in other words.
1. When exporting from GAUTH one needs to scan 3 barcodes.
2. It's possible to import into Aegis by scanning these barcodes.
3. IMO a simple way to do so, is to take a picture of each of these barcodes using any other device with a camera (i.e. laptop, smartphone...) and then scan these barcodes with Aegis.
