### ISSUE TITLE
[Feature Request] Backup file number

### ISSUE THREAD

**Issue by dtoxic47** [beemdevelopment/Aegis#970]
Add ability to change number of backups to be kept to be less than the default 5,maybe also add a warning if selecting lower then the default 5

**Comment by dtoxic47** [comment]
Well from 1 to 10 should suffice for who ever wants to change this settings,personally 1 is enough for me since i sync my phone with my NAS every day and don't want multiple backups,one is enough

**Comment by alexbakker** [comment]
> 1 is enough for me since i sync my phone with my NAS every day and don't want multiple backups,one is enough

#745 would probably fit your use case a bit better.

**Comment by dtoxic47** [comment]
yeap that would be good enough

**Comment by alexbakker** [comment]
Cool, I'll close this one then.
