### ISSUE TITLE
[Feature Request] Option: Set biometric login as default

### ISSUE THREAD

**Issue by marmat123** [beemdevelopment/Aegis#974]
When I start the app (Android, 2.0.3) I get the password login and the keyboard app starts automatically, hiding the link to the biometric login.

It would be advantageous for handling if you could not only activate the biometric login in the options, but also set it as the default login (with a back link to the password login). 

Thanks

**Comment by ElTopo** [comment]
I don't know if it's possible, but I really like how "Norton App Lock" (https://play.google.com/store/apps/details?id=com.symantec.applock) handles this situation: you can input PIN or use fingerprint on the same screen, there's no need to switch between fingerprint mode and PIN mode, here's a screenshot:
![nal](https://user-images.githubusercontent.com/217195/188225509-62ed6dc4-aa11-43f5-9413-814e68a1c985.png)

**Comment by marmat123** [comment]
No, sorry, it's not about replacing a function that one software already has with another software or even including a third software as a mediator for security related things that is actually managed by the system

A simple switch could switch the login page, they are both already integrated in the software. There's no need for a crutch that hooks into the login.

**Comment by alexbakker** [comment]
You're probably seeing the password reminder. Try entering your password once. After that, Aegis should start prompting for biometrics again until it's time for another password reminder.
