### ISSUE TITLE
Password requirement when adding Aegis to a second device.

### ISSUE THREAD

**Issue by johnlyons** [beemdevelopment/Aegis#978]
Hello.

I set up Aegis on one Android device, set password and it's working great - when I installed Aegis on a second device it is taking me through the setup process again as if it were a new account, should I just enter the same password or is a new password required for different devices?

**Comment by alexbakker** [comment]
Aegis stores everything locally and doesn't connect to the internet, so there are no "accounts". It's up to you to decide whether you want to use the same password on a new device.
