### ISSUE TITLE
Error when using face unlock

### ISSUE THREAD

**Issue by theleanbow** [beemdevelopment/Aegis#982]
###### Info

* __Version__: 2.0.3
* __Source__: F-droid
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Redmi Note 5 Pro
* __Android version and ROM__: 10, Havoc OS 3.12

###### Steps to reproduce

Enable face unlock in android.
Enable biometric lock on Aegis.
App tries to use biometric lock, and it throws a error

###### What do you expect to happen?
Login to the app just like it does with fingerprint verification.
...

###### What happens instead?
The app gives an error
![Screenshot_20220907-121728](https://user-images.githubusercontent.com/66841515/188806473-166d547b-512f-4049-a2fb-a033a3c1973d.jpeg)

...

PS: Could be because havoc os is using camera for face unlock as the redmi note 5 pro doesn't have a dedicated sensor for face unlock, would appreciate if we could just use the face unlock like in most of the other apps(for eg: bitwarden works perfectly fine with face unlock on this device)

**Comment by alexbakker** [comment]
Could you obtain a log with ADB? I'd be interested in seeing the exception that is logged. Like you said though, this is likely because your ROM doesn't properly integrate with Android's biometrics system.

**Comment by alexbakker** [comment]
No response.
