### ISSUE TITLE
How do I import from Microsoft Authenticator without root access?

### ISSUE THREAD

**Issue by HarryHewett** [beemdevelopment/Aegis#984]
I'm trying to import my entries from Microsoft Authenticator. The app says:

> Supply a copy of **/data/data/com.azure.authenticator/databases/PhoneFactor**, located in the internal storage directory of Microsoft Authenticator.

Can I do this without root access? If not, please can it be made clear in the app as I have spent a lot of time trying to acquire this file.

Thanks.

**Comment by alexbakker** [comment]
It is not possible to import from Microsoft Authenticator without currently having root access, or having had root access in the past to access the app's internal storage directory.
