### ISSUE TITLE
Add Yandex.Key support

### ISSUE THREAD

**Issue by dartraiden** [beemdevelopment/Aegis#985]
[Yandex](https://play.google.com/store/apps/details?id=ru.yandex.key&hl=en&gl=US) uses non-standard TOTP. When setting up the application for the first time, the user creates a pin and then enters it at each launch

![56bb72565c1648a8a161614147aeb92b](https://user-images.githubusercontent.com/5046855/190225756-53c396b1-049e-446a-a1cc-a9b9a73aa6cf.png)

It would be very convenient to have this support in Aegis.

There are already third-party implementations for Keepass, e.g. https://github.com/norblik/KeeYaOtp or https://github.com/Rookiestyle/KeePassOTP

**Comment by alexbakker** [comment]
This has already been implemented. See: #869. It's not available in a release yet, though.
