### ISSUE TITLE
Aegis fails to import from new Steam app beta

### ISSUE THREAD

**Issue by Wanyal** [beemdevelopment/Aegis#986]
###### Info
 * **Version**: 2.0.3
 * **Source**: F-droid
 * **Vault encrypted**: Yes (with biometric unlock)
 * **Device**: OnePlus 6T
 * **Android version and ROM**: 12, Lineage OS 19.
 
 ###### Steps to reproduce

1. Navigate to https://play.google.com/apps/testing/com.valvesoftware.android.steam.community and sign up for the new Steam app beta
2. After installing the new Steam app, make sure Steam Guard is set up
3. Go to Aegis and try to import from Steam using the usual method

 ###### What do you expect to happen?
Steam codes are imported to Aegis similarly to the old app
 
 ###### What happens instead?
 The process fails and Aegis gives error:
>com.beemdevelopment.aegis.importers.DatabaseImporterException: Empty directory: >/data/user/0/com.valvesoftware.android.steam.community/files

**Comment by alexbakker** [comment]
Thanks for the report.

I took a quick look at this, and it looks like newer versions of the Steam app have started encrypting the secret used for Steam Guard. As far as I can tell, it is now stored at ``shared_prefs/SecureStore.xml``. The file has the following structure: 

```xml
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="SteamGuard_1">{&quot;ct&quot;:&quot;REMOVED&quot;,&quot;iv&quot;:&quot;REMOVED&quot;,&quot;tlen&quot;:128,&quot;scheme&quot;:&quot;aes&quot;}</string>
</map>
```

Considering the filename, I guess they're using [SecureStore](https://docs.expo.dev/versions/latest/sdk/securestore/), which means this is encrypted using an Android Keystore key.

We'll have to add a check for newer versions of the Steam app and warn users that we won't be able to import anymore.
