### ISSUE TITLE
Error scanning QRcode on Samsung website.

### ISSUE THREAD

**Issue by WDD3MS** [beemdevelopment/Aegis#987]
###### Info

* __Version__: 2.0.3   (on And.11 Xiaomi and on And12 Samsung 
* __Source__: (Google Play)
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Xiaomi MI 8 ; Samsung 22 
* __Android version and ROM__: 11 and 12

###### Steps to reproduce

A detailed list of reproduction steps.

On Samsung website https://account.samsung.com/membership, on other site works well.
Trying to add 2FA via QRcode it didn't scan code on LCD, or picture in device.
trying 2 different codes.
This same code works ok  with another 2FA app.
The same code entering the secret manual, with default setting (encryption and all) works well. 

###### What do you expect to happen?

add account

###### What happens instead?

When I scan the LCD nothing happens. 

when I scan picture on android device, get this:
“com.google.zxing.NotFoundException”

**Comment by alexbakker** [comment]
I took a look at this and noticed that Samsung displays invalid QR codes when the website is in dark mode. Did you have dark mode enabled on the Samsung website, by any chance?

The next version of Aegis will have support for scanning these invalid QR codes. See: 0909341caa55a8b4afa468091a99375e96a006f1.

**Comment by WDD3MS** [comment]
Yes, it is possible. 
I turned off DarkReader, but it is still heavily dark.
And I have error reading qr code in MS auth, too.  
Sorry to bother you as this is probably a Samsung bug. But before that some applications could read qr code.
