### ISSUE TITLE
biometric authentication as default

### ISSUE THREAD

**Issue by reaseno** [beemdevelopment/Aegis#988]
I am missing the possibility to set the biometric authentication as default. So that when I open the app it is immediately displayed without having to select it again beforehand.

**Comment by alexbakker** [comment]
You're probably seeing the password reminder. Try entering your password once. After that, Aegis will start prompting for biometrics by default again, until it's time for another password reminder.

**Comment by reaseno** [comment]
Ah, didn't know. I removed that and now its as I want it to be 👍
