### ISSUE TITLE
Improve clarity of the password reminder

### ISSUE THREAD

**Issue by alexbakker** [beemdevelopment/Aegis#989]
Every once in a while, a user will ask why Aegis doesn't immediately prompt for biometrics when opening the app. These users are actually encountering the password reminder, but they don't seem to notice the popup telling them to enter their password (I suspect that perhaps the popup doesn't show at all on certain devices, but I've never been able to confirm this). We should work on making it even more obvious that they're supposed to enter their password once to confirm that they still remember it. Afterwards, Aegis will start prompting for biometrics by default again.

**Comment by orange-elephant** [comment]
Would a password reminder warning banner and subsequent dialog to verify the password, once the app is already unlocked be better.

I can imagine it being less confusing/ alarming if you actually *have* forgotten your password, as it is very obvious that you still have access to your tokens and can just go and change the password immediately.

It's not super obvious at the minute that you can still manually prompt for biometrics.

**Comment by alexbakker** [comment]
I'd actually prefer to keep the reminder before the user unlocks the app. The reason it was introduced is because sometimes users would forget that the password is actually the primary way to get into their vault. So I don't mind user having a minor "oh shit" moment when they realize they've forgotten it.

I think that the problem with the popup is that it just doesn't stand out very much. Like you said though, it also needs to be clear that biometric unlock is still an option. I haven't thought much about how exactly this should look, but I'm open to idea's.

**Comment by orange-elephant** [comment]
Yeah that makes perfect sense.

Some of the problems with the popup is it can be covered by password manager autofill prompts, and it hides too quickly/ upon absolutely any screen touch which maybe why people miss it entirely.

My idea was just a textview that shows when password reminder is due, and stays there until the password is inputted correctly, then have a link like the prompt biometric one which shows a dialog explaining why its necessary, drive home that fingerprint unlock is a convenience and not at all the same as a password.

I threw this together: 
![Screenshot_20221016-161916](https://user-images.githubusercontent.com/88595467/196043586-302c377e-9f72-42bf-bd15-4d03e2989589.png)

Some instructions on how to change the password if they have forgotten it could maybe go here too

**Comment by brnl** [comment]
Man, this was bugging me so much! I was hating the app that I had to close the keyboard every time and touch 'use biometrics'. I didn't know it was just a weekly password reminder until I tried installing on a new phone which didn't focus the password every time.

This is a big UX miss, if you ask me. :-)
