### ISSUE TITLE
No Progress bar

### ISSUE THREAD

**Issue by Biepa** [beemdevelopment/Aegis#99]
Hey,
since the last update there is no progress bar and my codes doesn't are renew.
They are renewed, when i close the app or switch in the view of last used apps and go back to aegis.
I checked my settings with the one mentioned in #35. All fine.
Aegis v0.4

**Comment by alexbakker** [comment]
Thanks for reaching out. This bug was fixed in v0.4.1. It should be live on F-Droid as well now.

**Comment by Biepa** [comment]
Did not saw, that there is a new version already. Updated.
Working. Thanks a lot.
