### ISSUE TITLE
Allow app unlocking via phone scheme or specific scheme

### ISSUE THREAD

**Issue by pepmts** [beemdevelopment/Aegis#990]
### Current process

Currently, unlocking the app is via a specific password (tedious to type it every time, as stated in the documentation) or via biometrics (not accessible on everyone's phone, and not everyone would want one's biometric data stored in the phone)

### Feature

Why not creating another unlocking feature, like with a scheme, so that it is faster to unlock, still reasonnably secure, and can easily be integrated with the phone security parameters, like bank or other apps that need the phone scheme to be unlocked.

Thanks for your app and work !

**Comment by alexbakker** [comment]
A similar thing was requested and rejected a while ago: #911.

**Comment by pepmts** [comment]
Okay, thanks for the answer then
