### ISSUE TITLE
App window closes after phone unlocked

### ISSUE THREAD

**Issue by escapedraccoon** [beemdevelopment/Aegis#991]
###### Info

* __Version__: 2.0.3
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: POCO X3 Pro
* __Android version and ROM__: Android 11, MIUI 12.5

###### Steps to reproduce

1. Open Aegis, use biometric unlock to access 
2. Lock the phone 
3. Unlock the phone

###### What do you expect to happen?

Aegis still is running and the active window. Just the biometric unlock is back. -> only unlocking gives you your codes back (if enabled in biometrics and passcode in settings).

###### What happens instead?

Aegis is now closed. I need to go back to the App drawer to launch it.

**Comment by alexbakker** [comment]
Could you clarify? The title states: "App window closes after phone unlocked". Yet under "What do you expect to happen?" you state: "Aegis is now closed.".

**Comment by alexbakker** [comment]
Thanks for clarifying. This is expected behavior and a consequence of how we had to implement automatic locking. I go into this in a bit more detail here: https://github.com/beemdevelopment/Aegis/issues/731#issuecomment-835486449.
