### ISSUE TITLE
BUG FIX: Remove animations accessibility setting not respected

### ISSUE THREAD

**Issue by MasterReach1** [beemdevelopment/Aegis#995]
Related bug: https://github.com/beemdevelopment/Aegis/issues/930#issue-1272901103

Bug fix: Added a check for the "Remove Animations" accessibility setting before animating the list. If enabled, the list just appears without animation.

PR submitted. Please provide any feedback, if needed.

**Comment by alexbakker** [comment]
Please don't create duplicate issues to get our attention.

**Comment by MasterReach1** [comment]
Many apologies. I am a new contributor, and I was not entirely sure whether a new issue was necessary. Thank you for the feedback
